;;; amiga/raw/hardware/blit  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   hardware/blit.i
;;;
;;; 0 functions, 50 constants, 1 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.HARDWARE.BLIT"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export))

(in-package "AMIGA.RAW.HARDWARE.BLIT")

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.HARDWARE.BLIT" ()

  ;; --- constants from hardware/blit.i ---
  (:const "+CLEANM-EN+" 6)
  (:const "+CLEANME+" #x40)
  (:const "+HSIZEBITS+" 6)
  (:const "+VSIZEBITS+" 10)
  (:const "+HSIZEMASK+" #x3F)
  (:const "+VSIZEMASK+" #x3FF)
  (:const "+MAXBYTESPERROW+" #x80)
  (:const "+MINBYTESPERROW+" #x80)
  (:const "+ABC+" #x80)
  (:const "+ABNC+" #x40)
  (:const "+ANBC+" #x20)
  (:const "+ANBNC+" #x10)
  (:const "+NABC+" 8)
  (:const "+NABNC+" 4)
  (:const "+NANBC+" 2)
  (:const "+NANBNC+" 1)
  (:const "+BC0-B-DEST+" 8)
  (:const "+BC0-B-SRCC+" 9)
  (:const "+BC0-B-SRCB+" 10)
  (:const "+BC0-B-SRCA+" 11)
  (:const "+BC0-F-DEST+" #x100)
  (:const "+BC0-F-SRCC+" #x200)
  (:const "+BC0-F-SRCB+" #x400)
  (:const "+BC0-F-SRCA+" #x800)
  (:const "+BC1-F-DESC+" 2)
  (:const "+DEST+" #x100)
  (:const "+SRCC+" #x200)
  (:const "+SRCB+" #x400)
  (:const "+SRCA+" #x800)
  (:const "+ASHIFTSHIFT+" 12)
  (:const "+BSHIFTSHIFT+" 12)
  (:const "+LINEMODE+" 1)
  (:const "+FILL-OR+" 8)
  (:const "+FILL-XOR+" #x10)
  (:const "+FILL-CARRYIN+" 4)
  (:const "+ONEDOT+" 2)
  (:const "+OVFLAG+" #x20)
  (:const "+SIGNFLAG+" #x40)
  (:const "+BLITREVERSE+" 2)
  (:const "+SUD+" #x10)
  (:const "+SUL+" 8)
  (:const "+AUL+" 4)
  (:const "+OCTANT8+" #x18)
  (:const "+OCTANT7+" 4)
  (:const "+OCTANT6+" 12)
  (:const "+OCTANT5+" #x1C)
  (:const "+OCTANT4+" #x14)
  (:const "+OCTANT3+" 8)
  (:const "+OCTANT2+" 0)
  (:const "+OCTANT1+" #x10)

  ;; --- structures from hardware/blit.i ---
  (:struct "BLTNODE" 18   ; bltnode (hardware/blit.i)
    ("N" :i32 0)
    ("FUNCTION" :i32 4)
    ("STAT" :i8 8)
    ("DUMMY" :i8 9)
    ("BLITSIZE" :i16 10)
    ("BEAMSYNC" :i16 12)
    ("CLEANUP" :i32 14)
    )
  )

(provide "amiga/raw/hardware/blit")
