;;; amiga/raw/hardware/custom  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   hardware/custom.i
;;;
;;; 0 functions, 115 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.HARDWARE.CUSTOM"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "+BLTDDAT+" "+DMACONR+" "+VPOSR+" "+VHPOSR+" "+DSKDATR+" "+JOY0DAT+" 
   "+JOY1DAT+" "+CLXDAT+" "+ADKCONR+" "+POT0DAT+" "+POT1DAT+" "+POTINP+" 
   "+SERDATR+" "+DSKBYTR+" "+INTENAR+" "+INTREQR+" "+DSKPT+" "+DSKLEN+" 
   "+DSKDAT+" "+REFPTR+" "+VPOSW+" "+VHPOSW+" "+COPCON+" "+SERDAT+" 
   "+SERPER+" "+POTGO+" "+JOYTEST+" "+STREQU+" "+STRVBL+" "+STRHOR+" 
   "+STRLONG+" "+BLTCON0+" "+BLTCON1+" "+BLTAFWM+" "+BLTALWM+" "+BLTCPT+" 
   "+BLTBPT+" "+BLTAPT+" "+BLTDPT+" "+BLTSIZE+" "+BLTCON0L+" "+BLTSIZV+" 
   "+BLTSIZH+" "+BLTCMOD+" "+BLTBMOD+" "+BLTAMOD+" "+BLTDMOD+" "+BLTCDAT+" 
   "+BLTBDAT+" "+BLTADAT+" "+DENISEID+" "+DSKSYNC+" "+COP1LC+" "+COP2LC+" 
   "+COPJMP1+" "+COPJMP2+" "+COPINS+" "+DIWSTRT+" "+DIWSTOP+" "+DDFSTRT+" 
   "+DDFSTOP+" "+DMACON+" "+CLXCON+" "+INTENA+" "+INTREQ+" "+ADKCON+" 
   "+AUD+" "+AUD0+" "+AUD1+" "+AUD2+" "+AUD3+" "+AC-PTR+" "+AC-LEN+" 
   "+AC-PER+" "+AC-VOL+" "+AC-DAT+" "+AC-SIZEOF+" "+BPLPT+" "+BPLCON0+" 
   "+BPLCON1+" "+BPLCON2+" "+BPLCON3+" "+BPL1MOD+" "+BPL2MOD+" "+BPLCON4+" 
   "+CLXCON2+" "+BPLDAT+" "+SPRPT+" "+SPR+" "+SD-POS+" "+SD-CTL+" 
   "+SD-DATAA+" "+SD-DATA-B+" "+SD-SIZEOF+" "+COLOR+" "+HTOTAL+" "+HSSTOP+" 
   "+HBSTRT+" "+HBSTOP+" "+VTOTAL+" "+VSSTOP+" "+VBSTRT+" "+VBSTOP+" 
   "+SPRHSTRT+" "+SPRHSTOP+" "+BPLHSTRT+" "+BPLHSTOP+" "+HHPOSW+" 
   "+HHPOSR+" "+BEAMCON0+" "+HSSTRT+" "+VSSTRT+" "+HCENTER+" "+DIWHIGH+" 
   "+FMODE+" ))

(in-package "AMIGA.RAW.HARDWARE.CUSTOM")

;;; --- constants from hardware/custom.i ---
(defconstant +bltddat+ 0)
(defconstant +dmaconr+ 2)
(defconstant +vposr+ 4)
(defconstant +vhposr+ 6)
(defconstant +dskdatr+ 8)
(defconstant +joy0dat+ 10)
(defconstant +joy1dat+ 12)
(defconstant +clxdat+ 14)
(defconstant +adkconr+ #x10)
(defconstant +pot0dat+ #x12)
(defconstant +pot1dat+ #x14)
(defconstant +potinp+ #x16)
(defconstant +serdatr+ #x18)
(defconstant +dskbytr+ #x1A)
(defconstant +intenar+ #x1C)
(defconstant +intreqr+ #x1E)
(defconstant +dskpt+ #x20)
(defconstant +dsklen+ #x24)
(defconstant +dskdat+ #x26)
(defconstant +refptr+ #x28)
(defconstant +vposw+ #x2A)
(defconstant +vhposw+ #x2C)
(defconstant +copcon+ #x2E)
(defconstant +serdat+ #x30)
(defconstant +serper+ #x32)
(defconstant +potgo+ #x34)
(defconstant +joytest+ #x36)
(defconstant +strequ+ #x38)
(defconstant +strvbl+ #x3A)
(defconstant +strhor+ #x3C)
(defconstant +strlong+ #x3E)
(defconstant +bltcon0+ #x40)
(defconstant +bltcon1+ #x42)
(defconstant +bltafwm+ #x44)
(defconstant +bltalwm+ #x46)
(defconstant +bltcpt+ #x48)
(defconstant +bltbpt+ #x4C)
(defconstant +bltapt+ #x50)
(defconstant +bltdpt+ #x54)
(defconstant +bltsize+ #x58)
(defconstant +bltcon0l+ #x5B)
(defconstant +bltsizv+ #x5C)
(defconstant +bltsizh+ #x5E)
(defconstant +bltcmod+ #x60)
(defconstant +bltbmod+ #x62)
(defconstant +bltamod+ #x64)
(defconstant +bltdmod+ #x66)
(defconstant +bltcdat+ #x70)
(defconstant +bltbdat+ #x72)
(defconstant +bltadat+ #x74)
(defconstant +deniseid+ #x7C)
(defconstant +dsksync+ #x7E)
(defconstant +cop1lc+ #x80)
(defconstant +cop2lc+ #x84)
(defconstant +copjmp1+ #x88)
(defconstant +copjmp2+ #x8A)
(defconstant +copins+ #x8C)
(defconstant +diwstrt+ #x8E)
(defconstant +diwstop+ #x90)
(defconstant +ddfstrt+ #x92)
(defconstant +ddfstop+ #x94)
(defconstant +dmacon+ #x96)
(defconstant +clxcon+ #x98)
(defconstant +intena+ #x9A)
(defconstant +intreq+ #x9C)
(defconstant +adkcon+ #x9E)
(defconstant +aud+ #xA0)
(defconstant +aud0+ #xA0)
(defconstant +aud1+ #xB0)
(defconstant +aud2+ #xC0)
(defconstant +aud3+ #xD0)
(defconstant +ac-ptr+ 0)
(defconstant +ac-len+ 4)
(defconstant +ac-per+ 6)
(defconstant +ac-vol+ 8)
(defconstant +ac-dat+ 10)
(defconstant +ac-sizeof+ #x10)
(defconstant +bplpt+ #xE0)
(defconstant +bplcon0+ #x100)
(defconstant +bplcon1+ #x102)
(defconstant +bplcon2+ #x104)
(defconstant +bplcon3+ #x106)
(defconstant +bpl1mod+ #x108)
(defconstant +bpl2mod+ #x10A)
(defconstant +bplcon4+ #x10C)
(defconstant +clxcon2+ #x10E)
(defconstant +bpldat+ #x110)
(defconstant +sprpt+ #x120)
(defconstant +spr+ #x140)
(defconstant +sd-pos+ 0)
(defconstant +sd-ctl+ 2)
(defconstant +sd-dataa+ 4)
(defconstant +sd-data-b+ 6)
(defconstant +sd-sizeof+ 8)
(defconstant +color+ #x180)
(defconstant +htotal+ #x1C0)
(defconstant +hsstop+ #x1C2)
(defconstant +hbstrt+ #x1C4)
(defconstant +hbstop+ #x1C6)
(defconstant +vtotal+ #x1C8)
(defconstant +vsstop+ #x1CA)
(defconstant +vbstrt+ #x1CC)
(defconstant +vbstop+ #x1CE)
(defconstant +sprhstrt+ #x1D0)
(defconstant +sprhstop+ #x1D2)
(defconstant +bplhstrt+ #x1D4)
(defconstant +bplhstop+ #x1D6)
(defconstant +hhposw+ #x1D8)
(defconstant +hhposr+ #x1DA)
(defconstant +beamcon0+ #x1DC)
(defconstant +hsstrt+ #x1DE)
(defconstant +vsstrt+ #x1E0)
(defconstant +hcenter+ #x1E2)
(defconstant +diwhigh+ #x1E4)
(defconstant +fmode+ #x1FC)

(provide "amiga/raw/hardware/custom")
