;;; amiga/raw/hardware/intbits  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   hardware/intbits.i
;;;
;;; 0 functions, 32 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.HARDWARE.INTBITS"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export))

(in-package "AMIGA.RAW.HARDWARE.INTBITS")

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.HARDWARE.INTBITS" ()

  ;; --- constants from hardware/intbits.i ---
  (:const "+INTB-SETCLR+" 15)
  (:const "+INTB-INTEN+" 14)
  (:const "+INTB-EXTER+" 13)
  (:const "+INTB-DSKSYNC+" 12)
  (:const "+INTB-RBF+" 11)
  (:const "+INTB-AUD3+" 10)
  (:const "+INTB-AUD2+" 9)
  (:const "+INTB-AUD1+" 8)
  (:const "+INTB-AUD0+" 7)
  (:const "+INTB-BLIT+" 6)
  (:const "+INTB-VERTB+" 5)
  (:const "+INTB-COPER+" 4)
  (:const "+INTB-PORTS+" 3)
  (:const "+INTB-SOFTINT+" 2)
  (:const "+INTB-DSKBLK+" 1)
  (:const "+INTB-TBE+" 0)
  (:const "+INTF-SETCLR+" #x8000)
  (:const "+INTF-INTEN+" #x4000)
  (:const "+INTF-EXTER+" #x2000)
  (:const "+INTF-DSKSYNC+" #x1000)
  (:const "+INTF-RBF+" #x800)
  (:const "+INTF-AUD3+" #x400)
  (:const "+INTF-AUD2+" #x200)
  (:const "+INTF-AUD1+" #x100)
  (:const "+INTF-AUD0+" #x80)
  (:const "+INTF-BLIT+" #x40)
  (:const "+INTF-VERTB+" #x20)
  (:const "+INTF-COPER+" #x10)
  (:const "+INTF-PORTS+" 8)
  (:const "+INTF-SOFTINT+" 4)
  (:const "+INTF-DSKBLK+" 2)
  (:const "+INTF-TBE+" 1)
  )

(provide "amiga/raw/hardware/intbits")
