;;; amiga/raw/reaction/reaction-class  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   reaction/reaction_class.h
;;;
;;; 0 functions, 4 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.REACTION.REACTION-CLASS"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export))

(in-package "AMIGA.RAW.REACTION.REACTION-CLASS")

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.REACTION.REACTION-CLASS" ()

  ;; --- constants from reaction/reaction_class.h ---
  (:const "+GM-CLIPRECT+" #x550001)
  (:const "+GMC-VISIBLE+" 2)
  (:const "+GMC-PARTIAL+" 1)
  (:const "+GMC-INVISIBLE+" 0)
  )

(provide "amiga/raw/reaction/reaction-class")
