;;; amiga/raw/reaction/reaction-prefs  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   reaction/reaction_prefs.h
;;;
;;; 0 functions, 8 constants, 0 structs.
;;; 2 C macros skipped: not an integer constant (string, call, float).
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.REACTION.REACTION-PREFS"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "+BVT-GT+" "+BVT-THIN+" "+BVT-THICK+" "+BVT-XEN+" "+BVT-XENTHIN+" 
   "+GLT-GT+" "+GLT-FLAT+" "+GLT-3-D+" ))

(in-package "AMIGA.RAW.REACTION.REACTION-PREFS")

;;; --- constants from reaction/reaction_prefs.h ---
(defconstant +bvt-gt+ 0)
(defconstant +bvt-thin+ 1)
(defconstant +bvt-thick+ 2)
(defconstant +bvt-xen+ 3)
(defconstant +bvt-xenthin+ 4)
(defconstant +glt-gt+ 0)
(defconstant +glt-flat+ 1)
(defconstant +glt-3-d+ 2)

(provide "amiga/raw/reaction/reaction-prefs")
