;;; amiga/raw/reaction/reaction-prefs  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   reaction/reaction_prefs.h
;;;
;;; 0 functions, 8 constants, 0 structs.
;;; 2 C macros skipped: not an integer constant (string, call, float).
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.REACTION.REACTION-PREFS"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export))

(in-package "AMIGA.RAW.REACTION.REACTION-PREFS")

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.REACTION.REACTION-PREFS" ()

  ;; --- constants from reaction/reaction_prefs.h ---
  (:const "+BVT-GT+" 0)
  (:const "+BVT-THIN+" 1)
  (:const "+BVT-THICK+" 2)
  (:const "+BVT-XEN+" 3)
  (:const "+BVT-XENTHIN+" 4)
  (:const "+GLT-GT+" 0)
  (:const "+GLT-FLAT+" 1)
  (:const "+GLT-3-D+" 2)
  )

(provide "amiga/raw/reaction/reaction-prefs")
