;;; amiga/raw/images/bevel  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   bevel_lib.sfd ($VER: bevel_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK bevel_lib.fd + clib/bevel_protos.h (via fd2sfd)
;;;   images/bevel.h
;;;
;;; 1 functions, 47 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.IMAGES.BEVEL"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export "*BEVEL-BASE*" "*BEVEL-VERSION*"))

(in-package "AMIGA.RAW.IMAGES.BEVEL")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *bevel-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "images/bevel.image" 0)))
(defvar *bevel-version*
  (and *bevel-base* (amiga.ffi:library-version *bevel-base*)))
(defun %version>= (n)
  (and *bevel-version* (>= *bevel-version* n)))

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.IMAGES.BEVEL"
    (:base *bevel-base* :version *bevel-version*)

  ;; --- constants from images/bevel.h ---
  (:const "+BEVEL-DUMMY+" #x85016000)
  (:const "+BEVEL-STYLE+" #x85016001)
  (:const "+BEVEL-LABEL+" #x85016003)
  (:const "+BEVEL-LABEL-IMAGE+" #x85016004)
  (:const "+BEVEL-LABEL-PLACE+" #x85016005)
  (:const "+BEVEL-INNER-TOP+" #x85016006)
  (:const "+BEVEL-INNER-LEFT+" #x85016007)
  (:const "+BEVEL-INNER-WIDTH+" #x85016008)
  (:const "+BEVEL-INNER-HEIGHT+" #x85016009)
  (:const "+BEVEL-HORIZ-SIZE+" #x8501600A)
  (:const "+BEVEL-HORZ-SIZE+" #x8501600A)
  (:const "+BEVEL-VERT-SIZE+" #x8501600B)
  (:const "+BEVEL-FILL-PEN+" #x8501600C)
  (:const "+BEVEL-FILL-PATTERN+" #x8501600D)
  (:const "+BEVEL-TEXT-PEN+" #x8501600E)
  (:const "+BEVEL-TRANSPARENT+" #x8501600F)
  (:const "+BEVEL-SOFT-STYLE+" #x85016010)
  (:const "+BEVEL-COLOR-MAP+" #x85016011)
  (:const "+BEVEL-COLOUR-MAP+" #x85016011)
  (:const "+BEVEL-FLAGS+" #x85016012)
  (:const "+BVS-THIN+" 0)
  (:const "+BVS-BUTTON+" 1)
  (:const "+BVS-GROUP+" 2)
  (:const "+BVS-FIELD+" 3)
  (:const "+BVS-NONE+" 4)
  (:const "+BVS-DROPBOX+" 5)
  (:const "+BVS-SBAR-HORIZ+" 6)
  (:const "+BVS-SBAR-VERT+" 7)
  (:const "+BVS-BOX+" 8)
  (:const "+BVS-STANDARD+" 11)
  (:const "+BVS-CONTAINER+" 12)
  (:const "+BVS-KNOB+" 13)
  (:const "+BVS-DISPLAY+" 14)
  (:const "+BVS-SBAR-HORZ+" 6)
  (:const "+BVS-FOCUS+" 9)
  (:const "+BVS-RADIOBUTTON+" 10)
  (:const "+BFLG-XENFILL+" 1)
  (:const "+BFLG-TRANS+" 2)
  (:const "+BVJ-TOP-CENTER+" 0)
  (:const "+BVJ-TOP-LEFT+" 1)
  (:const "+BVJ-TOP-RIGHT+" 2)
  (:const "+BVJ-IN-CENTER+" 3)
  (:const "+BVJ-IN-LEFT+" 4)
  (:const "+BVJ-IN-RIGHT+" 5)
  (:const "+BVJ-BOT-CENTER+" 6)
  (:const "+BVJ-BOT-LEFT+" 7)
  (:const "+BVJ-BOT-RIGHT+" 8)

  ;; --- functions (bevel_lib.sfd + MorphOS SDK) ---
  (:fn "BEVEL-GET-CLASS" -30 () :pointer 40)   ; Class * BEVEL_GetClass() () LVO -30
  )

(provide "amiga/raw/images/bevel")
