;;; amiga/raw/images/label  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   label_lib.sfd ($VER: label_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK label_lib.fd + clib/label_protos.h (via fd2sfd)
;;;   images/label.h
;;;
;;; 1 functions, 24 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.IMAGES.LABEL"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*LABEL-BASE*" "*LABEL-VERSION*"
   "+LJ-LEFT+" "+LJ-CENTRE+" "+LJ-RIGHT+" "+LJ-CENTER+" "+LABEL-LEFT+" 
   "+LABEL-CENTRE+" "+LABEL-CENTER+" "+LABEL-RIGHT+" "+LVALIGN-BOTTOM+" 
   "+LVALIGN-BASELINE+" "+LABEL-DUMMY+" "+LABEL-DRAW-INFO+" "+LABEL-TEXT+" 
   "+LABEL-IMAGE+" "+LABEL-MAPPING+" "+LABEL-JUSTIFICATION+" "+LABEL-KEY+" 
   "+LABEL-UNDERSCORE+" "+LABEL-DISPOSE-IMAGE+" "+LABEL-SOFT-STYLE+" 
   "+LABEL-VERTICAL-SPACING+" "+LABEL-VERTICAL-ALIGNMENT+" 
   "+LABEL-WORD-WRAP+" "+LABEL-MENU-MODE+" "LABEL-GET-CLASS" ))

(in-package "AMIGA.RAW.IMAGES.LABEL")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *label-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "images/label.image" 0)))
(defvar *label-version*
  (and *label-base* (amiga.ffi:library-version *label-base*)))
(defun %version>= (n)
  (and *label-version* (>= *label-version* n)))

;;; --- constants from images/label.h ---
(defconstant +lj-left+ 0)
(defconstant +lj-centre+ 1)
(defconstant +lj-right+ 2)
(defconstant +lj-center+ 1)
(defconstant +label-left+ 0)
(defconstant +label-centre+ 1)
(defconstant +label-center+ 1)
(defconstant +label-right+ 2)
(defconstant +lvalign-bottom+ 0)
(defconstant +lvalign-baseline+ 1)
(defconstant +label-dummy+ #x85006000)
(defconstant +label-draw-info+ #x80020018)
(defconstant +label-text+ #x85006001)
(defconstant +label-image+ #x85006002)
(defconstant +label-mapping+ #x85006003)
(defconstant +label-justification+ #x85006004)
(defconstant +label-key+ #x85006005)
(defconstant +label-underscore+ #x85006006)
(defconstant +label-dispose-image+ #x85006007)
(defconstant +label-soft-style+ #x85006008)
(defconstant +label-vertical-spacing+ #x85006009)
(defconstant +label-vertical-alignment+ #x8500600A)
(defconstant +label-word-wrap+ #x8500600B)
(defconstant +label-menu-mode+ #x8500600C)

;;; --- functions (label_lib.sfd + MorphOS SDK) ---
(when (%version>= 40)
  (amiga.ffi:defcfun label-get-class *label-base* -30 ()
    :result :pointer
    :doc "Class * LABEL_GetClass() () LVO -30"))

(provide "amiga/raw/images/label")
