;;; amiga/raw/images/led  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   images/led.i
;;;
;;; 0 functions, 9 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.IMAGES.LED"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "+LED-DUMMY+" "+LED-PAIRS+" "+LED-VALUES+" "+LED-COLON+" 
   "+LED-NEGATIVE+" "+LED-SIGNED+" "+LED-TIME+" "+LED-HEXADECIMAL+" 
   "+LED-RAW+" ))

(in-package "AMIGA.RAW.IMAGES.LED")

;;; --- constants from images/led.i ---
(defconstant +led-dummy+ #x84000000)
(defconstant +led-pairs+ #x84000001)
(defconstant +led-values+ #x84000002)
(defconstant +led-colon+ #x84000003)
(defconstant +led-negative+ #x84000004)
(defconstant +led-signed+ #x84000005)
(defconstant +led-time+ #x84000006)
(defconstant +led-hexadecimal+ #x84000007)
(defconstant +led-raw+ #x84000008)

(provide "amiga/raw/images/led")
