;;; amiga/raw/images/penmap  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   penmap_lib.sfd ($VER: penmap_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK penmap_lib.fd + clib/penmap_protos.h (via fd2sfd)
;;;   images/penmap.h
;;;
;;; 1 functions, 18 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.IMAGES.PENMAP"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*PENMAP-BASE*" "*PENMAP-VERSION*"
   "+PENMAP-DUMMY+" "+PENMAP-SELECT-BG-PEN+" "+PENMAP-SELECT-DATA+" 
   "+PENMAP-RENDER-BG-PEN+" "+PENMAP-RENDER-DATA+" "+PENMAP-PALETTE+" 
   "+PENMAP-SCREEN+" "+PENMAP-IMAGE-TYPE+" "+PENMAP-TRANSPARENT+" 
   "+PENMAP-PRECISION+" "+PENMAP-COLOR-MAP+" "+PENMAP-MASK-BLIT+" 
   "+PENMAP-COMPRESSED+" "+PENMAP-MASK-PLANE+" "+PENMAP-SELECT-MASK-PLANE+" 
   "+IMAGE-CHUNKY+" "+IMAGE-IMAGE+" "+IMAGE-DRAWLIST+" "PENMAP-GET-CLASS" ))

(in-package "AMIGA.RAW.IMAGES.PENMAP")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *penmap-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "images/penmap.image" 0)))
(defvar *penmap-version*
  (and *penmap-base* (amiga.ffi:library-version *penmap-base*)))
(defun %version>= (n)
  (and *penmap-version* (>= *penmap-version* n)))

;;; --- constants from images/penmap.h ---
(defconstant +penmap-dummy+ #x85018000)
(defconstant +penmap-select-bg-pen+ #x85018001)
(defconstant +penmap-select-data+ #x85018002)
(defconstant +penmap-render-bg-pen+ #x80020006)
(defconstant +penmap-render-data+ #x80020007)
(defconstant +penmap-palette+ #x85018003)
(defconstant +penmap-screen+ #x85018004)
(defconstant +penmap-image-type+ #x85018005)
(defconstant +penmap-transparent+ #x85018006)
(defconstant +penmap-precision+ #x85018008)
(defconstant +penmap-color-map+ #x85018009)
(defconstant +penmap-mask-blit+ #x8501800A)
(defconstant +penmap-compressed+ #x8501800B)
(defconstant +penmap-mask-plane+ #x8501800C)
(defconstant +penmap-select-mask-plane+ #x8501800D)
(defconstant +image-chunky+ 0)
(defconstant +image-image+ 1)
(defconstant +image-drawlist+ 2)

;;; --- functions (penmap_lib.sfd + MorphOS SDK) ---
(when (%version>= 40)
  (amiga.ffi:defcfun penmap-get-class *penmap-base* -30 ()
    :result :pointer
    :doc "Class * PENMAP_GetClass() () LVO -30"))

(provide "amiga/raw/images/penmap")
