;;; amiga/raw/images/penmap  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   penmap_lib.sfd ($VER: penmap_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK penmap_lib.fd + clib/penmap_protos.h (via fd2sfd)
;;;   images/penmap.h
;;;
;;; 1 functions, 18 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.IMAGES.PENMAP"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export "*PENMAP-BASE*" "*PENMAP-VERSION*"))

(in-package "AMIGA.RAW.IMAGES.PENMAP")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *penmap-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "images/penmap.image" 0)))
(defvar *penmap-version*
  (and *penmap-base* (amiga.ffi:library-version *penmap-base*)))
(defun %version>= (n)
  (and *penmap-version* (>= *penmap-version* n)))

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.IMAGES.PENMAP"
    (:base *penmap-base* :version *penmap-version*)

  ;; --- constants from images/penmap.h ---
  (:const "+PENMAP-DUMMY+" #x85018000)
  (:const "+PENMAP-SELECT-BG-PEN+" #x85018001)
  (:const "+PENMAP-SELECT-DATA+" #x85018002)
  (:const "+PENMAP-RENDER-BG-PEN+" #x80020006)
  (:const "+PENMAP-RENDER-DATA+" #x80020007)
  (:const "+PENMAP-PALETTE+" #x85018003)
  (:const "+PENMAP-SCREEN+" #x85018004)
  (:const "+PENMAP-IMAGE-TYPE+" #x85018005)
  (:const "+PENMAP-TRANSPARENT+" #x85018006)
  (:const "+PENMAP-PRECISION+" #x85018008)
  (:const "+PENMAP-COLOR-MAP+" #x85018009)
  (:const "+PENMAP-MASK-BLIT+" #x8501800A)
  (:const "+PENMAP-COMPRESSED+" #x8501800B)
  (:const "+PENMAP-MASK-PLANE+" #x8501800C)
  (:const "+PENMAP-SELECT-MASK-PLANE+" #x8501800D)
  (:const "+IMAGE-CHUNKY+" 0)
  (:const "+IMAGE-IMAGE+" 1)
  (:const "+IMAGE-DRAWLIST+" 2)

  ;; --- functions (penmap_lib.sfd + MorphOS SDK) ---
  (:fn "PENMAP-GET-CLASS" -30 () :pointer 40)   ; Class * PENMAP_GetClass() () LVO -30
  )

(provide "amiga/raw/images/penmap")
