;; Run serapeum tests and print failure details for triage.
(require "asdf")
(load "trunk/load-libs-ql.lisp")
(ensure-ql-lib :serapeum)
(asdf:load-system :serapeum)
(asdf:load-system :serapeum/tests)

(let* ((five (find-package "IT.BESE.FIVEAM"))
       (run-sym (and five (find-symbol "RUN" five)))
       (tpkg (find-package "SERAPEUM.TESTS"))
       (suite-sym (and tpkg (find-symbol "SERAPEUM" tpkg)))
       (results (and run-sym suite-sym (funcall run-sym suite-sym)))
       (reason-sym (and five (find-symbol "REASON" five)))
       (tc-sym (and five (find-symbol "TEST-CASE" five)))
       (name-sym (and five (find-symbol "NAME" five))))
  (format t "~%=== FAILURES ===~%")
  (dolist (r results)
    (let ((cn (symbol-name (class-name (class-of r)))))
      (unless (or (search "PASSED" cn) (search "SKIP" cn))
        (let* ((tc (ignore-errors (funcall tc-sym r)))
               (nm (and tc name-sym (ignore-errors (funcall name-sym tc))))
               (reason (ignore-errors (funcall reason-sym r))))
          (format t "~%[~A] ~A~%  ~A~%" cn nm reason))))))
(format t "~%=== done ===~%")
