;;; amiga/raw/classes/arexx  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   arexx_lib.sfd ($VER: arexx_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK arexx_lib.fd + clib/arexx_protos.h (via fd2sfd)
;;;   classes/arexx.h
;;;
;;; 1 functions, 17 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.CLASSES.AREXX"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*AREXX-BASE*" "*AREXX-VERSION*"
   "+AREXX-DUMMY+" "+AREXX-HOST-NAME+" "+AREXX-DEF-EXTENSION+" 
   "+AREXX-COMMANDS+" "+AREXX-ERROR-CODE+" "+AREXX-SIG-MASK+" 
   "+AREXX-NO-SLOT+" "+AREXX-REPLY-HOOK+" "+AREXX-MSG-PORT+" 
   "+RXERR-NO-COMMAND-LIST+" "+RXERR-NO-PORT-NAME+" 
   "+RXERR-PORT-ALREADY-EXISTS+" "+RXERR-OUT-OF-MEMORY+" 
   "+AREXX-DEF-EXTENTION+" "+AM-HANDLEEVENT+" "+AM-EXECUTE+" "+AM-FLUSH+" 
   "AREXX-GET-CLASS" ))

(in-package "AMIGA.RAW.CLASSES.AREXX")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *arexx-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "arexx.class" 0)))
(defvar *arexx-version*
  (and *arexx-base* (amiga.ffi:library-version *arexx-base*)))
(defun %version>= (n)
  (and *arexx-version* (>= *arexx-version* n)))

;;; --- constants from classes/arexx.h ---
(defconstant +arexx-dummy+ #x85030000)
(defconstant +arexx-host-name+ #x85030001)
(defconstant +arexx-def-extension+ #x85030002)
(defconstant +arexx-commands+ #x85030003)
(defconstant +arexx-error-code+ #x85030004)
(defconstant +arexx-sig-mask+ #x85030005)
(defconstant +arexx-no-slot+ #x85030006)
(defconstant +arexx-reply-hook+ #x85030007)
(defconstant +arexx-msg-port+ #x85030008)
(defconstant +rxerr-no-command-list+ 1)
(defconstant +rxerr-no-port-name+ 2)
(defconstant +rxerr-port-already-exists+ 3)
(defconstant +rxerr-out-of-memory+ 4)
(defconstant +arexx-def-extention+ #x85030002)
(defconstant +am-handleevent+ #x590001)
(defconstant +am-execute+ #x590002)
(defconstant +am-flush+ #x590003)

;;; --- functions (arexx_lib.sfd + MorphOS SDK) ---
(when (%version>= 40)
  (amiga.ffi:defcfun arexx-get-class *arexx-base* -30 ()
    :result :pointer
    :doc "Class * AREXX_GetClass() () LVO -30"))

(provide "amiga/raw/classes/arexx")
