;;; amiga/raw/classes/requester  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   requester_lib.sfd ($VER: requester_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK requester_lib.fd + clib/requester_protos.h (via fd2sfd)
;;;   classes/requester.h
;;;
;;; 1 functions, 62 constants, 0 structs.
;;; 1 C macro skipped: not an integer constant (string, call, float).
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.CLASSES.REQUESTER"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*REQUESTER-BASE*" "*REQUESTER-VERSION*"
   "+REQ-DUMMY+" "+REQS-DUMMY+" "+REQI-DUMMY+" "+REQP-DUMMY+" "+REQ-TYPE+" 
   "+REQ-TITLE-TEXT+" "+REQ-BODY-TEXT+" "+REQ-GADGET-TEXT+" 
   "+REQ-RETURN-CODE+" "+REQ-TAB-SIZE+" "+REQ-IMAGE+" "+REQ-VAR-ARGS+" 
   "+REQ-EVEN-BUTTONS+" "+REQ-WRAP-BORDER+" "+REQ-TIME-OUT-SECS+" 
   "+REQ-IDCMP-PTR+" "+REQ-INACTIVE+" "+REQ-CHAR-SET+" "+REQ-STAY-ON-TOP+" 
   "+REQ-FORCE-FOCUS+" "+REQI-MINIMUM+" "+REQI-MAXIMUM+" "+REQI-INVISIBLE+" 
   "+REQI-NUMBER+" "+REQI-ARROWS+" "+REQI-MAX-CHARS+" "+REQI-MIN-TEXT+" 
   "+REQI-MAX-TEXT+" "+REQI-MARK+" "+REQI-RETURN-ENDS+" 
   "+REQS-ALLOW-EMPTY+" "+REQS-INVISIBLE+" "+REQS-BUFFER+" 
   "+REQS-SHOW-DEFAULT+" "+REQS-MAX-CHARS+" "+REQS-CHOOSER-ARRAY+" 
   "+REQS-CHOOSER-ACTIVE+" "+REQS-MARK+" "+REQS-RETURN-ENDS+" 
   "+REQP-TOTAL+" "+REQP-CURRENT+" "+REQP-ABORT-TEXT+" 
   "+REQP-PROGRESS-TEXT+" "+REQP-OPEN-INACTIVE+" "+REQP-NO-TEXT+" 
   "+REQP-DYNAMIC+" "+REQP-CENTER-WINDOW+" "+REQP-LAST-POSITION+" 
   "+REQP-PERCENT+" "+REQP-TICKS+" "+REQP-SHORT-TICKS+" "+RM-OPENREQ+" 
   "+REQTYPE-INFO+" "+REQTYPE-INTEGER+" "+REQTYPE-STRING+" 
   "+REQTYPE-PROGRESS+" "+REQIMAGE-DEFAULT+" "+REQIMAGE-INFO+" 
   "+REQIMAGE-WARNING+" "+REQIMAGE-ERROR+" "+REQIMAGE-QUESTION+" 
   "+REQIMAGE-INSERTDISK+" "REQUESTER-GET-CLASS" ))

(in-package "AMIGA.RAW.CLASSES.REQUESTER")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *requester-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "requester.class" 0)))
(defvar *requester-version*
  (and *requester-base* (amiga.ffi:library-version *requester-base*)))
(defun %version>= (n)
  (and *requester-version* (>= *requester-version* n)))

;;; --- constants from classes/requester.h ---
(defconstant +req-dummy+ #x85045000)
(defconstant +reqs-dummy+ #x85045100)
(defconstant +reqi-dummy+ #x85045200)
(defconstant +reqp-dummy+ #x85045300)
(defconstant +req-type+ #x85045001)
(defconstant +req-title-text+ #x85045002)
(defconstant +req-body-text+ #x85045003)
(defconstant +req-gadget-text+ #x85045004)
(defconstant +req-return-code+ #x85045005)
(defconstant +req-tab-size+ #x85045006)
(defconstant +req-image+ #x85045007)
(defconstant +req-var-args+ #x85045008)
(defconstant +req-even-buttons+ #x85045009)
(defconstant +req-wrap-border+ #x8504500A)
(defconstant +req-time-out-secs+ #x8504500B)
(defconstant +req-idcmp-ptr+ #x8504500C)
(defconstant +req-inactive+ #x8504500D)
(defconstant +req-char-set+ #x8504500E)
(defconstant +req-stay-on-top+ #x8504500F)
(defconstant +req-force-focus+ #x85045010)
(defconstant +reqi-minimum+ #x85045201)
(defconstant +reqi-maximum+ #x85045202)
(defconstant +reqi-invisible+ #x85045203)
(defconstant +reqi-number+ #x85045204)
(defconstant +reqi-arrows+ #x85045205)
(defconstant +reqi-max-chars+ #x85045206)
(defconstant +reqi-min-text+ #x85045207)
(defconstant +reqi-max-text+ #x85045208)
(defconstant +reqi-mark+ #x85045209)
(defconstant +reqi-return-ends+ #x8504520A)
(defconstant +reqs-allow-empty+ #x85045101)
(defconstant +reqs-invisible+ #x85045203)
(defconstant +reqs-buffer+ #x85045102)
(defconstant +reqs-show-default+ #x85045103)
(defconstant +reqs-max-chars+ #x85045104)
(defconstant +reqs-chooser-array+ #x85045105)
(defconstant +reqs-chooser-active+ #x85045106)
(defconstant +reqs-mark+ #x85045107)
(defconstant +reqs-return-ends+ #x85045108)
(defconstant +reqp-total+ #x85045301)
(defconstant +reqp-current+ #x85045302)
(defconstant +reqp-abort-text+ #x85045004)
(defconstant +reqp-progress-text+ #x85045003)
(defconstant +reqp-open-inactive+ #x85045303)
(defconstant +reqp-no-text+ #x85045304)
(defconstant +reqp-dynamic+ #x85045305)
(defconstant +reqp-center-window+ #x85045306)
(defconstant +reqp-last-position+ #x85045307)
(defconstant +reqp-percent+ #x85045308)
(defconstant +reqp-ticks+ #x85045309)
(defconstant +reqp-short-ticks+ #x8504530A)
(defconstant +rm-openreq+ #x650001)
(defconstant +reqtype-info+ 0)
(defconstant +reqtype-integer+ 1)
(defconstant +reqtype-string+ 2)
(defconstant +reqtype-progress+ 3)
(defconstant +reqimage-default+ 0)
(defconstant +reqimage-info+ 1)
(defconstant +reqimage-warning+ 2)
(defconstant +reqimage-error+ 3)
(defconstant +reqimage-question+ 4)
(defconstant +reqimage-insertdisk+ 5)

;;; --- functions (requester_lib.sfd + MorphOS SDK) ---
(when (%version>= 40)
  (amiga.ffi:defcfun requester-get-class *requester-base* -30 ()
    :result :pointer
    :doc "Class * REQUESTER_GetClass() () LVO -30"))

(provide "amiga/raw/classes/requester")
