;;; amiga/raw/devices/audio  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   devices/audio.i
;;;
;;; 0 functions, 21 constants, 1 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.DEVICES.AUDIO"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export))

(in-package "AMIGA.RAW.DEVICES.AUDIO")

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.DEVICES.AUDIO" ()

  ;; --- constants from devices/audio.i ---
  (:const "+ADHARD-CHANNELS+" 4)
  (:const "+ADALLOC-MINPREC+" -128)
  (:const "+ADALLOC-MAXPREC+" #x7F)
  (:const "+ADCMD-FREE+" 9)
  (:const "+ADCMD-SETPREC+" 10)
  (:const "+ADCMD-FINISH+" 11)
  (:const "+ADCMD-PERVOL+" 12)
  (:const "+ADCMD-LOCK+" 13)
  (:const "+ADCMD-WAITCYCLE+" 14)
  (:const "+ADCMD-ALLOCATE+" #x20)
  (:const "+ADIOB-PERVOL+" 4)
  (:const "+ADIOF-PERVOL+" #x10)
  (:const "+ADIOB-SYNCCYCLE+" 5)
  (:const "+ADIOF-SYNCCYCLE+" #x20)
  (:const "+ADIOB-NOWAIT+" 6)
  (:const "+ADIOF-NOWAIT+" #x40)
  (:const "+ADIOB-WRITEMESSAGE+" 7)
  (:const "+ADIOF-WRITEMESSAGE+" #x80)
  (:const "+ADIOERR-NOALLOCATION+" -10)
  (:const "+ADIOERR-ALLOCFAILED+" -11)
  (:const "+ADIOERR-CHANNELSTOLEN+" -12)

  ;; --- structures from devices/audio.i ---
  (:struct "IO-AUDIO" 68   ; IOAudio (devices/audio.i)
    ("ALLOC-KEY" :i16 32)
    ("DATA" :fptr 34)
    ("LENGTH" :u32 38)
    ("PERIOD" :u16 42)
    ("VOLUME" :u16 44)
    ("CYCLES" :u16 46)
    ("WRITE-MSG" (:struct 20) 48)
    )
  )

(provide "amiga/raw/devices/audio")
