;;; amiga/raw/devices/bootblock  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   devices/bootblock.i
;;;
;;; 0 functions, 3 constants, 1 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.DEVICES.BOOTBLOCK"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "+BOOTSECTS+" "+BBNAME-DOS+" "+BBNAME-KICK+" "*BB-SIZE*" "BB-ID" 
   "BB-CHKSUM" "BB-DOSBLOCK" ))

(in-package "AMIGA.RAW.DEVICES.BOOTBLOCK")

;;; --- constants from devices/bootblock.i ---
(defconstant +bootsects+ 2)
(defconstant +bbname-dos+ #x444F5300)
(defconstant +bbname-kick+ #x4B49434B)

;;; --- structures from devices/bootblock.i ---
(ffi:defcstruct (bb :size 12)   ; BB (devices/bootblock.i)
  (id (:struct 4) 0)
  (chksum :i32 4)
  (dosblock :i32 8)
)

(provide "amiga/raw/devices/bootblock")
