;;; amiga/raw/devices/clipboard  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   devices/clipboard.i
;;;
;;; 0 functions, 7 constants, 4 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.DEVICES.CLIPBOARD"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export))

(in-package "AMIGA.RAW.DEVICES.CLIPBOARD")

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.DEVICES.CLIPBOARD" ()

  ;; --- constants from devices/clipboard.i ---
  (:const "+DEVICES-CLIPBOARD-I+" 1)
  (:const "+CBD-POST+" 9)
  (:const "+CBD-CURRENTREADID+" 10)
  (:const "+CBD-CURRENTWRITEID+" 11)
  (:const "+CBD-CHANGEHOOK+" 12)
  (:const "+CBERR-OBSOLETEID+" 1)
  (:const "+PRIMARY-CLIP+" 0)

  ;; --- structures from devices/clipboard.i ---
  (:struct "CLIPBOARD-UNIT-PARTIAL" 18   ; ClipboardUnitPartial (devices/clipboard.i)
    ("NODE" (:struct 14) 0)
    ("UNIT-NUM" :u32 14)
    )
  (:struct "IO-CLIP-REQ" 52   ; IOClipReq (devices/clipboard.i)
    ("MESSAGE" (:struct 20) 0)
    ("DEVICE" :fptr 20)
    ("UNIT" :fptr 24)
    ("COMMAND" :u16 28)
    ("FLAGS" :u8 30)
    ("ERROR" :i8 31)
    ("ACTUAL" :u32 32)
    ("LENGTH" :u32 36)
    ("DATA" :fptr 40)
    ("OFFSET" :u32 44)
    ("CLIP-ID" :i32 48)
    )
  (:struct "SATISFY-MSG" 26   ; SatisfyMsg (devices/clipboard.i)
    ("MSG" (:struct 20) 0)
    ("UNIT" :u16 20)
    ("CLIP-ID" :i32 22)
    )
  (:struct "CLIP-HOOK-MSG" 12   ; ClipHookMsg (devices/clipboard.i)
    ("TYPE" :u32 0)
    ("CHANGE-CMD" :i32 4)
    ("CLIP-ID" :i32 8)
    )
  )

(provide "amiga/raw/devices/clipboard")
