;;; amiga/raw/devices/gameport  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   devices/gameport.i
;;;
;;; 0 functions, 15 constants, 1 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.DEVICES.GAMEPORT"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "+GPD-READEVENT+" "+GPD-ASKCTYPE+" "+GPD-SETCTYPE+" "+GPD-ASKTRIGGER+" 
   "+GPD-SETTRIGGER+" "+GPTB-DOWNKEYS+" "+GPTF-DOWNKEYS+" "+GPTB-UPKEYS+" 
   "+GPTF-UPKEYS+" "+GPCT-ALLOCATED+" "+GPCT-NOCONTROLLER+" "+GPCT-MOUSE+" 
   "+GPCT-RELJOYSTICK+" "+GPCT-ABSJOYSTICK+" "+GPDERR-SETCTYPE+" 
   "*GAME-PORT-TRIGGER-SIZE*" "GAME-PORT-TRIGGER-KEYS" 
   "GAME-PORT-TRIGGER-TIMEOUT" "GAME-PORT-TRIGGER-X-DELTA" 
   "GAME-PORT-TRIGGER-Y-DELTA" ))

(in-package "AMIGA.RAW.DEVICES.GAMEPORT")

;;; --- constants from devices/gameport.i ---
(defconstant +gpd-readevent+ 9)
(defconstant +gpd-askctype+ 10)
(defconstant +gpd-setctype+ 11)
(defconstant +gpd-asktrigger+ 12)
(defconstant +gpd-settrigger+ 13)
(defconstant +gptb-downkeys+ 0)
(defconstant +gptf-downkeys+ 1)
(defconstant +gptb-upkeys+ 1)
(defconstant +gptf-upkeys+ 2)
(defconstant +gpct-allocated+ -1)
(defconstant +gpct-nocontroller+ 0)
(defconstant +gpct-mouse+ 1)
(defconstant +gpct-reljoystick+ 2)
(defconstant +gpct-absjoystick+ 3)
(defconstant +gpderr-setctype+ 1)

;;; --- structures from devices/gameport.i ---
(ffi:defcstruct (game-port-trigger :size 8)   ; GamePortTrigger (devices/gameport.i)
  (keys :u16 0)
  (timeout :u16 2)
  (x-delta :u16 4)
  (y-delta :u16 6)
)

(provide "amiga/raw/devices/gameport")
