;;; amiga/raw/devices/gameport  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   devices/gameport.i
;;;
;;; 0 functions, 15 constants, 1 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.DEVICES.GAMEPORT"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export))

(in-package "AMIGA.RAW.DEVICES.GAMEPORT")

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.DEVICES.GAMEPORT" ()

  ;; --- constants from devices/gameport.i ---
  (:const "+GPD-READEVENT+" 9)
  (:const "+GPD-ASKCTYPE+" 10)
  (:const "+GPD-SETCTYPE+" 11)
  (:const "+GPD-ASKTRIGGER+" 12)
  (:const "+GPD-SETTRIGGER+" 13)
  (:const "+GPTB-DOWNKEYS+" 0)
  (:const "+GPTF-DOWNKEYS+" 1)
  (:const "+GPTB-UPKEYS+" 1)
  (:const "+GPTF-UPKEYS+" 2)
  (:const "+GPCT-ALLOCATED+" -1)
  (:const "+GPCT-NOCONTROLLER+" 0)
  (:const "+GPCT-MOUSE+" 1)
  (:const "+GPCT-RELJOYSTICK+" 2)
  (:const "+GPCT-ABSJOYSTICK+" 3)
  (:const "+GPDERR-SETCTYPE+" 1)

  ;; --- structures from devices/gameport.i ---
  (:struct "GAME-PORT-TRIGGER" 8   ; GamePortTrigger (devices/gameport.i)
    ("KEYS" :u16 0)
    ("TIMEOUT" :u16 2)
    ("X-DELTA" :u16 4)
    ("Y-DELTA" :u16 6)
    )
  )

(provide "amiga/raw/devices/gameport")
