;;; amiga/raw/devices/narrator  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   devices/narrator.i
;;;
;;; 0 functions, 50 constants, 2 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.DEVICES.NARRATOR"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "+DEFPITCH+" "+DEFRATE+" "+DEFVOL+" "+DEFFREQ+" "+NATURALF0+" 
   "+ROBOTICF0+" "+MANUALF0+" "+MALE+" "+FEMALE+" "+DEFSEX+" "+DEFMODE+" 
   "+DEFARTIC+" "+DEFCENTRAL+" "+DEFF0-PERT+" "+DEFF0-ENTHUS+" 
   "+DEFPRIORITY+" "+MINRATE+" "+MAXRATE+" "+MINPITCH+" "+MAXPITCH+" 
   "+MINFREQ+" "+MAXFREQ+" "+MINVOL+" "+MAXVOL+" "+MINCENT+" "+MAXCENT+" 
   "+ND-NOT-USED+" "+ND-NO-MEM+" "+ND-NO-AUD-LIB+" "+ND-MAKE-BAD+" 
   "+ND-UNIT-ERR+" "+ND-CANT-ALLOC+" "+ND-UNIMPL+" "+ND-NO-WRITE+" 
   "+ND-EXPUNGED+" "+ND-PHON-ERR+" "+ND-RATE-ERR+" "+ND-PITCH-ERR+" 
   "+ND-SEX-ERR+" "+ND-MODE-ERR+" "+ND-FREQ-ERR+" "+ND-VOL-ERR+" 
   "+ND-D-CENT-ERR+" "+ND-CENT-PHON-ERR+" "+NDB-NEWIORB+" "+NDB-WORDSYNC+" 
   "+NDB-SYLSYNC+" "+NDF-NEWIORB+" "+NDF-WORDSYNC+" "+NDF-SYLSYNC+" 
   "*NDI-SIZE*" "NDI-RATE" "NDI-PITCH" "NDI-MODE" "NDI-SEX" "NDI-CHMASKS" 
   "NDI-NUMMASKS" "NDI-VOLUME" "NDI-SAMPFREQ" "NDI-MOUTHS" "NDI-CHANMASK" 
   "NDI-NUMCHAN" "NDI-FLAGS" "NDI-F0-ENTHUSIASM" "NDI-F0-PERTURB" 
   "NDI-F1-ADJ" "NDI-F2-ADJ" "NDI-F3-ADJ" "NDI-A1-ADJ" "NDI-A2-ADJ" 
   "NDI-A3-ADJ" "NDI-ARTICULATE" "NDI-CENTRALIZE" "NDI-CENTPHON" 
   "NDI-AVBIAS" "NDI-AFBIAS" "NDI-PRIORITY" "NDI-PAD1" "*MRB-SIZE*" 
   "MRB-WIDTH" "MRB-HEIGHT" "MRB-SHAPE" "MRB-SYNC" ))

(in-package "AMIGA.RAW.DEVICES.NARRATOR")

;;; --- constants from devices/narrator.i ---
(defconstant +defpitch+ #x6E)
(defconstant +defrate+ #x96)
(defconstant +defvol+ #x40)
(defconstant +deffreq+ #x56B8)
(defconstant +naturalf0+ 0)
(defconstant +roboticf0+ 1)
(defconstant +manualf0+ 2)
(defconstant +male+ 0)
(defconstant +female+ 1)
(defconstant +defsex+ 0)
(defconstant +defmode+ 0)
(defconstant +defartic+ #x64)
(defconstant +defcentral+ 0)
(defconstant +deff0-pert+ 0)
(defconstant +deff0-enthus+ #x20)
(defconstant +defpriority+ #x64)
(defconstant +minrate+ #x28)
(defconstant +maxrate+ #x190)
(defconstant +minpitch+ #x41)
(defconstant +maxpitch+ #x140)
(defconstant +minfreq+ #x1388)
(defconstant +maxfreq+ #x6D60)
(defconstant +minvol+ 0)
(defconstant +maxvol+ #x40)
(defconstant +mincent+ 0)
(defconstant +maxcent+ #x64)
(defconstant +nd-not-used+ -1)
(defconstant +nd-no-mem+ -2)
(defconstant +nd-no-aud-lib+ -3)
(defconstant +nd-make-bad+ -4)
(defconstant +nd-unit-err+ -5)
(defconstant +nd-cant-alloc+ -6)
(defconstant +nd-unimpl+ -7)
(defconstant +nd-no-write+ -8)
(defconstant +nd-expunged+ -9)
(defconstant +nd-phon-err+ -20)
(defconstant +nd-rate-err+ -21)
(defconstant +nd-pitch-err+ -22)
(defconstant +nd-sex-err+ -23)
(defconstant +nd-mode-err+ -24)
(defconstant +nd-freq-err+ -25)
(defconstant +nd-vol-err+ -26)
(defconstant +nd-d-cent-err+ -27)
(defconstant +nd-cent-phon-err+ -28)
(defconstant +ndb-newiorb+ 0)
(defconstant +ndb-wordsync+ 1)
(defconstant +ndb-sylsync+ 2)
(defconstant +ndf-newiorb+ 1)
(defconstant +ndf-wordsync+ 2)
(defconstant +ndf-sylsync+ 4)

;;; --- structures from devices/narrator.i ---
(ffi:defcstruct (ndi :size 88)   ; NDI (devices/narrator.i)
  (rate :u16 48)
  (pitch :u16 50)
  (mode :u16 52)
  (sex :u16 54)
  (chmasks :fptr 56)
  (nummasks :u16 60)
  (volume :u16 62)
  (sampfreq :u16 64)
  (mouths :u8 66)
  (chanmask :u8 67)
  (numchan :u8 68)
  (flags :u8 69)
  (f0-enthusiasm :u8 70)
  (f0-perturb :i8 71)
  (f1-adj :i8 72)
  (f2-adj :i8 73)
  (f3-adj :i8 74)
  (a1-adj :i8 75)
  (a2-adj :i8 76)
  (a3-adj :i8 77)
  (articulate :u8 78)
  (centralize :u8 79)
  (centphon :fptr 80)
  (avbias :i8 84)
  (afbias :i8 85)
  (priority :i8 86)
  (pad1 :i8 87)
)
(ffi:defcstruct (mrb :size 92)   ; MRB (devices/narrator.i)
  (width :u8 88)
  (height :u8 89)
  (shape :u8 90)
  (sync :u8 91)
)

(provide "amiga/raw/devices/narrator")
