;;; amiga/raw/devices/newstyle  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   devices/newstyle.i
;;;
;;; 0 functions, 19 constants, 1 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.DEVICES.NEWSTYLE"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export))

(in-package "AMIGA.RAW.DEVICES.NEWSTYLE")

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.DEVICES.NEWSTYLE" ()

  ;; --- constants from devices/newstyle.i ---
  (:const "+NSCMD-DEVICEQUERY+" #x4000)
  (:const "+NSDEVTYPE-UNKNOWN+" 0)
  (:const "+NSDEVTYPE-GAMEPORT+" 1)
  (:const "+NSDEVTYPE-TIMER+" 2)
  (:const "+NSDEVTYPE-KEYBOARD+" 3)
  (:const "+NSDEVTYPE-INPUT+" 4)
  (:const "+NSDEVTYPE-TRACKDISK+" 5)
  (:const "+NSDEVTYPE-CONSOLE+" 6)
  (:const "+NSDEVTYPE-SANA2+" 7)
  (:const "+NSDEVTYPE-AUDIOARD+" 8)
  (:const "+NSDEVTYPE-CLIPBOARD+" 9)
  (:const "+NSDEVTYPE-PRINTER+" 10)
  (:const "+NSDEVTYPE-SERIAL+" 11)
  (:const "+NSDEVTYPE-PARALLEL+" 12)
  (:const "+NSCMD-TD-READ64+" #xC000)
  (:const "+NSCMD-TD-WRITE64+" #xC001)
  (:const "+NSCMD-TD-SEEK64+" #xC002)
  (:const "+NSCMD-TD-FORMAT64+" #xC003)
  (:const "+IO-HIGHOFFSET+" #x20)

  ;; --- structures from devices/newstyle.i ---
  (:struct "NS-DEVICE-QUERY-RESULT" 16   ; NSDeviceQueryResult (devices/newstyle.i)
    ("DEV-QUERY-FORMAT" :u32 0)
    ("SIZE-AVAILABLE" :u32 4)
    ("DEVICE-TYPE" :u16 8)
    ("DEVICE-SUB-TYPE" :u16 10)
    ("SUPPORTED-COMMANDS" :fptr 12)
    )
  )

(provide "amiga/raw/devices/newstyle")
