;;; amiga/raw/prefs/font  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   prefs/font.i
;;;
;;; 0 functions, 5 constants, 1 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.PREFS.FONT"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export))

(in-package "AMIGA.RAW.PREFS.FONT")

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.PREFS.FONT" ()

  ;; --- constants from prefs/font.i ---
  (:const "+ID-FONT+" #x464F4E54)
  (:const "+FONTNAMESIZE+" #x80)
  (:const "+FP-WBFONT+" 0)
  (:const "+FP-SYSFONT+" 1)
  (:const "+FP-SCREENFONT+" 2)

  ;; --- structures from prefs/font.i ---
  (:struct "FONT-PREFS" 156   ; FontPrefs (prefs/font.i)
    ("RESERVED" (:struct 12) 0)
    ("RESERVED2" :u16 12)
    ("TYPE" :u16 14)
    ("FRONT-PEN" :u8 16)
    ("BACK-PEN" :u8 17)
    ("DRAW-MODE" :u8 18)
    ("SPECIAL-DRAW-MODE" :u8 19)
    ("TEXT-ATTR" (:struct 8) 20)
    ("NAME" (:struct 128) 28)
    )
  )

(provide "amiga/raw/prefs/font")
