;;; amiga/raw/prefs/icontrol  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   prefs/icontrol.i
;;;
;;; 0 functions, 13 constants, 1 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.PREFS.ICONTROL"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export))

(in-package "AMIGA.RAW.PREFS.ICONTROL")

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.PREFS.ICONTROL" ()

  ;; --- constants from prefs/icontrol.i ---
  (:const "+ID-ICTL+" #x4943544C)
  (:const "+ICB-COERCE-COLORS+" 0)
  (:const "+ICF-COERCE-COLORS+" 1)
  (:const "+ICB-COERCE-LACE+" 1)
  (:const "+ICF-COERCE-LACE+" 2)
  (:const "+ICB-STRGAD-FILTER+" 2)
  (:const "+ICF-STRGAD-FILTER+" 4)
  (:const "+ICB-MENUSNAP+" 3)
  (:const "+ICF-MENUSNAP+" 8)
  (:const "+ICB-MODEPROMOTE+" 4)
  (:const "+ICF-MODEPROMOTE+" #x10)
  (:const "+ICB-OFFSCRNWIN+" 15)
  (:const "+ICF-OFFSCRNWIN+" #x8000)

  ;; --- structures from prefs/icontrol.i ---
  (:struct "I-CONTROL-PREFS" 28   ; IControlPrefs (prefs/icontrol.i)
    ("RESERVED" (:struct 16) 0)
    ("TIME-OUT" :u16 16)
    ("META-DRAG" :i16 18)
    ("FLAGS" :u32 20)
    ("W-BTO-FRONT" :u8 24)
    ("FRONT-TO-BACK" :u8 25)
    ("REQ-TRUE" :u8 26)
    ("REQ-FALSE" :u8 27)
    )
  )

(provide "amiga/raw/prefs/icontrol")
