;;; amiga/raw/prefs/locale  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   prefs/locale.i
;;;
;;; 0 functions, 2 constants, 2 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.PREFS.LOCALE"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export))

(in-package "AMIGA.RAW.PREFS.LOCALE")

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.PREFS.LOCALE" ()

  ;; --- constants from prefs/locale.i ---
  (:const "+ID-LCLE+" #x4C434C45)
  (:const "+ID-CTRY+" #x43545259)

  ;; --- structures from prefs/locale.i ---
  (:struct "COUNTRY-PREFS" 504   ; CountryPrefs (prefs/locale.i)
    ("RESERVED" (:struct 16) 0)
    ("COUNTRY-CODE" :u32 16)
    ("TELEPHONE-CODE" :u32 20)
    ("MEASURING-SYSTEM" :u8 24)
    ("DATE-TIME-FORMAT" (:struct 80) 25)
    ("DATE-FORMAT" (:struct 40) 105)
    ("TIME-FORMAT" (:struct 40) 145)
    ("SHORT-DATE-TIME-FORMAT" (:struct 80) 185)
    ("SHORT-DATE-FORMAT" (:struct 40) 265)
    ("SHORT-TIME-FORMAT" (:struct 40) 305)
    ("DECIMAL-POINT" (:struct 10) 345)
    ("GROUP-SEPARATOR" (:struct 10) 355)
    ("FRAC-GROUP-SEPARATOR" (:struct 10) 365)
    ("GROUPING" (:struct 10) 375)
    ("FRAC-GROUPING" (:struct 10) 385)
    ("MON-DECIMAL-POINT" (:struct 10) 395)
    ("MON-GROUP-SEPARATOR" (:struct 10) 405)
    ("MON-FRAC-GROUP-SEPARATOR" (:struct 10) 415)
    ("MON-GROUPING" (:struct 10) 425)
    ("MON-FRAC-GROUPING" (:struct 10) 435)
    ("MON-FRAC-DIGITS" :u8 445)
    ("MON-INT-FRAC-DIGITS" :u8 446)
    ("MON-CS" (:struct 10) 447)
    ("MON-SMALL-CS" (:struct 10) 457)
    ("MON-INT-CS" (:struct 10) 467)
    ("MON-POSITIVE-SIGN" (:struct 10) 477)
    ("MON-POSITIVE-SPACE-SEP" :u8 487)
    ("MON-POSITIVE-SIGN-POS" :u8 488)
    ("MON-POSITIVE-CS-POS" :u8 489)
    ("MON-NEGATIVE-SIGN" (:struct 10) 490)
    ("MON-NEGATIVE-SPACE-SEP" :u8 500)
    ("MON-NEGATIVE-SIGN-POS" :u8 501)
    ("MON-NEGATIVE-CS-POS" :u8 502)
    ("CALENDAR-TYPE" :u8 503)
    )
  (:struct "LOCALE-PREFS" 860   ; LocalePrefs (prefs/locale.i)
    ("RESERVED" (:struct 16) 0)
    ("COUNTRY-NAME" (:struct 32) 16)
    ("PREFERRED-LANGUAGES" (:struct 300) 48)
    ("GMT-OFFSET" :i32 348)
    ("FLAGS" :u32 352)
    ("COUNTRY-DATA" (:struct 504) 356)
    )
  )

(provide "amiga/raw/prefs/locale")
