;;; amiga/raw/prefs/overscan  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   prefs/overscan.i
;;;
;;; 0 functions, 2 constants, 1 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.PREFS.OVERSCAN"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "+ID-OSCN+" "+OSCAN-MAGIC+" "*OVERSCAN-PREFS-SIZE*" 
   "OVERSCAN-PREFS-RESERVED" "OVERSCAN-PREFS-MAGIC" 
   "OVERSCAN-PREFS-H-START" "OVERSCAN-PREFS-H-STOP" 
   "OVERSCAN-PREFS-V-START" "OVERSCAN-PREFS-V-STOP" 
   "OVERSCAN-PREFS-DISPLAY-ID" "OVERSCAN-PREFS-VIEW-POS" 
   "OVERSCAN-PREFS-TEXT" "OVERSCAN-PREFS-STANDARD" ))

(in-package "AMIGA.RAW.PREFS.OVERSCAN")

;;; --- constants from prefs/overscan.i ---
(defconstant +id-oscn+ #x4F53434E)
(defconstant +oscan-magic+ #xFEDCBA89)

;;; --- structures from prefs/overscan.i ---
(ffi:defcstruct (overscan-prefs :size 36)   ; OverscanPrefs (prefs/overscan.i)
  (reserved :u32 0)
  (magic :u32 4)
  (h-start :u16 8)
  (h-stop :u16 10)
  (v-start :u16 12)
  (v-stop :u16 14)
  (display-id :u32 16)
  (view-pos (:struct 4) 20)
  (text (:struct 4) 24)
  (standard (:struct 8) 28)
)

(provide "amiga/raw/prefs/overscan")
