;;; amiga/raw/prefs/palette  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   prefs/palette.i
;;;
;;; 0 functions, 1 constants, 1 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.PREFS.PALETTE"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "+ID-PALT+" "*PALETTE-PREFS-SIZE*" "PALETTE-PREFS-RESERVED" 
   "PALETTE-PREFS-4-COLOR-PENS" "PALETTE-PREFS-8-COLOR-PENS" 
   "PALETTE-PREFS-COLORS" ))

(in-package "AMIGA.RAW.PREFS.PALETTE")

;;; --- constants from prefs/palette.i ---
(defconstant +id-palt+ #x50414C54)

;;; --- structures from prefs/palette.i ---
(ffi:defcstruct (palette-prefs :size 400)   ; PalettePrefs (prefs/palette.i)
  (reserved (:struct 16) 0)
  (4-color-pens (:struct 64) 16)
  (8-color-pens (:struct 64) 80)
  (colors (:struct 256) 144)
)

(provide "amiga/raw/prefs/palette")
