;;; amiga/raw/prefs/prefhdr  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   prefs/prefhdr.i
;;;
;;; 0 functions, 2 constants, 1 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.PREFS.PREFHDR"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export))

(in-package "AMIGA.RAW.PREFS.PREFHDR")

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.PREFS.PREFHDR" ()

  ;; --- constants from prefs/prefhdr.i ---
  (:const "+ID-PREF+" #x50524546)
  (:const "+ID-PRHD+" #x50524844)

  ;; --- structures from prefs/prefhdr.i ---
  (:struct "PREF-HEADER" 6   ; PrefHeader (prefs/prefhdr.i)
    ("VERSION" :u8 0)
    ("TYPE" :u8 1)
    ("FLAGS" :u32 2)
    )
  )

(provide "amiga/raw/prefs/prefhdr")
