;;; amiga/raw/prefs/prefhdr  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   prefs/prefhdr.i
;;;
;;; 0 functions, 2 constants, 1 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.PREFS.PREFHDR"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "+ID-PREF+" "+ID-PRHD+" "*PREF-HEADER-SIZE*" "PREF-HEADER-VERSION" 
   "PREF-HEADER-TYPE" "PREF-HEADER-FLAGS" ))

(in-package "AMIGA.RAW.PREFS.PREFHDR")

;;; --- constants from prefs/prefhdr.i ---
(defconstant +id-pref+ #x50524546)
(defconstant +id-prhd+ #x50524844)

;;; --- structures from prefs/prefhdr.i ---
(ffi:defcstruct (pref-header :size 6)   ; PrefHeader (prefs/prefhdr.i)
  (version :u8 0)
  (type :u8 1)
  (flags :u32 2)
)

(provide "amiga/raw/prefs/prefhdr")
