;;; amiga/raw/prefs/reaction  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   prefs/reaction.h
;;;
;;; 0 functions, 1 constants, 0 structs.
;;; 1 C macro skipped: not an integer constant (string, call, float).
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.PREFS.REACTION"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "+FONTNAMESIZE+" ))

(in-package "AMIGA.RAW.PREFS.REACTION")

;;; --- constants from prefs/reaction.h ---
(defconstant +fontnamesize+ #x80)

(provide "amiga/raw/prefs/reaction")
