;;; amiga/raw/prefs/screenmode  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   prefs/screenmode.i
;;;
;;; 0 functions, 3 constants, 1 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.PREFS.SCREENMODE"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "+ID-SCRM+" "+SMB-AUTOSCROLL+" "+SMF-AUTOSCROLL+" 
   "*SCREEN-MODE-PREFS-SIZE*" "SCREEN-MODE-PREFS-RESERVED" 
   "SCREEN-MODE-PREFS-DISPLAY-ID" "SCREEN-MODE-PREFS-WIDTH" 
   "SCREEN-MODE-PREFS-HEIGHT" "SCREEN-MODE-PREFS-DEPTH" 
   "SCREEN-MODE-PREFS-CONTROL" ))

(in-package "AMIGA.RAW.PREFS.SCREENMODE")

;;; --- constants from prefs/screenmode.i ---
(defconstant +id-scrm+ #x5343524D)
(defconstant +smb-autoscroll+ 0)
(defconstant +smf-autoscroll+ 1)

;;; --- structures from prefs/screenmode.i ---
(ffi:defcstruct (screen-mode-prefs :size 28)   ; ScreenModePrefs (prefs/screenmode.i)
  (reserved (:struct 16) 0)
  (display-id :u32 16)
  (width :u16 20)
  (height :u16 22)
  (depth :u16 24)
  (control :u16 26)
)

(provide "amiga/raw/prefs/screenmode")
