;;; amiga/raw/prefs/serial  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   prefs/serial.i
;;;
;;; 0 functions, 9 constants, 1 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.PREFS.SERIAL"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export))

(in-package "AMIGA.RAW.PREFS.SERIAL")

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.PREFS.SERIAL" ()

  ;; --- constants from prefs/serial.i ---
  (:const "+ID-SERL+" #x5345524C)
  (:const "+PARITY-NONE+" 0)
  (:const "+PARITY-EVEN+" 1)
  (:const "+PARITY-ODD+" 2)
  (:const "+PARITY-MARK+" 3)
  (:const "+PARITY-SPACE+" 4)
  (:const "+HSHAKE-XON+" 0)
  (:const "+HSHAKE-RTS+" 1)
  (:const "+HSHAKE-NONE+" 2)

  ;; --- structures from prefs/serial.i ---
  (:struct "SERIAL-PREFS" 33   ; SerialPrefs (prefs/serial.i)
    ("RESERVED" (:struct 12) 0)
    ("UNIT0-MAP" :u32 12)
    ("BAUD-RATE" :u32 16)
    ("INPUT-BUFFER" :u32 20)
    ("OUTPUT-BUFFER" :u32 24)
    ("INPUT-HANDSHAKE" :u8 28)
    ("OUTPUT-HANDSHAKE" :u8 29)
    ("PARITY" :u8 30)
    ("BITS-PER-CHAR" :u8 31)
    ("STOP-BITS" :u8 32)
    )
  )

(provide "amiga/raw/prefs/serial")
