;;; amiga/raw/prefs/wbpattern  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   prefs/wbpattern.i
;;;
;;; 0 functions, 30 constants, 1 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.PREFS.WBPATTERN"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export))

(in-package "AMIGA.RAW.PREFS.WBPATTERN")

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.PREFS.WBPATTERN" ()

  ;; --- constants from prefs/wbpattern.i ---
  (:const "+ID-PTRN+" #x5054524E)
  (:const "+WBP-ROOT+" 0)
  (:const "+WBP-DRAWER+" 1)
  (:const "+WBP-SCREEN+" 2)
  (:const "+WBPB-PATTERN+" 0)
  (:const "+WBPF-PATTERN+" 1)
  (:const "+WBPB-NOREMAP+" 4)
  (:const "+WBPF-NOREMAP+" #x10)
  (:const "+WBPF-DITHER-MASK+" #x300)
  (:const "+WBPF-DITHER-DEF+" 0)
  (:const "+WBPF-DITHER-BAD+" #x100)
  (:const "+WBPF-DITHER-GOOD+" #x200)
  (:const "+WBPF-DITHER-BEST+" #x300)
  (:const "+WBPF-PLACEMENT-MASK+" #x3000)
  (:const "+WBPF-PLACEMENT-TILE+" 0)
  (:const "+WBPF-PLACEMENT-CENTER+" #x1000)
  (:const "+WBPF-PLACEMENT-SCALE+" #x2000)
  (:const "+WBPF-PLACEMENT-SCALEGOOD+" #x3000)
  (:const "+WBPF-ALIGNMENT-MASK+" #xC000)
  (:const "+WBPF-ALIGNMENT-MIDDLE+" 0)
  (:const "+WBPF-ALIGNMENT-LEFTTOP+" #x4000)
  (:const "+WBPF-ALIGNMENT-RIGHTBOTTOM+" #x8000)
  (:const "+WBPF-PRECISION-DEF+" 0)
  (:const "+WBPF-PRECISION-ICON+" #x400)
  (:const "+WBPF-PRECISION-IMAGE+" #x800)
  (:const "+WBPF-PRECISION-EXACT+" #xC00)
  (:const "+MAXDEPTH+" 3)
  (:const "+DEFPATDEPTH+" 2)
  (:const "+PAT-WIDTH+" #x10)
  (:const "+PAT-HEIGHT+" #x10)

  ;; --- structures from prefs/wbpattern.i ---
  (:struct "WB-PATTERN-PREFS" 24   ; WBPatternPrefs (prefs/wbpattern.i)
    ("RESERVED" (:struct 16) 0)
    ("WHICH" :u16 16)
    ("FLAGS" :u16 18)
    ("REVISION" :i8 20)
    ("DEPTH" :i8 21)
    ("DATA-LENGTH" :u16 22)
    )
  )

(provide "amiga/raw/prefs/wbpattern")
