;;; amiga/raw/ahi  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   MorphOS SDK ahi_lib.fd + clib/ahi_protos.h (via fd2sfd)
;;;
;;; 21 functions, 0 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.AHI"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*AHI-BASE*" "*AHI-VERSION*"
   "AHI-ALLOC-AUDIO-A" "AHI-FREE-AUDIO" "AHI-KILL-AUDIO" 
   "AHI-CONTROL-AUDIO-A" "AHI-SET-VOL" "AHI-SET-FREQ" "AHI-SET-SOUND" 
   "AHI-SET-EFFECT" "AHI-LOAD-SOUND" "AHI-UNLOAD-SOUND" "AHI-NEXT-AUDIO-ID" 
   "AHI-GET-AUDIO-ATTRS-A" "AHI-BEST-AUDIO-IDA" "AHI-ALLOC-AUDIO-REQUEST-A" 
   "AHI-AUDIO-REQUEST-A" "AHI-FREE-AUDIO-REQUEST" "AHI-PLAY-A" 
   "AHI-SAMPLE-FRAME-SIZE" "AHI-ADD-AUDIO-MODE" "AHI-REMOVE-AUDIO-MODE" 
   "AHI-LOAD-MODE-FILE" ))

(in-package "AMIGA.RAW.AHI")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
;;; ahi.device is a device/resource: there is no OpenLibrary.  Set the base
;;; yourself (IORequest io_Device after OpenDevice, or OpenResource).
(defvar *ahi-base* nil)
(defvar *ahi-version*
  (and *ahi-base* (amiga.ffi:library-version *ahi-base*)))
(defun %version>= (n)
  (and *ahi-version* (>= *ahi-version* n)))

;;; --- functions (MorphOS SDK) ---
(amiga.ffi:defcfun ahi-alloc-audio-a *ahi-base* -42 (:a1 tag-list)
    :result :pointer
    :doc "struct AHIAudioCtrl * AHI_AllocAudioA(struct TagItem * tagList) (A1) LVO -42")
(amiga.ffi:defcfun ahi-free-audio *ahi-base* -48 (:a2 audio-ctrl)
    :result :void
    :doc "void AHI_FreeAudio(struct AHIAudioCtrl * AudioCtrl) (A2) LVO -48")
(amiga.ffi:defcfun ahi-kill-audio *ahi-base* -54 ()
    :result :void
    :doc "void AHI_KillAudio() () LVO -54")
(amiga.ffi:defcfun ahi-control-audio-a *ahi-base* -60 (:a2 audio-ctrl :a1 tag-list)
    :result :unsigned
    :doc "ULONG AHI_ControlAudioA(struct AHIAudioCtrl * AudioCtrl, struct TagItem * tagList) (A2,A1) LVO -60")
(amiga.ffi:defcfun ahi-set-vol *ahi-base* -66 (:d0 channel :d1 volume :d2 pan :a2 audio-ctrl :d3 flags)
    :result :void
    :doc "void AHI_SetVol(UWORD Channel, Fixed Volume, sposition Pan, struct AHIAudioCtrl * AudioCtrl, ULONG Flags) (D0,D1,D2,A2,D3) LVO -66")
(amiga.ffi:defcfun ahi-set-freq *ahi-base* -72 (:d0 channel :d1 freq :a2 audio-ctrl :d2 flags)
    :result :void
    :doc "void AHI_SetFreq(UWORD Channel, ULONG Freq, struct AHIAudioCtrl * AudioCtrl, ULONG Flags) (D0,D1,A2,D2) LVO -72")
(amiga.ffi:defcfun ahi-set-sound *ahi-base* -78 (:d0 channel :d1 sound :d2 offset :d3 length :a2 audio-ctrl :d4 flags)
    :result :void
    :doc "void AHI_SetSound(UWORD Channel, UWORD Sound, ULONG Offset, LONG Length, struct AHIAudioCtrl * AudioCtrl, ULONG Flags) (D0,D1,D2,D3,A2,D4) LVO -78")
(amiga.ffi:defcfun ahi-set-effect *ahi-base* -84 (:a0 effect :a2 audio-ctrl)
    :result :unsigned
    :doc "ULONG AHI_SetEffect(APTR Effect, struct AHIAudioCtrl * AudioCtrl) (A0,A2) LVO -84")
(amiga.ffi:defcfun ahi-load-sound *ahi-base* -90 (:d0 sound :d1 type :a0 info :a2 audio-ctrl)
    :result :unsigned
    :doc "ULONG AHI_LoadSound(UWORD Sound, ULONG Type, APTR Info, struct AHIAudioCtrl * AudioCtrl) (D0,D1,A0,A2) LVO -90")
(amiga.ffi:defcfun ahi-unload-sound *ahi-base* -96 (:d0 sound :a2 audioctrl)
    :result :void
    :doc "void AHI_UnloadSound(UWORD Sound, struct AHIAudioCtrl * Audioctrl) (D0,A2) LVO -96")
(amiga.ffi:defcfun ahi-next-audio-id *ahi-base* -102 (:d0 last-id)
    :result :unsigned
    :doc "ULONG AHI_NextAudioID(ULONG Last_ID) (D0) LVO -102")
(amiga.ffi:defcfun ahi-get-audio-attrs-a *ahi-base* -108 (:d0 id :a2 audioctrl :a1 tag-list)
    :result :bool
    :doc "BOOL AHI_GetAudioAttrsA(ULONG ID, struct AHIAudioCtrl * Audioctrl, struct TagItem * tagList) (D0,A2,A1) LVO -108")
(amiga.ffi:defcfun ahi-best-audio-ida *ahi-base* -114 (:a1 tag-list)
    :result :unsigned
    :doc "ULONG AHI_BestAudioIDA(struct TagItem * tagList) (A1) LVO -114")
(amiga.ffi:defcfun ahi-alloc-audio-request-a *ahi-base* -120 (:a0 tag-list)
    :result :pointer
    :doc "struct AHIAudioModeRequester * AHI_AllocAudioRequestA(struct TagItem * tagList) (A0) LVO -120")
(amiga.ffi:defcfun ahi-audio-request-a *ahi-base* -126 (:a0 requester :a1 tag-list)
    :result :bool
    :doc "BOOL AHI_AudioRequestA(struct AHIAudioModeRequester * requester, struct TagItem * tagList) (A0,A1) LVO -126")
(amiga.ffi:defcfun ahi-free-audio-request *ahi-base* -132 (:a0 requester)
    :result :void
    :doc "void AHI_FreeAudioRequest(struct AHIAudioModeRequester * requester) (A0) LVO -132")
(amiga.ffi:defcfun ahi-play-a *ahi-base* -138 (:a2 audioctrl :a1 tag-list)
    :result :void
    :doc "void AHI_PlayA(struct AHIAudioCtrl * Audioctrl, struct TagItem * tagList) (A2,A1) LVO -138")
(amiga.ffi:defcfun ahi-sample-frame-size *ahi-base* -144 (:d0 sample-type)
    :result :unsigned
    :doc "ULONG AHI_SampleFrameSize(ULONG SampleType) (D0) LVO -144")
(amiga.ffi:defcfun ahi-add-audio-mode *ahi-base* -150 (:a0 private)
    :result :unsigned
    :doc "ULONG AHI_AddAudioMode(struct TagItem * Private) (A0) LVO -150")
(amiga.ffi:defcfun ahi-remove-audio-mode *ahi-base* -156 (:d0 private)
    :result :unsigned
    :doc "ULONG AHI_RemoveAudioMode(ULONG Private) (D0) LVO -156")
(amiga.ffi:defcfun ahi-load-mode-file *ahi-base* -162 (:a0 private)
    :result :unsigned
    :doc "ULONG AHI_LoadModeFile(STRPTR Private) (A0) LVO -162")

(provide "amiga/raw/ahi")
