;;; amiga/raw/amigaguide  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   amigaguide_lib.sfd ($VER: amigaguide_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK amigaguide_lib.fd + clib/amigaguide_protos.h (via fd2sfd)
;;;   libraries/amigaguide.i
;;;
;;; 18 functions, 77 constants, 7 structs, 3 skipped (see comments).
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.AMIGAGUIDE"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*AMIGAGUIDE-BASE*" "*AMIGAGUIDE-VERSION*"
   "+APSH-TOOL-ID+" "+STARTUP-MSG-ID+" "+LOGIN-TOOL-ID+" "+LOGOUT-TOOL-ID+" 
   "+SHUTDOWN-MSG-ID+" "+ACTIVATE-TOOL-ID+" "+DEACTIVATE-TOOL-ID+" 
   "+ACTIVE-TOOL-ID+" "+INACTIVE-TOOL-ID+" "+TOOL-STATUS-ID+" 
   "+TOOL-CMD-ID+" "+TOOL-CMD-REPLY-ID+" "+SHUTDOWN-TOOL-ID+" "+AGA-DUMMY+" 
   "+AGA-PATH+" "+AGA-X-REF-LIST+" "+AGA-ACTIVATE+" "+AGA-CONTEXT+" 
   "+AGA-HELP-GROUP+" "+AGA-A-REXX-PORT+" "+AGA-A-REXX-PORT-NAME+" 
   "+AGA-SECURE+" "+HTB-LOAD-INDEX+" "+HTF-LOAD-INDEX+" "+HTB-LOAD-ALL+" 
   "+HTF-LOAD-ALL+" "+HTB-CACHE-NODE+" "+HTF-CACHE-NODE+" "+HTB-CACHE-DB+" 
   "+HTF-CACHE-DB+" "+HTB-UNIQUE+" "+HTF-UNIQUE+" "+HTB-NOACTIVATE+" 
   "+HTF-NOACTIVATE+" "+HTFC-SYSGADS+" "+HTH-OPEN+" "+HTH-CLOSE+" 
   "+HTERR-NOT-ENOUGH-MEMORY+" "+HTERR-CANT-OPEN-DATABASE+" 
   "+HTERR-CANT-FIND-NODE+" "+HTERR-CANT-OPEN-NODE+" 
   "+HTERR-CANT-OPEN-WINDOW+" "+HTERR-INVALID-COMMAND+" 
   "+HTERR-CANT-COMPLETE+" "+HTERR-PORT-CLOSED+" "+HTERR-CANT-CREATE-PORT+" 
   "+HTERR-KEYWORD-NOT-FOUND+" "+XR-GENERIC+" "+XR-FUNCTION+" 
   "+XR-COMMAND+" "+XR-INCLUDE+" "+XR-MACRO+" "+XR-STRUCT+" "+XR-FIELD+" 
   "+XR-TYPEDEF+" "+XR-DEFINE+" "+HM-FINDNODE+" "+HM-OPENNODE+" 
   "+HM-CLOSENODE+" "+HM-EXPUNGE+" "+HTNB-KEEP+" "+HTNF-KEEP+" 
   "+HTNB-RESERVED1+" "+HTNF-RESERVED1+" "+HTNB-RESERVED2+" 
   "+HTNF-RESERVED2+" "+HTNB-ASCII+" "+HTNF-ASCII+" "+HTNB-RESERVED3+" 
   "+HTNF-RESERVED3+" "+HTNB-CLEAN+" "+HTNF-CLEAN+" "+HTNB-DONE+" 
   "+HTNF-DONE+" "+HTNA-SCREEN+" "+HTNA-PENS+" "+HTNA-RECTANGLE+" 
   "*AMIGA-GUIDE-MSG-SIZE*" "AMIGA-GUIDE-MSG-MSG" "AMIGA-GUIDE-MSG-TYPE" 
   "AMIGA-GUIDE-MSG-DATA" "AMIGA-GUIDE-MSG-D-SIZE" "AMIGA-GUIDE-MSG-D-TYPE" 
   "AMIGA-GUIDE-MSG-PRI-RET" "AMIGA-GUIDE-MSG-SEC-RET" 
   "AMIGA-GUIDE-MSG-SYSTEM1" "AMIGA-GUIDE-MSG-SYSTEM2" 
   "*NEW-AMIGA-GUIDE-SIZE*" "NEW-AMIGA-GUIDE-LOCK" "NEW-AMIGA-GUIDE-NAME" 
   "NEW-AMIGA-GUIDE-SCREEN" "NEW-AMIGA-GUIDE-PUB-SCREEN" 
   "NEW-AMIGA-GUIDE-HOST-PORT" "NEW-AMIGA-GUIDE-CLIENT-PORT" 
   "NEW-AMIGA-GUIDE-BASE-NAME" "NEW-AMIGA-GUIDE-FLAGS" 
   "NEW-AMIGA-GUIDE-CONTEXT" "NEW-AMIGA-GUIDE-NODE" "NEW-AMIGA-GUIDE-LINE" 
   "NEW-AMIGA-GUIDE-EXTENS" "NEW-AMIGA-GUIDE-CLIENT" "*X-REF-SIZE*" 
   "X-REF-NODE" "X-REF-PAD" "X-REF-DF" "X-REF-FILE" "X-REF-NAME" 
   "X-REF-LINE" "*AMIGA-GUIDE-HOST-SIZE*" "AMIGA-GUIDE-HOST-DISPATCHER" 
   "AMIGA-GUIDE-HOST-RESERVED" "AMIGA-GUIDE-HOST-FLAGS" 
   "AMIGA-GUIDE-HOST-USE-CNT" "AMIGA-GUIDE-HOST-SYSTEM-DATA" 
   "AMIGA-GUIDE-HOST-USER-DATA" "*OP-FIND-HOST-SIZE*" "OP-FIND-HOST-ATTRS" 
   "OP-FIND-HOST-NODE" "OP-FIND-HOST-TOC" "OP-FIND-HOST-TITLE" 
   "OP-FIND-HOST-NEXT" "OP-FIND-HOST-PREV" "*OP-NODE-IO-SIZE*" 
   "OP-NODE-IO-ATTRS" "OP-NODE-IO-NODE" "OP-NODE-IO-FILE-NAME" 
   "OP-NODE-IO-DOC-BUFFER" "OP-NODE-IO-BUFF-LEN" "OP-NODE-IO-FLAGS" 
   "*OP-EXPUNGE-NODE-SIZE*" "OP-EXPUNGE-NODE-ATTRS" "LOCK-AMIGA-GUIDE-BASE" 
   "UNLOCK-AMIGA-GUIDE-BASE" "OPEN-AMIGA-GUIDE-A" 
   "OPEN-AMIGA-GUIDE-ASYNC-A" "CLOSE-AMIGA-GUIDE" "AMIGA-GUIDE-SIGNAL" 
   "GET-AMIGA-GUIDE-MSG" "REPLY-AMIGA-GUIDE-MSG" 
   "SET-AMIGA-GUIDE-CONTEXT-A" "SEND-AMIGA-GUIDE-CONTEXT-A" 
   "SEND-AMIGA-GUIDE-CMD-A" "SET-AMIGA-GUIDE-ATTRS-A" 
   "GET-AMIGA-GUIDE-ATTR" "LOAD-X-REF" "EXPUNGE-X-REF" 
   "ADD-AMIGA-GUIDE-HOST-A" "REMOVE-AMIGA-GUIDE-HOST-A" 
   "GET-AMIGA-GUIDE-STRING" ))

(in-package "AMIGA.RAW.AMIGAGUIDE")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *amigaguide-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "amigaguide.library" 0)))
(defvar *amigaguide-version*
  (and *amigaguide-base* (amiga.ffi:library-version *amigaguide-base*)))
(defun %version>= (n)
  (and *amigaguide-version* (>= *amigaguide-version* n)))

;;; --- constants from libraries/amigaguide.i ---
(defconstant +apsh-tool-id+ #x2AF8)
(defconstant +startup-msg-id+ #x2AF9)
(defconstant +login-tool-id+ #x2AFA)
(defconstant +logout-tool-id+ #x2AFB)
(defconstant +shutdown-msg-id+ #x2AFC)
(defconstant +activate-tool-id+ #x2AFD)
(defconstant +deactivate-tool-id+ #x2AFE)
(defconstant +active-tool-id+ #x2AFF)
(defconstant +inactive-tool-id+ #x2B00)
(defconstant +tool-status-id+ #x2B01)
(defconstant +tool-cmd-id+ #x2B02)
(defconstant +tool-cmd-reply-id+ #x2B03)
(defconstant +shutdown-tool-id+ #x2B04)
(defconstant +aga-dummy+ #x80000000)
(defconstant +aga-path+ #x80000001)
(defconstant +aga-x-ref-list+ #x80000002)
(defconstant +aga-activate+ #x80000003)
(defconstant +aga-context+ #x80000004)
(defconstant +aga-help-group+ #x80000005)
(defconstant +aga-a-rexx-port+ #x80000009)
(defconstant +aga-a-rexx-port-name+ #x8000000A)
(defconstant +aga-secure+ #x8000000B)
(defconstant +htb-load-index+ 0)
(defconstant +htf-load-index+ 1)
(defconstant +htb-load-all+ 1)
(defconstant +htf-load-all+ 2)
(defconstant +htb-cache-node+ 2)
(defconstant +htf-cache-node+ 4)
(defconstant +htb-cache-db+ 3)
(defconstant +htf-cache-db+ 8)
(defconstant +htb-unique+ 4)
(defconstant +htf-unique+ #x10)
(defconstant +htb-noactivate+ 5)
(defconstant +htf-noactivate+ #x20)
(defconstant +htfc-sysgads+ #x80000000)
(defconstant +hth-open+ 0)
(defconstant +hth-close+ 1)
(defconstant +hterr-not-enough-memory+ #x64)
(defconstant +hterr-cant-open-database+ #x65)
(defconstant +hterr-cant-find-node+ #x66)
(defconstant +hterr-cant-open-node+ #x67)
(defconstant +hterr-cant-open-window+ #x68)
(defconstant +hterr-invalid-command+ #x69)
(defconstant +hterr-cant-complete+ #x6A)
(defconstant +hterr-port-closed+ #x6B)
(defconstant +hterr-cant-create-port+ #x6C)
(defconstant +hterr-keyword-not-found+ #x71)
(defconstant +xr-generic+ 0)
(defconstant +xr-function+ 1)
(defconstant +xr-command+ 2)
(defconstant +xr-include+ 3)
(defconstant +xr-macro+ 4)
(defconstant +xr-struct+ 5)
(defconstant +xr-field+ 6)
(defconstant +xr-typedef+ 7)
(defconstant +xr-define+ 8)
(defconstant +hm-findnode+ 1)
(defconstant +hm-opennode+ 2)
(defconstant +hm-closenode+ 3)
(defconstant +hm-expunge+ 10)
(defconstant +htnb-keep+ 0)
(defconstant +htnf-keep+ 1)
(defconstant +htnb-reserved1+ 1)
(defconstant +htnf-reserved1+ 2)
(defconstant +htnb-reserved2+ 2)
(defconstant +htnf-reserved2+ 4)
(defconstant +htnb-ascii+ 3)
(defconstant +htnf-ascii+ 8)
(defconstant +htnb-reserved3+ 4)
(defconstant +htnf-reserved3+ #x10)
(defconstant +htnb-clean+ 5)
(defconstant +htnf-clean+ #x20)
(defconstant +htnb-done+ 6)
(defconstant +htnf-done+ #x40)
(defconstant +htna-screen+ #x80000001)
(defconstant +htna-pens+ #x80000002)
(defconstant +htna-rectangle+ #x80000003)

;;; --- structures from libraries/amigaguide.i ---
(ffi:defcstruct (amiga-guide-msg :size 52)   ; AmigaGuideMsg (libraries/amigaguide.i)
  (msg (:struct 20) 0)
  (type :u32 20)
  (data :fptr 24)
  (d-size :u32 28)
  (d-type :u32 32)
  (pri-ret :u32 36)
  (sec-ret :u32 40)
  (system1 :fptr 44)
  (system2 :fptr 48)
)
(ffi:defcstruct (new-amiga-guide :size 52)   ; NewAmigaGuide (libraries/amigaguide.i)
  (lock :u32 0)
  (name :fptr 4)
  (screen :fptr 8)
  (pub-screen :fptr 12)
  (host-port :fptr 16)
  (client-port :fptr 20)
  (base-name :fptr 24)
  (flags :u32 28)
  (context :fptr 32)
  (node :fptr 36)
  (line :i32 40)
  (extens :fptr 44)
  (client :fptr 48)
)
(ffi:defcstruct (x-ref :size 32)   ; XRef (libraries/amigaguide.i)
  (node (:struct 14) 0)
  (pad :u16 14)
  (df :fptr 16)
  (file :fptr 20)
  (name :fptr 24)
  (line :i32 28)
)
(ffi:defcstruct (amiga-guide-host :size 40)   ; AmigaGuideHost (libraries/amigaguide.i)
  (dispatcher (:struct 20) 0)
  (reserved :u32 20)
  (flags :u32 24)
  (use-cnt :u32 28)
  (system-data :fptr 32)
  (user-data :fptr 36)
)
(ffi:defcstruct (op-find-host :size 24)   ; opFindHost (libraries/amigaguide.i)
  (attrs :fptr 0)
  (node :fptr 4)
  (toc :fptr 8)
  (title :fptr 12)
  (next :fptr 16)
  (prev :fptr 20)
)
(ffi:defcstruct (op-node-io :size 24)   ; opNodeIO (libraries/amigaguide.i)
  (attrs :fptr 0)
  (node :fptr 4)
  (file-name :fptr 8)
  (doc-buffer :fptr 12)
  (buff-len :u32 16)
  (flags :u32 20)
)
(ffi:defcstruct (op-expunge-node :size 4)   ; opExpungeNode (libraries/amigaguide.i)
  (attrs :fptr 0)
)

;;; --- functions (amigaguide_lib.sfd + MorphOS SDK) ---
(when (%version>= 40)
  (amiga.ffi:defcfun lock-amiga-guide-base *amigaguide-base* -36 (:a0 handle)
    :result :signed
    :doc "LONG LockAmigaGuideBase(APTR handle) (A0) LVO -36"))
(when (%version>= 40)
  (amiga.ffi:defcfun unlock-amiga-guide-base *amigaguide-base* -42 (:d0 key)
    :result :void
    :doc "VOID UnlockAmigaGuideBase(LONG key) (D0) LVO -42"))
(when (%version>= 40)
  (amiga.ffi:defcfun open-amiga-guide-a *amigaguide-base* -54 (:a0 nag :a1 attrs)
    :result :pointer
    :doc "APTR OpenAmigaGuideA(struct NewAmigaGuide * nag, CONST struct TagItem * attrs) (A0,A1) LVO -54"))
(when (%version>= 40)
  (amiga.ffi:defcfun open-amiga-guide-async-a *amigaguide-base* -60 (:a0 nag :d0 attrs)
    :result :pointer
    :doc "APTR OpenAmigaGuideAsyncA(struct NewAmigaGuide * nag, CONST struct TagItem * attrs) (A0,D0) LVO -60"))
(when (%version>= 40)
  (amiga.ffi:defcfun close-amiga-guide *amigaguide-base* -66 (:a0 cl)
    :result :void
    :doc "VOID CloseAmigaGuide(APTR cl) (A0) LVO -66"))
(when (%version>= 40)
  (amiga.ffi:defcfun amiga-guide-signal *amigaguide-base* -72 (:a0 cl)
    :result :unsigned
    :doc "ULONG AmigaGuideSignal(APTR cl) (A0) LVO -72"))
(when (%version>= 40)
  (amiga.ffi:defcfun get-amiga-guide-msg *amigaguide-base* -78 (:a0 cl)
    :result :pointer
    :doc "struct AmigaGuideMsg * GetAmigaGuideMsg(APTR cl) (A0) LVO -78"))
(when (%version>= 40)
  (amiga.ffi:defcfun reply-amiga-guide-msg *amigaguide-base* -84 (:a0 amsg)
    :result :void
    :doc "VOID ReplyAmigaGuideMsg(struct AmigaGuideMsg * amsg) (A0) LVO -84"))
(when (%version>= 40)
  (amiga.ffi:defcfun set-amiga-guide-context-a *amigaguide-base* -90 (:a0 cl :d0 id :d1 attrs)
    :result :signed
    :doc "LONG SetAmigaGuideContextA(APTR cl, ULONG id, CONST struct TagItem * attrs) (A0,D0,D1) LVO -90"))
(when (%version>= 40)
  (amiga.ffi:defcfun send-amiga-guide-context-a *amigaguide-base* -96 (:a0 cl :d0 attrs)
    :result :signed
    :doc "LONG SendAmigaGuideContextA(APTR cl, CONST struct TagItem * attrs) (A0,D0) LVO -96"))
(when (%version>= 40)
  (amiga.ffi:defcfun send-amiga-guide-cmd-a *amigaguide-base* -102 (:a0 cl :d0 cmd :d1 attrs)
    :result :signed
    :doc "LONG SendAmigaGuideCmdA(APTR cl, STRPTR cmd, CONST struct TagItem * attrs) (A0,D0,D1) LVO -102"))
(when (%version>= 40)
  (amiga.ffi:defcfun set-amiga-guide-attrs-a *amigaguide-base* -108 (:a0 cl :a1 attrs)
    :result :signed
    :doc "LONG SetAmigaGuideAttrsA(APTR cl, CONST struct TagItem * attrs) (A0,A1) LVO -108"))
(when (%version>= 40)
  (amiga.ffi:defcfun get-amiga-guide-attr *amigaguide-base* -114 (:d0 tag1 :a0 cl :a1 storage)
    :result :signed
    :doc "LONG GetAmigaGuideAttr(Tag tag1, APTR cl, ULONG * storage) (D0,A0,A1) LVO -114"))
(when (%version>= 40)
  (amiga.ffi:defcfun load-x-ref *amigaguide-base* -126 (:a0 lock :a1 name)
    :result :signed
    :doc "LONG LoadXRef(BPTR lock, STRPTR name) (A0,A1) LVO -126"))
(when (%version>= 40)
  (amiga.ffi:defcfun expunge-x-ref *amigaguide-base* -132 ()
    :result :void
    :doc "VOID ExpungeXRef() () LVO -132"))
(when (%version>= 40)
  (amiga.ffi:defcfun add-amiga-guide-host-a *amigaguide-base* -138 (:a0 h :d0 name :a1 attrs)
    :result :pointer
    :doc "APTR AddAmigaGuideHostA(struct Hook * h, CONST_STRPTR name, CONST struct TagItem * attrs) (A0,D0,A1) LVO -138"))
(when (%version>= 40)
  (amiga.ffi:defcfun remove-amiga-guide-host-a *amigaguide-base* -144 (:a0 hh :a1 attrs)
    :result :signed
    :doc "LONG RemoveAmigaGuideHostA(APTR hh, CONST struct TagItem * attrs) (A0,A1) LVO -144"))
(when (%version>= 40)
  (amiga.ffi:defcfun get-amiga-guide-string *amigaguide-base* -210 (:d0 id)
    :result :pointer
    :doc "STRPTR GetAmigaGuideString(LONG id) (D0) LVO -210"))
;; skipped FindGuide: not a 68k register call (base,sysv)
;; skipped AG_UpdateLink: not a 68k register call (base,sysv)
;; skipped AG_LinkExists: not a 68k register call (base,sysv)

(provide "amiga/raw/amigaguide")
