;;; amiga/raw/arexx  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   arexx_lib.sfd ($VER: arexx_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK arexx_lib.fd + clib/arexx_protos.h (via fd2sfd)
;;;
;;; 1 functions, 0 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.AREXX"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*AREXX-BASE*" "*AREXX-VERSION*"
   "AREXX-GET-CLASS" ))

(in-package "AMIGA.RAW.AREXX")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *arexx-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "arexx.class" 0)))
(defvar *arexx-version*
  (and *arexx-base* (amiga.ffi:library-version *arexx-base*)))
(defun %version>= (n)
  (and *arexx-version* (>= *arexx-version* n)))

;;; --- functions (arexx_lib.sfd + MorphOS SDK) ---
(when (%version>= 40)
  (amiga.ffi:defcfun arexx-get-class *arexx-base* -30 ()
    :result :pointer
    :doc "Class * AREXX_GetClass() () LVO -30"))

(provide "amiga/raw/arexx")
