;;; amiga/raw/battmem  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   battmem_lib.sfd ($VER: battmem_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK battmem_lib.fd + clib/battmem_protos.h (via fd2sfd)
;;;   resources/battmem.i
;;;   resources/battmembitsamiga.i
;;;   resources/battmembitsshared.i
;;;
;;; 4 functions, 18 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.BATTMEM"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*BATTMEM-BASE*" "*BATTMEM-VERSION*"
   "+BATTMEM-AMIGA-AMNESIA-ADDR+" "+BATTMEM-AMIGA-AMNESIA-LEN+" 
   "+BATTMEM-SCSI-TIMEOUT-ADDR+" "+BATTMEM-SCSI-TIMEOUT-LEN+" 
   "+BATTMEM-SCSI-LUNS-ADDR+" "+BATTMEM-SCSI-LUNS-LEN+" 
   "+BATTMEM-SHARED-AMNESIA-ADDR+" "+BATTMEM-SHARED-AMNESIA-LEN+" 
   "+BATTMEM-SCSI-HOST-ID-ADDR+" "+BATTMEM-SCSI-HOST-ID-LEN+" 
   "+BATTMEM-SCSI-SYNC-XFER-ADDR+" "+BATTMEM-SCSI-SYNC-XFER-LEN+" 
   "+BATTMEM-SCSI-FAST-SYNC-ADDR+" "+BATTMEM-SCSI-FAST-SYNC-LEN+" 
   "+BATTMEM-SCSI-TAG-QUEUES-ADDR+" "+BATTMEM-SCSI-TAG-QUEUES-LEN+" 
   "+BATTMEM-IDE-EXTRA-WAIT-ADDR+" "+BATTMEM-IDE-EXTRA-WAIT-LEN+" 
   "OBTAIN-BATT-SEMAPHORE" "RELEASE-BATT-SEMAPHORE" "READ-BATT-MEM" 
   "WRITE-BATT-MEM" ))

(in-package "AMIGA.RAW.BATTMEM")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
;;; battmem.resource is a device/resource: there is no OpenLibrary.  Set the base
;;; yourself (IORequest io_Device after OpenDevice, or OpenResource).
(defvar *battmem-base* nil)
(defvar *battmem-version*
  (and *battmem-base* (amiga.ffi:library-version *battmem-base*)))
(defun %version>= (n)
  (and *battmem-version* (>= *battmem-version* n)))

;;; --- constants from resources/battmembitsamiga.i ---
(defconstant +battmem-amiga-amnesia-addr+ 0)
(defconstant +battmem-amiga-amnesia-len+ 1)
(defconstant +battmem-scsi-timeout-addr+ 1)
(defconstant +battmem-scsi-timeout-len+ 1)
(defconstant +battmem-scsi-luns-addr+ 2)
(defconstant +battmem-scsi-luns-len+ 1)

;;; --- constants from resources/battmembitsshared.i ---
(defconstant +battmem-shared-amnesia-addr+ #x40)
(defconstant +battmem-shared-amnesia-len+ 1)
(defconstant +battmem-scsi-host-id-addr+ #x41)
(defconstant +battmem-scsi-host-id-len+ 3)
(defconstant +battmem-scsi-sync-xfer-addr+ #x44)
(defconstant +battmem-scsi-sync-xfer-len+ 1)
(defconstant +battmem-scsi-fast-sync-addr+ #x45)
(defconstant +battmem-scsi-fast-sync-len+ 1)
(defconstant +battmem-scsi-tag-queues-addr+ #x46)
(defconstant +battmem-scsi-tag-queues-len+ 1)
(defconstant +battmem-ide-extra-wait-addr+ #x47)
(defconstant +battmem-ide-extra-wait-len+ 1)

;;; --- functions (battmem_lib.sfd + MorphOS SDK) ---
(amiga.ffi:defcfun obtain-batt-semaphore *battmem-base* -6 ()
    :result :void
    :doc "VOID ObtainBattSemaphore() () LVO -6")
(amiga.ffi:defcfun release-batt-semaphore *battmem-base* -12 ()
    :result :void
    :doc "VOID ReleaseBattSemaphore() () LVO -12")
(amiga.ffi:defcfun read-batt-mem *battmem-base* -18 (:a0 buffer :d0 offset :d1 length)
    :result :unsigned
    :doc "ULONG ReadBattMem(APTR buffer, ULONG offset, ULONG length) (A0,D0,D1) LVO -18")
(amiga.ffi:defcfun write-batt-mem *battmem-base* -24 (:a0 buffer :d0 offset :d1 length)
    :result :unsigned
    :doc "ULONG WriteBattMem(CONST_APTR buffer, ULONG offset, ULONG length) (A0,D0,D1) LVO -24")

(provide "amiga/raw/battmem")
