;;; amiga/raw/battmem  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   battmem_lib.sfd ($VER: battmem_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK battmem_lib.fd + clib/battmem_protos.h (via fd2sfd)
;;;   resources/battmem.i
;;;   resources/battmembitsamiga.i
;;;   resources/battmembitsshared.i
;;;
;;; 4 functions, 18 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.BATTMEM"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export "*BATTMEM-BASE*" "*BATTMEM-VERSION*"))

(in-package "AMIGA.RAW.BATTMEM")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
;;; battmem.resource is a device/resource: there is no OpenLibrary.  Set the base
;;; yourself (IORequest io_Device after OpenDevice, or OpenResource).
(defvar *battmem-base* nil)
(defvar *battmem-version*
  (and *battmem-base* (amiga.ffi:library-version *battmem-base*)))
(defun %version>= (n)
  (and *battmem-version* (>= *battmem-version* n)))

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.BATTMEM"
    (:base *battmem-base* :version *battmem-version*)

  ;; --- constants from resources/battmembitsamiga.i ---
  (:const "+BATTMEM-AMIGA-AMNESIA-ADDR+" 0)
  (:const "+BATTMEM-AMIGA-AMNESIA-LEN+" 1)
  (:const "+BATTMEM-SCSI-TIMEOUT-ADDR+" 1)
  (:const "+BATTMEM-SCSI-TIMEOUT-LEN+" 1)
  (:const "+BATTMEM-SCSI-LUNS-ADDR+" 2)
  (:const "+BATTMEM-SCSI-LUNS-LEN+" 1)

  ;; --- constants from resources/battmembitsshared.i ---
  (:const "+BATTMEM-SHARED-AMNESIA-ADDR+" #x40)
  (:const "+BATTMEM-SHARED-AMNESIA-LEN+" 1)
  (:const "+BATTMEM-SCSI-HOST-ID-ADDR+" #x41)
  (:const "+BATTMEM-SCSI-HOST-ID-LEN+" 3)
  (:const "+BATTMEM-SCSI-SYNC-XFER-ADDR+" #x44)
  (:const "+BATTMEM-SCSI-SYNC-XFER-LEN+" 1)
  (:const "+BATTMEM-SCSI-FAST-SYNC-ADDR+" #x45)
  (:const "+BATTMEM-SCSI-FAST-SYNC-LEN+" 1)
  (:const "+BATTMEM-SCSI-TAG-QUEUES-ADDR+" #x46)
  (:const "+BATTMEM-SCSI-TAG-QUEUES-LEN+" 1)
  (:const "+BATTMEM-IDE-EXTRA-WAIT-ADDR+" #x47)
  (:const "+BATTMEM-IDE-EXTRA-WAIT-LEN+" 1)

  ;; --- functions (battmem_lib.sfd + MorphOS SDK) ---
  (:fn "OBTAIN-BATT-SEMAPHORE" -6 () :void)   ; VOID ObtainBattSemaphore() () LVO -6
  (:fn "RELEASE-BATT-SEMAPHORE" -12 () :void)   ; VOID ReleaseBattSemaphore() () LVO -12
  (:fn "READ-BATT-MEM" -18 (:a0 :d0 :d1) :unsigned)   ; ULONG ReadBattMem(APTR buffer, ULONG offset, ULONG length) (A0,D0,D1) LVO -18
  (:fn "WRITE-BATT-MEM" -24 (:a0 :d0 :d1) :unsigned)   ; ULONG WriteBattMem(CONST_APTR buffer, ULONG offset, ULONG length) (A0,D0,D1) LVO -24
  )

(provide "amiga/raw/battmem")
