;;; amiga/raw/checkbox  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   checkbox_lib.sfd ($VER: checkbox_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK checkbox_lib.fd + clib/checkbox_protos.h (via fd2sfd)
;;;
;;; 1 functions, 0 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.CHECKBOX"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*CHECKBOX-BASE*" "*CHECKBOX-VERSION*"
   "CHECKBOX-GET-CLASS" ))

(in-package "AMIGA.RAW.CHECKBOX")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *checkbox-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/checkbox.gadget" 0)))
(defvar *checkbox-version*
  (and *checkbox-base* (amiga.ffi:library-version *checkbox-base*)))
(defun %version>= (n)
  (and *checkbox-version* (>= *checkbox-version* n)))

;;; --- functions (checkbox_lib.sfd + MorphOS SDK) ---
(when (%version>= 40)
  (amiga.ffi:defcfun checkbox-get-class *checkbox-base* -30 ()
    :result :pointer
    :doc "Class * CHECKBOX_GetClass() () LVO -30"))

(provide "amiga/raw/checkbox")
