;;; amiga/raw/chooser  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   chooser_lib.sfd ($VER: chooser_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK chooser_lib.fd + clib/chooser_protos.h (via fd2sfd)
;;;
;;; 7 functions, 0 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.CHOOSER"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*CHOOSER-BASE*" "*CHOOSER-VERSION*"
   "CHOOSER-GET-CLASS" "ALLOC-CHOOSER-NODE-A" "FREE-CHOOSER-NODE" 
   "SET-CHOOSER-NODE-ATTRS-A" "GET-CHOOSER-NODE-ATTRS-A" "SHOW-CHOOSER" 
   "HIDE-CHOOSER" ))

(in-package "AMIGA.RAW.CHOOSER")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *chooser-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/chooser.gadget" 0)))
(defvar *chooser-version*
  (and *chooser-base* (amiga.ffi:library-version *chooser-base*)))
(defun %version>= (n)
  (and *chooser-version* (>= *chooser-version* n)))

;;; --- functions (chooser_lib.sfd + MorphOS SDK) ---
(when (%version>= 40)
  (amiga.ffi:defcfun chooser-get-class *chooser-base* -30 ()
    :result :pointer
    :doc "Class * CHOOSER_GetClass() () LVO -30"))
(when (%version>= 40)
  (amiga.ffi:defcfun alloc-chooser-node-a *chooser-base* -36 (:a0 tags)
    :result :pointer
    :doc "struct Node * AllocChooserNodeA(struct TagItem * tags) (A0) LVO -36"))
(when (%version>= 40)
  (amiga.ffi:defcfun free-chooser-node *chooser-base* -42 (:a0 node)
    :result :void
    :doc "VOID FreeChooserNode(struct Node * node) (A0) LVO -42"))
(when (%version>= 40)
  (amiga.ffi:defcfun set-chooser-node-attrs-a *chooser-base* -48 (:a0 node :a1 tags)
    :result :void
    :doc "VOID SetChooserNodeAttrsA(struct Node * node, struct TagItem * tags) (A0,A1) LVO -48"))
(when (%version>= 40)
  (amiga.ffi:defcfun get-chooser-node-attrs-a *chooser-base* -54 (:a0 node :a1 tags)
    :result :void
    :doc "VOID GetChooserNodeAttrsA(struct Node * node, struct TagItem * tags) (A0,A1) LVO -54"))
(when (and (not (member :morphos *features*)) (%version>= 40))
  (amiga.ffi:defcfun show-chooser *chooser-base* -60 (:a0 o :a1 w :d0 xpos :d1 ypos)
    :result :unsigned
    :doc "ULONG ShowChooser(Object * o, struct Window * w, ULONG xpos, ULONG ypos) (A0,A1,D0,D1) LVO -60"))
(when (and (not (member :morphos *features*)) (%version>= 40))
  (amiga.ffi:defcfun hide-chooser *chooser-base* -66 (:a0 o :a1 w)
    :result :void
    :doc "VOID HideChooser(Object * o, struct Window * w) (A0,A1) LVO -66"))

(provide "amiga/raw/chooser")
