;;; amiga/raw/commodities  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   commodities_lib.sfd ($VER: commodities_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK commodities_lib.fd + clib/commodities_protos.h (via fd2sfd)
;;;   libraries/commodities.i
;;;
;;; 26 functions, 43 constants, 2 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.COMMODITIES"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*COMMODITIES-BASE*" "*COMMODITIES-VERSION*"
   "+NB-VERSION+" "+CBD-NAMELEN+" "+CBD-TITLELEN+" "+CBD-DESCRLEN+" 
   "+NBU-DUPLICATE+" "+NBU-UNIQUE+" "+NBU-NOTIFY+" "+COF-SHOW-HIDE+" 
   "+CX-INVALID+" "+CX-FILTER+" "+CX-TYPEFILTER+" "+CX-SEND+" "+CX-SIGNAL+" 
   "+CX-TRANSLATE+" "+CX-BROKER+" "+CX-DEBUG+" "+CX-CUSTOM+" "+CX-ZERO+" 
   "+CXM-IEVENT+" "+CXM-COMMAND+" "+CXCMD-DISABLE+" "+CXCMD-ENABLE+" 
   "+CXCMD-APPEAR+" "+CXCMD-DISAPPEAR+" "+CXCMD-KILL+" "+CXCMD-LIST-CHG+" 
   "+CXCMD-UNIQUE+" "+IX-VERSION+" "+IXSYM-SHIFT+" "+IXSYM-CAPS+" 
   "+IXSYM-ALT+" "+IXSYM-SHIFTMASK+" "+IXSYM-CAPSMASK+" "+IXSYM-ALTMASK+" 
   "+IX-NORMALQUALS+" "+CBERR-OK+" "+CBERR-SYSERR+" "+CBERR-DUP+" 
   "+CBERR-VERSION+" "+COERR-ISNULL+" "+COERR-NULLATTACH+" 
   "+COERR-BADFILTER+" "+COERR-BADTYPE+" "*NEW-BROKER-SIZE*" 
   "NEW-BROKER-VERSION" "NEW-BROKER-RESERVE1" "NEW-BROKER-NAME" 
   "NEW-BROKER-TITLE" "NEW-BROKER-DESCR" "NEW-BROKER-UNIQUE" 
   "NEW-BROKER-FLAGS" "NEW-BROKER-PRI" "NEW-BROKER-RESERVE2" 
   "NEW-BROKER-PORT" "NEW-BROKER-RESERVED-CHANNEL" "*INPUT-XPRESSION-SIZE*" 
   "INPUT-XPRESSION-VERSION" "INPUT-XPRESSION-CLASS" "INPUT-XPRESSION-CODE" 
   "INPUT-XPRESSION-CODE-MASK" "INPUT-XPRESSION-QUALIFIER" 
   "INPUT-XPRESSION-QUAL-MASK" "INPUT-XPRESSION-QUAL-SAME" "CREATE-CX-OBJ" 
   "CX-BROKER" "ACTIVATE-CX-OBJ" "DELETE-CX-OBJ" "DELETE-CX-OBJ-ALL" 
   "CX-OBJ-TYPE" "CX-OBJ-ERROR" "CLEAR-CX-OBJ-ERROR" "SET-CX-OBJ-PRI" 
   "ATTACH-CX-OBJ" "ENQUEUE-CX-OBJ" "INSERT-CX-OBJ" "REMOVE-CX-OBJ" 
   "SET-TRANSLATE" "SET-FILTER" "SET-FILTER-IX" "PARSE-IX" "CX-MSG-TYPE" 
   "CX-MSG-DATA" "CX-MSG-ID" "DIVERT-CX-MSG" "ROUTE-CX-MSG" 
   "DISPOSE-CX-MSG" "INVERT-KEY-MAP" "ADD-I-EVENTS" "MATCH-IX" ))

(in-package "AMIGA.RAW.COMMODITIES")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *commodities-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "commodities.library" 0)))
(defvar *commodities-version*
  (and *commodities-base* (amiga.ffi:library-version *commodities-base*)))
(defun %version>= (n)
  (and *commodities-version* (>= *commodities-version* n)))

;;; --- constants from libraries/commodities.i ---
(defconstant +nb-version+ 5)
(defconstant +cbd-namelen+ #x18)
(defconstant +cbd-titlelen+ #x28)
(defconstant +cbd-descrlen+ #x28)
(defconstant +nbu-duplicate+ 0)
(defconstant +nbu-unique+ 1)
(defconstant +nbu-notify+ 2)
(defconstant +cof-show-hide+ 4)
(defconstant +cx-invalid+ 0)
(defconstant +cx-filter+ 1)
(defconstant +cx-typefilter+ 2)
(defconstant +cx-send+ 3)
(defconstant +cx-signal+ 4)
(defconstant +cx-translate+ 5)
(defconstant +cx-broker+ 6)
(defconstant +cx-debug+ 7)
(defconstant +cx-custom+ 8)
(defconstant +cx-zero+ 9)
(defconstant +cxm-ievent+ #x20)
(defconstant +cxm-command+ #x40)
(defconstant +cxcmd-disable+ 15)
(defconstant +cxcmd-enable+ #x11)
(defconstant +cxcmd-appear+ #x13)
(defconstant +cxcmd-disappear+ #x15)
(defconstant +cxcmd-kill+ #x17)
(defconstant +cxcmd-list-chg+ #x1B)
(defconstant +cxcmd-unique+ #x19)
(defconstant +ix-version+ 2)
(defconstant +ixsym-shift+ 1)
(defconstant +ixsym-caps+ 2)
(defconstant +ixsym-alt+ 4)
(defconstant +ixsym-shiftmask+ 3)
(defconstant +ixsym-capsmask+ 7)
(defconstant +ixsym-altmask+ #x30)
(defconstant +ix-normalquals+ #x7FFF)
(defconstant +cberr-ok+ 0)
(defconstant +cberr-syserr+ 1)
(defconstant +cberr-dup+ 2)
(defconstant +cberr-version+ 3)
(defconstant +coerr-isnull+ 1)
(defconstant +coerr-nullattach+ 2)
(defconstant +coerr-badfilter+ 4)
(defconstant +coerr-badtype+ 8)

;;; --- structures from libraries/commodities.i ---
(ffi:defcstruct (new-broker :size 26)   ; NewBroker (libraries/commodities.i)
  (version :i8 0)
  (reserve1 :i8 1)
  (name :fptr 2)
  (title :fptr 6)
  (descr :fptr 10)
  (unique :i16 14)
  (flags :i16 16)
  (pri :i8 18)
  (reserve2 :i8 19)
  (port :fptr 20)
  (reserved-channel :i16 24)
)
(ffi:defcstruct (input-xpression :size 12)   ; InputXpression (libraries/commodities.i)
  (version :u8 0)
  (class :u8 1)
  (code :u16 2)
  (code-mask :u16 4)
  (qualifier :u16 6)
  (qual-mask :u16 8)
  (qual-same :u16 10)
)

;;; --- functions (commodities_lib.sfd + MorphOS SDK) ---
(amiga.ffi:defcfun create-cx-obj *commodities-base* -30 (:d0 type :a0 arg1 :a1 arg2)
    :result :pointer
    :doc "CxObj * CreateCxObj(ULONG type, LONG arg1, LONG arg2) (D0,A0,A1) LVO -30")
(amiga.ffi:defcfun cx-broker *commodities-base* -36 (:a0 nb :d0 error)
    :result :pointer
    :doc "CxObj * CxBroker(CONST struct NewBroker * nb, LONG * error) (A0,D0) LVO -36")
(amiga.ffi:defcfun activate-cx-obj *commodities-base* -42 (:a0 co :d0 flag)
    :result :signed
    :doc "LONG ActivateCxObj(CxObj * co, LONG flag) (A0,D0) LVO -42")
(amiga.ffi:defcfun delete-cx-obj *commodities-base* -48 (:a0 co)
    :result :void
    :doc "VOID DeleteCxObj(CxObj * co) (A0) LVO -48")
(amiga.ffi:defcfun delete-cx-obj-all *commodities-base* -54 (:a0 co)
    :result :void
    :doc "VOID DeleteCxObjAll(CxObj * co) (A0) LVO -54")
(amiga.ffi:defcfun cx-obj-type *commodities-base* -60 (:a0 co)
    :result :unsigned
    :doc "ULONG CxObjType(CONST CxObj * co) (A0) LVO -60")
(amiga.ffi:defcfun cx-obj-error *commodities-base* -66 (:a0 co)
    :result :signed
    :doc "LONG CxObjError(CONST CxObj * co) (A0) LVO -66")
(amiga.ffi:defcfun clear-cx-obj-error *commodities-base* -72 (:a0 co)
    :result :void
    :doc "VOID ClearCxObjError(CxObj * co) (A0) LVO -72")
(amiga.ffi:defcfun set-cx-obj-pri *commodities-base* -78 (:a0 co :d0 pri)
    :result :signed
    :doc "LONG SetCxObjPri(CxObj * co, LONG pri) (A0,D0) LVO -78")
(amiga.ffi:defcfun attach-cx-obj *commodities-base* -84 (:a0 head-obj :a1 co)
    :result :void
    :doc "VOID AttachCxObj(CxObj * headObj, CxObj * co) (A0,A1) LVO -84")
(amiga.ffi:defcfun enqueue-cx-obj *commodities-base* -90 (:a0 head-obj :a1 co)
    :result :void
    :doc "VOID EnqueueCxObj(CxObj * headObj, CxObj * co) (A0,A1) LVO -90")
(amiga.ffi:defcfun insert-cx-obj *commodities-base* -96 (:a0 head-obj :a1 co :a2 pred)
    :result :void
    :doc "VOID InsertCxObj(CxObj * headObj, CxObj * co, CxObj * pred) (A0,A1,A2) LVO -96")
(amiga.ffi:defcfun remove-cx-obj *commodities-base* -102 (:a0 co)
    :result :void
    :doc "VOID RemoveCxObj(CxObj * co) (A0) LVO -102")
(amiga.ffi:defcfun set-translate *commodities-base* -114 (:a0 translator :a1 events)
    :result :void
    :doc "VOID SetTranslate(CxObj * translator, struct InputEvent * events) (A0,A1) LVO -114")
(amiga.ffi:defcfun set-filter *commodities-base* -120 (:a0 filter :a1 text)
    :result :void
    :doc "VOID SetFilter(CxObj * filter, CONST_STRPTR text) (A0,A1) LVO -120")
(amiga.ffi:defcfun set-filter-ix *commodities-base* -126 (:a0 filter :a1 ix)
    :result :void
    :doc "VOID SetFilterIX(CxObj * filter, CONST IX * ix) (A0,A1) LVO -126")
(amiga.ffi:defcfun parse-ix *commodities-base* -132 (:a0 description :a1 ix)
    :result :signed
    :doc "LONG ParseIX(CONST_STRPTR description, IX * ix) (A0,A1) LVO -132")
(amiga.ffi:defcfun cx-msg-type *commodities-base* -138 (:a0 cxm)
    :result :unsigned
    :doc "ULONG CxMsgType(CONST CxMsg * cxm) (A0) LVO -138")
(amiga.ffi:defcfun cx-msg-data *commodities-base* -144 (:a0 cxm)
    :result :pointer
    :doc "APTR CxMsgData(CONST CxMsg * cxm) (A0) LVO -144")
(amiga.ffi:defcfun cx-msg-id *commodities-base* -150 (:a0 cxm)
    :result :signed
    :doc "LONG CxMsgID(CONST CxMsg * cxm) (A0) LVO -150")
(amiga.ffi:defcfun divert-cx-msg *commodities-base* -156 (:a0 cxm :a1 head-obj :a2 return-obj)
    :result :void
    :doc "VOID DivertCxMsg(CxMsg * cxm, CxObj * headObj, CxObj * returnObj) (A0,A1,A2) LVO -156")
(amiga.ffi:defcfun route-cx-msg *commodities-base* -162 (:a0 cxm :a1 co)
    :result :void
    :doc "VOID RouteCxMsg(CxMsg * cxm, CxObj * co) (A0,A1) LVO -162")
(amiga.ffi:defcfun dispose-cx-msg *commodities-base* -168 (:a0 cxm)
    :result :void
    :doc "VOID DisposeCxMsg(CxMsg * cxm) (A0) LVO -168")
(amiga.ffi:defcfun invert-key-map *commodities-base* -174 (:d0 ansi-code :a0 event :a1 km)
    :result :bool
    :doc "BOOL InvertKeyMap(ULONG ansiCode, struct InputEvent * event, CONST struct KeyMap * km) (D0,A0,A1) LVO -174")
(amiga.ffi:defcfun add-i-events *commodities-base* -180 (:a0 events)
    :result :void
    :doc "VOID AddIEvents(struct InputEvent * events) (A0) LVO -180")
(amiga.ffi:defcfun match-ix *commodities-base* -204 (:a0 event :a1 ix)
    :result :bool
    :doc "BOOL MatchIX(CONST struct InputEvent * event, CONST IX * ix) (A0,A1) LVO -204")

(provide "amiga/raw/commodities")
