;;; amiga/raw/console  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   console_lib.sfd ($VER: console_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK console_lib.fd + clib/console_protos.h (via fd2sfd)
;;;   devices/console.i
;;;   devices/conunit.i
;;;
;;; 2 functions, 65 constants, 2 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.CONSOLE"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export "*CONSOLE-BASE*" "*CONSOLE-VERSION*"))

(in-package "AMIGA.RAW.CONSOLE")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
;;; console.device is a device/resource: there is no OpenLibrary.  Set the base
;;; yourself (IORequest io_Device after OpenDevice, or OpenResource).
(defvar *console-base* nil)
(defvar *console-version*
  (and *console-base* (amiga.ffi:library-version *console-base*)))
(defun %version>= (n)
  (and *console-version* (>= *console-version* n)))

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.CONSOLE"
    (:base *console-base* :version *console-version*)

  ;; --- constants from devices/console.i ---
  (:const "+CD-ASKKEYMAP+" 9)
  (:const "+CD-SETKEYMAP+" 10)
  (:const "+CD-ASKDEFAULTKEYMAP+" 11)
  (:const "+CD-SETDEFAULTKEYMAP+" 12)
  (:const "+CD-SETUPSCROLLBACK+" 13)
  (:const "+CD-SETSCROLLBACKPOSITION+" 14)
  (:const "+SGR-PRIMARY+" 0)
  (:const "+SGR-BOLD+" 1)
  (:const "+SGR-ITALIC+" 3)
  (:const "+SGR-UNDERSCORE+" 4)
  (:const "+SGR-NEGATIVE+" 7)
  (:const "+SGR-NORMAL+" #x16)
  (:const "+SGR-NOTITALIC+" #x17)
  (:const "+SGR-NOTUNDERSCORE+" #x18)
  (:const "+SGR-POSITIVE+" #x1B)
  (:const "+SGR-BLACK+" #x1E)
  (:const "+SGR-RED+" #x1F)
  (:const "+SGR-GREEN+" #x20)
  (:const "+SGR-YELLOW+" #x21)
  (:const "+SGR-BLUE+" #x22)
  (:const "+SGR-MAGENTA+" #x23)
  (:const "+SGR-CYAN+" #x24)
  (:const "+SGR-WHITE+" #x25)
  (:const "+SGR-DEFAULT+" #x27)
  (:const "+SGR-BLACKBG+" #x28)
  (:const "+SGR-REDBG+" #x29)
  (:const "+SGR-GREENBG+" #x2A)
  (:const "+SGR-YELLOWBG+" #x2B)
  (:const "+SGR-BLUEBG+" #x2C)
  (:const "+SGR-MAGENTABG+" #x2D)
  (:const "+SGR-CYANBG+" #x2E)
  (:const "+SGR-WHITEBG+" #x2F)
  (:const "+SGR-DEFAULTBG+" #x31)
  (:const "+SGR-CLR0+" #x1E)
  (:const "+SGR-CLR1+" #x1F)
  (:const "+SGR-CLR2+" #x20)
  (:const "+SGR-CLR3+" #x21)
  (:const "+SGR-CLR4+" #x22)
  (:const "+SGR-CLR5+" #x23)
  (:const "+SGR-CLR6+" #x24)
  (:const "+SGR-CLR7+" #x25)
  (:const "+SGR-CLR0-BG+" #x28)
  (:const "+SGR-CLR1-BG+" #x29)
  (:const "+SGR-CLR2-BG+" #x2A)
  (:const "+SGR-CLR3-BG+" #x2B)
  (:const "+SGR-CLR4-BG+" #x2C)
  (:const "+SGR-CLR5-BG+" #x2D)
  (:const "+SGR-CLR6-BG+" #x2E)
  (:const "+SGR-CLR7-BG+" #x2F)
  (:const "+DSR-CPR+" 6)
  (:const "+CTC-HSETTAB+" 0)
  (:const "+CTC-HCLRTAB+" 2)
  (:const "+CTC-HCLRTABSALL+" 5)
  (:const "+TBC-HCLRTAB+" 0)
  (:const "+TBC-HCLRTABSALL+" 3)
  (:const "+M-LNM+" #x14)

  ;; --- structures from devices/console.i ---
  (:struct "CONSOLE-SCROLLBACK" 6   ; ConsoleScrollback (devices/console.i)
    ("SCROLLER-GADGET" :fptr 0)
    ("NUM-LINES" :u16 4)
    )

  ;; --- constants from devices/conunit.i ---
  (:const "+CONU-LIBRARY+" -1)
  (:const "+CONU-STANDARD+" 0)
  (:const "+CONU-CHARMAP+" 1)
  (:const "+CONU-SNIPMAP+" 3)
  (:const "+CONFLAG-DEFAULT+" 0)
  (:const "+CONFLAG-NODRAW-ON-NEWSIZE+" 1)
  (:const "+PMB-ASM+" #x15)
  (:const "+PMB-AWM+" #x16)
  (:const "+MAXTABS+" #x50)

  ;; --- structures from devices/conunit.i ---
  (:struct "CON-UNIT" 296   ; ConUnit (devices/conunit.i)
    ("WINDOW" :fptr 34)
    ("XCP" :i16 38)
    ("YCP" :i16 40)
    ("X-MAX" :i16 42)
    ("Y-MAX" :i16 44)
    ("XR-SIZE" :i16 46)
    ("YR-SIZE" :i16 48)
    ("XR-ORIGIN" :i16 50)
    ("YR-ORIGIN" :i16 52)
    ("XR-EXTANT" :i16 54)
    ("YR-EXTANT" :i16 56)
    ("X-MIN-SHRINK" :i16 58)
    ("Y-MIN-SHRINK" :i16 60)
    ("XCCP" :i16 62)
    ("YCCP" :i16 64)
    ("KEY-MAP-STRUCT" (:struct 32) 66)
    ("TAB-STOPS" (:struct 160) 98)
    ("MASK" :i8 258)
    ("FG-PEN" :i8 259)
    ("BG-PEN" :i8 260)
    ("AOL-PEN" :i8 261)
    ("DRAW-MODE" :i8 262)
    ("OBSOLETE1" :i8 263)
    ("OBSOLETE2" :fptr 264)
    ("MINTERMS" (:struct 8) 268)
    ("FONT" :fptr 276)
    ("ALGO-STYLE" :u8 280)
    ("TX-FLAGS" :u8 281)
    ("TX-HEIGHT" :u16 282)
    ("TX-WIDTH" :u16 284)
    ("TX-BASELINE" :u16 286)
    ("TX-SPACING" :i16 288)
    ("MODES" (:struct 3) 290)
    ("RAW-EVENTS" (:struct 3) 293)
    )

  ;; --- functions (console_lib.sfd + MorphOS SDK) ---
  (:fn "CD-INPUT-HANDLER" -42 (:a0 :a1) :pointer)   ; struct InputEvent * CDInputHandler(CONST struct InputEvent * events, struct Library * consoleDevice) (A0,A1) LVO -42
  (:fn "RAW-KEY-CONVERT" -48 (:a0 :a1 :d1 :a2) :signed)   ; LONG RawKeyConvert(CONST struct InputEvent * events, STRPTR buffer, LONG length, CONST struct KeyMap * keyMap) (A0,A1,D1,A2) LVO -48
  )

(provide "amiga/raw/console")
