;;; amiga/raw/dos  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   dos_lib.sfd ($VER: dos_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK dos_lib.fd + clib/dos_protos.h (via fd2sfd)
;;;   dos/datetime.i
;;;   dos/dos.i
;;;   dos/dos_lib.i
;;;   dos/dosasl.i
;;;   dos/dosextens.i
;;;   dos/doshunks.i
;;;   dos/dostags.i
;;;   dos/exall.i
;;;   dos/filehandler.i
;;;   dos/notify.i
;;;   dos/rdargs.i
;;;   dos/record.i
;;;   dos/shell.i
;;;   dos/stdio.i
;;;   dos/var.i
;;;
;;; 163 functions, 507 constants, 35 structs, 22 skipped (see comments).
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.DOS"
  (:use "CL" "FFI" "AMIGA.FFI")
  ;; distinct symbols  these names also exist in CL / FFI / AMIGA.FFI
  (:shadow "OPEN" "CLOSE" "READ" "WRITE" "DELETE-FILE" "FORMAT")
  (:export "*DOS-BASE*" "*DOS-VERSION*"))

(in-package "AMIGA.RAW.DOS")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *dos-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "dos.library" 0)))
(defvar *dos-version*
  (and *dos-base* (amiga.ffi:library-version *dos-base*)))
(defun %version>= (n)
  (and *dos-version* (>= *dos-version* n)))

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.DOS"
    (:base *dos-base* :version *dos-version*)

  ;; --- constants from dos/datetime.i ---
  (:const "+LEN-DATSTRING+" #x10)
  (:const "+DTB-SUBST+" 0)
  (:const "+DTF-SUBST+" 1)
  (:const "+DTB-FUTURE+" 1)
  (:const "+DTF-FUTURE+" 2)
  (:const "+FORMAT-DOS+" 0)
  (:const "+FORMAT-INT+" 1)
  (:const "+FORMAT-USA+" 2)
  (:const "+FORMAT-CDN+" 3)
  (:const "+FORMAT-DEF+" 4)
  (:const "+FORMAT-MAX+" 3)

  ;; --- structures from dos/datetime.i ---
  (:struct "DATE-TIME" 26   ; DateTime (dos/datetime.i)
    ("STAMP" (:struct 12) 0)
    ("FORMAT" :u8 12)
    ("FLAGS" :u8 13)
    ("STR-DAY" :fptr 14)
    ("STR-DATE" :fptr 18)
    ("STR-TIME" :fptr 22)
    )

  ;; --- constants from dos/dos.i ---
  (:const "+DOSTRUE+" -1)
  (:const "+DOSFALSE+" 0)
  (:const "+MODE-OLDFILE+" #x3ED)
  (:const "+MODE-NEWFILE+" #x3EE)
  (:const "+MODE-READWRITE+" #x3EC)
  (:const "+OFFSET-BEGINNING+" -1)
  (:const "+OFFSET-CURRENT+" 0)
  (:const "+OFFSET-END+" 1)
  (:const "+OFFSET-BEGINING+" -1)
  (:const "+BITSPERBYTE+" 8)
  (:const "+BYTESPERLONG+" 4)
  (:const "+BITSPERLONG+" #x20)
  (:const "+MAXINT+" #x7FFFFFFF)
  (:const "+MININT+" #x80000000)
  (:const "+SHARED-LOCK+" -2)
  (:const "+ACCESS-READ+" -2)
  (:const "+EXCLUSIVE-LOCK+" -1)
  (:const "+ACCESS-WRITE+" -1)
  (:const "+TICKS-PER-SECOND+" #x32)
  (:const "+FIBB-OTR-READ+" 15)
  (:const "+FIBF-OTR-READ+" #x8000)
  (:const "+FIBB-OTR-WRITE+" 14)
  (:const "+FIBF-OTR-WRITE+" #x4000)
  (:const "+FIBB-OTR-EXECUTE+" 13)
  (:const "+FIBF-OTR-EXECUTE+" #x2000)
  (:const "+FIBB-OTR-DELETE+" 12)
  (:const "+FIBF-OTR-DELETE+" #x1000)
  (:const "+FIBB-GRP-READ+" 11)
  (:const "+FIBF-GRP-READ+" #x800)
  (:const "+FIBB-GRP-WRITE+" 10)
  (:const "+FIBF-GRP-WRITE+" #x400)
  (:const "+FIBB-GRP-EXECUTE+" 9)
  (:const "+FIBF-GRP-EXECUTE+" #x200)
  (:const "+FIBB-GRP-DELETE+" 8)
  (:const "+FIBF-GRP-DELETE+" #x100)
  (:const "+FIBB-HOLD+" 7)
  (:const "+FIBF-HOLD+" #x80)
  (:const "+FIBB-SCRIPT+" 6)
  (:const "+FIBF-SCRIPT+" #x40)
  (:const "+FIBB-PURE+" 5)
  (:const "+FIBF-PURE+" #x20)
  (:const "+FIBB-ARCHIVE+" 4)
  (:const "+FIBF-ARCHIVE+" #x10)
  (:const "+FIBB-READ+" 3)
  (:const "+FIBF-READ+" 8)
  (:const "+FIBB-WRITE+" 2)
  (:const "+FIBF-WRITE+" 4)
  (:const "+FIBB-EXECUTE+" 1)
  (:const "+FIBF-EXECUTE+" 2)
  (:const "+FIBB-DELETE+" 0)
  (:const "+FIBF-DELETE+" 1)
  (:const "+FAULT-MAX+" #x52)
  (:const "+ID-WRITE-PROTECTED+" #x50)
  (:const "+ID-VALIDATING+" #x51)
  (:const "+ID-VALIDATED+" #x52)
  (:const "+ID-NO-DISK-PRESENT+" -1)
  (:const "+ID-UNREADABLE-DISK+" #x42414400)
  (:const "+ID-NOT-REALLY-DOS+" #x4E444F53)
  (:const "+ID-DOS-DISK+" #x444F5300)
  (:const "+ID-FFS-DISK+" #x444F5301)
  (:const "+ID-INTER-DOS-DISK+" #x444F5302)
  (:const "+ID-INTER-FFS-DISK+" #x444F5303)
  (:const "+ID-FASTDIR-DOS-DISK+" #x444F5304)
  (:const "+ID-FASTDIR-FFS-DISK+" #x444F5305)
  (:const "+ID-LONG-DOS-DISK+" #x444F5306)
  (:const "+ID-LONG-FFS-DISK+" #x444F5307)
  (:const "+ID-COMPLONG-FFS-DISK+" #x444F5308)
  (:const "+ID-KICKSTART-DISK+" #x4B49434B)
  (:const "+ID-MSDOS-DISK+" #x4D534400)
  (:const "+ERROR-NO-FREE-STORE+" #x67)
  (:const "+ERROR-TASK-TABLE-FULL+" #x69)
  (:const "+ERROR-BAD-TEMPLATE+" #x72)
  (:const "+ERROR-BAD-NUMBER+" #x73)
  (:const "+ERROR-REQUIRED-ARG-MISSING+" #x74)
  (:const "+ERROR-KEY-NEEDS-ARG+" #x75)
  (:const "+ERROR-TOO-MANY-ARGS+" #x76)
  (:const "+ERROR-UNMATCHED-QUOTES+" #x77)
  (:const "+ERROR-LINE-TOO-LONG+" #x78)
  (:const "+ERROR-FILE-NOT-OBJECT+" #x79)
  (:const "+ERROR-INVALID-RESIDENT-LIBRARY+" #x7A)
  (:const "+ERROR-NO-DEFAULT-DIR+" #xC9)
  (:const "+ERROR-OBJECT-IN-USE+" #xCA)
  (:const "+ERROR-OBJECT-EXISTS+" #xCB)
  (:const "+ERROR-DIR-NOT-FOUND+" #xCC)
  (:const "+ERROR-OBJECT-NOT-FOUND+" #xCD)
  (:const "+ERROR-BAD-STREAM-NAME+" #xCE)
  (:const "+ERROR-OBJECT-TOO-LARGE+" #xCF)
  (:const "+ERROR-ACTION-NOT-KNOWN+" #xD1)
  (:const "+ERROR-INVALID-COMPONENT-NAME+" #xD2)
  (:const "+ERROR-INVALID-LOCK+" #xD3)
  (:const "+ERROR-OBJECT-WRONG-TYPE+" #xD4)
  (:const "+ERROR-DISK-NOT-VALIDATED+" #xD5)
  (:const "+ERROR-DISK-WRITE-PROTECTED+" #xD6)
  (:const "+ERROR-RENAME-ACROSS-DEVICES+" #xD7)
  (:const "+ERROR-DIRECTORY-NOT-EMPTY+" #xD8)
  (:const "+ERROR-TOO-MANY-LEVELS+" #xD9)
  (:const "+ERROR-DEVICE-NOT-MOUNTED+" #xDA)
  (:const "+ERROR-SEEK-ERROR+" #xDB)
  (:const "+ERROR-COMMENT-TOO-BIG+" #xDC)
  (:const "+ERROR-DISK-FULL+" #xDD)
  (:const "+ERROR-DELETE-PROTECTED+" #xDE)
  (:const "+ERROR-WRITE-PROTECTED+" #xDF)
  (:const "+ERROR-READ-PROTECTED+" #xE0)
  (:const "+ERROR-NOT-A-DOS-DISK+" #xE1)
  (:const "+ERROR-NO-DISK+" #xE2)
  (:const "+ERROR-NO-MORE-ENTRIES+" #xE8)
  (:const "+ERROR-IS-SOFT-LINK+" #xE9)
  (:const "+ERROR-OBJECT-LINKED+" #xEA)
  (:const "+ERROR-BAD-HUNK+" #xEB)
  (:const "+ERROR-NOT-IMPLEMENTED+" #xEC)
  (:const "+ERROR-RECORD-NOT-LOCKED+" #xF0)
  (:const "+ERROR-LOCK-COLLISION+" #xF1)
  (:const "+ERROR-LOCK-TIMEOUT+" #xF2)
  (:const "+ERROR-UNLOCK-ERROR+" #xF3)
  (:const "+RETURN-OK+" 0)
  (:const "+RETURN-WARN+" 5)
  (:const "+RETURN-ERROR+" 10)
  (:const "+RETURN-FAIL+" #x14)
  (:const "+SIGBREAKB-CTRL-C+" 12)
  (:const "+SIGBREAKF-CTRL-C+" #x1000)
  (:const "+SIGBREAKB-CTRL-D+" 13)
  (:const "+SIGBREAKF-CTRL-D+" #x2000)
  (:const "+SIGBREAKB-CTRL-E+" 14)
  (:const "+SIGBREAKF-CTRL-E+" #x4000)
  (:const "+SIGBREAKB-CTRL-F+" 15)
  (:const "+SIGBREAKF-CTRL-F+" #x8000)
  (:const "+LOCK-DIFFERENT+" -1)
  (:const "+LOCK-SAME+" 0)
  (:const "+LOCK-SAME-VOLUME+" 1)
  (:const "+LOCK-SAME-HANDLER+" 1)
  (:const "+CHANGE-LOCK+" 0)
  (:const "+CHANGE-FH+" 1)
  (:const "+LINK-HARD+" 0)
  (:const "+LINK-SOFT+" 1)
  (:const "+ITEM-EQUAL+" -2)
  (:const "+ITEM-ERROR+" -1)
  (:const "+ITEM-NOTHING+" 0)
  (:const "+ITEM-UNQUOTED+" 1)
  (:const "+ITEM-QUOTED+" 2)
  (:const "+DOS-FILEHANDLE+" 0)
  (:const "+DOS-EXALLCONTROL+" 1)
  (:const "+DOS-FIB+" 2)
  (:const "+DOS-STDPKT+" 3)
  (:const "+DOS-CLI+" 4)
  (:const "+DOS-RDARGS+" 5)

  ;; --- structures from dos/dos.i ---
  (:struct "DATE-STAMP" 12   ; DateStamp (dos/dos.i)
    ("DAYS" :i32 0)
    ("MINUTE" :i32 4)
    ("TICK" :i32 8)
    )
  (:struct "FILE-INFO-BLOCK" 260   ; FileInfoBlock (dos/dos.i)
    ("DISK-KEY" :i32 0)
    ("DIR-ENTRY-TYPE" :i32 4)
    ("FILE-NAME" (:struct 108) 8)
    ("PROTECTION" :i32 116)
    ("ENTRY-TYPE" :i32 120)
    ("SIZE" :i32 124)
    ("NUM-BLOCKS" :i32 128)
    ("DATE-STAMP" (:struct 12) 132)
    ("COMMENT" (:struct 80) 144)
    ("OWNER-UID" :u16 224)
    ("OWNER-GID" :u16 226)
    ("RESERVED" (:struct 32) 228)
    )
  (:struct "INFO-DATA" 36   ; InfoData (dos/dos.i)
    ("NUM-SOFT-ERRORS" :i32 0)
    ("UNIT-NUMBER" :i32 4)
    ("DISK-STATE" :i32 8)
    ("NUM-BLOCKS" :i32 12)
    ("NUM-BLOCKS-USED" :i32 16)
    ("BYTES-PER-BLOCK" :i32 20)
    ("DISK-TYPE" :i32 24)
    ("VOLUME-NODE" :u32 28)
    ("IN-USE" :i32 32)
    )

  ;; --- constants from dos/dos_lib.i ---
  (:const "+RESERVE+" 4)
  (:const "+VSIZE+" 6)

  ;; --- constants from dos/dosasl.i ---
  (:const "+APB-DOWILD+" 0)
  (:const "+APF-DOWILD+" 1)
  (:const "+APB-ITSWILD+" 1)
  (:const "+APF-ITSWILD+" 2)
  (:const "+APB-DODIR+" 2)
  (:const "+APF-DODIR+" 4)
  (:const "+APB-DIDDIR+" 3)
  (:const "+APF-DIDDIR+" 8)
  (:const "+APB-NOMEMERR+" 4)
  (:const "+APF-NOMEMERR+" #x10)
  (:const "+APB-DODOT+" 5)
  (:const "+APF-DODOT+" #x20)
  (:const "+APB-DIR-CHANGED+" 6)
  (:const "+APF-DIR-CHANGED+" #x40)
  (:const "+APB-FOLLOW-H-LINKS+" 7)
  (:const "+APF-FOLLOW-H-LINKS+" #x80)
  (:const "+DDB-PATTERN-BIT+" 0)
  (:const "+DDF-PATTERN-BIT+" 1)
  (:const "+DDB-EXAMINED-BIT+" 1)
  (:const "+DDF-EXAMINED-BIT+" 2)
  (:const "+DDB-COMPLETED+" 2)
  (:const "+DDF-COMPLETED+" 4)
  (:const "+DDB-ALL-BIT+" 3)
  (:const "+DDF-ALL-BIT+" 8)
  (:const "+DDB-SINGLE+" 4)
  (:const "+DDF-SINGLE+" #x10)
  (:const "+P-ANY+" #x80)
  (:const "+P-SINGLE+" #x81)
  (:const "+P-ORSTART+" #x82)
  (:const "+P-ORNEXT+" #x83)
  (:const "+P-OREND+" #x84)
  (:const "+P-NOT+" #x85)
  (:const "+P-NOTEND+" #x86)
  (:const "+P-NOTCLASS+" #x87)
  (:const "+P-CLASS+" #x88)
  (:const "+P-REPBEG+" #x89)
  (:const "+P-REPEND+" #x8A)
  (:const "+P-STOP+" #x8B)
  (:const "+COMPLEX-BIT+" 1)
  (:const "+EXAMINE-BIT+" 2)
  (:const "+ERROR-BUFFER-OVERFLOW+" #x12F)
  (:const "+ERROR-BREAK+" #x130)
  (:const "+ERROR-NOT-EXECUTABLE+" #x131)

  ;; --- structures from dos/dosasl.i ---
  (:struct "ANCHOR-PATH" 280   ; AnchorPath (dos/dosasl.i)
    ("FIRST" (:struct 0) 0)
    ("BASE" :fptr 0)
    ("CURRENT" (:struct 0) 4)
    ("LAST" :fptr 4)
    ("BREAK-BITS" :i32 8)
    ("FOUND-BREAK" :i32 12)
    ("LENGTH" (:struct 0) 16)
    ("FLAGS" :i8 16)
    ("RESERVED" :i8 17)
    ("STRLEN" :i16 18)
    ("INFO" (:struct 260) 20)
    )
  (:struct "A-CHAIN" 273   ; AChain (dos/dosasl.i)
    ("CHILD" :fptr 0)
    ("PARENT" :fptr 4)
    ("LOCK" :i32 8)
    ("INFO" (:struct 260) 12)
    ("FLAGS" :i8 272)
    )

  ;; --- constants from dos/dosextens.i ---
  (:const "+PRB-FREESEGLIST+" 0)
  (:const "+PRF-FREESEGLIST+" 1)
  (:const "+PRB-FREECURRDIR+" 1)
  (:const "+PRF-FREECURRDIR+" 2)
  (:const "+PRB-FREECLI+" 2)
  (:const "+PRF-FREECLI+" 4)
  (:const "+PRB-CLOSEINPUT+" 3)
  (:const "+PRF-CLOSEINPUT+" 8)
  (:const "+PRB-CLOSEOUTPUT+" 4)
  (:const "+PRF-CLOSEOUTPUT+" #x10)
  (:const "+PRB-FREEARGS+" 5)
  (:const "+PRF-FREEARGS+" #x20)
  (:const "+PRB-CLOSEERROR+" 6)
  (:const "+PRF-CLOSEERROR+" #x40)
  (:const "+FH-FUNC1+" #x18)
  (:const "+FH-ARG1+" #x24)
  (:const "+DP-ACTION+" 8)
  (:const "+DP-STATUS+" 12)
  (:const "+DP-STATUS2+" #x10)
  (:const "+DP-BUF-ADDR+" #x14)
  (:const "+ACTION-NIL+" 0)
  (:const "+ACTION-STARTUP+" 0)
  (:const "+ACTION-GET-BLOCK+" 2)
  (:const "+ACTION-SET-MAP+" 4)
  (:const "+ACTION-DIE+" 5)
  (:const "+ACTION-EVENT+" 6)
  (:const "+ACTION-CURRENT-VOLUME+" 7)
  (:const "+ACTION-LOCATE-OBJECT+" 8)
  (:const "+ACTION-RENAME-DISK+" 9)
  (:const "+ACTION-WRITE+" #x57)
  (:const "+ACTION-READ+" #x52)
  (:const "+ACTION-FREE-LOCK+" 15)
  (:const "+ACTION-DELETE-OBJECT+" #x10)
  (:const "+ACTION-RENAME-OBJECT+" #x11)
  (:const "+ACTION-MORE-CACHE+" #x12)
  (:const "+ACTION-COPY-DIR+" #x13)
  (:const "+ACTION-WAIT-CHAR+" #x14)
  (:const "+ACTION-SET-PROTECT+" #x15)
  (:const "+ACTION-CREATE-DIR+" #x16)
  (:const "+ACTION-EXAMINE-OBJECT+" #x17)
  (:const "+ACTION-EXAMINE-NEXT+" #x18)
  (:const "+ACTION-DISK-INFO+" #x19)
  (:const "+ACTION-INFO+" #x1A)
  (:const "+ACTION-FLUSH+" #x1B)
  (:const "+ACTION-SET-COMMENT+" #x1C)
  (:const "+ACTION-PARENT+" #x1D)
  (:const "+ACTION-TIMER+" #x1E)
  (:const "+ACTION-INHIBIT+" #x1F)
  (:const "+ACTION-DISK-TYPE+" #x20)
  (:const "+ACTION-DISK-CHANGE+" #x21)
  (:const "+ACTION-SET-DATE+" #x22)
  (:const "+ACTION-UNDISK-INFO+" #x201)
  (:const "+ACTION-SCREEN-MODE+" #x3E2)
  (:const "+ACTION-READ-RETURN+" #x3E9)
  (:const "+ACTION-WRITE-RETURN+" #x3EA)
  (:const "+ACTION-SEEK+" #x3F0)
  (:const "+ACTION-FINDUPDATE+" #x3EC)
  (:const "+ACTION-FINDINPUT+" #x3ED)
  (:const "+ACTION-FINDOUTPUT+" #x3EE)
  (:const "+ACTION-END+" #x3EF)
  (:const "+ACTION-SET-FILE-SIZE+" #x3FE)
  (:const "+ACTION-WRITE-PROTECT+" #x3FF)
  (:const "+ACTION-SAME-LOCK+" #x28)
  (:const "+ACTION-CHANGE-SIGNAL+" #x3E3)
  (:const "+ACTION-FORMAT+" #x3FC)
  (:const "+ACTION-MAKE-LINK+" #x3FD)
  (:const "+ACTION-READ-LINK+" #x400)
  (:const "+ACTION-FH-FROM-LOCK+" #x402)
  (:const "+ACTION-IS-FILESYSTEM+" #x403)
  (:const "+ACTION-CHANGE-MODE+" #x404)
  (:const "+ACTION-COPY-DIR-FH+" #x406)
  (:const "+ACTION-PARENT-FH+" #x407)
  (:const "+ACTION-EXAMINE-ALL+" #x409)
  (:const "+ACTION-EXAMINE-FH+" #x40A)
  (:const "+ACTION-LOCK-RECORD+" #x7D8)
  (:const "+ACTION-FREE-RECORD+" #x7D9)
  (:const "+ACTION-ADD-NOTIFY+" #x1001)
  (:const "+ACTION-REMOVE-NOTIFY+" #x1002)
  (:const "+ACTION-EXAMINE-ALL-END+" #x40B)
  (:const "+ACTION-SET-OWNER+" #x40C)
  (:const "+ACTION-SERIALIZE-DISK+" #x1068)
  (:const "+RNB-WILDSTAR+" #x18)
  (:const "+RNF-WILDSTAR+" #x1000000)
  (:const "+RNB-PRIVATE1+" 1)
  (:const "+RNF-PRIVATE1+" 2)
  (:const "+DI-RES-LIST+" 0)
  (:const "+CMD-SYSTEM+" -1)
  (:const "+CMD-INTERNAL+" -2)
  (:const "+CMD-DISABLED+" -999)
  (:const "+DLT-DEVICE+" 0)
  (:const "+DLT-DIRECTORY+" 1)
  (:const "+DLT-VOLUME+" 2)
  (:const "+DLT-LATE+" 3)
  (:const "+DLT-NONBINDING+" 4)
  (:const "+DLT-PRIVATE+" -1)
  (:const "+DVPB-UNLOCK+" 0)
  (:const "+DVPF-UNLOCK+" 1)
  (:const "+DVPB-ASSIGN+" 1)
  (:const "+DVPF-ASSIGN+" 2)
  (:const "+LDB-DEVICES+" 2)
  (:const "+LDF-DEVICES+" 4)
  (:const "+LDB-VOLUMES+" 3)
  (:const "+LDF-VOLUMES+" 8)
  (:const "+LDB-ASSIGNS+" 4)
  (:const "+LDF-ASSIGNS+" #x10)
  (:const "+LDB-ENTRY+" 5)
  (:const "+LDF-ENTRY+" #x20)
  (:const "+LDB-DELETE+" 6)
  (:const "+LDF-DELETE+" #x40)
  (:const "+LDB-READ+" 0)
  (:const "+LDF-READ+" 1)
  (:const "+LDB-WRITE+" 1)
  (:const "+LDF-WRITE+" 2)
  (:const "+LDF-ALL+" #x1C)
  (:const "+REPORT-STREAM+" 0)
  (:const "+REPORT-TASK+" 1)
  (:const "+REPORT-LOCK+" 2)
  (:const "+REPORT-VOLUME+" 3)
  (:const "+REPORT-INSERT+" 4)
  (:const "+ABORT-DISK-ERROR+" #x128)
  (:const "+ABORT-BUSY+" #x120)
  (:const "+RUN-EXECUTE+" -1)
  (:const "+RUN-SYSTEM+" -2)
  (:const "+RUN-SYSTEM-ASYNCH+" -3)
  (:const "+ST-ROOT+" 1)
  (:const "+ST-USERDIR+" 2)
  (:const "+ST-SOFTLINK+" 3)
  (:const "+ST-LINKDIR+" 4)
  (:const "+ST-FILE+" -3)
  (:const "+ST-LINKFILE+" -4)
  (:const "+ST-PIPEFILE+" -5)

  ;; --- structures from dos/dosextens.i ---
  (:struct "PROCESS" 228   ; Process (dos/dosextens.i)
    ("TASK" (:struct 92) 0)
    ("MSG-PORT" (:struct 34) 92)
    ("PAD" :i16 126)
    ("SEG-LIST" :u32 128)
    ("STACK-SIZE" :i32 132)
    ("GLOB-VEC" :fptr 136)
    ("TASK-NUM" :i32 140)
    ("STACK-BASE" :u32 144)
    ("RESULT2" :i32 148)
    ("CURRENT-DIR" :u32 152)
    ("CIS" :u32 156)
    ("COS" :u32 160)
    ("CONSOLE-TASK" :fptr 164)
    ("FILE-SYSTEM-TASK" :fptr 168)
    ("CLI" :u32 172)
    ("RETURN-ADDR" :fptr 176)
    ("PKT-WAIT" :fptr 180)
    ("WINDOW-PTR" :fptr 184)
    ("HOME-DIR" :u32 188)
    ("FLAGS" :i32 192)
    ("EXIT-CODE" :fptr 196)
    ("EXIT-DATA" :i32 200)
    ("ARGUMENTS" :fptr 204)
    ("LOCAL-VARS" (:struct 12) 208)
    ("SHELL-PRIVATE" :fptr 220)
    ("CES" :u32 224)
    )
  (:struct "FILE-HANDLE" 44   ; FileHandle (dos/dosextens.i)
    ("LINK" :fptr 0)
    ("INTERACTIVE" :fptr 4)
    ("TYPE" :fptr 8)
    ("BUF" :i32 12)
    ("POS" :i32 16)
    ("END" :i32 20)
    ("FUNCS" :i32 24)
    ("FUNC2" :i32 28)
    ("FUNC3" :i32 32)
    ("ARGS" :i32 36)
    ("ARG2" :i32 40)
    )
  (:struct "DOS-PACKET" 48   ; DosPacket (dos/dosextens.i)
    ("LINK" :fptr 0)
    ("PORT" :fptr 4)
    ("TYPE" :i32 8)
    ("RES1" :i32 12)
    ("RES2" :i32 16)
    ("ARG1" :i32 20)
    ("ARG2" :i32 24)
    ("ARG3" :i32 28)
    ("ARG4" :i32 32)
    ("ARG5" :i32 36)
    ("ARG6" :i32 40)
    ("ARG7" :i32 44)
    )
  (:struct "STANDARD-PACKET" 68   ; StandardPacket (dos/dosextens.i)
    ("MSG" (:struct 20) 0)
    ("PKT" (:struct 48) 20)
    )
  (:struct "ERROR-STRING" 8   ; ErrorString (dos/dosextens.i)
    ("NUMS" :fptr 0)
    ("STRINGS" :fptr 4)
    )
  (:struct "DOS-LIBRARY" 70   ; DosLibrary (dos/dosextens.i)
    ("LIB" (:struct 34) 0)
    ("ROOT" :fptr 34)
    ("GV" :fptr 38)
    ("A2" :i32 42)
    ("A5" :i32 46)
    ("A6" :i32 50)
    ("ERRORS" :fptr 54)
    ("TIME-REQ" :fptr 58)
    ("UTILITY-BASE" :fptr 62)
    ("INTUITION-BASE" :fptr 66)
    )
  (:struct "ROOT-NODE" 56   ; RootNode (dos/dosextens.i)
    ("TASK-ARRAY" :u32 0)
    ("CONSOLE-SEGMENT" :u32 4)
    ("TIME" (:struct 12) 8)
    ("RESTART-SEG" :i32 20)
    ("INFO" :u32 24)
    ("FILE-HANDLER-SEGMENT" :u32 28)
    ("CLI-LIST" (:struct 12) 32)
    ("BOOT-PROC" :fptr 44)
    ("SHELL-SEGMENT" :u32 48)
    ("FLAGS" :i32 52)
    )
  (:struct "CLI-PROC-LIST" 16   ; CliProcList (dos/dosextens.i)
    ("NODE" (:struct 8) 0)
    ("FIRST" :i32 8)
    ("ARRAY" :fptr 12)
    )
  (:struct "DOS-INFO" 158   ; DosInfo (dos/dosextens.i)
    ("MC-NAME" :u32 0)
    ("DEV-INFO" :u32 4)
    ("DEVICES" :u32 8)
    ("HANDLERS" :u32 12)
    ("NET-HAND" :fptr 16)
    ("DEV-LOCK" (:struct 46) 20)
    ("ENTRY-LOCK" (:struct 46) 66)
    ("DELETE-LOCK" (:struct 46) 112)
    )
  (:struct "SEGMENT" 16   ; Segment (dos/dosextens.i)
    ("NEXT" :u32 0)
    ("UC" :i32 4)
    ("SEG" :u32 8)
    ("NAME" (:struct 4) 12)
    )
  (:struct "COMMAND-LINE-INTERFACE" 64   ; CommandLineInterface (dos/dosextens.i)
    ("RESULT2" :i32 0)
    ("SET-NAME" :u32 4)
    ("COMMAND-DIR" :u32 8)
    ("RETURN-CODE" :i32 12)
    ("COMMAND-NAME" :u32 16)
    ("FAIL-LEVEL" :i32 20)
    ("PROMPT" :u32 24)
    ("STANDARD-INPUT" :u32 28)
    ("CURRENT-INPUT" :u32 32)
    ("COMMAND-FILE" :u32 36)
    ("INTERACTIVE" :i32 40)
    ("BACKGROUND" :i32 44)
    ("CURRENT-OUTPUT" :u32 48)
    ("DEFAULT-STACK" :i32 52)
    ("STANDARD-OUTPUT" :u32 56)
    ("MODULE" :u32 60)
    )
  (:struct "DEV-LIST" 44   ; DevList (dos/dosextens.i)
    ("NEXT" :u32 0)
    ("TYPE" :i32 4)
    ("TASK" :fptr 8)
    ("LOCK" :u32 12)
    ("VOLUME-DATE" (:struct 12) 16)
    ("LOCK-LIST" :u32 28)
    ("DISK-TYPE" :i32 32)
    ("UNUSED" :i32 36)
    ("NAME" :u32 40)
    )
  (:struct "DEV-INFO" 44   ; DevInfo (dos/dosextens.i)
    ("NEXT" :u32 0)
    ("TYPE" :i32 4)
    ("TASK" :fptr 8)
    ("LOCK" :u32 12)
    ("HANDLER" :u32 16)
    ("STACKSIZE" :i32 20)
    ("PRIORITY" :i32 24)
    ("STARTUP" :i32 28)
    ("SEG-LIST" :u32 32)
    ("GLOB-VEC" :u32 36)
    ("NAME" :u32 40)
    )
  (:struct "DOS-LIST" 44   ; DosList (dos/dosextens.i)
    ("NEXT" :u32 0)
    ("TYPE" :i32 4)
    ("TASK" :fptr 8)
    ("LOCK" :u32 12)
    ("VOLUME-DATE" (:struct 0) 16)
    ("ASSIGN-NAME" (:struct 0) 16)
    ("HANDLER" :u32 16)
    ("LIST" (:struct 0) 20)
    ("STACK-SIZE" :i32 20)
    ("PRIORITY" :i32 24)
    ("LOCK-LIST" (:struct 0) 28)
    ("STARTUP" :u32 28)
    ("DISK-TYPE" (:struct 0) 32)
    ("SEG-LIST" :u32 32)
    ("GLOB-VEC" :u32 36)
    ("NAME" :u32 40)
    )
  (:struct "DEV-PROC" 16   ; DevProc (dos/dosextens.i)
    ("PORT" :fptr 0)
    ("LOCK" :u32 4)
    ("FLAGS" :u32 8)
    ("DEV-NODE" :fptr 12)
    )
  (:struct "FILE-LOCK" 20   ; FileLock (dos/dosextens.i)
    ("LINK" :u32 0)
    ("KEY" :i32 4)
    ("ACCESS" :i32 8)
    ("TASK" :fptr 12)
    ("VOLUME" :u32 16)
    )

  ;; --- constants from dos/doshunks.i ---
  (:const "+HUNK-UNIT+" #x3E7)
  (:const "+HUNK-NAME+" #x3E8)
  (:const "+HUNK-CODE+" #x3E9)
  (:const "+HUNK-DATA+" #x3EA)
  (:const "+HUNK-BSS+" #x3EB)
  (:const "+HUNK-RELOC32+" #x3EC)
  (:const "+HUNK-ABSRELOC32+" #x3EC)
  (:const "+HUNK-RELOC16+" #x3ED)
  (:const "+HUNK-RELRELOC16+" #x3ED)
  (:const "+HUNK-RELOC8+" #x3EE)
  (:const "+HUNK-RELRELOC8+" #x3EE)
  (:const "+HUNK-EXT+" #x3EF)
  (:const "+HUNK-SYMBOL+" #x3F0)
  (:const "+HUNK-DEBUG+" #x3F1)
  (:const "+HUNK-END+" #x3F2)
  (:const "+HUNK-HEADER+" #x3F3)
  (:const "+HUNK-OVERLAY+" #x3F5)
  (:const "+HUNK-BREAK+" #x3F6)
  (:const "+HUNK-DREL32+" #x3F7)
  (:const "+HUNK-DREL16+" #x3F8)
  (:const "+HUNK-DREL8+" #x3F9)
  (:const "+HUNK-LIB+" #x3FA)
  (:const "+HUNK-INDEX+" #x3FB)
  (:const "+HUNK-RELOC32-SHORT+" #x3FC)
  (:const "+HUNK-RELRELOC32+" #x3FD)
  (:const "+HUNK-ABSRELOC16+" #x3FE)
  (:const "+HUNKB-ADVISORY+" #x1D)
  (:const "+HUNKF-ADVISORY+" #x20000000)
  (:const "+HUNKB-CHIP+" #x1E)
  (:const "+HUNKF-CHIP+" #x40000000)
  (:const "+HUNKB-FAST+" #x1F)
  (:const "+HUNKF-FAST+" #x80000000)
  (:const "+EXT-SYMB+" 0)
  (:const "+EXT-DEF+" 1)
  (:const "+EXT-ABS+" 2)
  (:const "+EXT-RES+" 3)
  (:const "+EXT-COMMONDEF+" 4)
  (:const "+EXT-REF32+" #x81)
  (:const "+EXT-ABSREF32+" #x81)
  (:const "+EXT-COMMON+" #x82)
  (:const "+EXT-ABSCOMMON+" #x82)
  (:const "+EXT-REF16+" #x83)
  (:const "+EXT-RELREF16+" #x83)
  (:const "+EXT-REF8+" #x84)
  (:const "+EXT-RELREF8+" #x84)
  (:const "+EXT-DEXT32+" #x85)
  (:const "+EXT-DEXT16+" #x86)
  (:const "+EXT-DEXT8+" #x87)
  (:const "+EXT-RELREF32+" #x88)
  (:const "+EXT-RELCOMMON+" #x89)
  (:const "+EXT-ABSREF16+" #x8A)
  (:const "+EXT-ABSREF8+" #x8B)

  ;; --- constants from dos/dostags.i ---
  (:const "+SYS-DUMMY+" #x80000020)
  (:const "+SYS-INPUT+" #x80000021)
  (:const "+SYS-OUTPUT+" #x80000022)
  (:const "+SYS-ASYNCH+" #x80000023)
  (:const "+SYS-USER-SHELL+" #x80000024)
  (:const "+SYS-CUSTOM-SHELL+" #x80000025)
  (:const "+SYS-ERROR+" #x80000026)
  (:const "+SYS-EXECUTE-INPUT-STREAM+" #x80000027)
  (:const "+SYS-CMD-STREAM+" #x80000028)
  (:const "+NP-DUMMY+" #x800003E8)
  (:const "+NP-SEGLIST+" #x800003E9)
  (:const "+NP-FREE-SEGLIST+" #x800003EA)
  (:const "+NP-ENTRY+" #x800003EB)
  (:const "+NP-INPUT+" #x800003EC)
  (:const "+NP-OUTPUT+" #x800003ED)
  (:const "+NP-CLOSE-INPUT+" #x800003EE)
  (:const "+NP-CLOSE-OUTPUT+" #x800003EF)
  (:const "+NP-ERROR+" #x800003F0)
  (:const "+NP-CLOSE-ERROR+" #x800003F1)
  (:const "+NP-CURRENT-DIR+" #x800003F2)
  (:const "+NP-STACK-SIZE+" #x800003F3)
  (:const "+NP-NAME+" #x800003F4)
  (:const "+NP-PRIORITY+" #x800003F5)
  (:const "+NP-CONSOLE-TASK+" #x800003F6)
  (:const "+NP-WINDOW-PTR+" #x800003F7)
  (:const "+NP-HOME-DIR+" #x800003F8)
  (:const "+NP-COPY-VARS+" #x800003F9)
  (:const "+NP-CLI+" #x800003FA)
  (:const "+NP-PATH+" #x800003FB)
  (:const "+NP-COMMAND-NAME+" #x800003FC)
  (:const "+NP-ARGUMENTS+" #x800003FD)
  (:const "+NP-NOTIFY-ON-DEATH+" #x800003FE)
  (:const "+NP-SYNCHRONOUS+" #x800003FF)
  (:const "+NP-EXIT-CODE+" #x80000400)
  (:const "+NP-EXIT-DATA+" #x80000401)
  (:const "+ADO-DUMMY+" #x800007D0)
  (:const "+ADO-FH-MODE+" #x800007D1)
  (:const "+ADO-DIR-LEN+" #x800007D2)
  (:const "+ADO-COMM-NAME-LEN+" #x800007D3)
  (:const "+ADO-COMM-FILE-LEN+" #x800007D4)
  (:const "+ADO-PROMPT-LEN+" #x800007D5)

  ;; --- constants from dos/exall.i ---
  (:const "+ED-NAME+" 1)
  (:const "+ED-TYPE+" 2)
  (:const "+ED-SIZE+" 3)
  (:const "+ED-PROTECTION+" 4)
  (:const "+ED-DATE+" 5)
  (:const "+ED-COMMENT+" 6)
  (:const "+ED-OWNER+" 7)

  ;; --- structures from dos/exall.i ---
  (:struct "EX-ALL-DATA" 40   ; ExAllData (dos/exall.i)
    ("NEXT" :fptr 0)
    ("NAME" :fptr 4)
    ("TYPE" :i32 8)
    ("SIZE" :u32 12)
    ("PROT" :u32 16)
    ("DAYS" :u32 20)
    ("MINS" :u32 24)
    ("TICKS" :u32 28)
    ("COMMENT" :fptr 32)
    ("OWNER-UID" :u16 36)
    ("OWNER-GID" :u16 38)
    )
  (:struct "EX-ALL-CONTROL" 16   ; ExAllControl (dos/exall.i)
    ("ENTRIES" :u32 0)
    ("LAST-KEY" :u32 4)
    ("MATCH-STRING" :fptr 8)
    ("MATCH-FUNC" :fptr 12)
    )

  ;; --- constants from dos/filehandler.i ---
  (:const "+DE-TABLESIZE+" 0)
  (:const "+DE-SIZEBLOCK+" 1)
  (:const "+DE-SECORG+" 2)
  (:const "+DE-NUMHEADS+" 3)
  (:const "+DE-SECSPERBLK+" 4)
  (:const "+DE-BLKSPERTRACK+" 5)
  (:const "+DE-RESERVEDBLKS+" 6)
  (:const "+DE-PREFAC+" 7)
  (:const "+DE-INTERLEAVE+" 8)
  (:const "+DE-LOWCYL+" 9)
  (:const "+DE-UPPERCYL+" 10)
  (:const "+DE-NUMBUFFERS+" 11)
  (:const "+DE-MEMBUFTYPE+" 12)
  (:const "+DE-BUFMEMTYPE+" 12)
  (:const "+DE-MAXTRANSFER+" 13)
  (:const "+DE-MASK+" 14)
  (:const "+DE-BOOTPRI+" 15)
  (:const "+DE-DOSTYPE+" #x10)
  (:const "+DE-BAUD+" #x11)
  (:const "+DE-CONTROL+" #x12)
  (:const "+DE-BOOTBLOCKS+" #x13)
  (:const "+ENVB-SCSIDIRECT+" #x10)
  (:const "+ENVF-SCSIDIRECT+" #x10000)
  (:const "+ENVB-SUPERFLOPPY+" #x11)
  (:const "+ENVF-SUPERFLOPPY+" #x20000)
  (:const "+ENVB-DISABLENSD+" #x12)
  (:const "+ENVF-DISABLENSD+" #x40000)

  ;; --- structures from dos/filehandler.i ---
  (:struct "DOS-ENVEC" 80   ; DosEnvec (dos/filehandler.i)
    ("TABLE-SIZE" :u32 0)
    ("SIZE-BLOCK" :u32 4)
    ("SEC-ORG" :u32 8)
    ("SURFACES" :u32 12)
    ("SECTOR-PER-BLOCK" :u32 16)
    ("BLOCKS-PER-TRACK" :u32 20)
    ("RESERVED" :u32 24)
    ("PRE-ALLOC" :u32 28)
    ("INTERLEAVE" :u32 32)
    ("LOW-CYL" :u32 36)
    ("HIGH-CYL" :u32 40)
    ("NUM-BUFFERS" :u32 44)
    ("BUF-MEM-TYPE" :u32 48)
    ("MAX-TRANSFER" :u32 52)
    ("MASK" :u32 56)
    ("BOOT-PRI" :i32 60)
    ("DOS-TYPE" :u32 64)
    ("BAUD" :u32 68)
    ("CONTROL" :u32 72)
    ("BOOT-BLOCKS" :u32 76)
    )
  (:struct "FILE-SYS-STARTUP-MSG" 16   ; FileSysStartupMsg (dos/filehandler.i)
    ("UNIT" :u32 0)
    ("DEVICE" :u32 4)
    ("ENVIRON" :u32 8)
    ("FLAGS" :u32 12)
    )
  (:struct "DEVICE-NODE" 44   ; DeviceNode (dos/filehandler.i)
    ("NEXT" :u32 0)
    ("TYPE" :u32 4)
    ("TASK" :fptr 8)
    ("LOCK" :u32 12)
    ("HANDLER" :u32 16)
    ("STACK-SIZE" :u32 20)
    ("PRIORITY" :i32 24)
    ("STARTUP" :u32 28)
    ("SEG-LIST" :u32 32)
    ("GLOBAL-VEC" :u32 36)
    ("NAME" :u32 40)
    )

  ;; --- constants from dos/notify.i ---
  (:const "+NOTIFY-CLASS+" #x40000000)
  (:const "+NOTIFY-CODE+" #x1234)
  (:const "+NR-TASK+" #x10)
  (:const "+NRB-SEND-MESSAGE+" 0)
  (:const "+NRF-SEND-MESSAGE+" 1)
  (:const "+NRB-SEND-SIGNAL+" 1)
  (:const "+NRF-SEND-SIGNAL+" 2)
  (:const "+NRB-WAIT-REPLY+" 3)
  (:const "+NRF-WAIT-REPLY+" 8)
  (:const "+NRB-NOTIFY-INITIAL+" 4)
  (:const "+NRF-NOTIFY-INITIAL+" #x10)
  (:const "+NRB-MAGIC+" #x1F)
  (:const "+NRF-MAGIC+" #x80000000)
  (:const "+NR-HANDLER-FLAGS+" #xFFFF0000)

  ;; --- structures from dos/notify.i ---
  (:struct "NOTIFY-MESSAGE" 38   ; NotifyMessage (dos/notify.i)
    ("EXEC-MESSAGE" (:struct 20) 0)
    ("CLASS" :u32 20)
    ("CODE" :u16 24)
    ("N-REQ" :fptr 26)
    ("DO-NOT-TOUCH" :u32 30)
    ("DO-NOT-TOUCH2" :u32 34)
    )
  (:struct "NOTIFY-REQUEST" 48   ; NotifyRequest (dos/notify.i)
    ("NAME" :fptr 0)
    ("FULL-NAME" :fptr 4)
    ("USER-DATA" :u32 8)
    ("FLAGS" :u32 12)
    ("PORT" :fptr 16)
    ("SIGNAL-NUM" :u8 20)
    ("PAD" (:struct 3) 21)
    ("RESERVED" (:struct 16) 24)
    ("MSG-COUNT" :u32 40)
    ("HANDLER" :fptr 44)
    )

  ;; --- constants from dos/rdargs.i ---
  (:const "+RDAB-STDIN+" 0)
  (:const "+RDAF-STDIN+" 1)
  (:const "+RDAB-NOALLOC+" 1)
  (:const "+RDAF-NOALLOC+" 2)
  (:const "+RDAB-NOPROMPT+" 2)
  (:const "+RDAF-NOPROMPT+" 4)
  (:const "+MAX-TEMPLATE-ITEMS+" #x64)
  (:const "+MAX-MULTIARGS+" #x80)

  ;; --- structures from dos/rdargs.i ---
  (:struct "C-SOURCE" 12   ; CSource (dos/rdargs.i)
    ("BUFFER" :fptr 0)
    ("LENGTH" :i32 4)
    ("CUR-CHR" :i32 8)
    )
  (:struct "RD-ARGS" 32   ; RDArgs (dos/rdargs.i)
    ("SOURCE" (:struct 12) 0)
    ("DA-LIST" :fptr 12)
    ("BUFFER" :i32 16)
    ("BUF-SIZ" :i32 20)
    ("EXT-HELP" :fptr 24)
    ("FLAGS" :i32 28)
    )

  ;; --- constants from dos/record.i ---
  (:const "+REC-EXCLUSIVE+" 0)
  (:const "+REC-EXCLUSIVE-IMMED+" 1)
  (:const "+REC-SHARED+" 2)
  (:const "+REC-SHARED-IMMED+" 3)

  ;; --- structures from dos/record.i ---
  (:struct "RECORD-LOCK" 16   ; RecordLock (dos/record.i)
    ("FH" :u32 0)
    ("OFFSET" :u32 4)
    ("LENGTH" :u32 8)
    ("MODE" :u32 12)
    )

  ;; --- constants from dos/shell.i ---
  (:const "+SHELL-DUMMY+" #x80000BB8)
  (:const "+SHELL-FGETS-FULL+" #x80000BB9)
  (:const "+SHELL-ADDH-LINE+" #x80000BBA)

  ;; --- structures from dos/shell.i ---
  (:struct "EXTENDED-COMMAND-LINE-INTERFACE" 88   ; ExtendedCommandLineInterface (dos/shell.i)
    ("RESULT2" :i32 0)
    ("SET-NAME" :u32 4)
    ("COMMAND-DIR" :u32 8)
    ("RETURN-CODE" :i32 12)
    ("COMMAND-NAME" :u32 16)
    ("FAIL-LEVEL" :i32 20)
    ("PROMPT" :u32 24)
    ("STANDARD-INPUT" :u32 28)
    ("CURRENT-INPUT" :u32 32)
    ("COMMAND-FILE" :u32 36)
    ("INTERACTIVE" :i32 40)
    ("BACKGROUND" :i32 44)
    ("CURRENT-OUTPUT" :u32 48)
    ("DEFAULT-STACK" :i32 52)
    ("STANDARD-OUTPUT" :u32 56)
    ("MODULE" :u32 60)
    ("HOOK" (:struct 20) 64)
    ("THIS" :fptr 84)
    )
  (:struct "HISTORY-NODE" 12   ; HistoryNode (dos/shell.i)
    ("NODE" (:struct 8) 0)
    ("LINE" :fptr 8)
    )

  ;; --- constants from dos/stdio.i ---
  (:const "+DOS-STDIO-I+" 1)
  (:const "+BUF-LINE+" 0)
  (:const "+BUF-FULL+" 1)
  (:const "+BUF-NONE+" 2)
  (:const "+ENDSTREAMCH+" -1)

  ;; --- constants from dos/var.i ---
  (:const "+LV-VAR+" 0)
  (:const "+LV-ALIAS+" 1)
  (:const "+LVB-IGNORE+" 7)
  (:const "+LVF-IGNORE+" #x80)
  (:const "+GVB-GLOBAL-ONLY+" 8)
  (:const "+GVF-GLOBAL-ONLY+" #x100)
  (:const "+GVB-LOCAL-ONLY+" 9)
  (:const "+GVF-LOCAL-ONLY+" #x200)
  (:const "+GVB-BINARY-VAR+" 10)
  (:const "+GVF-BINARY-VAR+" #x400)
  (:const "+GVB-DONT-NULL-TERM+" 11)
  (:const "+GVF-DONT-NULL-TERM+" #x800)
  (:const "+GVB-SAVE-VAR+" 12)
  (:const "+GVF-SAVE-VAR+" #x1000)

  ;; --- structures from dos/var.i ---
  (:struct "LOCAL-VAR" 24   ; LocalVar (dos/var.i)
    ("NODE" (:struct 14) 0)
    ("FLAGS" :u16 14)
    ("VALUE" :fptr 16)
    ("LEN" :u32 20)
    )

  ;; --- functions (dos_lib.sfd + MorphOS SDK) ---
  (:fn "OPEN" -30 (:d1 :d2) :unsigned)   ; BPTR Open(CONST_STRPTR name, LONG accessMode) (D1,D2) LVO -30
  (:fn "CLOSE" -36 (:d1) :signed)   ; LONG Close(BPTR file) (D1) LVO -36
  (:fn "READ" -42 (:d1 :d2 :d3) :signed)   ; LONG Read(BPTR file, APTR buffer, LONG length) (D1,D2,D3) LVO -42
  (:fn "WRITE" -48 (:d1 :d2 :d3) :signed)   ; LONG Write(BPTR file, CONST_APTR buffer, LONG length) (D1,D2,D3) LVO -48
  (:fn "INPUT" -54 () :unsigned)   ; BPTR Input() () LVO -54
  (:fn "OUTPUT" -60 () :unsigned)   ; BPTR Output() () LVO -60
  (:fn "SEEK" -66 (:d1 :d2 :d3) :signed)   ; LONG Seek(BPTR file, LONG position, LONG offset) (D1,D2,D3) LVO -66
  (:fn "DELETE-FILE" -72 (:d1) :signed)   ; LONG DeleteFile(CONST_STRPTR name) (D1) LVO -72
  (:fn "RENAME" -78 (:d1 :d2) :signed)   ; LONG Rename(CONST_STRPTR oldName, CONST_STRPTR newName) (D1,D2) LVO -78
  (:fn "LOCK" -84 (:d1 :d2) :unsigned)   ; BPTR Lock(CONST_STRPTR name, LONG type) (D1,D2) LVO -84
  (:fn "UN-LOCK" -90 (:d1) :void)   ; VOID UnLock(BPTR lock) (D1) LVO -90
  (:fn "DUP-LOCK" -96 (:d1) :unsigned)   ; BPTR DupLock(BPTR lock) (D1) LVO -96
  (:fn "EXAMINE" -102 (:d1 :d2) :signed)   ; LONG Examine(BPTR lock, struct FileInfoBlock * fileInfoBlock) (D1,D2) LVO -102
  (:fn "EX-NEXT" -108 (:d1 :d2) :signed)   ; LONG ExNext(BPTR lock, struct FileInfoBlock * fileInfoBlock) (D1,D2) LVO -108
  (:fn "INFO" -114 (:d1 :d2) :signed)   ; LONG Info(BPTR lock, struct InfoData * parameterBlock) (D1,D2) LVO -114
  (:fn "CREATE-DIR" -120 (:d1) :unsigned)   ; BPTR CreateDir(CONST_STRPTR name) (D1) LVO -120
  (:fn "CURRENT-DIR" -126 (:d1) :unsigned)   ; BPTR CurrentDir(BPTR lock) (D1) LVO -126
  (:fn "IO-ERR" -132 () :signed)   ; LONG IoErr() () LVO -132
  (:fn "CREATE-PROC" -138 (:d1 :d2 :d3 :d4) :pointer)   ; struct MsgPort * CreateProc(CONST_STRPTR name, LONG pri, BPTR segList, LONG stackSize) (D1,D2,D3,D4) LVO -138
  (:fn "EXIT" -144 (:d1) :void)   ; VOID Exit(LONG returnCode) (D1) LVO -144
  (:fn "LOAD-SEG" -150 (:d1) :unsigned)   ; BPTR LoadSeg(CONST_STRPTR name) (D1) LVO -150
  (:fn "UN-LOAD-SEG" -156 (:d1) :void)   ; VOID UnLoadSeg(BPTR seglist) (D1) LVO -156
  (:fn "DEVICE-PROC" -174 (:d1) :pointer)   ; struct MsgPort * DeviceProc(CONST_STRPTR name) (D1) LVO -174
  (:fn "SET-COMMENT" -180 (:d1 :d2) :signed)   ; LONG SetComment(CONST_STRPTR name, CONST_STRPTR comment) (D1,D2) LVO -180
  (:fn "SET-PROTECTION" -186 (:d1 :d2) :signed)   ; LONG SetProtection(CONST_STRPTR name, LONG protect) (D1,D2) LVO -186
  (:fn "DATE-STAMP" -192 (:d1) :pointer)   ; struct DateStamp * DateStamp(struct DateStamp * date) (D1) LVO -192
  (:fn "DELAY" -198 (:d1) :void)   ; VOID Delay(LONG timeout) (D1) LVO -198
  (:fn "WAIT-FOR-CHAR" -204 (:d1 :d2) :signed)   ; LONG WaitForChar(BPTR file, LONG timeout) (D1,D2) LVO -204
  (:fn "PARENT-DIR" -210 (:d1) :unsigned)   ; BPTR ParentDir(BPTR lock) (D1) LVO -210
  (:fn "IS-INTERACTIVE" -216 (:d1) :signed)   ; LONG IsInteractive(BPTR file) (D1) LVO -216
  (:fn "EXECUTE" -222 (:d1 :d2 :d3) :signed)   ; LONG Execute(CONST_STRPTR string, BPTR file, BPTR file2) (D1,D2,D3) LVO -222
  (:fn "ALLOC-DOS-OBJECT" -228 (:d1 :d2) :pointer)   ; APTR AllocDosObject(ULONG type, CONST struct TagItem * tags) (D1,D2) LVO -228
  (:fn "FREE-DOS-OBJECT" -234 (:d1 :d2) :void)   ; VOID FreeDosObject(ULONG type, APTR ptr) (D1,D2) LVO -234
  (:fn "DO-PKT" -240 (:d1 :d2 :d3 :d4 :d5 :d6 :d7) :signed)   ; LONG DoPkt(struct MsgPort * port, LONG action, LONG arg1, LONG arg2, LONG arg3, LONG arg4, LONG arg5) (D1,D2,D3,D4,D5,D6,D7) LVO -240
  (:fn "SEND-PKT" -246 (:d1 :d2 :d3) :void)   ; VOID SendPkt(struct DosPacket * dp, struct MsgPort * port, struct MsgPort * replyport) (D1,D2,D3) LVO -246
  (:fn "WAIT-PKT" -252 () :pointer)   ; struct DosPacket * WaitPkt() () LVO -252
  (:fn "REPLY-PKT" -258 (:d1 :d2 :d3) :void)   ; VOID ReplyPkt(struct DosPacket * dp, LONG res1, LONG res2) (D1,D2,D3) LVO -258
  (:fn "ABORT-PKT" -264 (:d1 :d2) :void)   ; VOID AbortPkt(struct MsgPort * port, struct DosPacket * pkt) (D1,D2) LVO -264
  (:fn "LOCK-RECORD" -270 (:d1 :d2 :d3 :d4 :d5) :bool)   ; BOOL LockRecord(BPTR fh, ULONG offset, ULONG length, ULONG mode, ULONG timeout) (D1,D2,D3,D4,D5) LVO -270
  (:fn "LOCK-RECORDS" -276 (:d1 :d2) :bool)   ; BOOL LockRecords(CONST struct RecordLock * recArray, ULONG timeout) (D1,D2) LVO -276
  (:fn "UN-LOCK-RECORD" -282 (:d1 :d2 :d3) :bool)   ; BOOL UnLockRecord(BPTR fh, ULONG offset, ULONG length) (D1,D2,D3) LVO -282
  (:fn "UN-LOCK-RECORDS" -288 (:d1) :bool)   ; BOOL UnLockRecords(CONST struct RecordLock * recArray) (D1) LVO -288
  (:fn "SELECT-INPUT" -294 (:d1) :unsigned)   ; BPTR SelectInput(BPTR fh) (D1) LVO -294
  (:fn "SELECT-OUTPUT" -300 (:d1) :unsigned)   ; BPTR SelectOutput(BPTR fh) (D1) LVO -300
  (:fn "F-GET-C" -306 (:d1) :signed)   ; LONG FGetC(BPTR fh) (D1) LVO -306
  (:fn "F-PUT-C" -312 (:d1 :d2) :signed)   ; LONG FPutC(BPTR fh, LONG ch) (D1,D2) LVO -312
  (:fn "UN-GET-C" -318 (:d1 :d2) :signed)   ; LONG UnGetC(BPTR fh, LONG character) (D1,D2) LVO -318
  (:fn "F-READ" -324 (:d1 :d2 :d3 :d4) :signed)   ; LONG FRead(BPTR fh, APTR block, ULONG blocklen, ULONG number) (D1,D2,D3,D4) LVO -324
  (:fn "F-WRITE" -330 (:d1 :d2 :d3 :d4) :signed)   ; LONG FWrite(BPTR fh, CONST_APTR block, ULONG blocklen, ULONG number) (D1,D2,D3,D4) LVO -330
  (:fn "F-GETS" -336 (:d1 :d2 :d3) :pointer)   ; STRPTR FGets(BPTR fh, STRPTR buf, ULONG buflen) (D1,D2,D3) LVO -336
  (:fn "F-PUTS" -342 (:d1 :d2) :signed)   ; LONG FPuts(BPTR fh, CONST_STRPTR str) (D1,D2) LVO -342
  (:fn "VF-WRITEF" -348 (:d1 :d2 :d3) :void)   ; VOID VFWritef(BPTR fh, CONST_STRPTR format, CONST LONG * argarray) (D1,D2,D3) LVO -348
  (:fn "VF-PRINTF" -354 (:d1 :d2 :d3) :signed)   ; LONG VFPrintf(BPTR fh, CONST_STRPTR format, CONST_APTR argarray) (D1,D2,D3) LVO -354
  (:fn "FLUSH" -360 (:d1) :signed)   ; LONG Flush(BPTR fh) (D1) LVO -360
  (:fn "SET-V-BUF" -366 (:d1 :d2 :d3 :d4) :signed)   ; LONG SetVBuf(BPTR fh, STRPTR buff, LONG type, LONG size) (D1,D2,D3,D4) LVO -366
  (:fn "DUP-LOCK-FROM-FH" -372 (:d1) :unsigned)   ; BPTR DupLockFromFH(BPTR fh) (D1) LVO -372
  (:fn "OPEN-FROM-LOCK" -378 (:d1) :unsigned)   ; BPTR OpenFromLock(BPTR lock) (D1) LVO -378
  (:fn "PARENT-OF-FH" -384 (:d1) :unsigned)   ; BPTR ParentOfFH(BPTR fh) (D1) LVO -384
  (:fn "EXAMINE-FH" -390 (:d1 :d2) :bool)   ; BOOL ExamineFH(BPTR fh, struct FileInfoBlock * fib) (D1,D2) LVO -390
  (:fn "SET-FILE-DATE" -396 (:d1 :d2) :signed)   ; LONG SetFileDate(CONST_STRPTR name, CONST struct DateStamp * date) (D1,D2) LVO -396
  (:fn "NAME-FROM-LOCK" -402 (:d1 :d2 :d3) :signed)   ; LONG NameFromLock(BPTR lock, STRPTR buffer, LONG len) (D1,D2,D3) LVO -402
  (:fn "NAME-FROM-FH" -408 (:d1 :d2 :d3) :signed)   ; LONG NameFromFH(BPTR fh, STRPTR buffer, LONG len) (D1,D2,D3) LVO -408
  (:fn "SPLIT-NAME" -414 (:d1 :d2 :d3 :d4 :d5) :i16)   ; WORD SplitName(CONST_STRPTR name, UBYTE separator, STRPTR buf, WORD oldpos, LONG size) (D1,D2,D3,D4,D5) LVO -414
  (:fn "SAME-LOCK" -420 (:d1 :d2) :signed)   ; LONG SameLock(BPTR lock1, BPTR lock2) (D1,D2) LVO -420
  (:fn "SET-MODE" -426 (:d1 :d2) :signed)   ; LONG SetMode(BPTR fh, LONG mode) (D1,D2) LVO -426
  (:fn "EX-ALL" -432 (:d1 :d2 :d3 :d4 :d5) :signed)   ; LONG ExAll(BPTR lock, struct ExAllData * buffer, LONG size, LONG data, struct ExAllControl * control) (D1,D2,D3,D4,D5) LVO -432
  (:fn "READ-LINK" -438 (:d1 :d2 :d3 :d4 :d5) :signed)   ; LONG ReadLink(struct MsgPort * port, BPTR lock, CONST_STRPTR path, STRPTR buffer, ULONG size) (D1,D2,D3,D4,D5) LVO -438
  (:fn "MAKE-LINK" -444 (:d1 :d2 :d3) :signed)   ; LONG MakeLink(CONST_STRPTR name, LONG dest, LONG soft) (D1,D2,D3) LVO -444
  (:fn "CHANGE-MODE" -450 (:d1 :d2 :d3) :signed)   ; LONG ChangeMode(LONG type, BPTR fh, LONG newmode) (D1,D2,D3) LVO -450
  (:fn "SET-FILE-SIZE" -456 (:d1 :d2 :d3) :signed)   ; LONG SetFileSize(BPTR fh, LONG pos, LONG mode) (D1,D2,D3) LVO -456
  (:fn "SET-IO-ERR" -462 (:d1) :signed)   ; LONG SetIoErr(LONG result) (D1) LVO -462
  (:fn "FAULT" -468 (:d1 :d2 :d3 :d4) :bool)   ; BOOL Fault(LONG code, CONST_STRPTR header, STRPTR buffer, LONG len) (D1,D2,D3,D4) LVO -468
  (:fn "PRINT-FAULT" -474 (:d1 :d2) :bool)   ; BOOL PrintFault(LONG code, CONST_STRPTR header) (D1,D2) LVO -474
  (:fn "ERROR-REPORT" -480 (:d1 :d2 :d3 :d4) :signed)   ; LONG ErrorReport(LONG code, LONG type, ULONG arg1, struct MsgPort * device) (D1,D2,D3,D4) LVO -480
  (:fn "CLI" -492 () :pointer)   ; struct CommandLineInterface * Cli() () LVO -492
  (:fn "CREATE-NEW-PROC" -498 (:d1) :pointer)   ; struct Process * CreateNewProc(CONST struct TagItem * tags) (D1) LVO -498
  (:fn "RUN-COMMAND" -504 (:d1 :d2 :d3 :d4) :signed)   ; LONG RunCommand(BPTR seg, LONG stack, CONST_STRPTR paramptr, LONG paramlen) (D1,D2,D3,D4) LVO -504
  (:fn "GET-CONSOLE-TASK" -510 () :pointer)   ; struct MsgPort * GetConsoleTask() () LVO -510
  (:fn "SET-CONSOLE-TASK" -516 (:d1) :pointer)   ; struct MsgPort * SetConsoleTask(struct MsgPort * task) (D1) LVO -516
  (:fn "GET-FILE-SYS-TASK" -522 () :pointer)   ; struct MsgPort * GetFileSysTask() () LVO -522
  (:fn "SET-FILE-SYS-TASK" -528 (:d1) :pointer)   ; struct MsgPort * SetFileSysTask(struct MsgPort * task) (D1) LVO -528
  (:fn "GET-ARG-STR" -534 () :pointer)   ; STRPTR GetArgStr() () LVO -534
  (:fn "SET-ARG-STR" -540 (:d1) :pointer)   ; STRPTR SetArgStr(STRPTR string) (D1) LVO -540
  (:fn "FIND-CLI-PROC" -546 (:d1) :pointer)   ; struct Process * FindCliProc(ULONG num) (D1) LVO -546
  (:fn "MAX-CLI" -552 () :unsigned)   ; ULONG MaxCli() () LVO -552
  (:fn "SET-CURRENT-DIR-NAME" -558 (:d1) :bool)   ; BOOL SetCurrentDirName(CONST_STRPTR name) (D1) LVO -558
  (:fn "GET-CURRENT-DIR-NAME" -564 (:d1 :d2) :bool)   ; BOOL GetCurrentDirName(STRPTR buf, LONG len) (D1,D2) LVO -564
  (:fn "SET-PROGRAM-NAME" -570 (:d1) :bool)   ; BOOL SetProgramName(CONST_STRPTR name) (D1) LVO -570
  (:fn "GET-PROGRAM-NAME" -576 (:d1 :d2) :bool)   ; BOOL GetProgramName(STRPTR buf, LONG len) (D1,D2) LVO -576
  (:fn "SET-PROMPT" -582 (:d1) :bool)   ; BOOL SetPrompt(CONST_STRPTR name) (D1) LVO -582
  (:fn "GET-PROMPT" -588 (:d1 :d2) :bool)   ; BOOL GetPrompt(STRPTR buf, LONG len) (D1,D2) LVO -588
  (:fn "SET-PROGRAM-DIR" -594 (:d1) :unsigned)   ; BPTR SetProgramDir(BPTR lock) (D1) LVO -594
  (:fn "GET-PROGRAM-DIR" -600 () :unsigned)   ; BPTR GetProgramDir() () LVO -600
  (:fn "SYSTEM-TAG-LIST" -606 (:d1 :d2) :signed)   ; LONG SystemTagList(CONST_STRPTR command, CONST struct TagItem * tags) (D1,D2) LVO -606
  (:fn "ASSIGN-LOCK" -612 (:d1 :d2) :signed)   ; LONG AssignLock(CONST_STRPTR name, BPTR lock) (D1,D2) LVO -612
  (:fn "ASSIGN-LATE" -618 (:d1 :d2) :bool)   ; BOOL AssignLate(CONST_STRPTR name, CONST_STRPTR path) (D1,D2) LVO -618
  (:fn "ASSIGN-PATH" -624 (:d1 :d2) :bool)   ; BOOL AssignPath(CONST_STRPTR name, CONST_STRPTR path) (D1,D2) LVO -624
  (:fn "ASSIGN-ADD" -630 (:d1 :d2) :bool)   ; BOOL AssignAdd(CONST_STRPTR name, BPTR lock) (D1,D2) LVO -630
  (:fn "REM-ASSIGN-LIST" -636 (:d1 :d2) :signed)   ; LONG RemAssignList(CONST_STRPTR name, BPTR lock) (D1,D2) LVO -636
  (:fn "GET-DEVICE-PROC" -642 (:d1 :d2) :pointer)   ; struct DevProc * GetDeviceProc(CONST_STRPTR name, struct DevProc * dp) (D1,D2) LVO -642
  (:fn "FREE-DEVICE-PROC" -648 (:d1) :void)   ; VOID FreeDeviceProc(struct DevProc * dp) (D1) LVO -648
  (:fn "LOCK-DOS-LIST" -654 (:d1) :pointer)   ; struct DosList * LockDosList(ULONG flags) (D1) LVO -654
  (:fn "UN-LOCK-DOS-LIST" -660 (:d1) :void)   ; VOID UnLockDosList(ULONG flags) (D1) LVO -660
  (:fn "ATTEMPT-LOCK-DOS-LIST" -666 (:d1) :pointer)   ; struct DosList * AttemptLockDosList(ULONG flags) (D1) LVO -666
  (:fn "REM-DOS-ENTRY" -672 (:d1) :bool)   ; BOOL RemDosEntry(struct DosList * dlist) (D1) LVO -672
  (:fn "ADD-DOS-ENTRY" -678 (:d1) :signed)   ; LONG AddDosEntry(struct DosList * dlist) (D1) LVO -678
  (:fn "FIND-DOS-ENTRY" -684 (:d1 :d2 :d3) :pointer)   ; struct DosList * FindDosEntry(CONST struct DosList * dlist, CONST_STRPTR name, ULONG flags) (D1,D2,D3) LVO -684
  (:fn "NEXT-DOS-ENTRY" -690 (:d1 :d2) :pointer)   ; struct DosList * NextDosEntry(CONST struct DosList * dlist, ULONG flags) (D1,D2) LVO -690
  (:fn "MAKE-DOS-ENTRY" -696 (:d1 :d2) :pointer)   ; struct DosList * MakeDosEntry(CONST_STRPTR name, LONG type) (D1,D2) LVO -696
  (:fn "FREE-DOS-ENTRY" -702 (:d1) :void)   ; VOID FreeDosEntry(struct DosList * dlist) (D1) LVO -702
  (:fn "IS-FILE-SYSTEM" -708 (:d1) :bool)   ; BOOL IsFileSystem(CONST_STRPTR name) (D1) LVO -708
  (:fn "FORMAT" -714 (:d1 :d2 :d3) :bool)   ; BOOL Format(CONST_STRPTR filesystem, CONST_STRPTR volumename, ULONG dostype) (D1,D2,D3) LVO -714
  (:fn "RELABEL" -720 (:d1 :d2) :signed)   ; LONG Relabel(CONST_STRPTR drive, CONST_STRPTR newname) (D1,D2) LVO -720
  (:fn "INHIBIT" -726 (:d1 :d2) :signed)   ; LONG Inhibit(CONST_STRPTR name, LONG onoff) (D1,D2) LVO -726
  (:fn "ADD-BUFFERS" -732 (:d1 :d2) :signed)   ; LONG AddBuffers(CONST_STRPTR name, LONG number) (D1,D2) LVO -732
  (:fn "COMPARE-DATES" -738 (:d1 :d2) :signed)   ; LONG CompareDates(CONST struct DateStamp * date1, CONST struct DateStamp * date2) (D1,D2) LVO -738
  (:fn "DATE-TO-STR" -744 (:d1) :signed)   ; LONG DateToStr(struct DateTime * datetime) (D1) LVO -744
  (:fn "STR-TO-DATE" -750 (:d1) :signed)   ; LONG StrToDate(struct DateTime * datetime) (D1) LVO -750
  (:fn "INTERNAL-LOAD-SEG" -756 (:d0 :a0 :a1 :a2) :unsigned)   ; BPTR InternalLoadSeg(BPTR fh, BPTR table, CONST LONG * funcarray, LONG * stack) (D0,A0,A1,A2) LVO -756
  (:fn "INTERNAL-UN-LOAD-SEG" -762 (:d1 :a1) :bool)   ; BOOL InternalUnLoadSeg(BPTR seglist, APTR freefunc) (D1,A1) LVO -762
  (:fn "NEW-LOAD-SEG" -768 (:d1 :d2) :unsigned)   ; BPTR NewLoadSeg(CONST_STRPTR file, CONST struct TagItem * tags) (D1,D2) LVO -768
  (:fn "ADD-SEGMENT" -774 (:d1 :d2 :d3) :signed)   ; LONG AddSegment(CONST_STRPTR name, BPTR seg, LONG system) (D1,D2,D3) LVO -774
  (:fn "FIND-SEGMENT" -780 (:d1 :d2 :d3) :pointer)   ; struct Segment * FindSegment(CONST_STRPTR name, CONST struct Segment * seg, LONG system) (D1,D2,D3) LVO -780
  (:fn "REM-SEGMENT" -786 (:d1) :signed)   ; LONG RemSegment(struct Segment * seg) (D1) LVO -786
  (:fn "CHECK-SIGNAL" -792 (:d1) :signed)   ; LONG CheckSignal(LONG mask) (D1) LVO -792
  (:fn "READ-ARGS" -798 (:d1 :d2 :d3) :pointer)   ; struct RDArgs * ReadArgs(CONST_STRPTR arg_template, LONG * array, struct RDArgs * args) (D1,D2,D3) LVO -798
  (:fn "FIND-ARG" -804 (:d1 :d2) :signed)   ; LONG FindArg(CONST_STRPTR keyword, CONST_STRPTR arg_template) (D1,D2) LVO -804
  (:fn "READ-ITEM" -810 (:d1 :d2 :d3) :signed)   ; LONG ReadItem(CONST_STRPTR name, LONG maxchars, struct CSource * cSource) (D1,D2,D3) LVO -810
  (:fn "STR-TO-LONG" -816 (:d1 :d2) :signed)   ; LONG StrToLong(CONST_STRPTR string, LONG * value) (D1,D2) LVO -816
  (:fn "MATCH-FIRST" -822 (:d1 :d2) :signed)   ; LONG MatchFirst(CONST_STRPTR pat, struct AnchorPath * anchor) (D1,D2) LVO -822
  (:fn "MATCH-NEXT" -828 (:d1) :signed)   ; LONG MatchNext(struct AnchorPath * anchor) (D1) LVO -828
  (:fn "MATCH-END" -834 (:d1) :void)   ; VOID MatchEnd(struct AnchorPath * anchor) (D1) LVO -834
  (:fn "PARSE-PATTERN" -840 (:d1 :d2 :d3) :signed)   ; LONG ParsePattern(CONST_STRPTR pat, UBYTE * patbuf, LONG patbuflen) (D1,D2,D3) LVO -840
  (:fn "MATCH-PATTERN" -846 (:d1 :d2) :bool)   ; BOOL MatchPattern(CONST UBYTE * patbuf, CONST_STRPTR str) (D1,D2) LVO -846
  (:fn "FREE-ARGS" -858 (:d1) :void)   ; VOID FreeArgs(struct RDArgs * args) (D1) LVO -858
  (:fn "FILE-PART" -870 (:d1) :pointer)   ; STRPTR FilePart(CONST_STRPTR path) (D1) LVO -870
  (:fn "PATH-PART" -876 (:d1) :pointer)   ; STRPTR PathPart(CONST_STRPTR path) (D1) LVO -876
  (:fn "ADD-PART" -882 (:d1 :d2 :d3) :bool)   ; BOOL AddPart(STRPTR dirname, CONST_STRPTR filename, ULONG size) (D1,D2,D3) LVO -882
  (:fn "START-NOTIFY" -888 (:d1) :bool)   ; BOOL StartNotify(struct NotifyRequest * notify) (D1) LVO -888
  (:fn "END-NOTIFY" -894 (:d1) :void)   ; VOID EndNotify(struct NotifyRequest * notify) (D1) LVO -894
  (:fn "SET-VAR" -900 (:d1 :d2 :d3 :d4) :bool)   ; BOOL SetVar(CONST_STRPTR name, CONST_STRPTR buffer, LONG size, LONG flags) (D1,D2,D3,D4) LVO -900
  (:fn "GET-VAR" -906 (:d1 :d2 :d3 :d4) :signed)   ; LONG GetVar(CONST_STRPTR name, STRPTR buffer, LONG size, LONG flags) (D1,D2,D3,D4) LVO -906
  (:fn "DELETE-VAR" -912 (:d1 :d2) :signed)   ; LONG DeleteVar(CONST_STRPTR name, ULONG flags) (D1,D2) LVO -912
  (:fn "FIND-VAR" -918 (:d1 :d2) :pointer)   ; struct LocalVar * FindVar(CONST_STRPTR name, ULONG type) (D1,D2) LVO -918
  (:fn "CLI-INIT-NEWCLI" -930 (:a0) :signed)   ; LONG CliInitNewcli(struct DosPacket * dp) (A0) LVO -930
  (:fn "CLI-INIT-RUN" -936 (:a0) :signed)   ; LONG CliInitRun(struct DosPacket * dp) (A0) LVO -936
  (:fn "WRITE-CHARS" -942 (:d1 :d2) :signed)   ; LONG WriteChars(CONST_STRPTR buf, ULONG buflen) (D1,D2) LVO -942
  (:fn "PUT-STR" -948 (:d1) :signed)   ; LONG PutStr(CONST_STRPTR str) (D1) LVO -948
  (:fn "V-PRINTF" -954 (:d1 :d2) :signed)   ; LONG VPrintf(CONST_STRPTR format, CONST_APTR argarray) (D1,D2) LVO -954
  (:fn "PARSE-PATTERN-NO-CASE" -966 (:d1 :d2 :d3) :signed)   ; LONG ParsePatternNoCase(CONST_STRPTR pat, UBYTE * patbuf, LONG patbuflen) (D1,D2,D3) LVO -966
  (:fn "MATCH-PATTERN-NO-CASE" -972 (:d1 :d2) :bool)   ; BOOL MatchPatternNoCase(CONST UBYTE * patbuf, CONST_STRPTR str) (D1,D2) LVO -972
  (:fn "SAME-DEVICE" -984 (:d1 :d2) :bool)   ; BOOL SameDevice(BPTR lock1, BPTR lock2) (D1,D2) LVO -984
  (:fn "EX-ALL-END" -990 (:d1 :d2 :d3 :d4 :d5) :void)   ; VOID ExAllEnd(BPTR lock, struct ExAllData * buffer, LONG size, LONG data, struct ExAllControl * control) (D1,D2,D3,D4,D5) LVO -990
  (:fn "SET-OWNER" -996 (:d1 :d2) :bool)   ; BOOL SetOwner(CONST_STRPTR name, LONG owner_info) (D1,D2) LVO -996
  (:fn "VOLUME-REQUEST-HOOK" -1014 (:d1) :signed :not-morphos)   ; LONG VolumeRequestHook(CONST_STRPTR vol) (D1) LVO -1014
  (:fn "GET-CURRENT-DIR" -1026 () :unsigned :not-morphos)   ; BPTR GetCurrentDir() () LVO -1026
  (:fn "PUT-ERR-STR" -1128 (:d1) :signed :not-morphos)   ; LONG PutErrStr(CONST_STRPTR str) (D1) LVO -1128
  (:fn "ERROR-OUTPUT" -1134 () :signed :not-morphos)   ; LONG ErrorOutput() () LVO -1134
  (:fn "SELECT-ERROR" -1140 (:d1) :signed :not-morphos)   ; LONG SelectError(BPTR fh) (D1) LVO -1140
  (:fn "DO-SHELL-METHOD-TAG-LIST" -1152 (:d0 :a0) :pointer :not-morphos)   ; APTR DoShellMethodTagList(ULONG method, CONST struct TagItem * tags) (D0,A0) LVO -1152
  (:fn "SCAN-STACK-TOKEN" -1158 (:d1 :d2) :signed :not-morphos)   ; LONG ScanStackToken(BPTR seg, LONG defaultstack) (D1,D2) LVO -1158
  (:fn "ADD-SEGMENT-TAG-LIST" -1002 (:a0) :signed :morphos)   ; LONG AddSegmentTagList(struct TagItem * tags) (A0) LVO -1002
  (:fn "FIND-SEGMENT-TAG-LIST" -1008 (:a0) :pointer :morphos)   ; struct Segment * FindSegmentTagList(struct TagItem * tags) (A0) LVO -1008
  ;; skipped Seek64: not a 68k register call (base,sysv)
  ;; skipped SetFileSize64: not a 68k register call (base,sysv)
  ;; skipped LockRecord64: not a 68k register call (base,sysv)
  ;; skipped LockRecords64: not a 68k register call (base,sysv)
  ;; skipped UnLockRecord64: not a 68k register call (base,sysv)
  ;; skipped UnLockRecords64: not a 68k register call (base,sysv)
  ;; skipped NewReadLink: not a 68k register call (base,sysv)
  ;; skipped GetFileSysAttr: not a 68k register call (base,sysv)
  ;; skipped GetSegListAttr: not a 68k register call (base,sysv)
  ;; skipped SetDosObjectAttr: not a 68k register call (base,sysv)
  ;; skipped GetDosObjectAttr: not a 68k register call (base,sysv)
  ;; skipped Examine64: not a 68k register call (base,sysv)
  ;; skipped ExNext64: not a 68k register call (base,sysv)
  ;; skipped ExamineFH64: not a 68k register call (base,sysv)
  ;; skipped ReleaseCLINumber: not a 68k register call (base,sysv)
  ;; skipped QueryCLIDataTagList: not a 68k register call (base,sysv)
  ;; skipped FreeCLIData: not a 68k register call (base,sysv)
  ;; skipped GetSegListAttrTagList: not a 68k register call (base,sysv)
  ;; skipped SetFilePosixDateTagList: not a 68k register call (base,sysv)
  ;; skipped PosixDateStamp: not a 68k register call (base,sysv)
  ;; skipped PosixDateStampToDateStamp: not a 68k register call (base,sysv)
  ;; skipped DateStampToPosixDateStamp: not a 68k register call (base,sysv)
  )

(provide "amiga/raw/dos")
