;;; amiga/raw/exec  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   exec_lib.sfd ($VER: exec_lib.sfd 47.5 (30.11.2021))
;;;   MorphOS SDK exec_lib.fd + clib/exec_protos.h (via fd2sfd)
;;;   exec/alerts.i
;;;   exec/devices.i
;;;   exec/errors.i
;;;   exec/exec.i
;;;   exec/exec_lib.i
;;;   exec/execbase.i
;;;   exec/interrupts.i
;;;   exec/io.i
;;;   exec/libraries.i
;;;   exec/lists.i
;;;   exec/memory.i
;;;   exec/nodes.i
;;;   exec/ports.i
;;;   exec/resident.i
;;;   exec/semaphores.i
;;;   exec/tasks.i
;;;
;;; 144 functions, 370 constants, 27 structs, 20 skipped (see comments).
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.EXEC"
  (:use "CL" "FFI" "AMIGA.FFI")
  ;; distinct symbols  these names also exist in CL / FFI / AMIGA.FFI
  (:shadow "LIBRARY-VERSION" "DEBUG" "REMOVE" "SIGNAL" "CLOSE-LIBRARY")
  (:export "*EXEC-BASE*" "*EXEC-VERSION*"))

(in-package "AMIGA.RAW.EXEC")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *exec-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "exec.library" 0)))
(defvar *exec-version*
  (and *exec-base* (amiga.ffi:library-version *exec-base*)))
(defun %version>= (n)
  (and *exec-version* (>= *exec-version* n)))

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.EXEC"
    (:base *exec-base* :version *exec-version*)

  ;; --- constants from exec/alerts.i ---
  (:const "+ACPU-BUS-ERR+" #x80000002)
  (:const "+ACPU-ADDRESS-ERR+" #x80000003)
  (:const "+ACPU-INST-ERR+" #x80000004)
  (:const "+ACPU-DIV-ZERO+" #x80000005)
  (:const "+ACPU-CHK+" #x80000006)
  (:const "+ACPU-TRAPV+" #x80000007)
  (:const "+ACPU-PRIV-ERR+" #x80000008)
  (:const "+ACPU-TRACE+" #x80000009)
  (:const "+ACPU-LINE-A+" #x8000000A)
  (:const "+ACPU-LINE-F+" #x8000000B)
  (:const "+ACPU-FORMAT+" #x8000000E)
  (:const "+ACPU-SPURIOUS+" #x80000018)
  (:const "+ACPU-AUTO-VEC1+" #x80000019)
  (:const "+ACPU-AUTO-VEC2+" #x8000001A)
  (:const "+ACPU-AUTO-VEC3+" #x8000001B)
  (:const "+ACPU-AUTO-VEC4+" #x8000001C)
  (:const "+ACPU-AUTO-VEC5+" #x8000001D)
  (:const "+ACPU-AUTO-VEC6+" #x8000001E)
  (:const "+ACPU-AUTO-VEC7+" #x8000001F)
  (:const "+AT-DEAD-END+" #x80000000)
  (:const "+AT-RECOVERY+" 0)
  (:const "+AG-NO-MEMORY+" #x10000)
  (:const "+AG-MAKE-LIB+" #x20000)
  (:const "+AG-OPEN-LIB+" #x30000)
  (:const "+AG-OPEN-DEV+" #x40000)
  (:const "+AG-OPEN-RES+" #x50000)
  (:const "+AG-IO-ERROR+" #x60000)
  (:const "+AG-NO-SIGNAL+" #x70000)
  (:const "+AG-BAD-PARM+" #x80000)
  (:const "+AG-CLOSE-LIB+" #x90000)
  (:const "+AG-CLOSE-DEV+" #xA0000)
  (:const "+AG-PROC-CREATE+" #xB0000)
  (:const "+AO-EXEC-LIB+" #x8001)
  (:const "+AO-GRAPHICS-LIB+" #x8002)
  (:const "+AO-LAYERS-LIB+" #x8003)
  (:const "+AO-INTUITION+" #x8004)
  (:const "+AO-MATH-LIB+" #x8005)
  (:const "+AO-DOS-LIB+" #x8007)
  (:const "+AO-RAM-LIB+" #x8008)
  (:const "+AO-ICON-LIB+" #x8009)
  (:const "+AO-EXPANSION-LIB+" #x800A)
  (:const "+AO-DISKFONT-LIB+" #x800B)
  (:const "+AO-UTILITY-LIB+" #x800C)
  (:const "+AO-KEY-MAP-LIB+" #x800D)
  (:const "+AO-AUDIO-DEV+" #x8010)
  (:const "+AO-CONSOLE-DEV+" #x8011)
  (:const "+AO-GAME-PORT-DEV+" #x8012)
  (:const "+AO-KEYBOARD-DEV+" #x8013)
  (:const "+AO-TRACK-DISK-DEV+" #x8014)
  (:const "+AO-TIMER-DEV+" #x8015)
  (:const "+AO-CIA-RSRC+" #x8020)
  (:const "+AO-DISK-RSRC+" #x8021)
  (:const "+AO-MISC-RSRC+" #x8022)
  (:const "+AO-BOOT-STRAP+" #x8030)
  (:const "+AO-WORKBENCH+" #x8031)
  (:const "+AO-DISK-COPY+" #x8032)
  (:const "+AO-GAD-TOOLS+" #x8033)
  (:const "+AO-UNKNOWN+" #x8035)
  (:const "+AN-EXEC-LIB+" #x1000000)
  (:const "+AN-EXCPT-VECT+" #x1000001)
  (:const "+AN-BASE-CHK-SUM+" #x1000002)
  (:const "+AN-LIB-CHK-SUM+" #x1000003)
  (:const "+AN-MEM-CORRUPT+" #x81000005)
  (:const "+AN-INTR-MEM+" #x81000006)
  (:const "+AN-INIT-A-PTR+" #x1000007)
  (:const "+AN-SEM-CORRUPT+" #x1000008)
  (:const "+AN-FREE-TWICE+" #x1000009)
  (:const "+AN-BOGUS-EXCPT+" #x8100000A)
  (:const "+AN-IO-USED-TWICE+" #x100000B)
  (:const "+AN-MEMORY-INSANE+" #x100000C)
  (:const "+AN-IO-AFTER-CLOSE+" #x100000D)
  (:const "+AN-STACK-PROBE+" #x100000E)
  (:const "+AN-BAD-FREE-ADDR+" #x100000F)
  (:const "+AN-BAD-SEMAPHORE+" #x1000010)
  (:const "+AN-BAD-QUICK-INT+" #x810000FF)
  (:const "+AN-AVL-NOT-IMPL+" #x1000011)
  (:const "+AN-TREE-NOT-IMPL+" #x1000012)
  (:const "+AN-GRAPHICS-LIB+" #x2000000)
  (:const "+AN-GFX-NO-MEM+" #x82010000)
  (:const "+AN-GFX-NO-MEM-MSPC+" #x82010001)
  (:const "+AN-LONG-FRAME+" #x82010006)
  (:const "+AN-SHORT-FRAME+" #x82010007)
  (:const "+AN-TEXT-TMP-RAS+" #x2010009)
  (:const "+AN-BLT-BITMAP+" #x8201000A)
  (:const "+AN-REGION-MEMORY+" #x8201000B)
  (:const "+AN-MAKE-V-PORT+" #x82010030)
  (:const "+AN-GFX-NEW-ERROR+" #x200000C)
  (:const "+AN-GFX-FREE-ERROR+" #x200000D)
  (:const "+AN-GFX-NO-LCM+" #x82011234)
  (:const "+AN-OBSOLETE-FONT+" #x2000401)
  (:const "+AN-LAYERS-LIB+" #x3000000)
  (:const "+AN-LAYERS-NO-MEM+" #x83010000)
  (:const "+AN-INTUITION+" #x4000000)
  (:const "+AN-GADGET-TYPE+" #x84000001)
  (:const "+AN-BAD-GADGET+" #x4000001)
  (:const "+AN-CREATE-PORT+" #x84010002)
  (:const "+AN-ITEM-ALLOC+" #x4010003)
  (:const "+AN-SUB-ALLOC+" #x4010004)
  (:const "+AN-PLANE-ALLOC+" #x84010005)
  (:const "+AN-ITEM-BOX-TOP+" #x84000006)
  (:const "+AN-OPEN-SCREEN+" #x84010007)
  (:const "+AN-OPEN-SCRN-RAST+" #x84010008)
  (:const "+AN-SYS-SCRN-TYPE+" #x84000009)
  (:const "+AN-ADD-SW-GADGET+" #x8401000A)
  (:const "+AN-OPEN-WINDOW+" #x8401000B)
  (:const "+AN-BAD-STATE+" #x8400000C)
  (:const "+AN-BAD-MESSAGE+" #x8400000D)
  (:const "+AN-WEIRD-ECHO+" #x8400000E)
  (:const "+AN-NO-CONSOLE+" #x8400000F)
  (:const "+AN-NO-I-SEM+" #x4000010)
  (:const "+AN-I-SEM-ORDER+" #x4000011)
  (:const "+AN-DEAD-INTUI+" #x4000012)
  (:const "+AN-MATH-LIB+" #x5000000)
  (:const "+AN-DOS-LIB+" #x7000000)
  (:const "+AN-START-MEM+" #x7010001)
  (:const "+AN-END-TASK+" #x7000002)
  (:const "+AN-Q-PKT-FAIL+" #x7000003)
  (:const "+AN-ASYNC-PKT+" #x7000004)
  (:const "+AN-FREE-VEC+" #x7000005)
  (:const "+AN-DISK-BLK-SEQ+" #x7000006)
  (:const "+AN-BITMAP+" #x7000007)
  (:const "+AN-KEY-FREE+" #x7000008)
  (:const "+AN-BAD-CHK-SUM+" #x7000009)
  (:const "+AN-DISK-ERROR+" #x700000A)
  (:const "+AN-KEY-RANGE+" #x700000B)
  (:const "+AN-BAD-OVERLAY+" #x700000C)
  (:const "+AN-BAD-INIT-FUNC+" #x700000D)
  (:const "+AN-FILE-RECLOSED+" #x700000E)
  (:const "+AN-CLI-OBSOLETE+" #x700000F)
  (:const "+AN-RAM-LIB+" #x8000000)
  (:const "+AN-BAD-SEG-LIST+" #x8000001)
  (:const "+AN-ICON-LIB+" #x9000000)
  (:const "+AN-EXPANSION-LIB+" #xA000000)
  (:const "+AN-BAD-EXPANSION-FREE+" #xA000001)
  (:const "+AN-DISKFONT-LIB+" #xB000000)
  (:const "+AN-AUDIO-DEV+" #x10000000)
  (:const "+AN-CONSOLE-DEV+" #x11000000)
  (:const "+AN-NO-WINDOW+" #x11000001)
  (:const "+AN-GAME-PORT-DEV+" #x12000000)
  (:const "+AN-KEYBOARD-DEV+" #x13000000)
  (:const "+AN-TRACK-DISK-DEV+" #x14000000)
  (:const "+AN-TD-CALIB-SEEK+" #x14000001)
  (:const "+AN-TD-DELAY+" #x14000002)
  (:const "+AN-TIMER-DEV+" #x15000000)
  (:const "+AN-TM-BAD-REQ+" #x15000001)
  (:const "+AN-TM-BAD-SUPPLY+" #x15000002)
  (:const "+AN-CIA-RSRC+" #x20000000)
  (:const "+AN-DISK-RSRC+" #x21000000)
  (:const "+AN-DR-HAS-DISK+" #x21000001)
  (:const "+AN-DR-INT-NO-ACT+" #x21000002)
  (:const "+AN-MISC-RSRC+" #x22000000)
  (:const "+AN-BOOT-STRAP+" #x30000000)
  (:const "+AN-BOOT-ERROR+" #x30000001)
  (:const "+AN-WORKBENCH+" #x31000000)
  (:const "+AN-NO-FONTS+" #xB1000001)
  (:const "+AN-WB-BAD-STARTUP-MSG1+" #x31000001)
  (:const "+AN-WB-BAD-STARTUP-MSG2+" #x31000002)
  (:const "+AN-WB-BAD-IO-MSG+" #x31000003)
  (:const "+AN-WB-RE-LAYOUT-TOOL-MENU+" #xB1010009)
  (:const "+AN-DISK-COPY+" #x32000000)
  (:const "+AN-GAD-TOOLS+" #x33000000)
  (:const "+AN-UTILITY-LIB+" #x34000000)
  (:const "+AN-UNKNOWN+" #x35000000)

  ;; --- constants from exec/devices.i ---
  (:const "+UNITB-ACTIVE+" 0)
  (:const "+UNITF-ACTIVE+" 1)
  (:const "+UNITB-INTASK+" 1)
  (:const "+UNITF-INTASK+" 2)

  ;; --- structures from exec/devices.i ---
  (:struct "DEVICE" 34   ; DD (exec/devices.i)
    )
  (:struct "UNIT" 38   ; UNIT (exec/devices.i)
    ("FLAGS" :u8 34)
    ("PAD" :u8 35)
    ("OPENCNT" :u16 36)
    )

  ;; --- constants from exec/errors.i ---
  (:const "+IOERR-OPENFAIL+" -1)
  (:const "+IOERR-ABORTED+" -2)
  (:const "+IOERR-NOCMD+" -3)
  (:const "+IOERR-BADLENGTH+" -4)
  (:const "+IOERR-BADADDRESS+" -5)
  (:const "+IOERR-UNITBUSY+" -6)
  (:const "+IOERR-SELFTEST+" -7)
  (:const "+ERR-OPENDEVICE+" -1)

  ;; --- constants from exec/execbase.i ---
  (:const "+AFB-68010+" 0)
  (:const "+AFF-68010+" 1)
  (:const "+AFB-68020+" 1)
  (:const "+AFF-68020+" 2)
  (:const "+AFB-68030+" 2)
  (:const "+AFF-68030+" 4)
  (:const "+AFB-68040+" 3)
  (:const "+AFF-68040+" 8)
  (:const "+AFB-68881+" 4)
  (:const "+AFF-68881+" #x10)
  (:const "+AFB-68882+" 5)
  (:const "+AFF-68882+" #x20)
  (:const "+AFB-FPU40+" 6)
  (:const "+AFF-FPU40+" #x40)
  (:const "+AFB-68060+" 7)
  (:const "+AFF-68060+" #x80)
  (:const "+AFB-FPGA+" 10)
  (:const "+AFF-FPGA+" #x400)
  (:const "+AFB-PRIVATE+" 15)
  (:const "+AFF-PRIVATE+" #x8000)
  (:const "+CACRB-ENABLE-I+" 0)
  (:const "+CACRF-ENABLE-I+" 1)
  (:const "+CACRB-FREEZE-I+" 1)
  (:const "+CACRF-FREEZE-I+" 2)
  (:const "+CACRB-CLEAR-I+" 3)
  (:const "+CACRF-CLEAR-I+" 8)
  (:const "+CACRB-IBE+" 4)
  (:const "+CACRF-IBE+" #x10)
  (:const "+CACRB-ENABLE-D+" 8)
  (:const "+CACRF-ENABLE-D+" #x100)
  (:const "+CACRB-FREEZE-D+" 9)
  (:const "+CACRF-FREEZE-D+" #x200)
  (:const "+CACRB-CLEAR-D+" 11)
  (:const "+CACRF-CLEAR-D+" #x800)
  (:const "+CACRB-DBE+" 12)
  (:const "+CACRF-DBE+" #x1000)
  (:const "+CACRB-WRITE-ALLOCATE+" 13)
  (:const "+CACRF-WRITE-ALLOCATE+" #x2000)
  (:const "+CACRB-ENABLE-E+" #x1E)
  (:const "+CACRF-ENABLE-E+" #x40000000)
  (:const "+CACRB-COPY-BACK+" #x1F)
  (:const "+CACRF-COPY-BACK+" #x80000000)
  (:const "+DMAB-CONTINUE+" 1)
  (:const "+DMAF-CONTINUE+" 2)
  (:const "+DMAB-NO-MODIFY+" 2)
  (:const "+DMAF-NO-MODIFY+" 4)
  (:const "+DMAB-READ-FROM-RAM+" 3)
  (:const "+DMAF-READ-FROM-RAM+" 8)

  ;; --- structures from exec/execbase.i ---
  (:struct "EXEC-BASE" 632   ; ExecBase (exec/execbase.i)
    ("SOFT-VER" :u16 34)
    ("LOW-MEM-CHK-SUM" :i16 36)
    ("CHK-BASE" :u32 38)
    ("COLD-CAPTURE" :fptr 42)
    ("COOL-CAPTURE" :fptr 46)
    ("WARM-CAPTURE" :fptr 50)
    ("SYS-STK-UPPER" :fptr 54)
    ("SYS-STK-LOWER" :fptr 58)
    ("MAX-LOC-MEM" :u32 62)
    ("DEBUG-ENTRY" :fptr 66)
    ("DEBUG-DATA" :fptr 70)
    ("ALERT-DATA" :fptr 74)
    ("MAX-EXT-MEM" :fptr 78)
    ("CHK-SUM" :i16 82)
    ("INT-VECTS" (:struct 0) 84)
    ("IVTBE" (:struct 12) 84)
    ("IVDSKBLK" (:struct 12) 96)
    ("IVSOFTINT" (:struct 12) 108)
    ("IVPORTS" (:struct 12) 120)
    ("IVCOPER" (:struct 12) 132)
    ("IVVERTB" (:struct 12) 144)
    ("IVBLIT" (:struct 12) 156)
    ("IVAUD0" (:struct 12) 168)
    ("IVAUD1" (:struct 12) 180)
    ("IVAUD2" (:struct 12) 192)
    ("IVAUD3" (:struct 12) 204)
    ("IVRBF" (:struct 12) 216)
    ("IVDSKSYNC" (:struct 12) 228)
    ("IVEXTER" (:struct 12) 240)
    ("IVINTEN" (:struct 12) 252)
    ("IVNMI" (:struct 12) 264)
    ("THIS-TASK" :fptr 276)
    ("IDLE-COUNT" :u32 280)
    ("DISP-COUNT" :u32 284)
    ("QUANTUM" :u16 288)
    ("ELAPSED" :u16 290)
    ("SYS-FLAGS" :u16 292)
    ("ID-NEST-CNT" :i8 294)
    ("TD-NEST-CNT" :i8 295)
    ("ATTN-FLAGS" :u16 296)
    ("ATTN-RESCHED" :u16 298)
    ("RES-MODULES" :fptr 300)
    ("TASK-TRAP-CODE" :fptr 304)
    ("TASK-EXCEPT-CODE" :fptr 308)
    ("TASK-EXIT-CODE" :fptr 312)
    ("TASK-SIG-ALLOC" :u32 316)
    ("TASK-TRAP-ALLOC" :u16 320)
    ("MEM-LIST" (:struct 14) 322)
    ("RESOURCE-LIST" (:struct 14) 336)
    ("DEVICE-LIST" (:struct 14) 350)
    ("INTR-LIST" (:struct 14) 364)
    ("LIB-LIST" (:struct 14) 378)
    ("PORT-LIST" (:struct 14) 392)
    ("TASK-READY" (:struct 14) 406)
    ("TASK-WAIT" (:struct 14) 420)
    ("SOFT-INTS" (:struct 80) 434)
    ("LAST-ALERT" (:struct 16) 514)
    ("V-BLANK-FREQUENCY" :u8 530)
    ("POWER-SUPPLY-FREQUENCY" :u8 531)
    ("SEMAPHORE-LIST" (:struct 14) 532)
    ("KICK-MEM-PTR" :fptr 546)
    ("KICK-TAG-PTR" :fptr 550)
    ("KICK-CHECK-SUM" :fptr 554)
    ("PAD0" :u16 558)
    ("LAUNCH-POINT" :u32 560)
    ("RAM-LIB-PRIVATE" :fptr 564)
    ("E-CLOCK-FREQUENCY" :u32 568)
    ("CACHE-CONTROL" :u32 572)
    ("TASK-ID" :u32 576)
    ("RESERVED1" (:struct 20) 580)
    ("MMU-LOCK" :fptr 600)
    ("RESERVED2" (:struct 12) 604)
    ("MEM-HANDLERS" (:struct 12) 616)
    ("MEM-HANDLER" :fptr 628)
    )

  ;; --- constants from exec/interrupts.i ---
  (:const "+SB-SAR+" 15)
  (:const "+SF-SAR+" #x8000)
  (:const "+SB-TQE+" 14)
  (:const "+SF-TQE+" #x4000)
  (:const "+SB-SINT+" 13)
  (:const "+SF-SINT+" #x2000)
  (:const "+SIH-PRIMASK+" #xF0)
  (:const "+SIH-QUEUES+" 5)
  (:const "+INTB-NMI+" 15)
  (:const "+INTF-NMI+" #x8000)

  ;; --- structures from exec/interrupts.i ---
  (:struct "INTERRUPT" 22   ; IS (exec/interrupts.i)
    ("DATA" :fptr 14)
    ("CODE" :fptr 18)
    )
  (:struct "INT-VECTOR" 12   ; IV (exec/interrupts.i)
    ("DATA" :fptr 0)
    ("CODE" :fptr 4)
    ("NODE" :fptr 8)
    )
  (:struct "SOFT-INT-LIST" 16   ; SH (exec/interrupts.i)
    ("PAD" :u16 14)
    )

  ;; --- constants from exec/io.i ---
  (:const "+IOB-QUICK+" 0)
  (:const "+IOF-QUICK+" 1)
  (:const "+DEV-BEGINIO+" -6)
  (:const "+DEV-ABORTIO+" -12)
  (:const "+CMD-INVALID+" 0)
  (:const "+CMD-RESET+" 1)
  (:const "+CMD-READ+" 2)
  (:const "+CMD-WRITE+" 3)
  (:const "+CMD-UPDATE+" 4)
  (:const "+CMD-CLEAR+" 5)
  (:const "+CMD-STOP+" 6)
  (:const "+CMD-START+" 7)
  (:const "+CMD-FLUSH+" 8)
  (:const "+CMD-NONSTD+" 9)

  ;; --- structures from exec/io.i ---
  (:struct "IO-REQUEST" 32   ; IO (exec/io.i)
    ("DEVICE" :fptr 20)
    ("UNIT" :fptr 24)
    ("COMMAND" :u16 28)
    ("FLAGS" :u8 30)
    ("ERROR" :i8 31)
    )
  (:struct "IO-STD-REQ" 48   ; IO (exec/io.i)
    ("DEVICE" :fptr 20)
    ("UNIT" :fptr 24)
    ("COMMAND" :u16 28)
    ("FLAGS" :u8 30)
    ("ERROR" :i8 31)
    ("ACTUAL" :u32 32)
    ("LENGTH" :u32 36)
    ("DATA" :fptr 40)
    ("OFFSET" :u32 44)
    )

  ;; --- constants from exec/libraries.i ---
  (:const "+LIB-VECTSIZE+" 6)
  (:const "+LIB-RESERVED+" 4)
  (:const "+LIB-BASE+" -6)
  (:const "+LIB-USERDEF+" -30)
  (:const "+LIB-NONSTD+" -30)
  (:const "+LIB-OPEN+" -6)
  (:const "+LIB-CLOSE+" -12)
  (:const "+LIB-EXPUNGE+" -18)
  (:const "+LIB-EXTFUNC+" -24)
  (:const "+LIBB-SUMMING+" 0)
  (:const "+LIBF-SUMMING+" 1)
  (:const "+LIBB-CHANGED+" 1)
  (:const "+LIBF-CHANGED+" 2)
  (:const "+LIBB-SUMUSED+" 2)
  (:const "+LIBF-SUMUSED+" 4)
  (:const "+LIBB-DELEXP+" 3)
  (:const "+LIBF-DELEXP+" 8)
  (:const "+LIBB-EXP0-CNT+" 4)
  (:const "+LIBF-EXP0-CNT+" #x10)

  ;; --- structures from exec/libraries.i ---
  (:struct "LIBRARY" 34   ; LIB (exec/libraries.i)
    ("FLAGS" :u8 14)
    ("PAD" :u8 15)
    ("NEGSIZE" :u16 16)
    ("POSSIZE" :u16 18)
    ("VERSION" :u16 20)
    ("REVISION" :u16 22)
    ("IDSTRING" :fptr 24)
    ("SUM" :u32 28)
    ("OPENCNT" :u16 32)
    )

  ;; --- structures from exec/lists.i ---
  (:struct "LIST" 14   ; LH (exec/lists.i)
    ("HEAD" :fptr 0)
    ("TAIL" :fptr 4)
    ("TAILPRED" :fptr 8)
    ("TYPE" :u8 12)
    ("PAD" :u8 13)
    )
  (:struct "MIN-LIST" 12   ; MLH (exec/lists.i)
    ("HEAD" :fptr 0)
    ("TAIL" :fptr 4)
    ("TAILPRED" :fptr 8)
    )

  ;; --- constants from exec/memory.i ---
  (:const "+MEMF-ANY+" 0)
  (:const "+MEMB-PUBLIC+" 0)
  (:const "+MEMF-PUBLIC+" 1)
  (:const "+MEMB-CHIP+" 1)
  (:const "+MEMF-CHIP+" 2)
  (:const "+MEMB-FAST+" 2)
  (:const "+MEMF-FAST+" 4)
  (:const "+MEMB-LOCAL+" 8)
  (:const "+MEMF-LOCAL+" #x100)
  (:const "+MEMB-24-BITDMA+" 9)
  (:const "+MEMF-24-BITDMA+" #x200)
  (:const "+MEMB-KICK+" 10)
  (:const "+MEMF-KICK+" #x400)
  (:const "+MEMB-CLEAR+" #x10)
  (:const "+MEMF-CLEAR+" #x10000)
  (:const "+MEMB-LARGEST+" #x11)
  (:const "+MEMF-LARGEST+" #x20000)
  (:const "+MEMB-REVERSE+" #x12)
  (:const "+MEMF-REVERSE+" #x40000)
  (:const "+MEMB-TOTAL+" #x13)
  (:const "+MEMF-TOTAL+" #x80000)
  (:const "+MEMB-NO-EXPUNGE+" #x1F)
  (:const "+MEMF-NO-EXPUNGE+" #x80000000)
  (:const "+MEM-BLOCKSIZE+" 8)
  (:const "+MEM-BLOCKMASK+" 7)
  (:const "+MEMHB-RECYCLE+" 0)
  (:const "+MEMHF-RECYCLE+" 1)
  (:const "+MEM-DID-NOTHING+" 0)
  (:const "+MEM-ALL-DONE+" -1)
  (:const "+MEM-TRY-AGAIN+" 1)

  ;; --- structures from exec/memory.i ---
  (:struct "MEM-LIST" 16   ; ML (exec/memory.i)
    ("NUMENTRIES" :u16 14)
    )
  (:struct "MEM-ENTRY" 8   ; ME (exec/memory.i)
    ("REQS" (:struct 0) 0)
    ("ADDR" :fptr 0)
    ("LENGTH" :u32 4)
    )
  (:struct "MEM-HANDLER-DATA" 12   ; MemHandlerData (exec/memory.i)
    ("REQUEST-SIZE" :u32 0)
    ("REQUEST-FLAGS" :u32 4)
    ("FLAGS" :u32 8)
    )
  (:struct "MEM-HEADER" 32   ; MH (exec/memory.i)
    ("ATTRIBUTES" :u16 14)
    ("FIRST" :fptr 16)
    ("LOWER" :fptr 20)
    ("UPPER" :fptr 24)
    ("FREE" :u32 28)
    )
  (:struct "MEM-CHUNK" 12   ; MC (exec/memory.i)
    ("NEXT" :fptr 0)
    ("BYTES" :u32 4)
    ("SIZE" :fptr 8)
    )

  ;; --- constants from exec/nodes.i ---
  (:const "+NT-UNKNOWN+" 0)
  (:const "+NT-TASK+" 1)
  (:const "+NT-INTERRUPT+" 2)
  (:const "+NT-DEVICE+" 3)
  (:const "+NT-MSGPORT+" 4)
  (:const "+NT-MESSAGE+" 5)
  (:const "+NT-FREEMSG+" 6)
  (:const "+NT-REPLYMSG+" 7)
  (:const "+NT-RESOURCE+" 8)
  (:const "+NT-LIBRARY+" 9)
  (:const "+NT-MEMORY+" 10)
  (:const "+NT-SOFTINT+" 11)
  (:const "+NT-FONT+" 12)
  (:const "+NT-PROCESS+" 13)
  (:const "+NT-SEMAPHORE+" 14)
  (:const "+NT-SIGNALSEM+" 15)
  (:const "+NT-BOOTNODE+" #x10)
  (:const "+NT-KICKMEM+" #x11)
  (:const "+NT-GRAPHICS+" #x12)
  (:const "+NT-DEATHMESSAGE+" #x13)
  (:const "+NT-USER+" #xFE)
  (:const "+NT-EXTENDED+" #xFF)

  ;; --- structures from exec/nodes.i ---
  (:struct "NODE" 14   ; LN (exec/nodes.i)
    ("SUCC" :fptr 0)
    ("PRED" :fptr 4)
    ("TYPE" :u8 8)
    ("PRI" :i8 9)
    ("NAME" :fptr 10)
    )
  (:struct "MIN-NODE" 8   ; MLN (exec/nodes.i)
    ("SUCC" :fptr 0)
    ("PRED" :fptr 4)
    )

  ;; --- constants from exec/ports.i ---
  (:const "+MP-SOFTINT+" #x10)
  (:const "+PF-ACTION+" 3)
  (:const "+PA-SIGNAL+" 0)
  (:const "+PA-SOFTINT+" 1)
  (:const "+PA-IGNORE+" 2)

  ;; --- structures from exec/ports.i ---
  (:struct "MSG-PORT" 34   ; MP (exec/ports.i)
    ("FLAGS" :u8 14)
    ("SIGBIT" :u8 15)
    ("SIGTASK" :fptr 16)
    ("MSGLIST" (:struct 14) 20)
    )
  (:struct "MESSAGE" 20   ; MN (exec/ports.i)
    ("REPLYPORT" :fptr 14)
    ("LENGTH" :u16 18)
    )

  ;; --- constants from exec/resident.i ---
  (:const "+RTC-MATCHWORD+" #x4AFC)
  (:const "+RTB-COLDSTART+" 0)
  (:const "+RTF-COLDSTART+" 1)
  (:const "+RTB-SINGLETASK+" 1)
  (:const "+RTF-SINGLETASK+" 2)
  (:const "+RTB-AFTERDOS+" 2)
  (:const "+RTF-AFTERDOS+" 4)
  (:const "+RTB-AUTOINIT+" 7)
  (:const "+RTF-AUTOINIT+" #x80)
  (:const "+RTW-NEVER+" 0)
  (:const "+RTW-COLDSTART+" 1)

  ;; --- structures from exec/resident.i ---
  (:struct "RESIDENT" 26   ; RT (exec/resident.i)
    ("MATCHWORD" :u16 0)
    ("MATCHTAG" :fptr 2)
    ("ENDSKIP" :fptr 6)
    ("FLAGS" :u8 10)
    ("VERSION" :u8 11)
    ("TYPE" :u8 12)
    ("PRI" :i8 13)
    ("NAME" :fptr 14)
    ("IDSTRING" :fptr 18)
    ("INIT" :fptr 22)
    )

  ;; --- constants from exec/semaphores.i ---
  (:const "+SM-LOCKMSG+" #x10)

  ;; --- structures from exec/semaphores.i ---
  (:struct "SEMAPHORE-REQUEST" 12   ; SSR (exec/semaphores.i)
    ("WAITER" :fptr 8)
    )
  (:struct "SIGNAL-SEMAPHORE" 46   ; SS (exec/semaphores.i)
    ("NESTCOUNT" :i16 14)
    ("WAITQUEUE" (:struct 12) 16)
    ("MULTIPLELINK" (:struct 12) 28)
    ("OWNER" :fptr 40)
    ("QUEUECOUNT" :i16 44)
    )
  (:struct "SEMAPHORE-MESSAGE" 24   ; SemaphoreMessage (exec/semaphores.i)
    ("SEMAPHORE" :fptr 20)
    )
  (:struct "SEMAPHORE" 36   ; SM (exec/semaphores.i)
    ("BIDS" :i16 34)
    )

  ;; --- constants from exec/tasks.i ---
  (:const "+TB-PROCTIME+" 0)
  (:const "+TF-PROCTIME+" 1)
  (:const "+TB-ETASK+" 3)
  (:const "+TF-ETASK+" 8)
  (:const "+TB-STACKCHK+" 4)
  (:const "+TF-STACKCHK+" #x10)
  (:const "+TB-EXCEPT+" 5)
  (:const "+TF-EXCEPT+" #x20)
  (:const "+TB-SWITCH+" 6)
  (:const "+TF-SWITCH+" #x40)
  (:const "+TB-LAUNCH+" 7)
  (:const "+TF-LAUNCH+" #x80)
  (:const "+TS-INVALID+" 0)
  (:const "+TS-ADDED+" 1)
  (:const "+TS-RUN+" 2)
  (:const "+TS-READY+" 3)
  (:const "+TS-WAIT+" 4)
  (:const "+TS-EXCEPT+" 5)
  (:const "+TS-REMOVED+" 6)
  (:const "+SIGB-ABORT+" 0)
  (:const "+SIGF-ABORT+" 1)
  (:const "+SIGB-CHILD+" 1)
  (:const "+SIGF-CHILD+" 2)
  (:const "+SIGB-BLIT+" 4)
  (:const "+SIGF-BLIT+" #x10)
  (:const "+SIGB-SINGLE+" 4)
  (:const "+SIGF-SINGLE+" #x10)
  (:const "+SIGB-INTUITION+" 5)
  (:const "+SIGF-INTUITION+" #x20)
  (:const "+SIGB-NET+" 7)
  (:const "+SIGF-NET+" #x80)
  (:const "+SIGB-DOS+" 8)
  (:const "+SIGF-DOS+" #x100)
  (:const "+SYS-SIGALLOC+" #xFFFF)
  (:const "+SYS-TRAPALLOC+" #x8000)

  ;; --- structures from exec/tasks.i ---
  (:struct "TASK" 92   ; TC_Struct (exec/tasks.i)
    ("FLAGS" :u8 14)
    ("STATE" :u8 15)
    ("IDNESTCNT" :i8 16)
    ("TDNESTCNT" :i8 17)
    ("SIGALLOC" :u32 18)
    ("SIGWAIT" :u32 22)
    ("SIGRECVD" :u32 26)
    ("SIGEXCEPT" :u32 30)
    ("TRAPALLOC" :u16 34)
    ("TRAPABLE" :u16 36)
    ("EXCEPTDATA" :fptr 38)
    ("EXCEPTCODE" :fptr 42)
    ("TRAPDATA" :fptr 46)
    ("TRAPCODE" :fptr 50)
    ("SPREG" :fptr 54)
    ("SPLOWER" :fptr 58)
    ("SPUPPER" :fptr 62)
    ("SWITCH" :fptr 66)
    ("LAUNCH" :fptr 70)
    ("MEMENTRY" (:struct 14) 74)
    ("USERDATA" :fptr 88)
    )
  (:struct "STACK-SWAP-STRUCT" 12   ; StackSwapStruct (exec/tasks.i)
    ("LOWER" :fptr 0)
    ("UPPER" :u32 4)
    ("POINTER" :fptr 8)
    )

  ;; --- functions (exec_lib.sfd + MorphOS SDK) ---
  ;; skipped Supervisor: argument in A5 (reserved by the call dispatcher)
  (:fn "INIT-CODE" -72 (:d0 :d1) :void)   ; VOID InitCode(ULONG startClass, ULONG version) (D0,D1) LVO -72
  (:fn "INIT-STRUCT" -78 (:a1 :a2 :d0) :void)   ; VOID InitStruct(CONST_APTR initTable, APTR memory, ULONG size) (A1,A2,D0) LVO -78
  (:fn "MAKE-LIBRARY" -84 (:a0 :a1 :a2 :d0 :d1) :pointer)   ; struct Library * MakeLibrary(CONST_APTR funcInit, CONST_APTR structInit, APTR libInit, ULONG dataSize, ULONG segList) (A0,A1,A2,D0,D1) LVO -84
  (:fn "MAKE-FUNCTIONS" -90 (:a0 :a1 :a2) :void)   ; VOID MakeFunctions(APTR target, CONST_APTR functionArray, ULONG funcDispBase) (A0,A1,A2) LVO -90
  (:fn "FIND-RESIDENT" -96 (:a1) :pointer)   ; struct Resident * FindResident(CONST_STRPTR name) (A1) LVO -96
  (:fn "INIT-RESIDENT" -102 (:a1 :d1) :pointer)   ; APTR InitResident(CONST struct Resident * resident, ULONG segList) (A1,D1) LVO -102
  (:fn "ALERT" -108 (:d7) :void)   ; VOID Alert(ULONG alertNum) (D7) LVO -108
  (:fn "DEBUG" -114 (:d0) :void)   ; VOID Debug(ULONG flags) (D0) LVO -114
  (:fn "DISABLE" -120 () :void)   ; VOID Disable() () LVO -120
  (:fn "ENABLE" -126 () :void)   ; VOID Enable() () LVO -126
  (:fn "FORBID" -132 () :void)   ; VOID Forbid() () LVO -132
  (:fn "PERMIT" -138 () :void)   ; VOID Permit() () LVO -138
  (:fn "SET-SR" -144 (:d0 :d1) :unsigned)   ; ULONG SetSR(ULONG newSR, ULONG mask) (D0,D1) LVO -144
  (:fn "SUPER-STATE" -150 () :pointer)   ; APTR SuperState() () LVO -150
  (:fn "USER-STATE" -156 (:d0) :void)   ; VOID UserState(APTR sysStack) (D0) LVO -156
  (:fn "SET-INT-VECTOR" -162 (:d0 :a1) :pointer)   ; struct Interrupt * SetIntVector(LONG intNumber, struct Interrupt * interrupt) (D0,A1) LVO -162
  (:fn "ADD-INT-SERVER" -168 (:d0 :a1) :void)   ; VOID AddIntServer(LONG intNumber, struct Interrupt * interrupt) (D0,A1) LVO -168
  (:fn "REM-INT-SERVER" -174 (:d0 :a1) :void)   ; VOID RemIntServer(LONG intNumber, struct Interrupt * interrupt) (D0,A1) LVO -174
  (:fn "CAUSE" -180 (:a1) :void)   ; VOID Cause(CONST struct Interrupt * interrupt) (A1) LVO -180
  (:fn "ALLOCATE" -186 (:a0 :d0) :pointer)   ; APTR Allocate(struct MemHeader * freeList, ULONG byteSize) (A0,D0) LVO -186
  (:fn "DEALLOCATE" -192 (:a0 :a1 :d0) :void)   ; VOID Deallocate(struct MemHeader * freeList, APTR memoryBlock, ULONG byteSize) (A0,A1,D0) LVO -192
  (:fn "ALLOC-MEM" -198 (:d0 :d1) :pointer)   ; APTR AllocMem(ULONG byteSize, ULONG requirements) (D0,D1) LVO -198
  (:fn "ALLOC-ABS" -204 (:d0 :a1) :pointer)   ; APTR AllocAbs(ULONG byteSize, APTR location) (D0,A1) LVO -204
  (:fn "FREE-MEM" -210 (:a1 :d0) :void)   ; VOID FreeMem(APTR memoryBlock, ULONG byteSize) (A1,D0) LVO -210
  (:fn "AVAIL-MEM" -216 (:d1) :unsigned)   ; ULONG AvailMem(ULONG requirements) (D1) LVO -216
  (:fn "ALLOC-ENTRY" -222 (:a0) :pointer)   ; struct MemList * AllocEntry(CONST struct MemList * entry) (A0) LVO -222
  (:fn "FREE-ENTRY" -228 (:a0) :void)   ; VOID FreeEntry(struct MemList * entry) (A0) LVO -228
  (:fn "INSERT" -234 (:a0 :a1 :a2) :void)   ; VOID Insert(struct List * list, struct Node * node, struct Node * pred) (A0,A1,A2) LVO -234
  (:fn "ADD-HEAD" -240 (:a0 :a1) :void)   ; VOID AddHead(struct List * list, struct Node * node) (A0,A1) LVO -240
  (:fn "ADD-TAIL" -246 (:a0 :a1) :void)   ; VOID AddTail(struct List * list, struct Node * node) (A0,A1) LVO -246
  (:fn "REMOVE" -252 (:a1) :void)   ; VOID Remove(struct Node * node) (A1) LVO -252
  (:fn "REM-HEAD" -258 (:a0) :pointer)   ; struct Node * RemHead(struct List * list) (A0) LVO -258
  (:fn "REM-TAIL" -264 (:a0) :pointer)   ; struct Node * RemTail(struct List * list) (A0) LVO -264
  (:fn "ENQUEUE" -270 (:a0 :a1) :void)   ; VOID Enqueue(struct List * list, struct Node * node) (A0,A1) LVO -270
  (:fn "FIND-NAME" -276 (:a0 :a1) :pointer)   ; struct Node * FindName(struct List * list, CONST_STRPTR name) (A0,A1) LVO -276
  (:fn "ADD-TASK" -282 (:a1 :a2 :a3) :pointer)   ; APTR AddTask(struct Task * task, APTR initPC, APTR finalPC) (A1,A2,A3) LVO -282
  (:fn "REM-TASK" -288 (:a1) :void)   ; VOID RemTask(struct Task * task) (A1) LVO -288
  (:fn "FIND-TASK" -294 (:a1) :pointer)   ; struct Task * FindTask(CONST_STRPTR name) (A1) LVO -294
  (:fn "SET-TASK-PRI" -300 (:a1 :d0) :i8)   ; BYTE SetTaskPri(struct Task * task, LONG priority) (A1,D0) LVO -300
  (:fn "SET-SIGNAL" -306 (:d0 :d1) :unsigned)   ; ULONG SetSignal(ULONG newSignals, ULONG signalSet) (D0,D1) LVO -306
  (:fn "SET-EXCEPT" -312 (:d0 :d1) :unsigned)   ; ULONG SetExcept(ULONG newSignals, ULONG signalSet) (D0,D1) LVO -312
  (:fn "WAIT" -318 (:d0) :unsigned)   ; ULONG Wait(ULONG signalSet) (D0) LVO -318
  (:fn "SIGNAL" -324 (:a1 :d0) :void)   ; VOID Signal(struct Task * task, ULONG signalSet) (A1,D0) LVO -324
  (:fn "ALLOC-SIGNAL" -330 (:d0) :i8)   ; BYTE AllocSignal(BYTE signalNum) (D0) LVO -330
  (:fn "FREE-SIGNAL" -336 (:d0) :void)   ; VOID FreeSignal(BYTE signalNum) (D0) LVO -336
  (:fn "ALLOC-TRAP" -342 (:d0) :signed)   ; LONG AllocTrap(LONG trapNum) (D0) LVO -342
  (:fn "FREE-TRAP" -348 (:d0) :void)   ; VOID FreeTrap(LONG trapNum) (D0) LVO -348
  (:fn "ADD-PORT" -354 (:a1) :void)   ; VOID AddPort(struct MsgPort * port) (A1) LVO -354
  (:fn "REM-PORT" -360 (:a1) :void)   ; VOID RemPort(struct MsgPort * port) (A1) LVO -360
  (:fn "PUT-MSG" -366 (:a0 :a1) :void)   ; VOID PutMsg(struct MsgPort * port, struct Message * message) (A0,A1) LVO -366
  (:fn "GET-MSG" -372 (:a0) :pointer)   ; struct Message * GetMsg(struct MsgPort * port) (A0) LVO -372
  (:fn "REPLY-MSG" -378 (:a1) :void)   ; VOID ReplyMsg(struct Message * message) (A1) LVO -378
  (:fn "WAIT-PORT" -384 (:a0) :pointer)   ; struct Message * WaitPort(struct MsgPort * port) (A0) LVO -384
  (:fn "FIND-PORT" -390 (:a1) :pointer)   ; struct MsgPort * FindPort(CONST_STRPTR name) (A1) LVO -390
  (:fn "ADD-LIBRARY" -396 (:a1) :void)   ; VOID AddLibrary(struct Library * library) (A1) LVO -396
  (:fn "REM-LIBRARY" -402 (:a1) :void)   ; VOID RemLibrary(struct Library * library) (A1) LVO -402
  (:fn "OLD-OPEN-LIBRARY" -408 (:a1) :pointer)   ; struct Library * OldOpenLibrary(CONST_STRPTR libName) (A1) LVO -408
  (:fn "CLOSE-LIBRARY" -414 (:a1) :void)   ; VOID CloseLibrary(struct Library * library) (A1) LVO -414
  (:fn "SET-FUNCTION" -420 (:a1 :a0 :d0) :pointer)   ; APTR SetFunction(struct Library * library, LONG funcOffset, APTR newFunction) (A1,A0,D0) LVO -420
  (:fn "SUM-LIBRARY" -426 (:a1) :void)   ; VOID SumLibrary(struct Library * library) (A1) LVO -426
  (:fn "ADD-DEVICE" -432 (:a1) :void)   ; VOID AddDevice(struct Device * device) (A1) LVO -432
  (:fn "REM-DEVICE" -438 (:a1) :void)   ; VOID RemDevice(struct Device * device) (A1) LVO -438
  (:fn "OPEN-DEVICE" -444 (:a0 :d0 :a1 :d1) :i8)   ; BYTE OpenDevice(CONST_STRPTR devName, ULONG unit, struct IORequest * ioRequest, ULONG flags) (A0,D0,A1,D1) LVO -444
  (:fn "CLOSE-DEVICE" -450 (:a1) :void)   ; VOID CloseDevice(struct IORequest * ioRequest) (A1) LVO -450
  (:fn "DO-IO" -456 (:a1) :i8)   ; BYTE DoIO(struct IORequest * ioRequest) (A1) LVO -456
  (:fn "SEND-IO" -462 (:a1) :void)   ; VOID SendIO(struct IORequest * ioRequest) (A1) LVO -462
  (:fn "CHECK-IO" -468 (:a1) :pointer)   ; struct IORequest * CheckIO(CONST struct IORequest * ioRequest) (A1) LVO -468
  (:fn "WAIT-IO" -474 (:a1) :i8)   ; BYTE WaitIO(struct IORequest * ioRequest) (A1) LVO -474
  (:fn "ABORT-IO" -480 (:a1) :void)   ; VOID AbortIO(struct IORequest * ioRequest) (A1) LVO -480
  (:fn "ADD-RESOURCE" -486 (:a1) :void)   ; VOID AddResource(APTR resource) (A1) LVO -486
  (:fn "REM-RESOURCE" -492 (:a1) :void)   ; VOID RemResource(APTR resource) (A1) LVO -492
  (:fn "OPEN-RESOURCE" -498 (:a1) :pointer)   ; APTR OpenResource(CONST_STRPTR resName) (A1) LVO -498
  (:fn "RAW-DO-FMT" -522 (:a0 :a1 :a2 :a3) :pointer)   ; APTR RawDoFmt(CONST_STRPTR formatString, APTR dataStream, APTR putChProc, APTR putChData) (A0,A1,A2,A3) LVO -522
  (:fn "GET-CC" -528 () :unsigned)   ; ULONG GetCC() () LVO -528
  (:fn "TYPE-OF-MEM" -534 (:a1) :unsigned)   ; ULONG TypeOfMem(CONST_APTR address) (A1) LVO -534
  (:fn "PROCURE" -540 (:a0 :a1) :unsigned)   ; ULONG Procure(struct SignalSemaphore * sigSem, struct SemaphoreMessage * bidMsg) (A0,A1) LVO -540
  (:fn "VACATE" -546 (:a0 :a1) :void)   ; VOID Vacate(struct SignalSemaphore * sigSem, struct SemaphoreMessage * bidMsg) (A0,A1) LVO -546
  (:fn "OPEN-LIBRARY" -552 (:a1 :d0) :pointer)   ; struct Library * OpenLibrary(CONST_STRPTR libName, ULONG version) (A1,D0) LVO -552
  (:fn "INIT-SEMAPHORE" -558 (:a0) :void)   ; VOID InitSemaphore(struct SignalSemaphore * sigSem) (A0) LVO -558
  (:fn "OBTAIN-SEMAPHORE" -564 (:a0) :void)   ; VOID ObtainSemaphore(struct SignalSemaphore * sigSem) (A0) LVO -564
  (:fn "RELEASE-SEMAPHORE" -570 (:a0) :void)   ; VOID ReleaseSemaphore(struct SignalSemaphore * sigSem) (A0) LVO -570
  (:fn "ATTEMPT-SEMAPHORE" -576 (:a0) :unsigned)   ; ULONG AttemptSemaphore(struct SignalSemaphore * sigSem) (A0) LVO -576
  (:fn "OBTAIN-SEMAPHORE-LIST" -582 (:a0) :void)   ; VOID ObtainSemaphoreList(struct List * sigSem) (A0) LVO -582
  (:fn "RELEASE-SEMAPHORE-LIST" -588 (:a0) :void)   ; VOID ReleaseSemaphoreList(struct List * sigSem) (A0) LVO -588
  (:fn "FIND-SEMAPHORE" -594 (:a1) :pointer)   ; struct SignalSemaphore * FindSemaphore(CONST_STRPTR name) (A1) LVO -594
  (:fn "ADD-SEMAPHORE" -600 (:a1) :void)   ; VOID AddSemaphore(struct SignalSemaphore * sigSem) (A1) LVO -600
  (:fn "REM-SEMAPHORE" -606 (:a1) :void)   ; VOID RemSemaphore(struct SignalSemaphore * sigSem) (A1) LVO -606
  (:fn "SUM-KICK-DATA" -612 () :unsigned)   ; ULONG SumKickData() () LVO -612
  (:fn "ADD-MEM-LIST" -618 (:d0 :d1 :d2 :a0 :a1) :void)   ; VOID AddMemList(ULONG size, ULONG attributes, LONG pri, APTR base, STRPTR name) (D0,D1,D2,A0,A1) LVO -618
  (:fn "COPY-MEM" -624 (:a0 :a1 :d0) :void)   ; VOID CopyMem(CONST_APTR source, APTR dest, ULONG size) (A0,A1,D0) LVO -624
  (:fn "COPY-MEM-QUICK" -630 (:a0 :a1 :d0) :void)   ; VOID CopyMemQuick(CONST_APTR source, APTR dest, ULONG size) (A0,A1,D0) LVO -630
  (:fn "CACHE-CLEAR-U" -636 () :void)   ; VOID CacheClearU() () LVO -636
  (:fn "CACHE-CLEAR-E" -642 (:a0 :d0 :d1) :void)   ; VOID CacheClearE(APTR address, ULONG length, ULONG caches) (A0,D0,D1) LVO -642
  (:fn "CACHE-CONTROL" -648 (:d0 :d1) :unsigned)   ; ULONG CacheControl(ULONG cacheBits, ULONG cacheMask) (D0,D1) LVO -648
  (:fn "CREATE-IO-REQUEST" -654 (:a0 :d0) :pointer)   ; APTR CreateIORequest(struct MsgPort * port, ULONG size) (A0,D0) LVO -654
  (:fn "DELETE-IO-REQUEST" -660 (:a0) :void)   ; VOID DeleteIORequest(APTR iorequest) (A0) LVO -660
  (:fn "CREATE-MSG-PORT" -666 () :pointer)   ; struct MsgPort * CreateMsgPort() () LVO -666
  (:fn "DELETE-MSG-PORT" -672 (:a0) :void)   ; VOID DeleteMsgPort(struct MsgPort * port) (A0) LVO -672
  (:fn "OBTAIN-SEMAPHORE-SHARED" -678 (:a0) :void)   ; VOID ObtainSemaphoreShared(struct SignalSemaphore * sigSem) (A0) LVO -678
  (:fn "ALLOC-VEC" -684 (:d0 :d1) :pointer)   ; APTR AllocVec(ULONG byteSize, ULONG requirements) (D0,D1) LVO -684
  (:fn "FREE-VEC" -690 (:a1) :void)   ; VOID FreeVec(APTR memoryBlock) (A1) LVO -690
  (:fn "CREATE-POOL" -696 (:d0 :d1 :d2) :pointer)   ; APTR CreatePool(ULONG requirements, ULONG puddleSize, ULONG threshSize) (D0,D1,D2) LVO -696
  (:fn "DELETE-POOL" -702 (:a0) :void)   ; VOID DeletePool(APTR poolHeader) (A0) LVO -702
  (:fn "ALLOC-POOLED" -708 (:a0 :d0) :pointer)   ; APTR AllocPooled(APTR poolHeader, ULONG memSize) (A0,D0) LVO -708
  (:fn "FREE-POOLED" -714 (:a0 :a1 :d0) :void)   ; VOID FreePooled(APTR poolHeader, APTR memory, ULONG memSize) (A0,A1,D0) LVO -714
  (:fn "ATTEMPT-SEMAPHORE-SHARED" -720 (:a0) :unsigned)   ; ULONG AttemptSemaphoreShared(struct SignalSemaphore * sigSem) (A0) LVO -720
  (:fn "COLD-REBOOT" -726 () :void)   ; VOID ColdReboot() () LVO -726
  (:fn "STACK-SWAP" -732 (:a0) :void)   ; VOID StackSwap(struct StackSwapStruct * newStack) (A0) LVO -732
  (:fn "CACHE-PRE-DMA" -762 (:a0 :a1 :d0) :pointer)   ; APTR CachePreDMA(CONST_APTR address, ULONG * length, ULONG flags) (A0,A1,D0) LVO -762
  (:fn "CACHE-POST-DMA" -768 (:a0 :a1 :d0) :void)   ; VOID CachePostDMA(CONST_APTR address, ULONG * length, ULONG flags) (A0,A1,D0) LVO -768
  (:fn "ADD-MEM-HANDLER" -774 (:a1) :void)   ; VOID AddMemHandler(struct Interrupt * memhand) (A1) LVO -774
  (:fn "REM-MEM-HANDLER" -780 (:a1) :void)   ; VOID RemMemHandler(struct Interrupt * memhand) (A1) LVO -780
  (:fn "OBTAIN-QUICK-VECTOR" -786 (:a0) :unsigned)   ; ULONG ObtainQuickVector(APTR interruptCode) (A0) LVO -786
  (:fn "NEW-MIN-LIST" -828 (:a0) :void :not-morphos 45)   ; VOID NewMinList(struct MinList * minlist) (A0) LVO -828
  (:fn "NEW-GET-TASK-ATTRS-A" -738 (:a0 :a1 :d0 :d1 :a2) :unsigned :morphos)   ; ULONG NewGetTaskAttrsA(struct Task * task, APTR Data, ULONG DataSize, ULONG Type, struct TagItem * Tags) (A0,A1,D0,D1,A2) LVO -738
  (:fn "NEW-SET-TASK-ATTRS-A" -744 (:a0 :a1 :d0 :d1 :a2) :unsigned :morphos)   ; ULONG NewSetTaskAttrsA(struct Task * task, APTR Data, ULONG DataSize, ULONG Type, struct TagItem * Tags) (A0,A1,D0,D1,A2) LVO -744
  (:fn "CHILD-STATUS" -750 (:d0) :unsigned :morphos)   ; ULONG ChildStatus(ULONG tid) (D0) LVO -750
  (:fn "CHILD-WAIT" -756 (:d0) :unsigned :morphos)   ; ULONG ChildWait(ULONG tid) (D0) LVO -756
  (:fn "NEW-SET-FUNCTION" -792 (:a0 :a1 :d0 :a2) :pointer :morphos)   ; APTR NewSetFunction(struct Library * library, APTR function, LONG offset, struct TagItem * tags) (A0,A1,D0,A2) LVO -792
  (:fn "NEW-CREATE-LIBRARY" -798 (:a0) :pointer :morphos)   ; struct Library * NewCreateLibrary(struct TagItem * tags) (A0) LVO -798
  (:fn "NEW-PPC-STACK-SWAP" -804 (:a0 :a1 :a2) :unsigned :morphos)   ; ULONG NewPPCStackSwap(struct StackSwapStruct * newStack, APTR function, struct PPCStackSwapArgs * args) (A0,A1,A2) LVO -804
  ;; skipped VNewRawDoFmt: not a 68k register call (base,sysv)
  (:fn "CACHE-FLUSH-DATA-AREA" -828 (:a0 :d0) :void :morphos)   ; VOID CacheFlushDataArea(APTR Address, ULONG Size) (A0,D0) LVO -828
  (:fn "CACHE-INVALID-INST-AREA" -834 (:a0 :d0) :void :morphos)   ; VOID CacheInvalidInstArea(APTR Address, ULONG Size) (A0,D0) LVO -834
  (:fn "CACHE-INVALID-DATA-AREA" -840 (:a0 :d0) :void :morphos)   ; VOID CacheInvalidDataArea(APTR Address, ULONG Size) (A0,D0) LVO -840
  (:fn "CACHE-FLUSH-DATA-INST-AREA" -846 (:a0 :d0) :void :morphos)   ; VOID CacheFlushDataInstArea(APTR Address, ULONG Size) (A0,D0) LVO -846
  (:fn "CACHE-TRASH-CACHE-AREA" -852 (:a0 :d0) :void :morphos)   ; VOID CacheTrashCacheArea(APTR Address, ULONG Size) (A0,D0) LVO -852
  (:fn "ALLOC-TASK-POOLED" -858 (:d0) :pointer :morphos)   ; APTR AllocTaskPooled(ULONG Size) (D0) LVO -858
  (:fn "FREE-TASK-POOLED" -864 (:a1 :d0) :void :morphos)   ; VOID FreeTaskPooled(APTR Address, ULONG Size) (A1,D0) LVO -864
  (:fn "ALLOC-VEC-TASK-POOLED" -870 (:d0) :pointer :morphos)   ; APTR AllocVecTaskPooled(ULONG Size) (D0) LVO -870
  (:fn "FREE-VEC-TASK-POOLED" -876 (:a1) :void :morphos)   ; VOID FreeVecTaskPooled(APTR Address) (A1) LVO -876
  (:fn "FLUSH-POOL" -882 (:a0) :void :morphos)   ; VOID FlushPool(APTR poolHeader) (A0) LVO -882
  (:fn "FLUSH-TASK-POOL" -888 () :void :morphos)   ; VOID FlushTaskPool() () LVO -888
  (:fn "ALLOC-VEC-POOLED" -894 (:a0 :d0) :pointer :morphos)   ; APTR AllocVecPooled(APTR poolHeader, ULONG memSize) (A0,D0) LVO -894
  (:fn "FREE-VEC-POOLED" -900 (:a0 :a1) :void :morphos)   ; VOID FreeVecPooled(APTR poolHeader, APTR memory) (A0,A1) LVO -900
  (:fn "NEW-GET-SYSTEM-ATTRS-A" -906 (:a0 :d0 :d1 :a1) :unsigned :morphos)   ; ULONG NewGetSystemAttrsA(APTR Data, ULONG DataSize, ULONG Type, struct TagItem * Tags) (A0,D0,D1,A1) LVO -906
  (:fn "NEW-SET-SYSTEM-ATTRS-A" -912 (:a0 :d0 :d1 :a1) :unsigned :morphos)   ; ULONG NewSetSystemAttrsA(APTR Data, ULONG DataSize, ULONG Type, struct TagItem * Tags) (A0,D0,D1,A1) LVO -912
  (:fn "NEW-CREATE-TASK-A" -918 (:a0) :pointer :morphos)   ; struct Task * NewCreateTaskA(struct TagItem * Tags) (A0) LVO -918
  ;; skipped NewRawDoFmt: not a 68k register call (base,sysv)
  ;; skipped AllocateAligned: not a 68k register call (base,sysv)
  ;; skipped AllocMemAligned: not a 68k register call (base,sysv)
  ;; skipped AllocVecAligned: not a 68k register call (base,sysv)
  ;; skipped AddExecNotify: not a 68k register call (base,sysv)
  ;; skipped RemExecNotify: not a 68k register call (base,sysv)
  (:fn "FIND-EXEC-NODE" -960 (:d0 :a0) :pointer :morphos)   ; struct Node * FindExecNode(ULONG type, CONST_STRPTR name) (D0,A0) LVO -960
  (:fn "ADD-EXEC-NODE-A" -966 (:a0 :a1) :pointer :morphos)   ; APTR AddExecNodeA(APTR innode, struct TagItem * Tags) (A0,A1) LVO -966
  (:fn "ALLOC-VEC-DMA" -972 (:d0 :d1) :pointer :morphos)   ; APTR AllocVecDMA(ULONG byteSize, ULONG requirements) (D0,D1) LVO -972
  (:fn "FREE-VEC-DMA" -978 (:a1) :void :morphos)   ; VOID FreeVecDMA(APTR memoryBlock) (A1) LVO -978
  ;; skipped AllocPooledAligned: not a 68k register call (base,sysv)
  ;; skipped AddResident: not a 68k register call (base,sysv)
  ;; skipped FindTaskByPID: not a 68k register call (base,sysv)
  (:fn "DUMP-TASK-STATE" -1026 (:a0) :void :morphos)   ; void DumpTaskState(struct Task * task) (A0) LVO -1026
  ;; skipped AddExecNotifyType: not a 68k register call (base,sysv)
  ;; skipped ShutdownA: not a 68k register call (base,sysv)
  ;; skipped AvailPool: not a 68k register call (base,sysv)
  ;; skipped PutMsgHead: not a 68k register call (base,sysv)
  (:fn "NEW-GET-TASK-PID-ATTRS-A" -1068 (:d0 :a0 :d1 :d2 :a1) :unsigned :morphos)   ; ULONG NewGetTaskPIDAttrsA(ULONG TaskPID, APTR Data, ULONG DataSize, ULONG Type, struct TagItem * Tags) (D0,A0,D1,D2,A1) LVO -1068
  (:fn "NEW-SET-TASK-PID-ATTRS-A" -1074 (:d0 :a0 :d1 :d2 :a1) :unsigned :morphos)   ; ULONG NewSetTaskPIDAttrsA(ULONG TaskPID, APTR Data, ULONG DataSize, ULONG Type, struct TagItem * Tags) (D0,A0,D1,D2,A1) LVO -1074
  ;; skipped TLSAllocA: not a 68k register call (base,sysv)
  ;; skipped TLSFree: not a 68k register call (base,sysv)
  ;; skipped TLSGetValue: not a 68k register call (base,sysv)
  ;; skipped TLSSetValue: not a 68k register call (base,sysv)
  ;; skipped TLSCallDestructors: not a 68k register call (base,sysv)
  )

(provide "amiga/raw/exec")
