;;; amiga/raw/getcolor  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   getcolor_lib.sfd ($VER: getcolor_lib.sfd 47.1 (30.11.2021))
;;;
;;; 1 functions, 0 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.GETCOLOR"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*GETCOLOR-BASE*" "*GETCOLOR-VERSION*"
   "GETCOLOR-GET-CLASS" ))

(in-package "AMIGA.RAW.GETCOLOR")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *getcolor-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/getcolor.gadget" 0)))
(defvar *getcolor-version*
  (and *getcolor-base* (amiga.ffi:library-version *getcolor-base*)))
(defun %version>= (n)
  (and *getcolor-version* (>= *getcolor-version* n)))

;;; --- functions (getcolor_lib.sfd) ---
(when (%version>= 40)
  (amiga.ffi:defcfun getcolor-get-class *getcolor-base* -30 ()
    :result :pointer
    :doc "Class * GETCOLOR_GetClass() () LVO -30"))

(provide "amiga/raw/getcolor")
