;;; amiga/raw/getfile  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   getfile_lib.sfd ($VER: getfile_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK getfile_lib.fd + clib/getfile_protos.h (via fd2sfd)
;;;
;;; 1 functions, 0 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.GETFILE"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*GETFILE-BASE*" "*GETFILE-VERSION*"
   "GETFILE-GET-CLASS" ))

(in-package "AMIGA.RAW.GETFILE")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *getfile-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/getfile.gadget" 0)))
(defvar *getfile-version*
  (and *getfile-base* (amiga.ffi:library-version *getfile-base*)))
(defun %version>= (n)
  (and *getfile-version* (>= *getfile-version* n)))

;;; --- functions (getfile_lib.sfd + MorphOS SDK) ---
(when (%version>= 40)
  (amiga.ffi:defcfun getfile-get-class *getfile-base* -30 ()
    :result :pointer
    :doc "Class * GETFILE_GetClass() () LVO -30"))

(provide "amiga/raw/getfile")
