;;; amiga/raw/getfont  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   getfont_lib.sfd ($VER: getfont_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK getfont_lib.fd + clib/getfont_protos.h (via fd2sfd)
;;;
;;; 1 functions, 0 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.GETFONT"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*GETFONT-BASE*" "*GETFONT-VERSION*"
   "GETFONT-GET-CLASS" ))

(in-package "AMIGA.RAW.GETFONT")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *getfont-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/getfont.gadget" 0)))
(defvar *getfont-version*
  (and *getfont-base* (amiga.ffi:library-version *getfont-base*)))
(defun %version>= (n)
  (and *getfont-version* (>= *getfont-version* n)))

;;; --- functions (getfont_lib.sfd + MorphOS SDK) ---
(when (%version>= 40)
  (amiga.ffi:defcfun getfont-get-class *getfont-base* -30 ()
    :result :pointer
    :doc "Class * GETFONT_GetClass() () LVO -30"))

(provide "amiga/raw/getfont")
