;;; amiga/raw/icon  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   icon_lib.sfd ($VER: icon_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK icon_lib.fd + clib/icon_protos.h (via fd2sfd)
;;;   workbench/icon.i
;;;
;;; 24 functions, 87 constants, 1 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.ICON"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export "*ICON-BASE*" "*ICON-VERSION*"))

(in-package "AMIGA.RAW.ICON")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *icon-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "icon.library" 0)))
(defvar *icon-version*
  (and *icon-base* (amiga.ffi:library-version *icon-base*)))
(defun %version>= (n)
  (and *icon-version* (>= *icon-version* n)))

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.ICON"
    (:base *icon-base* :version *icon-version*)

  ;; --- constants from workbench/icon.i ---
  (:const "+ICONA-DUMMY+" #x80009000)
  (:const "+ICONA-ERROR-CODE+" #x80009001)
  (:const "+ICONA-ERROR-TAG-ITEM+" #x8000904B)
  (:const "+ICONCTRLA-SET-GLOBAL-SCREEN+" #x80009002)
  (:const "+ICONCTRLA-GET-GLOBAL-SCREEN+" #x80009003)
  (:const "+ICONCTRLA-SET-GLOBAL-PRECISION+" #x80009004)
  (:const "+ICONCTRLA-GET-GLOBAL-PRECISION+" #x80009005)
  (:const "+ICONCTRLA-SET-GLOBAL-EMBOSS-RECT+" #x80009006)
  (:const "+ICONCTRLA-GET-GLOBAL-EMBOSS-RECT+" #x80009007)
  (:const "+ICONCTRLA-SET-GLOBAL-FRAMELESS+" #x80009008)
  (:const "+ICONCTRLA-GET-GLOBAL-FRAMELESS+" #x80009009)
  (:const "+ICONCTRLA-SET-GLOBAL-NEW-ICONS-SUPPORT+" #x8000900A)
  (:const "+ICONCTRLA-GET-GLOBAL-NEW-ICONS-SUPPORT+" #x8000900B)
  (:const "+ICONCTRLA-SET-GLOBAL-COLOR-ICON-SUPPORT+" #x8000904D)
  (:const "+ICONCTRLA-GET-GLOBAL-COLOR-ICON-SUPPORT+" #x8000904E)
  (:const "+ICONCTRLA-SET-GLOBAL-IDENTIFY-HOOK+" #x8000900C)
  (:const "+ICONCTRLA-GET-GLOBAL-IDENTIFY-HOOK+" #x8000900D)
  (:const "+ICONCTRLA-SET-GLOBAL-MAX-NAME-LENGTH+" #x80009043)
  (:const "+ICONCTRLA-GET-GLOBAL-MAX-NAME-LENGTH+" #x80009044)
  (:const "+ICONCTRLA-GET-IMAGE-MASK1+" #x8000900E)
  (:const "+ICONCTRLA-GET-IMAGE-MASK2+" #x8000900F)
  (:const "+ICONCTRLA-SET-TRANSPARENT-COLOR1+" #x80009010)
  (:const "+ICONCTRLA-GET-TRANSPARENT-COLOR1+" #x80009011)
  (:const "+ICONCTRLA-SET-TRANSPARENT-COLOR2+" #x80009012)
  (:const "+ICONCTRLA-GET-TRANSPARENT-COLOR2+" #x80009013)
  (:const "+ICONCTRLA-SET-PALETTE1+" #x80009014)
  (:const "+ICONCTRLA-GET-PALETTE1+" #x80009015)
  (:const "+ICONCTRLA-SET-PALETTE2+" #x80009016)
  (:const "+ICONCTRLA-GET-PALETTE2+" #x80009017)
  (:const "+ICONCTRLA-SET-PALETTE-SIZE1+" #x80009018)
  (:const "+ICONCTRLA-GET-PALETTE-SIZE1+" #x80009019)
  (:const "+ICONCTRLA-SET-PALETTE-SIZE2+" #x8000901A)
  (:const "+ICONCTRLA-GET-PALETTE-SIZE2+" #x8000901B)
  (:const "+ICONCTRLA-SET-IMAGE-DATA1+" #x8000901C)
  (:const "+ICONCTRLA-GET-IMAGE-DATA1+" #x8000901D)
  (:const "+ICONCTRLA-SET-IMAGE-DATA2+" #x8000901E)
  (:const "+ICONCTRLA-GET-IMAGE-DATA2+" #x8000901F)
  (:const "+ICONCTRLA-SET-FRAMELESS+" #x80009020)
  (:const "+ICONCTRLA-GET-FRAMELESS+" #x80009021)
  (:const "+ICONCTRLA-SET-NEW-ICONS-SUPPORT+" #x80009022)
  (:const "+ICONCTRLA-GET-NEW-ICONS-SUPPORT+" #x80009023)
  (:const "+ICONCTRLA-SET-ASPECT-RATIO+" #x80009024)
  (:const "+ICONCTRLA-GET-ASPECT-RATIO+" #x80009025)
  (:const "+ICONCTRLA-SET-WIDTH+" #x80009026)
  (:const "+ICONCTRLA-GET-WIDTH+" #x80009027)
  (:const "+ICONCTRLA-SET-HEIGHT+" #x80009028)
  (:const "+ICONCTRLA-GET-HEIGHT+" #x80009029)
  (:const "+ICONCTRLA-IS-PALETTE-MAPPED+" #x8000902A)
  (:const "+ICONCTRLA-GET-SCREEN+" #x8000902B)
  (:const "+ICONCTRLA-HAS-REAL-IMAGE2+" #x8000902C)
  (:const "+ICONCTRLA-IS-NEW-ICON+" #x8000904F)
  (:const "+ICONCTRLA-IS-NATIVE-ICON+" #x80009050)
  (:const "+ICON-ASPECT-RATIO-UNKNOWN+" 0)
  (:const "+ICONGETA-GET-DEFAULT-TYPE+" #x8000902D)
  (:const "+ICONGETA-GET-DEFAULT-NAME+" #x8000902E)
  (:const "+ICONGETA-FAIL-IF-UNAVAILABLE+" #x8000902F)
  (:const "+ICONGETA-GET-PALETTE-MAPPED-ICON+" #x80009030)
  (:const "+ICONGETA-IS-DEFAULT-ICON+" #x80009031)
  (:const "+ICONGETA-REMAP-ICON+" #x80009032)
  (:const "+ICONGETA-GENERATE-IMAGE-MASKS+" #x80009033)
  (:const "+ICONGETA-LABEL+" #x80009034)
  (:const "+ICONGETA-SCREEN+" #x80009045)
  (:const "+ICONGETA-IDENTIFY-BUFFER+" #x8000907A)
  (:const "+ICONGETA-IDENTIFY-ONLY+" #x8000907B)
  (:const "+ICONPUTA-NOTIFY-WORKBENCH+" #x80009035)
  (:const "+ICONPUTA-PUT-DEFAULT-TYPE+" #x80009036)
  (:const "+ICONPUTA-PUT-DEFAULT-NAME+" #x80009037)
  (:const "+ICONPUTA-DROP-PLANAR-ICON-IMAGE+" #x80009038)
  (:const "+ICONPUTA-DROP-CHUNKY-ICON-IMAGE+" #x80009039)
  (:const "+ICONPUTA-DROP-NEW-ICON-TOOL-TYPES+" #x8000903A)
  (:const "+ICONPUTA-OPTIMIZE-IMAGE-SPACE+" #x8000903B)
  (:const "+ICONPUTA-ONLY-UPDATE-POSITION+" #x80009048)
  (:const "+ICONPUTA-PRESERVE-OLD-ICON-IMAGES+" #x80009054)
  (:const "+ICONDUPA-DUPLICATE-DRAWER-DATA+" #x8000903C)
  (:const "+ICONDUPA-DUPLICATE-IMAGES+" #x8000903D)
  (:const "+ICONDUPA-DUPLICATE-IMAGE-DATA+" #x8000903E)
  (:const "+ICONDUPA-DUPLICATE-DEFAULT-TOOL+" #x8000903F)
  (:const "+ICONDUPA-DUPLICATE-TOOL-TYPES+" #x80009040)
  (:const "+ICONDUPA-DUPLICATE-TOOL-WINDOW+" #x80009041)
  (:const "+ICONDUPA-ACTIVATE-IMAGE-DATA+" #x80009052)
  (:const "+ICONDRAWA-DRAW-INFO+" #x80009042)
  (:const "+ICONDRAWA-FRAMELESS+" #x80009046)
  (:const "+ICONDRAWA-ERASE-BACKGROUND+" #x80009047)
  (:const "+ICONDRAWA-BORDERLESS+" #x80009053)
  (:const "+ICONDRAWA-IS-LINK+" #x80009059)
  (:const "+ICONDRAWA-LABEL-SHADOW+" #x8000905D)
  (:const "+ICONDRAWA-LABEL-OUTLINE+" #x8000905E)

  ;; --- structures from workbench/icon.i ---
  (:struct "ICON-IDENTIFY-MSG" 36   ; IconIdentifyMsg (workbench/icon.i)
    ("SYS-BASE" :fptr 0)
    ("DOS-BASE" :fptr 4)
    ("UTILITY-BASE" :fptr 8)
    ("ICON-BASE" :fptr 12)
    ("FILE-LOCK" :u32 16)
    ("PARENT-LOCK" :u32 20)
    ("FIB" :fptr 24)
    ("FILE-HANDLE" :u32 28)
    ("TAGS" :fptr 32)
    )

  ;; --- functions (icon_lib.sfd + MorphOS SDK) ---
  (:fn "FREE-FREE-LIST" -54 (:a0) :void)   ; VOID FreeFreeList(struct FreeList * freelist) (A0) LVO -54
  (:fn "ADD-FREE-LIST" -72 (:a0 :a1 :a2) :bool)   ; BOOL AddFreeList(struct FreeList * freelist, CONST_APTR mem, ULONG size) (A0,A1,A2) LVO -72
  (:fn "GET-DISK-OBJECT" -78 (:a0) :pointer)   ; struct DiskObject * GetDiskObject(CONST_STRPTR name) (A0) LVO -78
  (:fn "PUT-DISK-OBJECT" -84 (:a0 :a1) :bool)   ; BOOL PutDiskObject(CONST_STRPTR name, CONST struct DiskObject * diskobj) (A0,A1) LVO -84
  (:fn "FREE-DISK-OBJECT" -90 (:a0) :void)   ; VOID FreeDiskObject(struct DiskObject * diskobj) (A0) LVO -90
  (:fn "FIND-TOOL-TYPE" -96 (:a0 :a1) :pointer)   ; UBYTE * FindToolType(CONST_STRPTR * toolTypeArray, CONST_STRPTR typeName) (A0,A1) LVO -96
  (:fn "MATCH-TOOL-VALUE" -102 (:a0 :a1) :bool)   ; BOOL MatchToolValue(CONST_STRPTR typeString, CONST_STRPTR value) (A0,A1) LVO -102
  (:fn "BUMP-REVISION" -108 (:a0 :a1) :pointer)   ; STRPTR BumpRevision(STRPTR newname, CONST_STRPTR oldname) (A0,A1) LVO -108
  (:fn "FREE-ALLOC" -114 (:a0 :a1 :a2) :pointer :not-morphos)   ; APTR FreeAlloc(struct FreeList * free, ULONG len, ULONG type) (A0,A1,A2) LVO -114
  (:fn "GET-DEF-DISK-OBJECT" -120 (:d0) :pointer)   ; struct DiskObject * GetDefDiskObject(LONG type) (D0) LVO -120
  (:fn "PUT-DEF-DISK-OBJECT" -126 (:a0) :bool)   ; BOOL PutDefDiskObject(CONST struct DiskObject * diskObject) (A0) LVO -126
  (:fn "GET-DISK-OBJECT-NEW" -132 (:a0) :pointer)   ; struct DiskObject * GetDiskObjectNew(CONST_STRPTR name) (A0) LVO -132
  (:fn "DELETE-DISK-OBJECT" -138 (:a0) :bool)   ; BOOL DeleteDiskObject(CONST_STRPTR name) (A0) LVO -138
  (:fn "FREE-FREE" -144 (:a0 :a1) :void :not-morphos 44)   ; VOID FreeFree(struct FreeList * fl, APTR address) (A0,A1) LVO -144
  (:fn "DUP-DISK-OBJECT-A" -150 (:a0 :a1) :pointer 44)   ; struct DiskObject * DupDiskObjectA(CONST struct DiskObject * diskObject, CONST struct TagItem * tags) (A0,A1) LVO -150
  (:fn "ICON-CONTROL-A" -156 (:a0 :a1) :unsigned 44)   ; ULONG IconControlA(struct DiskObject * icon, CONST struct TagItem * tags) (A0,A1) LVO -156
  (:fn "DRAW-ICON-STATE-A" -162 (:a0 :a1 :a2 :d0 :d1 :d2 :a3) :void 44)   ; VOID DrawIconStateA(struct RastPort * rp, CONST struct DiskObject * icon, CONST_STRPTR label, LONG leftOffset, LONG topOffset, ULONG state, CONST struct TagItem * tags) (A0,A1,A2,D0,D1,D2,A3) LVO -162
  (:fn "GET-ICON-RECTANGLE-A" -168 (:a0 :a1 :a2 :a3 :a4) :bool 44)   ; BOOL GetIconRectangleA(struct RastPort * rp, CONST struct DiskObject * icon, CONST_STRPTR label, struct Rectangle * rect, CONST struct TagItem * tags) (A0,A1,A2,A3,A4) LVO -168
  (:fn "NEW-DISK-OBJECT" -174 (:d0) :pointer 44)   ; struct DiskObject * NewDiskObject(LONG type) (D0) LVO -174
  (:fn "GET-ICON-TAG-LIST" -180 (:a0 :a1) :pointer 44)   ; struct DiskObject * GetIconTagList(CONST_STRPTR name, CONST struct TagItem * tags) (A0,A1) LVO -180
  (:fn "PUT-ICON-TAG-LIST" -186 (:a0 :a1 :a2) :bool 44)   ; BOOL PutIconTagList(CONST_STRPTR name, CONST struct DiskObject * icon, CONST struct TagItem * tags) (A0,A1,A2) LVO -186
  (:fn "LAYOUT-ICON-A" -192 (:a0 :a1 :a2) :bool 44)   ; BOOL LayoutIconA(struct DiskObject * icon, struct Screen * screen, struct TagItem * tags) (A0,A1,A2) LVO -192
  (:fn "CHANGE-TO-SELECTED-ICON-COLOR" -198 (:a0) :void 44)   ; VOID ChangeToSelectedIconColor(struct ColorRegister * cr) (A0) LVO -198
  (:fn "BUMP-REVISION-LENGTH" -204 (:a0 :a1 :d0) :pointer :not-morphos 44)   ; STRPTR BumpRevisionLength(STRPTR newname, CONST_STRPTR oldname, ULONG maxLength) (A0,A1,D0) LVO -204
  )

(provide "amiga/raw/icon")
