;;; amiga/raw/input  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   input_lib.sfd ($VER: input_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK input_lib.fd + clib/input_protos.h (via fd2sfd)
;;;   devices/input.i
;;;
;;; 1 functions, 9 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.INPUT"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export "*INPUT-BASE*" "*INPUT-VERSION*"))

(in-package "AMIGA.RAW.INPUT")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
;;; input.device is a device/resource: there is no OpenLibrary.  Set the base
;;; yourself (IORequest io_Device after OpenDevice, or OpenResource).
(defvar *input-base* nil)
(defvar *input-version*
  (and *input-base* (amiga.ffi:library-version *input-base*)))
(defun %version>= (n)
  (and *input-version* (>= *input-version* n)))

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.INPUT"
    (:base *input-base* :version *input-version*)

  ;; --- constants from devices/input.i ---
  (:const "+IND-ADDHANDLER+" 9)
  (:const "+IND-REMHANDLER+" 10)
  (:const "+IND-WRITEEVENT+" 11)
  (:const "+IND-SETTHRESH+" 12)
  (:const "+IND-SETPERIOD+" 13)
  (:const "+IND-SETMPORT+" 14)
  (:const "+IND-SETMTYPE+" 15)
  (:const "+IND-SETMTRIG+" #x10)
  (:const "+IND-ADDEVENT+" #x18)

  ;; --- functions (input_lib.sfd + MorphOS SDK) ---
  (:fn "PEEK-QUALIFIER" -42 () :u16)   ; UWORD PeekQualifier() () LVO -42
  )

(provide "amiga/raw/input")
