;;; amiga/raw/integer  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   integer_lib.sfd ($VER: integer_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK integer_lib.fd + clib/integer_protos.h (via fd2sfd)
;;;
;;; 1 functions, 0 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.INTEGER"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*INTEGER-BASE*" "*INTEGER-VERSION*"
   "INTEGER-GET-CLASS" ))

(in-package "AMIGA.RAW.INTEGER")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *integer-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/integer.gadget" 0)))
(defvar *integer-version*
  (and *integer-base* (amiga.ffi:library-version *integer-base*)))
(defun %version>= (n)
  (and *integer-version* (>= *integer-version* n)))

;;; --- functions (integer_lib.sfd + MorphOS SDK) ---
(when (%version>= 40)
  (amiga.ffi:defcfun integer-get-class *integer-base* -30 ()
    :result :pointer
    :doc "Class * INTEGER_GetClass() () LVO -30"))

(provide "amiga/raw/integer")
