;;; amiga/raw/keymap  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   keymap_lib.sfd ($VER: keymap_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK keymap_lib.fd + clib/keymap_protos.h (via fd2sfd)
;;;   devices/keymap.i
;;;
;;; 9 functions, 22 constants, 3 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.KEYMAP"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*KEYMAP-BASE*" "*KEYMAP-VERSION*"
   "+KCB-NOP+" "+KCF-NOP+" "+KC-NOQUAL+" "+KC-VANILLA+" "+KCB-SHIFT+" 
   "+KCF-SHIFT+" "+KCB-ALT+" "+KCF-ALT+" "+KCB-CONTROL+" "+KCF-CONTROL+" 
   "+KCB-DOWNUP+" "+KCF-DOWNUP+" "+KCB-DEAD+" "+KCF-DEAD+" "+KCB-STRING+" 
   "+KCF-STRING+" "+DPB-MOD+" "+DPF-MOD+" "+DPB-DEAD+" "+DPF-DEAD+" 
   "+DP-2-DINDEXMASK+" "+DP-2-DFACSHIFT+" "*KEY-MAP-SIZE*" 
   "KEY-MAP-LO-KEY-MAP-TYPES" "KEY-MAP-LO-KEY-MAP" "KEY-MAP-LO-CAPSABLE" 
   "KEY-MAP-LO-REPEATABLE" "KEY-MAP-HI-KEY-MAP-TYPES" "KEY-MAP-HI-KEY-MAP" 
   "KEY-MAP-HI-CAPSABLE" "KEY-MAP-HI-REPEATABLE" "*KEY-MAP-NODE-SIZE*" 
   "KEY-MAP-NODE-NODE" "KEY-MAP-NODE-KEY-MAP" "*KEY-MAP-RESOURCE-SIZE*" 
   "KEY-MAP-RESOURCE-NODE" "KEY-MAP-RESOURCE-LIST" "SET-KEY-MAP-DEFAULT" 
   "ASK-KEY-MAP-DEFAULT" "MAP-RAW-KEY" "MAP-ANSI" "MAP-RAW-KEY-UCS4" 
   "MAP-UCS4" "TO-ANSI" "TO-UCS4" "GET-KEY-MAP-CODEPAGE" ))

(in-package "AMIGA.RAW.KEYMAP")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *keymap-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "keymap.library" 0)))
(defvar *keymap-version*
  (and *keymap-base* (amiga.ffi:library-version *keymap-base*)))
(defun %version>= (n)
  (and *keymap-version* (>= *keymap-version* n)))

;;; --- constants from devices/keymap.i ---
(defconstant +kcb-nop+ 7)
(defconstant +kcf-nop+ #x80)
(defconstant +kc-noqual+ 0)
(defconstant +kc-vanilla+ 7)
(defconstant +kcb-shift+ 0)
(defconstant +kcf-shift+ 1)
(defconstant +kcb-alt+ 1)
(defconstant +kcf-alt+ 2)
(defconstant +kcb-control+ 2)
(defconstant +kcf-control+ 4)
(defconstant +kcb-downup+ 3)
(defconstant +kcf-downup+ 8)
(defconstant +kcb-dead+ 5)
(defconstant +kcf-dead+ #x20)
(defconstant +kcb-string+ 6)
(defconstant +kcf-string+ #x40)
(defconstant +dpb-mod+ 0)
(defconstant +dpf-mod+ 1)
(defconstant +dpb-dead+ 3)
(defconstant +dpf-dead+ 8)
(defconstant +dp-2-dindexmask+ 15)
(defconstant +dp-2-dfacshift+ 4)

;;; --- structures from devices/keymap.i ---
(ffi:defcstruct (key-map :size 32)   ; KeyMap (devices/keymap.i)
  (lo-key-map-types :fptr 0)
  (lo-key-map :fptr 4)
  (lo-capsable :fptr 8)
  (lo-repeatable :fptr 12)
  (hi-key-map-types :fptr 16)
  (hi-key-map :fptr 20)
  (hi-capsable :fptr 24)
  (hi-repeatable :fptr 28)
)
(ffi:defcstruct (key-map-node :size 46)   ; KeyMapNode (devices/keymap.i)
  (node (:struct 14) 0)
  (key-map (:struct 32) 14)
)
(ffi:defcstruct (key-map-resource :size 28)   ; KeyMapResource (devices/keymap.i)
  (node (:struct 14) 0)
  (list (:struct 14) 14)
)

;;; --- functions (keymap_lib.sfd + MorphOS SDK) ---
(amiga.ffi:defcfun set-key-map-default *keymap-base* -30 (:a0 key-map)
    :result :void
    :doc "VOID SetKeyMapDefault(struct KeyMap * keyMap) (A0) LVO -30")
(amiga.ffi:defcfun ask-key-map-default *keymap-base* -36 ()
    :result :pointer
    :doc "struct KeyMap * AskKeyMapDefault() () LVO -36")
(amiga.ffi:defcfun map-raw-key *keymap-base* -42 (:a0 event :a1 buffer :d1 length :a2 key-map)
    :result :i16
    :doc "WORD MapRawKey(CONST struct InputEvent * event, STRPTR buffer, WORD length, CONST struct KeyMap * keyMap) (A0,A1,D1,A2) LVO -42")
(amiga.ffi:defcfun map-ansi *keymap-base* -48 (:a0 string :d0 count :a1 buffer :d1 length :a2 key-map)
    :result :signed
    :doc "LONG MapANSI(CONST_STRPTR string, LONG count, STRPTR buffer, LONG length, CONST struct KeyMap * keyMap) (A0,D0,A1,D1,A2) LVO -48")
(when (member :morphos *features*)
  (amiga.ffi:defcfun map-raw-key-ucs4 *keymap-base* -54 (:a0 event :a1 buffer :d1 length :a2 key-map)
    :result :i16
    :doc "WORD MapRawKeyUCS4(CONST struct InputEvent * event, WSTRPTR buffer, LONG length, CONST struct KeyMap * keyMap) (A0,A1,D1,A2) LVO -54"))
(when (member :morphos *features*)
  (amiga.ffi:defcfun map-ucs4 *keymap-base* -60 (:a0 string :d0 count :a1 buffer :d1 length :a2 key-map)
    :result :signed
    :doc "LONG MapUCS4(CONST_WSTRPTR string, LONG count, STRPTR buffer, LONG length, CONST struct KeyMap * keyMap) (A0,D0,A1,D1,A2) LVO -60"))
(when (member :morphos *features*)
  (amiga.ffi:defcfun to-ansi *keymap-base* -66 (:a0 ucs4char :a1 key-map)
    :result :unsigned
    :doc "char ToANSI(WCHAR ucs4char, CONST struct KeyMap * keyMap) (A0,A1) LVO -66"))
(when (member :morphos *features*)
  (amiga.ffi:defcfun to-ucs4 *keymap-base* -72 (:a0 asciichar :a1 key-map)
    :result :unsigned
    :doc "WCHAR ToUCS4(char asciichar, CONST struct KeyMap * keyMap) (A0,A1) LVO -72"))
(when (member :morphos *features*)
  (amiga.ffi:defcfun get-key-map-codepage *keymap-base* -78 (:a0 key-map)
    :result :pointer
    :doc "CONST_STRPTR GetKeyMapCodepage(CONST struct KeyMap * keyMap) (A0) LVO -78"))

(provide "amiga/raw/keymap")
