;;; amiga/raw/listview  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   listview_lib.sfd ($VER: listview_lib.sfd 47.1 (30.11.2021))
;;;
;;; 1 functions, 0 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.LISTVIEW"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*LISTVIEW-BASE*" "*LISTVIEW-VERSION*"
   "LISTVIEW-GET-CLASS" ))

(in-package "AMIGA.RAW.LISTVIEW")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *listview-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/listview.gadget" 0)))
(defvar *listview-version*
  (and *listview-base* (amiga.ffi:library-version *listview-base*)))
(defun %version>= (n)
  (and *listview-version* (>= *listview-version* n)))

;;; --- functions (listview_lib.sfd) ---
(when (%version>= 40)
  (amiga.ffi:defcfun listview-get-class *listview-base* -30 ()
    :result :pointer
    :doc "Class * LISTVIEW_GetClass() () LVO -30"))

(provide "amiga/raw/listview")
