;;; amiga/raw/lowlevel  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   lowlevel_lib.sfd ($VER: lowlevel_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK lowlevel_lib.fd + clib/lowlevel_protos.h (via fd2sfd)
;;;   libraries/lowlevel.i
;;;
;;; 15 functions, 151 constants, 1 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.LOWLEVEL"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export "*LOWLEVEL-BASE*" "*LOWLEVEL-VERSION*"))

(in-package "AMIGA.RAW.LOWLEVEL")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *lowlevel-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "lowlevel.library" 0)))
(defvar *lowlevel-version*
  (and *lowlevel-base* (amiga.ffi:library-version *lowlevel-base*)))
(defun %version>= (n)
  (and *lowlevel-version* (>= *lowlevel-version* n)))

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.LOWLEVEL"
    (:base *lowlevel-base* :version *lowlevel-version*)

  ;; --- constants from libraries/lowlevel.i ---
  (:const "+LLKB-LSHIFT+" #x10)
  (:const "+LLKF-LSHIFT+" #x10000)
  (:const "+LLKB-RSHIFT+" #x11)
  (:const "+LLKF-RSHIFT+" #x20000)
  (:const "+LLKB-CAPSLOCK+" #x12)
  (:const "+LLKF-CAPSLOCK+" #x40000)
  (:const "+LLKB-CONTROL+" #x13)
  (:const "+LLKF-CONTROL+" #x80000)
  (:const "+LLKB-LALT+" #x14)
  (:const "+LLKF-LALT+" #x100000)
  (:const "+LLKB-RALT+" #x15)
  (:const "+LLKF-RALT+" #x200000)
  (:const "+LLKB-LAMIGA+" #x16)
  (:const "+LLKF-LAMIGA+" #x400000)
  (:const "+LLKB-RAMIGA+" #x17)
  (:const "+LLKF-RAMIGA+" #x800000)
  (:const "+SJA-DUMMY+" #x80C00100)
  (:const "+SJA-TYPE+" #x80C00101)
  (:const "+SJA-REINITIALIZE+" #x80C00102)
  (:const "+SJA-TYPE-AUTOSENSE+" 0)
  (:const "+SJA-TYPE-GAMECTLR+" 1)
  (:const "+SJA-TYPE-MOUSE+" 2)
  (:const "+SJA-TYPE-JOYSTK+" 3)
  (:const "+JP-TYPE-NOTAVAIL+" 0)
  (:const "+JP-TYPE-GAMECTLR+" #x10000000)
  (:const "+JP-TYPE-MOUSE+" #x20000000)
  (:const "+JP-TYPE-JOYSTK+" #x30000000)
  (:const "+JP-TYPE-UNKNOWN+" #x40000000)
  (:const "+JP-TYPE-MASK+" #xF0000000)
  (:const "+JPB-BUTTON-BLUE+" #x17)
  (:const "+JPF-BUTTON-BLUE+" #x800000)
  (:const "+JPB-BUTTON-RED+" #x16)
  (:const "+JPF-BUTTON-RED+" #x400000)
  (:const "+JPB-BUTTON-YELLOW+" #x15)
  (:const "+JPF-BUTTON-YELLOW+" #x200000)
  (:const "+JPB-BUTTON-GREEN+" #x14)
  (:const "+JPF-BUTTON-GREEN+" #x100000)
  (:const "+JPB-BUTTON-FORWARD+" #x13)
  (:const "+JPF-BUTTON-FORWARD+" #x80000)
  (:const "+JPB-BUTTON-REVERSE+" #x12)
  (:const "+JPF-BUTTON-REVERSE+" #x40000)
  (:const "+JPB-BUTTON-PLAY+" #x11)
  (:const "+JPF-BUTTON-PLAY+" #x20000)
  (:const "+JP-BUTTON-MASK+" #xFE0000)
  (:const "+JPB-JOY-UP+" 3)
  (:const "+JPF-JOY-UP+" 8)
  (:const "+JPB-JOY-DOWN+" 2)
  (:const "+JPF-JOY-DOWN+" 4)
  (:const "+JPB-JOY-LEFT+" 1)
  (:const "+JPF-JOY-LEFT+" 2)
  (:const "+JPB-JOY-RIGHT+" 0)
  (:const "+JPF-JOY-RIGHT+" 1)
  (:const "+JP-DIRECTION-MASK+" 15)
  (:const "+JP-MHORZ-MASK+" #xFF)
  (:const "+JP-MVERT-MASK+" #xFF00)
  (:const "+JP-MOUSE-MASK+" #xFFFF)
  (:const "+JPB-BTN1+" #x17)
  (:const "+JPF-BTN1+" #x800000)
  (:const "+JPB-BTN2+" #x16)
  (:const "+JPF-BTN2+" #x400000)
  (:const "+JPB-BTN3+" #x15)
  (:const "+JPF-BTN3+" #x200000)
  (:const "+JPB-BTN4+" #x14)
  (:const "+JPF-BTN4+" #x100000)
  (:const "+JPB-BTN5+" #x13)
  (:const "+JPF-BTN5+" #x80000)
  (:const "+JPB-BTN6+" #x12)
  (:const "+JPF-BTN6+" #x40000)
  (:const "+JPB-BTN7+" #x11)
  (:const "+JPF-BTN7+" #x20000)
  (:const "+JPB-UP+" 3)
  (:const "+JPF-UP+" 8)
  (:const "+JPB-DOWN+" 2)
  (:const "+JPF-DOWN+" 4)
  (:const "+JPB-LEFT+" 1)
  (:const "+JPF-LEFT+" 2)
  (:const "+JPB-RIGHT+" 0)
  (:const "+JPF-RIGHT+" 1)
  (:const "+SCON-DUMMY+" #x80C00000)
  (:const "+SCON-TAKE-OVER-SYS+" #x80C00000)
  (:const "+SCON-KILL-REQ+" #x80C00001)
  (:const "+SCON-CD-REBOOT+" #x80C00002)
  (:const "+SCON-STOP-INPUT+" #x80C00003)
  (:const "+SCON-ADD-CREATE-KEYS+" #x80C00004)
  (:const "+SCON-REM-CREATE-KEYS+" #x80C00005)
  (:const "+CD-REBOOT-ON+" 1)
  (:const "+CD-REBOOT-OFF+" 0)
  (:const "+CD-REBOOT-DEFAULT+" 2)
  (:const "+RAWKEY-PORT0-BUTTON-BLUE+" #x72)
  (:const "+RAWKEY-PORT0-BUTTON-RED+" #x78)
  (:const "+RAWKEY-PORT0-BUTTON-YELLOW+" #x77)
  (:const "+RAWKEY-PORT0-BUTTON-GREEN+" #x76)
  (:const "+RAWKEY-PORT0-BUTTON-FORWARD+" #x75)
  (:const "+RAWKEY-PORT0-BUTTON-REVERSE+" #x74)
  (:const "+RAWKEY-PORT0-BUTTON-PLAY+" #x73)
  (:const "+RAWKEY-PORT0-JOY-UP+" #x79)
  (:const "+RAWKEY-PORT0-JOY-DOWN+" #x7A)
  (:const "+RAWKEY-PORT0-JOY-LEFT+" #x7C)
  (:const "+RAWKEY-PORT0-JOY-RIGHT+" #x7B)
  (:const "+RAWKEY-PORT1-BUTTON-BLUE+" #x172)
  (:const "+RAWKEY-PORT1-BUTTON-RED+" #x178)
  (:const "+RAWKEY-PORT1-BUTTON-YELLOW+" #x177)
  (:const "+RAWKEY-PORT1-BUTTON-GREEN+" #x176)
  (:const "+RAWKEY-PORT1-BUTTON-FORWARD+" #x175)
  (:const "+RAWKEY-PORT1-BUTTON-REVERSE+" #x174)
  (:const "+RAWKEY-PORT1-BUTTON-PLAY+" #x173)
  (:const "+RAWKEY-PORT1-JOY-UP+" #x179)
  (:const "+RAWKEY-PORT1-JOY-DOWN+" #x17A)
  (:const "+RAWKEY-PORT1-JOY-LEFT+" #x17C)
  (:const "+RAWKEY-PORT1-JOY-RIGHT+" #x17B)
  (:const "+RAWKEY-PORT2-BUTTON-BLUE+" #x272)
  (:const "+RAWKEY-PORT2-BUTTON-RED+" #x278)
  (:const "+RAWKEY-PORT2-BUTTON-YELLOW+" #x277)
  (:const "+RAWKEY-PORT2-BUTTON-GREEN+" #x276)
  (:const "+RAWKEY-PORT2-BUTTON-FORWARD+" #x275)
  (:const "+RAWKEY-PORT2-BUTTON-REVERSE+" #x274)
  (:const "+RAWKEY-PORT2-BUTTON-PLAY+" #x273)
  (:const "+RAWKEY-PORT2-JOY-UP+" #x279)
  (:const "+RAWKEY-PORT2-JOY-DOWN+" #x27A)
  (:const "+RAWKEY-PORT2-JOY-LEFT+" #x27C)
  (:const "+RAWKEY-PORT2-JOY-RIGHT+" #x27B)
  (:const "+RAWKEY-PORT3-BUTTON-BLUE+" #x372)
  (:const "+RAWKEY-PORT3-BUTTON-RED+" #x378)
  (:const "+RAWKEY-PORT3-BUTTON-YELLOW+" #x377)
  (:const "+RAWKEY-PORT3-BUTTON-GREEN+" #x376)
  (:const "+RAWKEY-PORT3-BUTTON-FORWARD+" #x375)
  (:const "+RAWKEY-PORT3-BUTTON-REVERSE+" #x374)
  (:const "+RAWKEY-PORT3-BUTTON-PLAY+" #x373)
  (:const "+RAWKEY-PORT3-JOY-UP+" #x379)
  (:const "+RAWKEY-PORT3-JOY-DOWN+" #x37A)
  (:const "+RAWKEY-PORT3-JOY-LEFT+" #x37C)
  (:const "+RAWKEY-PORT3-JOY-RIGHT+" #x37B)
  (:const "+LANG-UNKNOWN+" 0)
  (:const "+LANG-AMERICAN+" 1)
  (:const "+LANG-ENGLISH+" 2)
  (:const "+LANG-GERMAN+" 3)
  (:const "+LANG-FRENCH+" 4)
  (:const "+LANG-SPANISH+" 5)
  (:const "+LANG-ITALIAN+" 6)
  (:const "+LANG-PORTUGUESE+" 7)
  (:const "+LANG-DANISH+" 8)
  (:const "+LANG-DUTCH+" 9)
  (:const "+LANG-NORWEGIAN+" 10)
  (:const "+LANG-FINNISH+" 11)
  (:const "+LANG-SWEDISH+" 12)
  (:const "+LANG-JAPANESE+" 13)
  (:const "+LANG-CHINESE+" 14)
  (:const "+LANG-ARABIC+" 15)
  (:const "+LANG-GREEK+" #x10)
  (:const "+LANG-HEBREW+" #x11)
  (:const "+LANG-KOREAN+" #x12)

  ;; --- structures from libraries/lowlevel.i ---
  (:struct "KEY-QUERY" 4   ; KeyQuery (libraries/lowlevel.i)
    ("KEY-CODE" :u16 0)
    ("PRESSED" :u16 2)
    )

  ;; --- functions (lowlevel_lib.sfd + MorphOS SDK) ---
  (:fn "READ-JOY-PORT" -30 (:d0) :unsigned 40)   ; ULONG ReadJoyPort(ULONG port) (D0) LVO -30
  (:fn "GET-LANGUAGE-SELECTION" -36 () :u8 40)   ; UBYTE GetLanguageSelection() () LVO -36
  (:fn "GET-KEY" -48 () :unsigned 40)   ; ULONG GetKey() () LVO -48
  (:fn "QUERY-KEYS" -54 (:a0 :d1) :void 40)   ; VOID QueryKeys(struct KeyQuery * queryArray, LONG arraySize) (A0,D1) LVO -54
  (:fn "ADD-KB-INT" -60 (:a0 :a1) :pointer 40)   ; APTR AddKBInt(APTR intRoutine, APTR intData) (A0,A1) LVO -60
  (:fn "REM-KB-INT" -66 (:a1) :void 40)   ; VOID RemKBInt(APTR intHandle) (A1) LVO -66
  (:fn "SYSTEM-CONTROL-A" -72 (:a1) :unsigned 40)   ; ULONG SystemControlA(CONST struct TagItem * tagList) (A1) LVO -72
  (:fn "ADD-TIMER-INT" -78 (:a0 :a1) :pointer 40)   ; APTR AddTimerInt(APTR intRoutine, APTR intData) (A0,A1) LVO -78
  (:fn "REM-TIMER-INT" -84 (:a1) :void 40)   ; VOID RemTimerInt(APTR intHandle) (A1) LVO -84
  (:fn "STOP-TIMER-INT" -90 (:a1) :void 40)   ; VOID StopTimerInt(APTR intHandle) (A1) LVO -90
  (:fn "START-TIMER-INT" -96 (:a1 :d0 :d1) :void 40)   ; VOID StartTimerInt(APTR intHandle, ULONG timeInterval, BOOL continuous) (A1,D0,D1) LVO -96
  (:fn "ELAPSED-TIME" -102 (:a0) :unsigned 40)   ; ULONG ElapsedTime(struct EClockVal * context) (A0) LVO -102
  (:fn "ADD-V-BLANK-INT" -108 (:a0 :a1) :pointer 40)   ; APTR AddVBlankInt(APTR intRoutine, APTR intData) (A0,A1) LVO -108
  (:fn "REM-V-BLANK-INT" -114 (:a1) :void 40)   ; VOID RemVBlankInt(APTR intHandle) (A1) LVO -114
  (:fn "SET-JOY-PORT-ATTRS-A" -132 (:d0 :a1) :bool 40)   ; BOOL SetJoyPortAttrsA(ULONG portNumber, CONST struct TagItem * tagList) (D0,A1) LVO -132
  )

(provide "amiga/raw/lowlevel")
