;;; amiga/raw/mathieeedoubbas  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   mathieeedoubbas_lib.sfd ($VER: mathieeedoubbas_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK mathieeedoubbas_lib.fd + clib/mathieeedoubbas_protos.h (via fd2sfd)
;;;   libraries/mathieeedp.h
;;;
;;; 3 functions, 0 constants, 0 structs, 20 skipped (see comments).
;;; 24 C macros skipped: not an integer constant (string, call, float).
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.MATHIEEEDOUBBAS"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*MATHIEEEDOUBBAS-BASE*" "*MATHIEEEDOUBBAS-VERSION*"
   "IEEEDP-FIX" "IEEEDP-CMP" "IEEEDP-TST" ))

(in-package "AMIGA.RAW.MATHIEEEDOUBBAS")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *mathieeedoubbas-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "mathieeedoubbas.library" 0)))
(defvar *mathieeedoubbas-version*
  (and *mathieeedoubbas-base* (amiga.ffi:library-version *mathieeedoubbas-base*)))
(defun %version>= (n)
  (and *mathieeedoubbas-version* (>= *mathieeedoubbas-version* n)))

;;; --- functions (mathieeedoubbas_lib.sfd + MorphOS SDK) ---
;; skipped IEEEDPFix: 64-bit register-pair argument
(when (member :morphos *features*)
  (amiga.ffi:defcfun ieeedp-fix *mathieeedoubbas-base* -30 (:d0 parm)
    :result :signed
    :doc "LONG IEEEDPFix(DOUBLE parm) (D0) LVO -30"))
;; skipped IEEEDPFlt: DOUBLE result (d0/d1 register pair)
;; skipped IEEEDPCmp: 64-bit register-pair argument
(when (member :morphos *features*)
  (amiga.ffi:defcfun ieeedp-cmp *mathieeedoubbas-base* -42 (:d0 left-parm :d2 right-parm)
    :result :signed
    :doc "LONG IEEEDPCmp(DOUBLE leftParm, DOUBLE rightParm) (D0,D2) LVO -42"))
;; skipped IEEEDPTst: 64-bit register-pair argument
(when (member :morphos *features*)
  (amiga.ffi:defcfun ieeedp-tst *mathieeedoubbas-base* -48 (:d0 parm)
    :result :signed
    :doc "LONG IEEEDPTst(DOUBLE parm) (D0) LVO -48"))
;; skipped IEEEDPAbs: DOUBLE result (d0/d1 register pair)
;; skipped IEEEDPAbs: DOUBLE result (d0/d1 register pair)
;; skipped IEEEDPNeg: DOUBLE result (d0/d1 register pair)
;; skipped IEEEDPNeg: DOUBLE result (d0/d1 register pair)
;; skipped IEEEDPAdd: DOUBLE result (d0/d1 register pair)
;; skipped IEEEDPAdd: DOUBLE result (d0/d1 register pair)
;; skipped IEEEDPSub: DOUBLE result (d0/d1 register pair)
;; skipped IEEEDPSub: DOUBLE result (d0/d1 register pair)
;; skipped IEEEDPMul: DOUBLE result (d0/d1 register pair)
;; skipped IEEEDPMul: DOUBLE result (d0/d1 register pair)
;; skipped IEEEDPDiv: DOUBLE result (d0/d1 register pair)
;; skipped IEEEDPDiv: DOUBLE result (d0/d1 register pair)
;; skipped IEEEDPFloor: DOUBLE result (d0/d1 register pair)
;; skipped IEEEDPFloor: DOUBLE result (d0/d1 register pair)
;; skipped IEEEDPCeil: DOUBLE result (d0/d1 register pair)
;; skipped IEEEDPCeil: DOUBLE result (d0/d1 register pair)

(provide "amiga/raw/mathieeedoubbas")
