;;; amiga/raw/mathffp  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   mathffp_lib.sfd ($VER: mathffp_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK mathffp_lib.fd + clib/mathffp_protos.h (via fd2sfd)
;;;   libraries/mathffp.h
;;;
;;; 12 functions, 0 constants, 0 structs.
;;; 26 C macros skipped: not an integer constant (string, call, float).
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.MATHFFP"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*MATHFFP-BASE*" "*MATHFFP-VERSION*"
   "SP-FIX" "SP-FLT" "SP-CMP" "SP-TST" "SP-ABS" "SP-NEG" "SP-ADD" "SP-SUB" 
   "SP-MUL" "SP-DIV" "SP-FLOOR" "SP-CEIL" ))

(in-package "AMIGA.RAW.MATHFFP")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *mathffp-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "mathffp.library" 0)))
(defvar *mathffp-version*
  (and *mathffp-base* (amiga.ffi:library-version *mathffp-base*)))
(defun %version>= (n)
  (and *mathffp-version* (>= *mathffp-version* n)))

;;; --- functions (mathffp_lib.sfd + MorphOS SDK) ---
(amiga.ffi:defcfun sp-fix *mathffp-base* -30 (:d0 parm)
    :result :signed
    :doc "LONG SPFix(FLOAT parm) (D0) LVO -30")
(amiga.ffi:defcfun sp-flt *mathffp-base* -36 (:d0 integer)
    :result :unsigned
    :doc "FLOAT SPFlt(LONG integer) (D0) LVO -36")
(amiga.ffi:defcfun sp-cmp *mathffp-base* -42 (:d1 left-parm :d0 right-parm)
    :result :signed
    :doc "LONG SPCmp(FLOAT leftParm, FLOAT rightParm) (D1,D0) LVO -42")
(amiga.ffi:defcfun sp-tst *mathffp-base* -48 (:d1 parm)
    :result :signed
    :doc "LONG SPTst(FLOAT parm) (D1) LVO -48")
(amiga.ffi:defcfun sp-abs *mathffp-base* -54 (:d0 parm)
    :result :unsigned
    :doc "FLOAT SPAbs(FLOAT parm) (D0) LVO -54")
(amiga.ffi:defcfun sp-neg *mathffp-base* -60 (:d0 parm)
    :result :unsigned
    :doc "FLOAT SPNeg(FLOAT parm) (D0) LVO -60")
(amiga.ffi:defcfun sp-add *mathffp-base* -66 (:d1 left-parm :d0 right-parm)
    :result :unsigned
    :doc "FLOAT SPAdd(FLOAT leftParm, FLOAT rightParm) (D1,D0) LVO -66")
(amiga.ffi:defcfun sp-sub *mathffp-base* -72 (:d1 left-parm :d0 right-parm)
    :result :unsigned
    :doc "FLOAT SPSub(FLOAT leftParm, FLOAT rightParm) (D1,D0) LVO -72")
(amiga.ffi:defcfun sp-mul *mathffp-base* -78 (:d1 left-parm :d0 right-parm)
    :result :unsigned
    :doc "FLOAT SPMul(FLOAT leftParm, FLOAT rightParm) (D1,D0) LVO -78")
(amiga.ffi:defcfun sp-div *mathffp-base* -84 (:d1 left-parm :d0 right-parm)
    :result :unsigned
    :doc "FLOAT SPDiv(FLOAT leftParm, FLOAT rightParm) (D1,D0) LVO -84")
(amiga.ffi:defcfun sp-floor *mathffp-base* -90 (:d0 parm)
    :result :unsigned
    :doc "FLOAT SPFloor(FLOAT parm) (D0) LVO -90")
(amiga.ffi:defcfun sp-ceil *mathffp-base* -96 (:d0 parm)
    :result :unsigned
    :doc "FLOAT SPCeil(FLOAT parm) (D0) LVO -96")

(provide "amiga/raw/mathffp")
