;;; amiga/raw/mathieeesingtrans  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   mathieeesingtrans_lib.sfd ($VER: mathieeesingtrans_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK mathieeesingtrans_lib.fd + clib/mathieeesingtrans_protos.h (via fd2sfd)
;;;   libraries/mathieeesp.h
;;;
;;; 17 functions, 0 constants, 0 structs.
;;; 24 C macros skipped: not an integer or ASCII-string constant (call, float, non-ASCII).
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.MATHIEEESINGTRANS"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export "*MATHIEEESINGTRANS-BASE*" "*MATHIEEESINGTRANS-VERSION*"))

(in-package "AMIGA.RAW.MATHIEEESINGTRANS")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *mathieeesingtrans-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "mathieeesingtrans.library" 0)))
(defvar *mathieeesingtrans-version*
  (and *mathieeesingtrans-base* (amiga.ffi:library-version *mathieeesingtrans-base*)))
(defun %version>= (n)
  (and *mathieeesingtrans-version* (>= *mathieeesingtrans-version* n)))

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.MATHIEEESINGTRANS"
    (:base *mathieeesingtrans-base* :version *mathieeesingtrans-version*)

  ;; --- functions (mathieeesingtrans_lib.sfd + MorphOS SDK) ---
  (:fn "IEEESP-ATAN" -30 (:d0) :unsigned)   ; FLOAT IEEESPAtan(FLOAT parm) (D0) LVO -30
  (:fn "IEEESP-SIN" -36 (:d0) :unsigned)   ; FLOAT IEEESPSin(FLOAT parm) (D0) LVO -36
  (:fn "IEEESP-COS" -42 (:d0) :unsigned)   ; FLOAT IEEESPCos(FLOAT parm) (D0) LVO -42
  (:fn "IEEESP-TAN" -48 (:d0) :unsigned)   ; FLOAT IEEESPTan(FLOAT parm) (D0) LVO -48
  (:fn "IEEESP-SINCOS" -54 (:a0 :d0) :unsigned)   ; FLOAT IEEESPSincos(FLOAT * cosptr, FLOAT parm) (A0,D0) LVO -54
  (:fn "IEEESP-SINH" -60 (:d0) :unsigned)   ; FLOAT IEEESPSinh(FLOAT parm) (D0) LVO -60
  (:fn "IEEESP-COSH" -66 (:d0) :unsigned)   ; FLOAT IEEESPCosh(FLOAT parm) (D0) LVO -66
  (:fn "IEEESP-TANH" -72 (:d0) :unsigned)   ; FLOAT IEEESPTanh(FLOAT parm) (D0) LVO -72
  (:fn "IEEESP-EXP" -78 (:d0) :unsigned)   ; FLOAT IEEESPExp(FLOAT parm) (D0) LVO -78
  (:fn "IEEESP-LOG" -84 (:d0) :unsigned)   ; FLOAT IEEESPLog(FLOAT parm) (D0) LVO -84
  (:fn "IEEESP-POW" -90 (:d1 :d0) :unsigned)   ; FLOAT IEEESPPow(FLOAT exp, FLOAT arg) (D1,D0) LVO -90
  (:fn "IEEESP-SQRT" -96 (:d0) :unsigned)   ; FLOAT IEEESPSqrt(FLOAT parm) (D0) LVO -96
  (:fn "IEEESP-TIEEE" -102 (:d0) :unsigned)   ; FLOAT IEEESPTieee(FLOAT parm) (D0) LVO -102
  (:fn "IEEESP-FIEEE" -108 (:d0) :unsigned)   ; FLOAT IEEESPFieee(FLOAT parm) (D0) LVO -108
  (:fn "IEEESP-ASIN" -114 (:d0) :unsigned)   ; FLOAT IEEESPAsin(FLOAT parm) (D0) LVO -114
  (:fn "IEEESP-ACOS" -120 (:d0) :unsigned)   ; FLOAT IEEESPAcos(FLOAT parm) (D0) LVO -120
  (:fn "IEEESP-LOG10" -126 (:d0) :unsigned)   ; FLOAT IEEESPLog10(FLOAT parm) (D0) LVO -126
  )

(provide "amiga/raw/mathieeesingtrans")
