;;; amiga/raw/potgo  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   potgo_lib.sfd ($VER: potgo_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK potgo_lib.fd + clib/potgo_protos.h (via fd2sfd)
;;;   resources/potgo.i
;;;
;;; 3 functions, 1 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.POTGO"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*POTGO-BASE*" "*POTGO-VERSION*"
   "+RESOURCES-POTGO-I+" "ALLOC-POT-BITS" "FREE-POT-BITS" "WRITE-POTGO" ))

(in-package "AMIGA.RAW.POTGO")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
;;; potgo.resource is a device/resource: there is no OpenLibrary.  Set the base
;;; yourself (IORequest io_Device after OpenDevice, or OpenResource).
(defvar *potgo-base* nil)
(defvar *potgo-version*
  (and *potgo-base* (amiga.ffi:library-version *potgo-base*)))
(defun %version>= (n)
  (and *potgo-version* (>= *potgo-version* n)))

;;; --- constants from resources/potgo.i ---
(defconstant +resources-potgo-i+ 1)

;;; --- functions (potgo_lib.sfd + MorphOS SDK) ---
(amiga.ffi:defcfun alloc-pot-bits *potgo-base* -6 (:d0 bits)
    :result :u16
    :doc "UWORD AllocPotBits(UWORD bits) (D0) LVO -6")
(amiga.ffi:defcfun free-pot-bits *potgo-base* -12 (:d0 bits)
    :result :void
    :doc "VOID FreePotBits(UWORD bits) (D0) LVO -12")
(amiga.ffi:defcfun write-potgo *potgo-base* -18 (:d0 word :d1 mask)
    :result :void
    :doc "VOID WritePotgo(UWORD word, UWORD mask) (D0,D1) LVO -18")

(provide "amiga/raw/potgo")
