;;; amiga/raw/radiobutton  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   radiobutton_lib.sfd ($VER: radiobutton_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK radiobutton_lib.fd + clib/radiobutton_protos.h (via fd2sfd)
;;;
;;; 5 functions, 0 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.RADIOBUTTON"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*RADIOBUTTON-BASE*" "*RADIOBUTTON-VERSION*"
   "RADIOBUTTON-GET-CLASS" "ALLOC-RADIO-BUTTON-NODE-A" 
   "FREE-RADIO-BUTTON-NODE" "SET-RADIO-BUTTON-NODE-ATTRS-A" 
   "GET-RADIO-BUTTON-NODE-ATTRS-A" ))

(in-package "AMIGA.RAW.RADIOBUTTON")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *radiobutton-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/radiobutton.gadget" 0)))
(defvar *radiobutton-version*
  (and *radiobutton-base* (amiga.ffi:library-version *radiobutton-base*)))
(defun %version>= (n)
  (and *radiobutton-version* (>= *radiobutton-version* n)))

;;; --- functions (radiobutton_lib.sfd + MorphOS SDK) ---
(when (%version>= 40)
  (amiga.ffi:defcfun radiobutton-get-class *radiobutton-base* -30 ()
    :result :pointer
    :doc "Class * RADIOBUTTON_GetClass() () LVO -30"))
(when (%version>= 40)
  (amiga.ffi:defcfun alloc-radio-button-node-a *radiobutton-base* -36 (:d0 columns :a0 tags)
    :result :pointer
    :doc "struct Node * AllocRadioButtonNodeA(ULONG columns, struct TagItem * tags) (D0,A0) LVO -36"))
(when (%version>= 40)
  (amiga.ffi:defcfun free-radio-button-node *radiobutton-base* -42 (:a0 node)
    :result :void
    :doc "VOID FreeRadioButtonNode(struct Node * node) (A0) LVO -42"))
(when (%version>= 40)
  (amiga.ffi:defcfun set-radio-button-node-attrs-a *radiobutton-base* -48 (:a0 node :a1 tags)
    :result :void
    :doc "VOID SetRadioButtonNodeAttrsA(struct Node * node, struct TagItem * tags) (A0,A1) LVO -48"))
(when (%version>= 40)
  (amiga.ffi:defcfun get-radio-button-node-attrs-a *radiobutton-base* -54 (:a0 node :a1 tags)
    :result :void
    :doc "VOID GetRadioButtonNodeAttrsA(struct Node * node, struct TagItem * tags) (A0,A1) LVO -54"))

(provide "amiga/raw/radiobutton")
