;;; amiga/raw/slider  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   slider_lib.sfd ($VER: slider_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK slider_lib.fd + clib/slider_protos.h (via fd2sfd)
;;;
;;; 1 functions, 0 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.SLIDER"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*SLIDER-BASE*" "*SLIDER-VERSION*"
   "SLIDER-GET-CLASS" ))

(in-package "AMIGA.RAW.SLIDER")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *slider-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/slider.gadget" 0)))
(defvar *slider-version*
  (and *slider-base* (amiga.ffi:library-version *slider-base*)))
(defun %version>= (n)
  (and *slider-version* (>= *slider-version* n)))

;;; --- functions (slider_lib.sfd + MorphOS SDK) ---
(when (%version>= 40)
  (amiga.ffi:defcfun slider-get-class *slider-base* -30 ()
    :result :pointer
    :doc "Class * SLIDER_GetClass() () LVO -30"))

(provide "amiga/raw/slider")
