;;; amiga/raw/timer  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   timer_lib.sfd ($VER: timer_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK timer_lib.fd + clib/timer_protos.h (via fd2sfd)
;;;   devices/timer.i
;;;
;;; 5 functions, 8 constants, 3 structs, 3 skipped (see comments).
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.TIMER"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*TIMER-BASE*" "*TIMER-VERSION*"
   "+UNIT-MICROHZ+" "+UNIT-VBLANK+" "+UNIT-ECLOCK+" "+UNIT-WAITUNTIL+" 
   "+UNIT-WAITECLOCK+" "+TR-ADDREQUEST+" "+TR-GETSYSTIME+" 
   "+TR-SETSYSTIME+" "*TIMEVAL-SIZE*" "TIMEVAL-SECS" "TIMEVAL-MICRO" 
   "*ECLOCKVAL-SIZE*" "ECLOCKVAL-HI" "ECLOCKVAL-LO" "*TIMEREQUEST-SIZE*" 
   "TIMEREQUEST-TIME" "ADD-TIME" "SUB-TIME" "CMP-TIME" "READ-E-CLOCK" 
   "GET-SYS-TIME" ))

(in-package "AMIGA.RAW.TIMER")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
;;; timer.device is a device/resource: there is no OpenLibrary.  Set the base
;;; yourself (IORequest io_Device after OpenDevice, or OpenResource).
(defvar *timer-base* nil)
(defvar *timer-version*
  (and *timer-base* (amiga.ffi:library-version *timer-base*)))
(defun %version>= (n)
  (and *timer-version* (>= *timer-version* n)))

;;; --- constants from devices/timer.i ---
(defconstant +unit-microhz+ 0)
(defconstant +unit-vblank+ 1)
(defconstant +unit-eclock+ 2)
(defconstant +unit-waituntil+ 3)
(defconstant +unit-waiteclock+ 4)
(defconstant +tr-addrequest+ 9)
(defconstant +tr-getsystime+ 10)
(defconstant +tr-setsystime+ 11)

;;; --- structures from devices/timer.i ---
(ffi:defcstruct (timeval :size 8)   ; TIMEVAL (devices/timer.i)
  (secs :u32 0)
  (micro :u32 4)
)
(ffi:defcstruct (eclockval :size 8)   ; ECLOCKVAL (devices/timer.i)
  (hi :u32 0)
  (lo :u32 4)
)
(ffi:defcstruct (timerequest :size 40)   ; TIMEREQUEST (devices/timer.i)
  (time (:struct 8) 32)
)

;;; --- functions (timer_lib.sfd + MorphOS SDK) ---
(amiga.ffi:defcfun add-time *timer-base* -42 (:a0 dest :a1 src)
    :result :void
    :doc "VOID AddTime(TimeVal_Type * dest, CONST TimeVal_Type * src) (A0,A1) LVO -42")
(amiga.ffi:defcfun sub-time *timer-base* -48 (:a0 dest :a1 src)
    :result :void
    :doc "VOID SubTime(TimeVal_Type * dest, CONST TimeVal_Type * src) (A0,A1) LVO -48")
(amiga.ffi:defcfun cmp-time *timer-base* -54 (:a0 dest :a1 src)
    :result :signed
    :doc "LONG CmpTime(CONST TimeVal_Type * dest, CONST TimeVal_Type * src) (A0,A1) LVO -54")
(amiga.ffi:defcfun read-e-clock *timer-base* -60 (:a0 dest)
    :result :unsigned
    :doc "ULONG ReadEClock(struct EClockVal * dest) (A0) LVO -60")
(amiga.ffi:defcfun get-sys-time *timer-base* -66 (:a0 dest)
    :result :void
    :doc "VOID GetSysTime(TimeVal_Type * dest) (A0) LVO -66")
;; skipped ReadCPUClock: not a 68k register call (base,sysv)
;; skipped GetUpTime: not a 68k register call (base,sysv)
;; skipped GetUTCSysTime: not a 68k register call (base,sysv)

(provide "amiga/raw/timer")
