;;; amiga/raw/trackfile  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   trackfile_lib.sfd ($VER: trackfile_lib.sfd 2.3 (10.8.2020))
;;;   devices/trackfile.h
;;;
;;; 8 functions, 34 constants, 0 structs.
;;; 1 C macro skipped: not an integer constant (string, call, float).
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.TRACKFILE"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*TRACKFILE-BASE*" "*TRACKFILE-VERSION*"
   "+TFUNIT-CONTROL+" "+TFSU-NEXT-AVAILABLE-UNIT+" "+TFERROR-UNIT-BUSY+" 
   "+TFERROR-OUT-OF-MEMORY+" "+TFERROR-UNIT-NOT-FOUND+" 
   "+TFERROR-ALREADY-IN-USE+" "+TFERROR-UNIT-NOT-ACTIVE+" 
   "+TFERROR-INVALID-FILE+" "+TFERROR-INVALID-FILE-SIZE+" 
   "+TFERROR-NO-FILE-GIVEN+" "+TFERROR-ABORTED+" 
   "+TFERROR-INVALID-DRIVE-TYPE+" "+TFERROR-PROCESS-FAILED+" 
   "+TFERROR-NO-MEDIUM-PRESENT+" "+TFERROR-READ-ONLY-VOLUME+" 
   "+TFERROR-READ-ONLY-FILE+" "+TFERROR-DUPLICATE-DISK+" 
   "+TFERROR-DUPLICATE-VOLUME+" "+TFERROR-DENIED+" 
   "+TFERROR-NOT-SUPPORTED+" "+TF-DUMMY+" "+TF-IMAGE-FILE-NAME+" 
   "+TF-IMAGE-FILE-HANDLE+" "+TF-WRITE-PROTECTED+" "+TF-DRIVE-TYPE+" 
   "+TF-TIMEOUT+" "+TF-ENABLE-CHECKSUMS+" "+TF-TAG-ITEM-FAILED+" 
   "+TF-MAX-CACHE-MEMORY+" "+TF-ENABLE-UNIT-CACHE+" 
   "+TF-PREFILL-UNIT-CACHE+" "+TFGUD-ALL-UNITS+" "+TFEFS-UNSUPPORTED+" 
   "+TF-MINIMUM-CACHE-SIZE+" "TF-START-UNIT-TAG-LIST" 
   "TF-STOP-UNIT-TAG-LIST" "TF-INSERT-MEDIA-TAG-LIST" 
   "TF-EJECT-MEDIA-TAG-LIST" "TF-GET-UNIT-DATA" "TF-FREE-UNIT-DATA" 
   "TF-CHANGE-UNIT-TAG-LIST" "TF-EXAMINE-FILE-SIZE" ))

(in-package "AMIGA.RAW.TRACKFILE")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
;;; trackfile.device is a device/resource: there is no OpenLibrary.  Set the base
;;; yourself (IORequest io_Device after OpenDevice, or OpenResource).
(defvar *trackfile-base* nil)
(defvar *trackfile-version*
  (and *trackfile-base* (amiga.ffi:library-version *trackfile-base*)))
(defun %version>= (n)
  (and *trackfile-version* (>= *trackfile-version* n)))

;;; --- constants from devices/trackfile.h ---
(defconstant +tfunit-control+ -1)
(defconstant +tfsu-next-available-unit+ -1)
(defconstant +tferror-unit-busy+ -202041)
(defconstant +tferror-out-of-memory+ -202042)
(defconstant +tferror-unit-not-found+ -202043)
(defconstant +tferror-already-in-use+ -202044)
(defconstant +tferror-unit-not-active+ -202045)
(defconstant +tferror-invalid-file+ -202046)
(defconstant +tferror-invalid-file-size+ -202047)
(defconstant +tferror-no-file-given+ -202048)
(defconstant +tferror-aborted+ -202049)
(defconstant +tferror-invalid-drive-type+ -202050)
(defconstant +tferror-process-failed+ -202051)
(defconstant +tferror-no-medium-present+ -202052)
(defconstant +tferror-read-only-volume+ -202053)
(defconstant +tferror-read-only-file+ -202054)
(defconstant +tferror-duplicate-disk+ -202055)
(defconstant +tferror-duplicate-volume+ -202056)
(defconstant +tferror-denied+ -202057)
(defconstant +tferror-not-supported+ -202058)
(defconstant +tf-dummy+ #xA0200400)
(defconstant +tf-image-file-name+ #xA0200401)
(defconstant +tf-image-file-handle+ #xA0200402)
(defconstant +tf-write-protected+ #xA0200403)
(defconstant +tf-drive-type+ #xA0200404)
(defconstant +tf-timeout+ #xA0200405)
(defconstant +tf-enable-checksums+ #xA0200406)
(defconstant +tf-tag-item-failed+ #xA0200407)
(defconstant +tf-max-cache-memory+ #xA0200408)
(defconstant +tf-enable-unit-cache+ #xA0200409)
(defconstant +tf-prefill-unit-cache+ #xA020040A)
(defconstant +tfgud-all-units+ -1)
(defconstant +tfefs-unsupported+ -1)
(defconstant +tf-minimum-cache-size+ #xB3B0)

;;; --- functions (trackfile_lib.sfd) ---
(amiga.ffi:defcfun tf-start-unit-tag-list *trackfile-base* -42 (:d0 which-unit :a0 tags)
    :result :signed
    :doc "LONG TFStartUnitTagList(LONG which_unit, CONST struct TagItem * tags) (D0,A0) LVO -42")
(amiga.ffi:defcfun tf-stop-unit-tag-list *trackfile-base* -48 (:d0 which-unit :a0 tags)
    :result :signed
    :doc "LONG TFStopUnitTagList(LONG which_unit, CONST struct TagItem * tags) (D0,A0) LVO -48")
(amiga.ffi:defcfun tf-insert-media-tag-list *trackfile-base* -54 (:d0 which-unit :a0 tags)
    :result :signed
    :doc "LONG TFInsertMediaTagList(LONG which_unit, CONST struct TagItem * tags) (D0,A0) LVO -54")
(amiga.ffi:defcfun tf-eject-media-tag-list *trackfile-base* -60 (:d0 which-unit :a0 tags)
    :result :signed
    :doc "LONG TFEjectMediaTagList(LONG which_unit, CONST struct TagItem * tags) (D0,A0) LVO -60")
(amiga.ffi:defcfun tf-get-unit-data *trackfile-base* -66 (:d0 which-unit)
    :result :pointer
    :doc "struct TrackFileUnitData * TFGetUnitData(LONG which_unit) (D0) LVO -66")
(amiga.ffi:defcfun tf-free-unit-data *trackfile-base* -72 (:a0 tfud)
    :result :void
    :doc "VOID TFFreeUnitData(struct TrackFileUnitData * tfud) (A0) LVO -72")
(amiga.ffi:defcfun tf-change-unit-tag-list *trackfile-base* -78 (:d0 which-unit :a0 tags)
    :result :signed
    :doc "LONG TFChangeUnitTagList(LONG which_unit, CONST struct TagItem * tags) (D0,A0) LVO -78")
(amiga.ffi:defcfun tf-examine-file-size *trackfile-base* -84 (:d0 file-size)
    :result :signed
    :doc "LONG TFExamineFileSize(LONG file_size) (D0) LVO -84")

(provide "amiga/raw/trackfile")
