;;; amiga/raw/trackfile  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   trackfile_lib.sfd ($VER: trackfile_lib.sfd 2.3 (10.8.2020))
;;;
;;; 8 functions, 0 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.TRACKFILE"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*TRACKFILE-BASE*" "*TRACKFILE-VERSION*"
   "TF-START-UNIT-TAG-LIST" "TF-STOP-UNIT-TAG-LIST" 
   "TF-INSERT-MEDIA-TAG-LIST" "TF-EJECT-MEDIA-TAG-LIST" "TF-GET-UNIT-DATA" 
   "TF-FREE-UNIT-DATA" "TF-CHANGE-UNIT-TAG-LIST" "TF-EXAMINE-FILE-SIZE" ))

(in-package "AMIGA.RAW.TRACKFILE")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
;;; trackfile.device is a device/resource: there is no OpenLibrary.  Set the base
;;; yourself (IORequest io_Device after OpenDevice, or OpenResource).
(defvar *trackfile-base* nil)
(defvar *trackfile-version*
  (and *trackfile-base* (amiga.ffi:library-version *trackfile-base*)))
(defun %version>= (n)
  (and *trackfile-version* (>= *trackfile-version* n)))

;;; --- functions (trackfile_lib.sfd) ---
(amiga.ffi:defcfun tf-start-unit-tag-list *trackfile-base* -42 (:d0 which-unit :a0 tags)
    :result :signed
    :doc "LONG TFStartUnitTagList(LONG which_unit, CONST struct TagItem * tags) (D0,A0) LVO -42")
(amiga.ffi:defcfun tf-stop-unit-tag-list *trackfile-base* -48 (:d0 which-unit :a0 tags)
    :result :signed
    :doc "LONG TFStopUnitTagList(LONG which_unit, CONST struct TagItem * tags) (D0,A0) LVO -48")
(amiga.ffi:defcfun tf-insert-media-tag-list *trackfile-base* -54 (:d0 which-unit :a0 tags)
    :result :signed
    :doc "LONG TFInsertMediaTagList(LONG which_unit, CONST struct TagItem * tags) (D0,A0) LVO -54")
(amiga.ffi:defcfun tf-eject-media-tag-list *trackfile-base* -60 (:d0 which-unit :a0 tags)
    :result :signed
    :doc "LONG TFEjectMediaTagList(LONG which_unit, CONST struct TagItem * tags) (D0,A0) LVO -60")
(amiga.ffi:defcfun tf-get-unit-data *trackfile-base* -66 (:d0 which-unit)
    :result :pointer
    :doc "struct TrackFileUnitData * TFGetUnitData(LONG which_unit) (D0) LVO -66")
(amiga.ffi:defcfun tf-free-unit-data *trackfile-base* -72 (:a0 tfud)
    :result :void
    :doc "VOID TFFreeUnitData(struct TrackFileUnitData * tfud) (A0) LVO -72")
(amiga.ffi:defcfun tf-change-unit-tag-list *trackfile-base* -78 (:d0 which-unit :a0 tags)
    :result :signed
    :doc "LONG TFChangeUnitTagList(LONG which_unit, CONST struct TagItem * tags) (D0,A0) LVO -78")
(amiga.ffi:defcfun tf-examine-file-size *trackfile-base* -84 (:d0 file-size)
    :result :signed
    :doc "LONG TFExamineFileSize(LONG file_size) (D0) LVO -84")

(provide "amiga/raw/trackfile")
