;;; amiga/raw/utility  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   utility_lib.sfd ($VER: utility_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK utility_lib.fd + clib/utility_protos.h (via fd2sfd)
;;;   utility/date.i
;;;   utility/hooks.i
;;;   utility/name.i
;;;   utility/pack.i
;;;   utility/tagitem.i
;;;   utility/utility.i
;;;
;;; 43 functions, 28 constants, 5 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.UTILITY"
  (:use "CL" "FFI" "AMIGA.FFI")
  ;; distinct symbols  these names also exist in CL / FFI / AMIGA.FFI
  (:shadow "+TAG-DONE+" "+TAG-IGNORE+" "+TAG-MORE+" "+TAG-SKIP+")
  (:export "*UTILITY-BASE*" "*UTILITY-VERSION*"))

(in-package "AMIGA.RAW.UTILITY")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *utility-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "utility.library" 0)))
(defvar *utility-version*
  (and *utility-base* (amiga.ffi:library-version *utility-base*)))
(defun %version>= (n)
  (and *utility-version* (>= *utility-version* n)))

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.UTILITY"
    (:base *utility-base* :version *utility-version*)

  ;; --- structures from utility/date.i ---
  (:struct "CLOCKDATA" 14   ; CLOCKDATA (utility/date.i)
    ("SEC" :u16 0)
    ("MIN" :u16 2)
    ("HOUR" :u16 4)
    ("MDAY" :u16 6)
    ("MONTH" :u16 8)
    ("YEAR" :u16 10)
    ("WDAY" :u16 12)
    )

  ;; --- structures from utility/hooks.i ---
  (:struct "HOOK" 20   ; HOOK (utility/hooks.i)
    ("ENTRY" :fptr 8)
    ("SUB-ENTRY" :fptr 12)
    ("DATA" :fptr 16)
    )

  ;; --- constants from utility/name.i ---
  (:const "+UTILITY-NAME-I+" 1)
  (:const "+ANO-NAME-SPACE+" #xFA0)
  (:const "+ANO-USER-SPACE+" #xFA1)
  (:const "+ANO-PRIORITY+" #xFA2)
  (:const "+ANO-FLAGS+" #xFA3)
  (:const "+NSB-NODUPS+" 0)
  (:const "+NSF-NODUPS+" 1)
  (:const "+NSB-CASE+" 1)
  (:const "+NSF-CASE+" 2)

  ;; --- structures from utility/name.i ---
  (:struct "NAMED-OBJECT" 4   ; NamedObject (utility/name.i)
    ("OBJECT" :fptr 0)
    ("NAMED-OBJECT-END" (:struct 0) 4)
    )

  ;; --- constants from utility/pack.i ---
  (:const "+UTILITY-PACK-I+" 1)
  (:const "+PSTB-SIGNED+" #x1F)
  (:const "+PSTF-SIGNED+" #x80000000)
  (:const "+PSTB-UNPACK+" #x1E)
  (:const "+PSTF-UNPACK+" #x40000000)
  (:const "+PSTB-PACK+" #x1D)
  (:const "+PSTF-PACK+" #x20000000)
  (:const "+PSTB-EXISTS+" #x1A)
  (:const "+PSTF-EXISTS+" #x4000000)

  ;; --- constants from utility/tagitem.i ---
  (:const "+TAG-DONE+" 0)
  (:const "+TAG-END+" 0)
  (:const "+TAG-IGNORE+" 1)
  (:const "+TAG-MORE+" 2)
  (:const "+TAG-SKIP+" 3)
  (:const "+TAG-USER+" #x80000000)
  (:const "+TAGFILTER-AND+" 0)
  (:const "+TAGFILTER-NOT+" 1)
  (:const "+MAP-REMOVE-NOT-FOUND+" 0)
  (:const "+MAP-KEEP-NOT-FOUND+" 1)

  ;; --- structures from utility/tagitem.i ---
  (:struct "TAG-ITEM" 8   ; TagItem (utility/tagitem.i)
    ("TAG" :u32 0)
    ("DATA" :u32 4)
    )

  ;; --- structures from utility/utility.i ---
  (:struct "UTILITY-BASE" 36   ; UtilityBase (utility/utility.i)
    ("LANGUAGE" :u8 34)
    ("RESERVED" :u8 35)
    )

  ;; --- functions (utility_lib.sfd + MorphOS SDK) ---
  (:fn "FIND-TAG-ITEM" -30 (:d0 :a0) :pointer)   ; struct TagItem * FindTagItem(Tag tagVal, CONST struct TagItem * tagList) (D0,A0) LVO -30
  (:fn "GET-TAG-DATA" -36 (:d0 :d1 :a0) :unsigned)   ; ULONG GetTagData(Tag tagValue, ULONG defaultVal, CONST struct TagItem * tagList) (D0,D1,A0) LVO -36
  (:fn "PACK-BOOL-TAGS" -42 (:d0 :a0 :a1) :unsigned)   ; ULONG PackBoolTags(ULONG initialFlags, CONST struct TagItem * tagList, CONST struct TagItem * boolMap) (D0,A0,A1) LVO -42
  (:fn "NEXT-TAG-ITEM" -48 (:a0) :pointer)   ; struct TagItem * NextTagItem(struct TagItem ** tagListPtr) (A0) LVO -48
  (:fn "FILTER-TAG-CHANGES" -54 (:a0 :a1 :d0) :void)   ; VOID FilterTagChanges(struct TagItem * changeList, struct TagItem * originalList, ULONG apply) (A0,A1,D0) LVO -54
  (:fn "MAP-TAGS" -60 (:a0 :a1 :d0) :void)   ; VOID MapTags(struct TagItem * tagList, CONST struct TagItem * mapList, ULONG mapType) (A0,A1,D0) LVO -60
  (:fn "ALLOCATE-TAG-ITEMS" -66 (:d0) :pointer)   ; struct TagItem * AllocateTagItems(ULONG numTags) (D0) LVO -66
  (:fn "CLONE-TAG-ITEMS" -72 (:a0) :pointer)   ; struct TagItem * CloneTagItems(CONST struct TagItem * tagList) (A0) LVO -72
  (:fn "FREE-TAG-ITEMS" -78 (:a0) :void)   ; VOID FreeTagItems(struct TagItem * tagList) (A0) LVO -78
  (:fn "REFRESH-TAG-ITEM-CLONES" -84 (:a0 :a1) :void)   ; VOID RefreshTagItemClones(struct TagItem * clone, CONST struct TagItem * original) (A0,A1) LVO -84
  (:fn "TAG-IN-ARRAY" -90 (:d0 :a0) :bool)   ; BOOL TagInArray(Tag tagValue, CONST Tag * tagArray) (D0,A0) LVO -90
  (:fn "FILTER-TAG-ITEMS" -96 (:a0 :a1 :d0) :unsigned)   ; ULONG FilterTagItems(struct TagItem * tagList, CONST Tag * filterArray, ULONG logic) (A0,A1,D0) LVO -96
  (:fn "CALL-HOOK-PKT" -102 (:a0 :a2 :a1) :unsigned)   ; ULONG CallHookPkt(struct Hook * hook, APTR object, APTR paramPacket) (A0,A2,A1) LVO -102
  (:fn "AMIGA2-DATE" -120 (:d0 :a0) :void)   ; VOID Amiga2Date(ULONG seconds, struct ClockData * result) (D0,A0) LVO -120
  (:fn "DATE2-AMIGA" -126 (:a0) :unsigned)   ; ULONG Date2Amiga(CONST struct ClockData * date) (A0) LVO -126
  (:fn "CHECK-DATE" -132 (:a0) :unsigned)   ; ULONG CheckDate(CONST struct ClockData * date) (A0) LVO -132
  (:fn "S-MULT32" -138 (:d0 :d1) :signed)   ; LONG SMult32(LONG arg1, LONG arg2) (D0,D1) LVO -138
  (:fn "U-MULT32" -144 (:d0 :d1) :unsigned)   ; ULONG UMult32(ULONG arg1, ULONG arg2) (D0,D1) LVO -144
  (:fn "S-DIV-MOD32" -150 (:d0 :d1) :signed)   ; LONG SDivMod32(LONG dividend, LONG divisor) (D0,D1) LVO -150
  (:fn "U-DIV-MOD32" -156 (:d0 :d1) :unsigned)   ; ULONG UDivMod32(ULONG dividend, ULONG divisor) (D0,D1) LVO -156
  (:fn "STRICMP" -162 (:a0 :a1) :signed)   ; LONG Stricmp(CONST_STRPTR string1, CONST_STRPTR string2) (A0,A1) LVO -162
  (:fn "STRNICMP" -168 (:a0 :a1 :d0) :signed)   ; LONG Strnicmp(CONST_STRPTR string1, CONST_STRPTR string2, LONG length) (A0,A1,D0) LVO -168
  (:fn "TO-UPPER" -174 (:d0) :u8)   ; UBYTE ToUpper(UBYTE character) (D0) LVO -174
  (:fn "TO-LOWER" -180 (:d0) :u8)   ; UBYTE ToLower(UBYTE character) (D0) LVO -180
  (:fn "APPLY-TAG-CHANGES" -186 (:a0 :a1) :void)   ; VOID ApplyTagChanges(struct TagItem * list, CONST struct TagItem * changeList) (A0,A1) LVO -186
  (:fn "S-MULT64" -198 (:d0 :d1) :signed)   ; LONG SMult64(LONG arg1, LONG arg2) (D0,D1) LVO -198
  (:fn "U-MULT64" -204 (:d0 :d1) :unsigned)   ; ULONG UMult64(ULONG arg1, ULONG arg2) (D0,D1) LVO -204
  (:fn "PACK-STRUCTURE-TAGS" -210 (:a0 :a1 :a2) :unsigned)   ; ULONG PackStructureTags(APTR pack, CONST ULONG * packTable, CONST struct TagItem * tagList) (A0,A1,A2) LVO -210
  (:fn "UNPACK-STRUCTURE-TAGS" -216 (:a0 :a1 :a2) :unsigned)   ; ULONG UnpackStructureTags(CONST_APTR pack, CONST ULONG * packTable, struct TagItem * tagList) (A0,A1,A2) LVO -216
  (:fn "ADD-NAMED-OBJECT" -222 (:a0 :a1) :bool)   ; BOOL AddNamedObject(struct NamedObject * nameSpace, struct NamedObject * object) (A0,A1) LVO -222
  (:fn "ALLOC-NAMED-OBJECT-A" -228 (:a0 :a1) :pointer)   ; struct NamedObject * AllocNamedObjectA(CONST_STRPTR name, CONST struct TagItem * tagList) (A0,A1) LVO -228
  (:fn "ATTEMPT-REM-NAMED-OBJECT" -234 (:a0) :signed)   ; LONG AttemptRemNamedObject(struct NamedObject * object) (A0) LVO -234
  (:fn "FIND-NAMED-OBJECT" -240 (:a0 :a1 :a2) :pointer)   ; struct NamedObject * FindNamedObject(struct NamedObject * nameSpace, CONST_STRPTR name, CONST struct NamedObject * lastObject) (A0,A1,A2) LVO -240
  (:fn "FREE-NAMED-OBJECT" -246 (:a0) :void)   ; VOID FreeNamedObject(struct NamedObject * object) (A0) LVO -246
  (:fn "NAMED-OBJECT-NAME" -252 (:a0) :pointer)   ; STRPTR NamedObjectName(struct NamedObject * object) (A0) LVO -252
  (:fn "RELEASE-NAMED-OBJECT" -258 (:a0) :void)   ; VOID ReleaseNamedObject(struct NamedObject * object) (A0) LVO -258
  (:fn "REM-NAMED-OBJECT" -264 (:a0 :a1) :void)   ; VOID RemNamedObject(struct NamedObject * object, struct Message * message) (A0,A1) LVO -264
  (:fn "GET-UNIQUE-ID" -270 () :unsigned)   ; ULONG GetUniqueID() () LVO -270
  (:fn "VSN-PRINTF" -312 (:a0 :d0 :a1 :a2) :signed :not-morphos 47)   ; LONG VSNPrintf(STRPTR buffer, ULONG bufsize, CONST_STRPTR fmt, CONST_APTR data) (A0,D0,A1,A2) LVO -312
  (:fn "STRNCPY" -438 (:a1 :a0 :d0) :pointer :not-morphos 47)   ; STRPTR Strncpy(STRPTR dst, CONST_STRPTR src, ULONG size) (A1,A0,D0) LVO -438
  (:fn "STRNCAT" -444 (:a1 :a0 :d0) :pointer :not-morphos 47)   ; STRPTR Strncat(STRPTR dst, CONST_STRPTR src, ULONG size) (A1,A0,D0) LVO -444
  (:fn "S-DIV-MOD64" -450 (:d1 :d0 :d2) :signed :not-morphos 47)   ; LONG SDivMod64(LONG hi, LONG lo, LONG divisor) (D1,D0,D2) LVO -450
  (:fn "U-DIV-MOD64" -456 (:d1 :d0 :d2) :unsigned :not-morphos 47)   ; ULONG UDivMod64(ULONG hi, ULONG lo, ULONG divisor) (D1,D0,D2) LVO -456
  )

(provide "amiga/raw/utility")
