#!/usr/bin/env python3
"""run-on-vampire.py LISP-FILE [CLAMIGA-ARGS...] -- run one Lisp file on the
real Amiga through amiagent, with the cross-built binary.

Pushes build/cross/clamiga beside the installed release's binary (as
bin/aos3/clamiga-dev, so it finds the release's lib/), pushes LISP-FILE
into a scratch drawer, runs it detached under `stack 128000` with the
output redirected to a log, waits for the run's done sentinel and prints
the log (also saved as build/amiga/vamp-<name>.log).  Any further
arguments go to clamiga (e.g. --no-jit).  Modelled on
clamacs/spike/run-vamp.py.

Environment: AMIGA_HOST (default 192.168.50.235), AMIGA_TOKEN (default
"vamp"), VAMP_RELEASE (the release drawer, default
Work:Download/clamiga-0.10.0), VAMP_OUT (scratch drawer, default
Work:Download/bench), VAMP_SETENV=NAME=VALUE (one AmigaDOS environment
variable set before the launch), VAMP_BINARY (skip the push and run this
binary instead, e.g. the release's own), VAMP_TIMEOUT (seconds, 1200)."""
import os, sys, time
sys.path.insert(0, os.path.expanduser("~/Development/MySources/amimcp/server"))
from amiga import Amiga

if len(sys.argv) < 2:
    sys.exit(__doc__)
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
LISP = sys.argv[1]
EXTRA = " ".join(sys.argv[2:])
NAME = os.path.splitext(os.path.basename(LISP))[0]
HOST = os.environ.get("AMIGA_HOST", "192.168.50.235")
TOKEN = os.environ.get("AMIGA_TOKEN", "vamp")
RELEASE = os.environ.get("VAMP_RELEASE", "Work:Download/clamiga-0.10.0")
OUT = os.environ.get("VAMP_OUT", "Work:Download/bench")
SETENV = os.environ.get("VAMP_SETENV", "")
SETENV_LINE = ("setenv " + SETENV.replace("=", " ", 1)) if SETENV else ""
# an AmigaDOS setenv persists until reboot: undo it after the run
UNSETENV_LINE = ("UnSetEnv " + SETENV.split("=", 1)[0]) if SETENV else ""
TIMEOUT = int(os.environ.get("VAMP_TIMEOUT", "1200"))
BINARY = os.environ.get("VAMP_BINARY", "")

a = Amiga(HOST, token=TOKEN, timeout=600)

def sh(cmd, timeout=120):
    r = a.exec_command(cmd, timeout=timeout)
    return r if isinstance(r, str) else "\n".join(str(x) for x in r)

print("box:", a.system_info())
if not BINARY:
    BINARY = RELEASE + "/bin/aos3/clamiga-dev"
    a.write_file(BINARY, open(os.path.join(ROOT, "build", "cross", "clamiga"), "rb").read())
    sh(f"Protect {BINARY} +e")
    print("pushed build/cross/clamiga ->", BINARY)
sh(f"MakeDir >NIL: {OUT}")
a.write_file(f"{OUT}/{NAME}.lisp", open(LISP, "rb").read())

script = f"""; generated by verify/realamiga/run-on-vampire.py
failat 21
cd {OUT}
Delete >NIL: {NAME}-done {NAME}.log
echo "=== run start ===" >{NAME}.log
version >>{NAME}.log
stack 128000
{SETENV_LINE}
{BINARY} --no-userinit --heap 8M --non-interactive {EXTRA} --load {OUT}/{NAME}.lisp >>{NAME}.log
echo "=== run end ===" >>{NAME}.log
{UNSETENV_LINE}
echo done >{NAME}-done
"""
a.write_file(f"{OUT}/run-{NAME}", script.encode("latin-1"))
sh(f"Protect {OUT}/run-{NAME} +s")
sh(f"Delete >NIL: {OUT}/{NAME}-done")
a.arexx(f"address command 'Run >NIL: Execute {OUT}/run-{NAME}'")
print("launched; polling for", f"{OUT}/{NAME}-done")
deadline = time.time() + TIMEOUT
while time.time() < deadline:
    time.sleep(10)
    if f"{NAME}-done" in str(a.list_dir(OUT)):
        break
    print("  ...", time.strftime("%H:%M:%S"), flush=True)
else:
    print("TIMEOUT waiting for the run; partial log follows")
log = a.read_file(f"{OUT}/{NAME}.log")
if not isinstance(log, str):
    log = log.decode("latin-1", "replace")
print(log)
os.makedirs(os.path.join(ROOT, "build", "amiga"), exist_ok=True)
open(os.path.join(ROOT, "build", "amiga", f"vamp-{NAME}.log"), "w").write(log)
