;;; amiga/raw/gadgets/chooser  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   chooser_lib.sfd ($VER: chooser_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK chooser_lib.fd + clib/chooser_protos.h (via fd2sfd)
;;;   gadgets/chooser.h
;;;
;;; 7 functions, 33 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.GADGETS.CHOOSER"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*CHOOSER-BASE*" "*CHOOSER-VERSION*"
   "+CHOOSER-MIN-WIDTH+" "+CHOOSER-MIN-HEIGHT+" "+CNA-DUMMY+" "+CNA-TEXT+" 
   "+CNA-IMAGE+" "+CNA-SEL-IMAGE+" "+CNA-USER-DATA+" "+CNA-SEPARATOR+" 
   "+CNA-DISABLED+" "+CNA-BG-PEN+" "+CNA-FG-PEN+" "+CNA-READ-ONLY+" 
   "+CNA-COPY-TEXT+" "+CHOOSER-DUMMY+" "+CHOOSER-POP-UP+" 
   "+CHOOSER-DROP-DOWN+" "+CHOOSER-TITLE+" "+CHOOSER-LABELS+" 
   "+CHOOSER-ACTIVE+" "+CHOOSER-SELECTED+" "+CHOOSER-WIDTH+" 
   "+CHOOSER-AUTO-FIT+" "+CHOOSER-MAX-LABELS+" "+CHOOSER-OFFSET+" 
   "+CHOOSER-HIDDEN+" "+CHOOSER-LABEL-ARRAY+" "+CHOOSER-JUSTIFICATION+" 
   "+CHOOSER-IMAGE-JUSTIFICATION+" "+CHOOSER-SELECTED-NODE+" 
   "+CHOOSER-DEACTIVATE-ON-MOST-RAW-KEYS+" "+CHJ-LEFT+" "+CHJ-CENTER+" 
   "+CHJ-RIGHT+" "CHOOSER-GET-CLASS" "ALLOC-CHOOSER-NODE-A" 
   "FREE-CHOOSER-NODE" "SET-CHOOSER-NODE-ATTRS-A" 
   "GET-CHOOSER-NODE-ATTRS-A" "SHOW-CHOOSER" "HIDE-CHOOSER" ))

(in-package "AMIGA.RAW.GADGETS.CHOOSER")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *chooser-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/chooser.gadget" 0)))
(defvar *chooser-version*
  (and *chooser-base* (amiga.ffi:library-version *chooser-base*)))
(defun %version>= (n)
  (and *chooser-version* (>= *chooser-version* n)))

;;; --- constants from gadgets/chooser.h ---
(defconstant +chooser-min-width+ #x24)
(defconstant +chooser-min-height+ 10)
(defconstant +cna-dummy+ #x85001500)
(defconstant +cna-text+ #x85001501)
(defconstant +cna-image+ #x85001502)
(defconstant +cna-sel-image+ #x85001503)
(defconstant +cna-user-data+ #x85001504)
(defconstant +cna-separator+ #x85001505)
(defconstant +cna-disabled+ #x85001506)
(defconstant +cna-bg-pen+ #x85001507)
(defconstant +cna-fg-pen+ #x85001508)
(defconstant +cna-read-only+ #x85001509)
(defconstant +cna-copy-text+ #x8500150A)
(defconstant +chooser-dummy+ #x85001000)
(defconstant +chooser-pop-up+ #x85001001)
(defconstant +chooser-drop-down+ #x85001002)
(defconstant +chooser-title+ #x85001003)
(defconstant +chooser-labels+ #x85001004)
(defconstant +chooser-active+ #x85001005)
(defconstant +chooser-selected+ #x85001005)
(defconstant +chooser-width+ #x85001006)
(defconstant +chooser-auto-fit+ #x85001007)
(defconstant +chooser-max-labels+ #x85001009)
(defconstant +chooser-offset+ #x8500100A)
(defconstant +chooser-hidden+ #x8500100B)
(defconstant +chooser-label-array+ #x8500100C)
(defconstant +chooser-justification+ #x8500100D)
(defconstant +chooser-image-justification+ #x8500100E)
(defconstant +chooser-selected-node+ #x8500100F)
(defconstant +chooser-deactivate-on-most-raw-keys+ #x85001010)
(defconstant +chj-left+ 0)
(defconstant +chj-center+ 1)
(defconstant +chj-right+ 2)

;;; --- functions (chooser_lib.sfd + MorphOS SDK) ---
(when (%version>= 40)
  (amiga.ffi:defcfun chooser-get-class *chooser-base* -30 ()
    :result :pointer
    :doc "Class * CHOOSER_GetClass() () LVO -30"))
(when (%version>= 40)
  (amiga.ffi:defcfun alloc-chooser-node-a *chooser-base* -36 (:a0 tags)
    :result :pointer
    :doc "struct Node * AllocChooserNodeA(struct TagItem * tags) (A0) LVO -36"))
(when (%version>= 40)
  (amiga.ffi:defcfun free-chooser-node *chooser-base* -42 (:a0 node)
    :result :void
    :doc "VOID FreeChooserNode(struct Node * node) (A0) LVO -42"))
(when (%version>= 40)
  (amiga.ffi:defcfun set-chooser-node-attrs-a *chooser-base* -48 (:a0 node :a1 tags)
    :result :void
    :doc "VOID SetChooserNodeAttrsA(struct Node * node, struct TagItem * tags) (A0,A1) LVO -48"))
(when (%version>= 40)
  (amiga.ffi:defcfun get-chooser-node-attrs-a *chooser-base* -54 (:a0 node :a1 tags)
    :result :void
    :doc "VOID GetChooserNodeAttrsA(struct Node * node, struct TagItem * tags) (A0,A1) LVO -54"))
(when (and (not (member :morphos *features*)) (%version>= 40))
  (amiga.ffi:defcfun show-chooser *chooser-base* -60 (:a0 o :a1 w :d0 xpos :d1 ypos)
    :result :unsigned
    :doc "ULONG ShowChooser(Object * o, struct Window * w, ULONG xpos, ULONG ypos) (A0,A1,D0,D1) LVO -60"))
(when (and (not (member :morphos *features*)) (%version>= 40))
  (amiga.ffi:defcfun hide-chooser *chooser-base* -66 (:a0 o :a1 w)
    :result :void
    :doc "VOID HideChooser(Object * o, struct Window * w) (A0,A1) LVO -66"))

(provide "amiga/raw/gadgets/chooser")
