;;; amiga/raw/gadgets/colorwheel  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   colorwheel_lib.sfd ($VER: colorwheel_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK colorwheel_lib.fd + clib/colorwheel_protos.h (via fd2sfd)
;;;   gadgets/colorwheel.i
;;;
;;; 2 functions, 15 constants, 2 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.GADGETS.COLORWHEEL"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export "*COLORWHEEL-BASE*" "*COLORWHEEL-VERSION*"))

(in-package "AMIGA.RAW.GADGETS.COLORWHEEL")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *colorwheel-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/colorwheel.gadget" 0)))
(defvar *colorwheel-version*
  (and *colorwheel-base* (amiga.ffi:library-version *colorwheel-base*)))
(defun %version>= (n)
  (and *colorwheel-version* (>= *colorwheel-version* n)))

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.GADGETS.COLORWHEEL"
    (:base *colorwheel-base* :version *colorwheel-version*)

  ;; --- constants from gadgets/colorwheel.i ---
  (:const "+WHEEL-DUMMY+" #x84000000)
  (:const "+WHEEL-HUE+" #x84000001)
  (:const "+WHEEL-SATURATION+" #x84000002)
  (:const "+WHEEL-BRIGHTNESS+" #x84000003)
  (:const "+WHEEL-HSB+" #x84000004)
  (:const "+WHEEL-RED+" #x84000005)
  (:const "+WHEEL-GREEN+" #x84000006)
  (:const "+WHEEL-BLUE+" #x84000007)
  (:const "+WHEEL-RGB+" #x84000008)
  (:const "+WHEEL-SCREEN+" #x84000009)
  (:const "+WHEEL-ABBRV+" #x8400000A)
  (:const "+WHEEL-DONATION+" #x8400000B)
  (:const "+WHEEL-BEVEL-BOX+" #x8400000C)
  (:const "+WHEEL-GRADIENT-SLIDER+" #x8400000D)
  (:const "+WHEEL-MAX-PENS+" #x8400000E)

  ;; --- structures from gadgets/colorwheel.i ---
  (:struct "COLOR-WHEEL-HSB" 12   ; ColorWheelHSB (gadgets/colorwheel.i)
    ("HUE" :u32 0)
    ("SATURATION" :u32 4)
    ("BRIGHTNESS" :u32 8)
    )
  (:struct "COLOR-WHEEL-RGB" 12   ; ColorWheelRGB (gadgets/colorwheel.i)
    ("RED" :u32 0)
    ("GREEN" :u32 4)
    ("BLUE" :u32 8)
    )

  ;; --- functions (colorwheel_lib.sfd + MorphOS SDK) ---
  (:fn "CONVERT-HSB-TO-RGB" -30 (:a0 :a1) :void)   ; VOID ConvertHSBToRGB(CONST struct ColorWheelHSB * hsb, struct ColorWheelRGB * rgb) (A0,A1) LVO -30
  (:fn "CONVERT-RGB-TO-HSB" -36 (:a0 :a1) :void)   ; VOID ConvertRGBToHSB(CONST struct ColorWheelRGB * rgb, struct ColorWheelHSB * hsb) (A0,A1) LVO -36
  )

(provide "amiga/raw/gadgets/colorwheel")
