;;; amiga/raw/gadgets/getcolor  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   getcolor_lib.sfd ($VER: getcolor_lib.sfd 47.1 (30.11.2021))
;;;   gadgets/getcolor.h
;;;
;;; 1 functions, 21 constants, 0 structs.
;;; 1 C macro skipped: not an integer or ASCII-string constant (call, float, non-ASCII).
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.GADGETS.GETCOLOR"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export "*GETCOLOR-BASE*" "*GETCOLOR-VERSION*"))

(in-package "AMIGA.RAW.GADGETS.GETCOLOR")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *getcolor-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/getcolor.gadget" 0)))
(defvar *getcolor-version*
  (and *getcolor-base* (amiga.ffi:library-version *getcolor-base*)))
(defun %version>= (n)
  (and *getcolor-version* (>= *getcolor-version* n)))

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.GADGETS.GETCOLOR"
    (:base *getcolor-base* :version *getcolor-version*)

  ;; --- constants from gadgets/getcolor.h ---
  (:const "+GETCOLOR-DUMMY+" #x85043000)
  (:const "+GETCOLOR-TITLE-TEXT+" #x85043001)
  (:const "+GETCOLOR-SCREEN+" #x85043002)
  (:const "+GETCOLOR-COLOR+" #x85043003)
  (:const "+GETCOLOR-RED+" #x85043004)
  (:const "+GETCOLOR-GREEN+" #x85043005)
  (:const "+GETCOLOR-BLUE+" #x85043006)
  (:const "+GETCOLOR-HUE+" #x85043007)
  (:const "+GETCOLOR-SATURATION+" #x85043008)
  (:const "+GETCOLOR-BRIGHTNESS+" #x85043009)
  (:const "+GETCOLOR-RGB+" #x8504300A)
  (:const "+GETCOLOR-HSB+" #x8504300B)
  (:const "+GETCOLOR-COLOR-WHEEL+" #x8504300C)
  (:const "+GETCOLOR-RGB-SLIDERS+" #x8504300D)
  (:const "+GETCOLOR-HSB-SLIDERS+" #x8504300E)
  (:const "+GETCOLOR-SWITCH-MODE+" #x8504300F)
  (:const "+GETCOLOR-INITIAL+" #x85043010)
  (:const "+GETCOLOR-SHOW-RGB+" #x85043011)
  (:const "+GETCOLOR-SHOW-HSB+" #x85043012)
  (:const "+GETCOLOR-SMALL-TEXT-ATTR+" #x85043013)
  (:const "+GCOLOR-REQUEST+" #x630001)

  ;; --- functions (getcolor_lib.sfd) ---
  (:fn "GETCOLOR-GET-CLASS" -30 () :pointer 40)   ; Class * GETCOLOR_GetClass() () LVO -30
  )

(provide "amiga/raw/gadgets/getcolor")
