;;; amiga/raw/gadgets/getfile  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   getfile_lib.sfd ($VER: getfile_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK getfile_lib.fd + clib/getfile_protos.h (via fd2sfd)
;;;   gadgets/getfile.h
;;;
;;; 1 functions, 29 constants, 0 structs.
;;; 1 C macro skipped: not an integer constant (string, call, float).
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.GADGETS.GETFILE"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*GETFILE-BASE*" "*GETFILE-VERSION*"
   "+GETFILE-DUMMY+" "+GETFILE-TITLE-TEXT+" "+GETFILE-LEFT-EDGE+" 
   "+GETFILE-TOP-EDGE+" "+GETFILE-WIDTH+" "+GETFILE-HEIGHT+" 
   "+GETFILE-FILE+" "+GETFILE-DRAWER+" "+GETFILE-FULL-FILE+" 
   "+GETFILE-FULL-FILE-EXPAND+" "+GETFILE-PATTERN+" 
   "+GETFILE-DO-SAVE-MODE+" "+GETFILE-DO-MULTI-SELECT+" 
   "+GETFILE-DO-PATTERNS+" "+GETFILE-DRAWERS-ONLY+" "+GETFILE-FILTER-FUNC+" 
   "+GETFILE-REJECT-ICONS+" "+GETFILE-REJECT-PATTERN+" 
   "+GETFILE-ACCEPT-PATTERN+" "+GETFILE-FILTER-DRAWERS+" 
   "+GETFILE-FILELIST+" "+GETFILE-LB-NODE-STRUCTS+" "+GETFILE-READ-ONLY+" 
   "+GETFILE-FILE-PART-ONLY+" "+GETFILE-ALLOW-EMPTY-FILE-SELECTION+" 
   "+GETFILE-FILTER-HOOK+" "+GETFILE-INITIAL-SHOW-VOLUMES+" 
   "+GFILE-REQUEST+" "+GFILE-FREELIST+" "GETFILE-GET-CLASS" ))

(in-package "AMIGA.RAW.GADGETS.GETFILE")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *getfile-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/getfile.gadget" 0)))
(defvar *getfile-version*
  (and *getfile-base* (amiga.ffi:library-version *getfile-base*)))
(defun %version>= (n)
  (and *getfile-version* (>= *getfile-version* n)))

;;; --- constants from gadgets/getfile.h ---
(defconstant +getfile-dummy+ #x85060000)
(defconstant +getfile-title-text+ #x85060001)
(defconstant +getfile-left-edge+ #x85060002)
(defconstant +getfile-top-edge+ #x85060003)
(defconstant +getfile-width+ #x85060004)
(defconstant +getfile-height+ #x85060005)
(defconstant +getfile-file+ #x85060006)
(defconstant +getfile-drawer+ #x85060007)
(defconstant +getfile-full-file+ #x85060008)
(defconstant +getfile-full-file-expand+ #x85060009)
(defconstant +getfile-pattern+ #x8506000A)
(defconstant +getfile-do-save-mode+ #x8506000B)
(defconstant +getfile-do-multi-select+ #x8506000C)
(defconstant +getfile-do-patterns+ #x8506000D)
(defconstant +getfile-drawers-only+ #x8506000E)
(defconstant +getfile-filter-func+ #x8506000F)
(defconstant +getfile-reject-icons+ #x85060010)
(defconstant +getfile-reject-pattern+ #x85060011)
(defconstant +getfile-accept-pattern+ #x85060012)
(defconstant +getfile-filter-drawers+ #x85060013)
(defconstant +getfile-filelist+ #x85060014)
(defconstant +getfile-lb-node-structs+ #x85060015)
(defconstant +getfile-read-only+ #x85060016)
(defconstant +getfile-file-part-only+ #x85060017)
(defconstant +getfile-allow-empty-file-selection+ #x85060018)
(defconstant +getfile-filter-hook+ #x85060019)
(defconstant +getfile-initial-show-volumes+ #x8506001A)
(defconstant +gfile-request+ #x620001)
(defconstant +gfile-freelist+ #x620002)

;;; --- functions (getfile_lib.sfd + MorphOS SDK) ---
(when (%version>= 40)
  (amiga.ffi:defcfun getfile-get-class *getfile-base* -30 ()
    :result :pointer
    :doc "Class * GETFILE_GetClass() () LVO -30"))

(provide "amiga/raw/gadgets/getfile")
