;;; amiga/raw/gadgets/getfont  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   getfont_lib.sfd ($VER: getfont_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK getfont_lib.fd + clib/getfont_protos.h (via fd2sfd)
;;;   gadgets/getfont.h
;;;
;;; 1 functions, 36 constants, 0 structs.
;;; 1 C macro skipped: not an integer constant (string, call, float).
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.GADGETS.GETFONT"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*GETFONT-BASE*" "*GETFONT-VERSION*"
   "+GETFONT-DUMMY+" "+GETFONT-TEXT-ATTR+" "+GETFONT-DO-FRONT-PEN+" 
   "+GETFONT-DO-BACK-PEN+" "+GETFONT-DO-STYLE+" "+GETFONT-DO-DRAW-MODE+" 
   "+GETFONT-MIN-HEIGHT+" "+GETFONT-MAX-HEIGHT+" 
   "+GETFONT-FIXED-WIDTH-ONLY+" "+GETFONT-TITLE-TEXT+" "+GETFONT-HEIGHT+" 
   "+GETFONT-WIDTH+" "+GETFONT-LEFT-EDGE+" "+GETFONT-TOP-EDGE+" 
   "+GETFONT-FRONT-PEN+" "+GETFONT-BACK-PEN+" "+GETFONT-DRAW-MODE+" 
   "+GETFONT-MAX-FRONT-PEN+" "+GETFONT-MAX-BACK-PEN+" "+GETFONT-MODE-LIST+" 
   "+GETFONT-FRONT-PENS+" "+GETFONT-BACK-PENS+" "+GETFONT-SOFT-STYLE+" 
   "+GETFONT-SAMPLE-TEXT+" "+GETFONT-DO-CHAR-SET+" "+GETFONT-CHAR-SET+" 
   "+GETFONT-O-TAG-ONLY+" "+GETFONT-SCALABLE-ONLY+" 
   "+GETFONT-DO-SPECIAL-MODE+" "+GETFONT-SPECIAL-MODE+" 
   "+GETFONT-FILTER-FUNC+" "+GETFONT-CS-FILTER-FUNC+" 
   "+GETFONT-SPECIAL-MODE-BITMAP+" "+GETFONT-SPECIAL-MODE-BITMAP-WIDTH+" 
   "+GETFONT-SPECIAL-MODE-BITMAP-HEIGHT+" "+GFONT-REQUEST+" 
   "GETFONT-GET-CLASS" ))

(in-package "AMIGA.RAW.GADGETS.GETFONT")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *getfont-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/getfont.gadget" 0)))
(defvar *getfont-version*
  (and *getfont-base* (amiga.ffi:library-version *getfont-base*)))
(defun %version>= (n)
  (and *getfont-version* (>= *getfont-version* n)))

;;; --- constants from gadgets/getfont.h ---
(defconstant +getfont-dummy+ #x85040000)
(defconstant +getfont-text-attr+ #x85040001)
(defconstant +getfont-do-front-pen+ #x85040002)
(defconstant +getfont-do-back-pen+ #x85040003)
(defconstant +getfont-do-style+ #x85040004)
(defconstant +getfont-do-draw-mode+ #x85040005)
(defconstant +getfont-min-height+ #x85040006)
(defconstant +getfont-max-height+ #x85040007)
(defconstant +getfont-fixed-width-only+ #x85040008)
(defconstant +getfont-title-text+ #x85040009)
(defconstant +getfont-height+ #x8504000A)
(defconstant +getfont-width+ #x8504000B)
(defconstant +getfont-left-edge+ #x8504000C)
(defconstant +getfont-top-edge+ #x8504000D)
(defconstant +getfont-front-pen+ #x8504000E)
(defconstant +getfont-back-pen+ #x8504000F)
(defconstant +getfont-draw-mode+ #x85040010)
(defconstant +getfont-max-front-pen+ #x85040011)
(defconstant +getfont-max-back-pen+ #x85040012)
(defconstant +getfont-mode-list+ #x85040013)
(defconstant +getfont-front-pens+ #x85040014)
(defconstant +getfont-back-pens+ #x85040015)
(defconstant +getfont-soft-style+ #x85040016)
(defconstant +getfont-sample-text+ #x85040017)
(defconstant +getfont-do-char-set+ #x85040018)
(defconstant +getfont-char-set+ #x85040019)
(defconstant +getfont-o-tag-only+ #x8504001A)
(defconstant +getfont-scalable-only+ #x8504001B)
(defconstant +getfont-do-special-mode+ #x8504001C)
(defconstant +getfont-special-mode+ #x8504001D)
(defconstant +getfont-filter-func+ #x8504001E)
(defconstant +getfont-cs-filter-func+ #x8504001F)
(defconstant +getfont-special-mode-bitmap+ #x85040020)
(defconstant +getfont-special-mode-bitmap-width+ #x85040021)
(defconstant +getfont-special-mode-bitmap-height+ #x85040022)
(defconstant +gfont-request+ #x600001)

;;; --- functions (getfont_lib.sfd + MorphOS SDK) ---
(when (%version>= 40)
  (amiga.ffi:defcfun getfont-get-class *getfont-base* -30 ()
    :result :pointer
    :doc "Class * GETFONT_GetClass() () LVO -30"))

(provide "amiga/raw/gadgets/getfont")
