;;; amiga/raw/gadgets/getfont  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   getfont_lib.sfd ($VER: getfont_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK getfont_lib.fd + clib/getfont_protos.h (via fd2sfd)
;;;   gadgets/getfont.h
;;;
;;; 1 functions, 36 constants, 1 structs.
;;; 1 C macro skipped: not an integer or ASCII-string constant (call, float, non-ASCII).
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.GADGETS.GETFONT"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export "*GETFONT-BASE*" "*GETFONT-VERSION*"))

(in-package "AMIGA.RAW.GADGETS.GETFONT")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *getfont-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/getfont.gadget" 0)))
(defvar *getfont-version*
  (and *getfont-base* (amiga.ffi:library-version *getfont-base*)))
(defun %version>= (n)
  (and *getfont-version* (>= *getfont-version* n)))

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.GADGETS.GETFONT"
    (:base *getfont-base* :version *getfont-version*)

  ;; --- constants from gadgets/getfont.h ---
  (:const "+GETFONT-DUMMY+" #x85040000)
  (:const "+GETFONT-TEXT-ATTR+" #x85040001)
  (:const "+GETFONT-DO-FRONT-PEN+" #x85040002)
  (:const "+GETFONT-DO-BACK-PEN+" #x85040003)
  (:const "+GETFONT-DO-STYLE+" #x85040004)
  (:const "+GETFONT-DO-DRAW-MODE+" #x85040005)
  (:const "+GETFONT-MIN-HEIGHT+" #x85040006)
  (:const "+GETFONT-MAX-HEIGHT+" #x85040007)
  (:const "+GETFONT-FIXED-WIDTH-ONLY+" #x85040008)
  (:const "+GETFONT-TITLE-TEXT+" #x85040009)
  (:const "+GETFONT-HEIGHT+" #x8504000A)
  (:const "+GETFONT-WIDTH+" #x8504000B)
  (:const "+GETFONT-LEFT-EDGE+" #x8504000C)
  (:const "+GETFONT-TOP-EDGE+" #x8504000D)
  (:const "+GETFONT-FRONT-PEN+" #x8504000E)
  (:const "+GETFONT-BACK-PEN+" #x8504000F)
  (:const "+GETFONT-DRAW-MODE+" #x85040010)
  (:const "+GETFONT-MAX-FRONT-PEN+" #x85040011)
  (:const "+GETFONT-MAX-BACK-PEN+" #x85040012)
  (:const "+GETFONT-MODE-LIST+" #x85040013)
  (:const "+GETFONT-FRONT-PENS+" #x85040014)
  (:const "+GETFONT-BACK-PENS+" #x85040015)
  (:const "+GETFONT-SOFT-STYLE+" #x85040016)
  (:const "+GETFONT-SAMPLE-TEXT+" #x85040017)
  (:const "+GETFONT-DO-CHAR-SET+" #x85040018)
  (:const "+GETFONT-CHAR-SET+" #x85040019)
  (:const "+GETFONT-O-TAG-ONLY+" #x8504001A)
  (:const "+GETFONT-SCALABLE-ONLY+" #x8504001B)
  (:const "+GETFONT-DO-SPECIAL-MODE+" #x8504001C)
  (:const "+GETFONT-SPECIAL-MODE+" #x8504001D)
  (:const "+GETFONT-FILTER-FUNC+" #x8504001E)
  (:const "+GETFONT-CS-FILTER-FUNC+" #x8504001F)
  (:const "+GETFONT-SPECIAL-MODE-BITMAP+" #x85040020)
  (:const "+GETFONT-SPECIAL-MODE-BITMAP-WIDTH+" #x85040021)
  (:const "+GETFONT-SPECIAL-MODE-BITMAP-HEIGHT+" #x85040022)
  (:const "+GFONT-REQUEST+" #x600001)

  ;; --- structures from gadgets/getfont.h ---
  (:struct "GF-REQUEST" 8   ; gfRequest (gadgets/getfont.h)
    ("METHOD-ID" :u32 0)
    ("WINDOW" :fptr 4)
    )

  ;; --- functions (getfont_lib.sfd + MorphOS SDK) ---
  (:fn "GETFONT-GET-CLASS" -30 () :pointer 40)   ; Class * GETFONT_GetClass() () LVO -30
  )

(provide "amiga/raw/gadgets/getfont")
