;;; amiga/raw/gadgets/gradientslider  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   gadgets/gradientslider.i
;;;
;;; 0 functions, 6 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.GADGETS.GRADIENTSLIDER"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export))

(in-package "AMIGA.RAW.GADGETS.GRADIENTSLIDER")

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.GADGETS.GRADIENTSLIDER" ()

  ;; --- constants from gadgets/gradientslider.i ---
  (:const "+GRAD-DUMMY+" #x85000000)
  (:const "+GRAD-MAX-VAL+" #x85000001)
  (:const "+GRAD-CUR-VAL+" #x85000002)
  (:const "+GRAD-SKIP-VAL+" #x85000003)
  (:const "+GRAD-KNOB-PIXELS+" #x85000004)
  (:const "+GRAD-PEN-ARRAY+" #x85000005)
  )

(provide "amiga/raw/gadgets/gradientslider")
