;;; amiga/raw/gadgets/gradientslider  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   gadgets/gradientslider.i
;;;
;;; 0 functions, 6 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.GADGETS.GRADIENTSLIDER"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "+GRAD-DUMMY+" "+GRAD-MAX-VAL+" "+GRAD-CUR-VAL+" "+GRAD-SKIP-VAL+" 
   "+GRAD-KNOB-PIXELS+" "+GRAD-PEN-ARRAY+" ))

(in-package "AMIGA.RAW.GADGETS.GRADIENTSLIDER")

;;; --- constants from gadgets/gradientslider.i ---
(defconstant +grad-dummy+ #x85000000)
(defconstant +grad-max-val+ #x85000001)
(defconstant +grad-cur-val+ #x85000002)
(defconstant +grad-skip-val+ #x85000003)
(defconstant +grad-knob-pixels+ #x85000004)
(defconstant +grad-pen-array+ #x85000005)

(provide "amiga/raw/gadgets/gradientslider")
