;;; amiga/raw/gadgets/integer  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   integer_lib.sfd ($VER: integer_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK integer_lib.fd + clib/integer_protos.h (via fd2sfd)
;;;   gadgets/integer.h
;;;
;;; 1 functions, 8 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.GADGETS.INTEGER"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*INTEGER-BASE*" "*INTEGER-VERSION*"
   "+INTEGER-DUMMY+" "+INTEGER-NUMBER+" "+INTEGER-MAX-CHARS+" 
   "+INTEGER-MINIMUM+" "+INTEGER-MAXIMUM+" "+INTEGER-ARROWS+" 
   "+INTEGER-MIN-VISIBLE+" "+INTEGER-SKIP-VAL+" "INTEGER-GET-CLASS" ))

(in-package "AMIGA.RAW.GADGETS.INTEGER")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *integer-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/integer.gadget" 0)))
(defvar *integer-version*
  (and *integer-base* (amiga.ffi:library-version *integer-base*)))
(defun %version>= (n)
  (and *integer-version* (>= *integer-version* n)))

;;; --- constants from gadgets/integer.h ---
(defconstant +integer-dummy+ #x85002000)
(defconstant +integer-number+ #x85002001)
(defconstant +integer-max-chars+ #x85002002)
(defconstant +integer-minimum+ #x85002003)
(defconstant +integer-maximum+ #x85002004)
(defconstant +integer-arrows+ #x85002005)
(defconstant +integer-min-visible+ #x85002006)
(defconstant +integer-skip-val+ #x85002007)

;;; --- functions (integer_lib.sfd + MorphOS SDK) ---
(when (%version>= 40)
  (amiga.ffi:defcfun integer-get-class *integer-base* -30 ()
    :result :pointer
    :doc "Class * INTEGER_GetClass() () LVO -30"))

(provide "amiga/raw/gadgets/integer")
