;;; amiga/raw/gadgets/integer  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   integer_lib.sfd ($VER: integer_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK integer_lib.fd + clib/integer_protos.h (via fd2sfd)
;;;   gadgets/integer.h
;;;
;;; 1 functions, 8 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.GADGETS.INTEGER"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export "*INTEGER-BASE*" "*INTEGER-VERSION*"))

(in-package "AMIGA.RAW.GADGETS.INTEGER")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *integer-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/integer.gadget" 0)))
(defvar *integer-version*
  (and *integer-base* (amiga.ffi:library-version *integer-base*)))
(defun %version>= (n)
  (and *integer-version* (>= *integer-version* n)))

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.GADGETS.INTEGER"
    (:base *integer-base* :version *integer-version*)

  ;; --- constants from gadgets/integer.h ---
  (:const "+INTEGER-DUMMY+" #x85002000)
  (:const "+INTEGER-NUMBER+" #x85002001)
  (:const "+INTEGER-MAX-CHARS+" #x85002002)
  (:const "+INTEGER-MINIMUM+" #x85002003)
  (:const "+INTEGER-MAXIMUM+" #x85002004)
  (:const "+INTEGER-ARROWS+" #x85002005)
  (:const "+INTEGER-MIN-VISIBLE+" #x85002006)
  (:const "+INTEGER-SKIP-VAL+" #x85002007)

  ;; --- functions (integer_lib.sfd + MorphOS SDK) ---
  (:fn "INTEGER-GET-CLASS" -30 () :pointer 40)   ; Class * INTEGER_GetClass() () LVO -30
  )

(provide "amiga/raw/gadgets/integer")
