;;; amiga/raw/gadgets/listview  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   listview_lib.sfd ($VER: listview_lib.sfd 47.1 (30.11.2021))
;;;   gadgets/listview.h
;;;
;;; 1 functions, 20 constants, 1 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.GADGETS.LISTVIEW"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export "*LISTVIEW-BASE*" "*LISTVIEW-VERSION*"))

(in-package "AMIGA.RAW.GADGETS.LISTVIEW")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *listview-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/listview.gadget" 0)))
(defvar *listview-version*
  (and *listview-base* (amiga.ffi:library-version *listview-base*)))
(defun %version>= (n)
  (and *listview-version* (>= *listview-version* n)))

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.GADGETS.LISTVIEW"
    (:base *listview-base* :version *listview-version*)

  ;; --- constants from gadgets/listview.h ---
  (:const "+LVJ-LEFT+" 0)
  (:const "+LVJ-CENTER+" 1)
  (:const "+LVJ-RIGHT+" 2)
  (:const "+LISTVIEW-DUMMY+" #x84000000)
  (:const "+LISTVIEW-LABELS+" #x84000001)
  (:const "+LISTVIEW-TOP+" #x84000002)
  (:const "+LISTVIEW-VISIBLE+" #x84000003)
  (:const "+LISTVIEW-TOTAL+" #x84000004)
  (:const "+LISTVIEW-SHOW-SELECTED+" #x84000006)
  (:const "+LISTVIEW-SELECTED+" #x84000007)
  (:const "+LISTVIEW-SELECTED-NODE+" #x84000007)
  (:const "+LISTVIEW-MAKE-VISIBLE+" #x84000008)
  (:const "+LISTVIEW-MULTI-SELECT+" #x84000009)
  (:const "+LISTVIEW-ITEM-HEIGHT+" #x8400000A)
  (:const "+LISTVIEW-CALL-HOOK+" #x8400000B)
  (:const "+LISTVIEW-SCROLL-UP+" #x8400000C)
  (:const "+LISTVIEW-SCROLL-DOWN+" #x8400000D)
  (:const "+LISTVIEW-SCROLL-LEFT+" #x8400000E)
  (:const "+LISTVIEW-SCROLL-RIGHT+" #x8400000F)
  (:const "+LISTVIEW-SPACING+" #x84000010)

  ;; --- structures from gadgets/listview.h ---
  (:struct "LIST-LABEL-NODE" 48   ; ListLabelNode (gadgets/listview.h)
    ("NODE" (:struct 14) 0)
    ("USER-DATA" :u32 14)
    ("RENDER-FOREGROUND" :i16 18)
    ("RENDER-BACKGROUND" :i16 20)
    ("SELECT-FOREGROUND" :i16 22)
    ("SELECT-BACKGROUND" :i16 24)
    ("RENDER-IMAGE" :fptr 26)
    ("SELECT-IMAGE" :fptr 30)
    ("TEXT-LENGTH" :i16 34)
    ("LEFT-EDGE" :i16 36)
    ("TOP-EDGE" :i16 38)
    ("WIDTH" :i16 40)
    ("HEIGHT" :i16 42)
    ("JUSTIFICATION" :i16 44)
    ("SELECTED" :i16 46)
    )

  ;; --- functions (listview_lib.sfd) ---
  (:fn "LISTVIEW-GET-CLASS" -30 () :pointer 40)   ; Class * LISTVIEW_GetClass() () LVO -30
  )

(provide "amiga/raw/gadgets/listview")
