;;; amiga/raw/gadgets/palette  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   palette_lib.sfd ($VER: palette_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK palette_lib.fd + clib/palette_protos.h (via fd2sfd)
;;;   gadgets/palette.h
;;;
;;; 1 functions, 18 constants, 1 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.GADGETS.PALETTE"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export "*PALETTE-BASE*" "*PALETTE-VERSION*"))

(in-package "AMIGA.RAW.GADGETS.PALETTE")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *palette-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/palette.gadget" 0)))
(defvar *palette-version*
  (and *palette-base* (amiga.ffi:library-version *palette-base*)))
(defun %version>= (n)
  (and *palette-version* (>= *palette-version* n)))

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.GADGETS.PALETTE"
    (:base *palette-base* :version *palette-version*)

  ;; --- constants from gadgets/palette.h ---
  (:const "+PALETTE-DUMMY+" #x85004000)
  (:const "+PALETTE-COLOUR+" #x85004001)
  (:const "+PALETTE-COLOUR-OFFSET+" #x85004002)
  (:const "+PALETTE-COLOUR-TABLE+" #x85004003)
  (:const "+PALETTE-NUM-COLOURS+" #x85004004)
  (:const "+PALETTE-MIN-COLOURS+" #x85004005)
  (:const "+PALETTE-RENDER-HOOK+" #x85004007)
  (:const "+PB-DRAW+" #x202)
  (:const "+PBCB-OK+" 0)
  (:const "+PBCB-UNKNOWN+" 1)
  (:const "+PBR-NORMAL+" 0)
  (:const "+PBR-SELECTED+" 1)
  (:const "+PBR-NORMALDISABLED+" 2)
  (:const "+PBR-SELECTEDDISABLED+" 8)
  (:const "+PALETTE-COLOR+" #x85004001)
  (:const "+PALETTE-COLOR-OFFSET+" #x85004002)
  (:const "+PALETTE-COLOR-TABLE+" #x85004003)
  (:const "+PALETTE-NUM-COLORS+" #x85004004)

  ;; --- structures from gadgets/palette.h ---
  (:struct "P-BOX-DRAW-MSG" 32   ; PBoxDrawMsg (gadgets/palette.h)
    ("METHOD-ID" :u32 0)
    ("RASTPORT" :fptr 4)
    ("DRAW-INFO" :fptr 8)
    ("BOUNDS" (:struct 8) 12)
    ("STATE" :u32 20)
    ("COLOR" :u32 24)
    ("GADGET" :fptr 28)
    )

  ;; --- functions (palette_lib.sfd + MorphOS SDK) ---
  (:fn "PALETTE-GET-CLASS" -30 () :pointer 40)   ; Class * PALETTE_GetClass() () LVO -30
  )

(provide "amiga/raw/gadgets/palette")
