;;; amiga/raw/gadgets/radiobutton  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   radiobutton_lib.sfd ($VER: radiobutton_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK radiobutton_lib.fd + clib/radiobutton_protos.h (via fd2sfd)
;;;   gadgets/radiobutton.h
;;;
;;; 5 functions, 13 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.GADGETS.RADIOBUTTON"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*RADIOBUTTON-BASE*" "*RADIOBUTTON-VERSION*"
   "+RBNA-DUMMY+" "+RBNA-USER-DATA+" "+RBNA-LABELS+" "+RBNA-LABEL+" 
   "+RBNA-HINT-INFO+" "+RBNA-DISABLED+" "+RADIOBUTTON-DUMMY+" 
   "+RADIOBUTTON-LABELS+" "+RADIOBUTTON-STRINGS+" "+RADIOBUTTON-SPACING+" 
   "+RADIOBUTTON-SELECTED+" "+RADIOBUTTON-LABEL-PLACE+" 
   "+RADIOBUTTON-LABEL-ARRAY+" "RADIOBUTTON-GET-CLASS" 
   "ALLOC-RADIO-BUTTON-NODE-A" "FREE-RADIO-BUTTON-NODE" 
   "SET-RADIO-BUTTON-NODE-ATTRS-A" "GET-RADIO-BUTTON-NODE-ATTRS-A" ))

(in-package "AMIGA.RAW.GADGETS.RADIOBUTTON")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *radiobutton-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/radiobutton.gadget" 0)))
(defvar *radiobutton-version*
  (and *radiobutton-base* (amiga.ffi:library-version *radiobutton-base*)))
(defun %version>= (n)
  (and *radiobutton-version* (>= *radiobutton-version* n)))

;;; --- constants from gadgets/radiobutton.h ---
(defconstant +rbna-dummy+ #x80020000)
(defconstant +rbna-user-data+ #x80020001)
(defconstant +rbna-labels+ #x80020002)
(defconstant +rbna-label+ #x80020002)
(defconstant +rbna-hint-info+ #x80020003)
(defconstant +rbna-disabled+ #x80020004)
(defconstant +radiobutton-dummy+ #x85014000)
(defconstant +radiobutton-labels+ #x85014001)
(defconstant +radiobutton-strings+ #x85014002)
(defconstant +radiobutton-spacing+ #x85014003)
(defconstant +radiobutton-selected+ #x85014004)
(defconstant +radiobutton-label-place+ #x85014005)
(defconstant +radiobutton-label-array+ #x85014006)

;;; --- functions (radiobutton_lib.sfd + MorphOS SDK) ---
(when (%version>= 40)
  (amiga.ffi:defcfun radiobutton-get-class *radiobutton-base* -30 ()
    :result :pointer
    :doc "Class * RADIOBUTTON_GetClass() () LVO -30"))
(when (%version>= 40)
  (amiga.ffi:defcfun alloc-radio-button-node-a *radiobutton-base* -36 (:d0 columns :a0 tags)
    :result :pointer
    :doc "struct Node * AllocRadioButtonNodeA(ULONG columns, struct TagItem * tags) (D0,A0) LVO -36"))
(when (%version>= 40)
  (amiga.ffi:defcfun free-radio-button-node *radiobutton-base* -42 (:a0 node)
    :result :void
    :doc "VOID FreeRadioButtonNode(struct Node * node) (A0) LVO -42"))
(when (%version>= 40)
  (amiga.ffi:defcfun set-radio-button-node-attrs-a *radiobutton-base* -48 (:a0 node :a1 tags)
    :result :void
    :doc "VOID SetRadioButtonNodeAttrsA(struct Node * node, struct TagItem * tags) (A0,A1) LVO -48"))
(when (%version>= 40)
  (amiga.ffi:defcfun get-radio-button-node-attrs-a *radiobutton-base* -54 (:a0 node :a1 tags)
    :result :void
    :doc "VOID GetRadioButtonNodeAttrsA(struct Node * node, struct TagItem * tags) (A0,A1) LVO -54"))

(provide "amiga/raw/gadgets/radiobutton")
