;;; amiga/raw/gadgets/scroller  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   scroller_lib.sfd ($VER: scroller_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK scroller_lib.fd + clib/scroller_protos.h (via fd2sfd)
;;;   gadgets/scroller.h
;;;
;;; 1 functions, 14 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.GADGETS.SCROLLER"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*SCROLLER-BASE*" "*SCROLLER-VERSION*"
   "+SCROLLER-DUMMY+" "+SCROLLER-TOP+" "+SCROLLER-VISIBLE+" 
   "+SCROLLER-TOTAL+" "+SCROLLER-ORIENTATION+" "+SCROLLER-ARROWS+" 
   "+SCROLLER-STRETCH+" "+SCROLLER-ARROW-DELTA+" "+SCROLLER-SIGNAL-TASK+" 
   "+SCROLLER-SIGNAL-TASK-BIT+" "+SORIENT-HORIZ+" "+SORIENT-VERT+" 
   "+SCROLLER-HORIZONTAL+" "+SCROLLER-VERTICAL+" "SCROLLER-GET-CLASS" ))

(in-package "AMIGA.RAW.GADGETS.SCROLLER")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *scroller-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/scroller.gadget" 0)))
(defvar *scroller-version*
  (and *scroller-base* (amiga.ffi:library-version *scroller-base*)))
(defun %version>= (n)
  (and *scroller-version* (>= *scroller-version* n)))

;;; --- constants from gadgets/scroller.h ---
(defconstant +scroller-dummy+ #x85005000)
(defconstant +scroller-top+ #x85005001)
(defconstant +scroller-visible+ #x85005002)
(defconstant +scroller-total+ #x85005003)
(defconstant +scroller-orientation+ #x85005004)
(defconstant +scroller-arrows+ #x85005005)
(defconstant +scroller-stretch+ #x85005006)
(defconstant +scroller-arrow-delta+ #x85005007)
(defconstant +scroller-signal-task+ #x8500500A)
(defconstant +scroller-signal-task-bit+ #x8500500B)
(defconstant +sorient-horiz+ 2)
(defconstant +sorient-vert+ 4)
(defconstant +scroller-horizontal+ 2)
(defconstant +scroller-vertical+ 4)

;;; --- functions (scroller_lib.sfd + MorphOS SDK) ---
(when (%version>= 40)
  (amiga.ffi:defcfun scroller-get-class *scroller-base* -30 ()
    :result :pointer
    :doc "Class * SCROLLER_GetClass() () LVO -30"))

(provide "amiga/raw/gadgets/scroller")
