;;; amiga/raw/gadgets/sketchboard  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   sketchboard_lib.sfd ($VER: sketchboard_lib.sfd 47.1 (30.11.2021))
;;;   gadgets/sketchboard.h
;;;
;;; 1 functions, 54 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.GADGETS.SKETCHBOARD"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*SKETCHBOARD-BASE*" "*SKETCHBOARD-VERSION*"
   "+SKETCHBOARD-DUMMY+" "+SGA-BITMAP+" "+SGA-MOUSE-X+" "+SGA-MOUSE-Y+" 
   "+SGA-WIDTH+" "+SGA-HEIGHT+" "+SGA-A-PEN+" "+SGA-TOOL+" 
   "+SGA-UNDO-AVAILABLE+" "+SGA-REDO-AVAILABLE+" "+SGA-SHOW-GRID+" 
   "+SGA-SCALE+" "+SGA-AF-PT+" "+SGA-AF-PT-SIZE+" "+SGA-H-PROP-TOTAL+" 
   "+SGA-H-PROP-TOP+" "+SGA-H-PROP-VISIBLE+" "+SGA-V-PROP-TOTAL+" 
   "+SGA-V-PROP-TOP+" "+SGA-V-PROP-VISIBLE+" "+SGA-HOT-SPOT+" 
   "+SGA-CHANGED+" "+SGA-RASTPORT+" "+SGA-SKETCH-BOARD-RECT+" 
   "+SGA-SUB-WIDTH+" "+SGA-SUB-HEIGHT+" "+SGA-DOUBLE-SCALE-X+" 
   "+SGA-DOUBLE-SCALE-Y+" "+SGA-TOP-LAYER-BITMAP+" "+SGA-TOP-LAYER-WIDTH+" 
   "+SGA-WITH-BEVEL+" "+SGA-SCROLL-WHEEL-RESPONSE+" "+SGA-MAX-UNDO-STEPS+" 
   "+SGA-UPDATED-BITMAP+" "+SGA-MAX-SCALE+" "+SGTOOL-FREEHAND-DOTS+" 
   "+SGTOOL-FREEHAND+" "+SGTOOL-ELLIPSE+" "+SGTOOL-ELLIPSE-FILLED+" 
   "+SGTOOL-RECT+" "+SGTOOL-RECT-FILLED+" "+SGTOOL-LINE+" "+SGTOOL-FILL+" 
   "+SGTOOL-GETPEN+" "+SGTOOL-HOTSPOT+" "+SGTOOL-SELECT+" "+SGTOOL-MOVE+" 
   "+SGSCROLLWHEEL-NOTHING+" "+SGSCROLLWHEEL-SCROLLANDZOOM+" 
   "+SGSCROLLWHEEL-ZOOM+" "+SGM-CLEAR+" "+SGM-UNDO+" "+SGM-REDO+" 
   "+SGM-SCROLL+" "SKETCHBOARD-GET-CLASS" ))

(in-package "AMIGA.RAW.GADGETS.SKETCHBOARD")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *sketchboard-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/sketchboard.gadget" 0)))
(defvar *sketchboard-version*
  (and *sketchboard-base* (amiga.ffi:library-version *sketchboard-base*)))
(defun %version>= (n)
  (and *sketchboard-version* (>= *sketchboard-version* n)))

;;; --- constants from gadgets/sketchboard.h ---
(defconstant +sketchboard-dummy+ #x85024600)
(defconstant +sga-bitmap+ #x85024600)
(defconstant +sga-mouse-x+ #x85024601)
(defconstant +sga-mouse-y+ #x85024602)
(defconstant +sga-width+ #x85024603)
(defconstant +sga-height+ #x85024604)
(defconstant +sga-a-pen+ #x85024605)
(defconstant +sga-tool+ #x85024606)
(defconstant +sga-undo-available+ #x85024607)
(defconstant +sga-redo-available+ #x85024608)
(defconstant +sga-show-grid+ #x85024609)
(defconstant +sga-scale+ #x8502460A)
(defconstant +sga-af-pt+ #x8502460B)
(defconstant +sga-af-pt-size+ #x8502460C)
(defconstant +sga-h-prop-total+ #x8502460D)
(defconstant +sga-h-prop-top+ #x8502460E)
(defconstant +sga-h-prop-visible+ #x8502460F)
(defconstant +sga-v-prop-total+ #x85024610)
(defconstant +sga-v-prop-top+ #x85024611)
(defconstant +sga-v-prop-visible+ #x85024612)
(defconstant +sga-hot-spot+ #x85024613)
(defconstant +sga-changed+ #x85024614)
(defconstant +sga-rastport+ #x85024615)
(defconstant +sga-sketch-board-rect+ #x85024616)
(defconstant +sga-sub-width+ #x85024617)
(defconstant +sga-sub-height+ #x85024618)
(defconstant +sga-double-scale-x+ #x85024619)
(defconstant +sga-double-scale-y+ #x8502461A)
(defconstant +sga-top-layer-bitmap+ #x8502461B)
(defconstant +sga-top-layer-width+ #x8502461C)
(defconstant +sga-with-bevel+ #x8502461D)
(defconstant +sga-scroll-wheel-response+ #x8502461E)
(defconstant +sga-max-undo-steps+ #x8502461F)
(defconstant +sga-updated-bitmap+ #x85024620)
(defconstant +sga-max-scale+ #x85024621)
(defconstant +sgtool-freehand-dots+ 0)
(defconstant +sgtool-freehand+ 1)
(defconstant +sgtool-ellipse+ 2)
(defconstant +sgtool-ellipse-filled+ 3)
(defconstant +sgtool-rect+ 4)
(defconstant +sgtool-rect-filled+ 5)
(defconstant +sgtool-line+ 6)
(defconstant +sgtool-fill+ 7)
(defconstant +sgtool-getpen+ 8)
(defconstant +sgtool-hotspot+ 9)
(defconstant +sgtool-select+ 10)
(defconstant +sgtool-move+ 11)
(defconstant +sgscrollwheel-nothing+ 0)
(defconstant +sgscrollwheel-scrollandzoom+ 1)
(defconstant +sgscrollwheel-zoom+ 2)
(defconstant +sgm-clear+ #x580100)
(defconstant +sgm-undo+ #x580101)
(defconstant +sgm-redo+ #x580102)
(defconstant +sgm-scroll+ #x580103)

;;; --- functions (sketchboard_lib.sfd) ---
(when (%version>= 40)
  (amiga.ffi:defcfun sketchboard-get-class *sketchboard-base* -30 ()
    :result :pointer
    :doc "Class * SKETCHBOARD_GetClass() () LVO -30"))

(provide "amiga/raw/gadgets/sketchboard")
