;;; amiga/raw/gadgets/slider  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   slider_lib.sfd ($VER: slider_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK slider_lib.fd + clib/slider_protos.h (via fd2sfd)
;;;   gadgets/slider.h
;;;
;;; 1 functions, 32 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.GADGETS.SLIDER"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export "*SLIDER-BASE*" "*SLIDER-VERSION*"))

(in-package "AMIGA.RAW.GADGETS.SLIDER")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *slider-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/slider.gadget" 0)))
(defvar *slider-version*
  (and *slider-base* (amiga.ffi:library-version *slider-base*)))
(defun %version>= (n)
  (and *slider-version* (>= *slider-version* n)))

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.GADGETS.SLIDER"
    (:base *slider-base* :version *slider-version*)

  ;; --- constants from gadgets/slider.h ---
  (:const "+SLIDER-DUMMY+" #x85028000)
  (:const "+SLIDER-MIN+" #x85028001)
  (:const "+SLIDER-MAX+" #x85028002)
  (:const "+SLIDER-LEVEL+" #x85028003)
  (:const "+SLIDER-ORIENTATION+" #x85028004)
  (:const "+SLIDER-DISP-HOOK+" #x85028005)
  (:const "+SLIDER-TICKS+" #x85028006)
  (:const "+SLIDER-SHORT-TICKS+" #x85028007)
  (:const "+SLIDER-TICK-SIZE+" #x85028008)
  (:const "+SLIDER-KNOB-IMAGE+" #x85028009)
  (:const "+SLIDER-BODY-FILL+" #x8502800A)
  (:const "+SLIDER-BODY-IMAGE+" #x8502800B)
  (:const "+SLIDER-GRADIENT+" #x8502800C)
  (:const "+SLIDER-PEN-ARRAY+" #x8502800D)
  (:const "+SLIDER-INVERT+" #x8502800E)
  (:const "+SLIDER-KNOB-DELTA+" #x8502800F)
  (:const "+SLIDER-LEVEL-FORMAT+" #x85028010)
  (:const "+SLIDER-LEVEL-PLACE+" #x85028011)
  (:const "+SLIDER-LEVEL-JUSTIFY+" #x85028012)
  (:const "+SLIDER-LEVEL-DOMAIN+" #x85028013)
  (:const "+SLIDER-LEVEL-SPACE+" #x85028014)
  (:const "+SLIDER-LEVEL-HOOK+" #x85028015)
  (:const "+SLIDER-LEVEL-MAX-LEN+" #x85028016)
  (:const "+SLIDER-NOTIFY-DISABLE+" #x85028017)
  (:const "+SLIDER-INIT-DISP-HOOK+" #x85028018)
  (:const "+SORIENT-HORIZ+" 2)
  (:const "+SORIENT-VERT+" 4)
  (:const "+SLIDER-HORIZONTAL+" 2)
  (:const "+SLIDER-VERTICAL+" 4)
  (:const "+SLJ-LEFT+" 0)
  (:const "+SLJ-CENTER+" 1)
  (:const "+SLJ-RIGHT+" 2)

  ;; --- functions (slider_lib.sfd + MorphOS SDK) ---
  (:fn "SLIDER-GET-CLASS" -30 () :pointer 40)   ; Class * SLIDER_GetClass() () LVO -30
  )

(provide "amiga/raw/gadgets/slider")
