;;; amiga/raw/gadgets/speedbar  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   speedbar_lib.sfd ($VER: speedbar_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK speedbar_lib.fd + clib/speedbar_protos.h (via fd2sfd)
;;;   gadgets/speedbar.h
;;;
;;; 5 functions, 57 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.GADGETS.SPEEDBAR"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export "*SPEEDBAR-BASE*" "*SPEEDBAR-VERSION*"))

(in-package "AMIGA.RAW.GADGETS.SPEEDBAR")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *speedbar-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/speedbar.gadget" 0)))
(defvar *speedbar-version*
  (and *speedbar-base* (amiga.ffi:library-version *speedbar-base*)))
(defun %version>= (n)
  (and *speedbar-version* (>= *speedbar-version* n)))

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.GADGETS.SPEEDBAR"
    (:base *speedbar-base* :version *speedbar-version*)

  ;; --- constants from gadgets/speedbar.h ---
  (:const "+SBNA-DUMMY+" #x80010000)
  (:const "+SBNA-LEFT+" #x80010001)
  (:const "+SBNA-TOP+" #x80010002)
  (:const "+SBNA-WIDTH+" #x80010003)
  (:const "+SBNA-HEIGHT+" #x80010004)
  (:const "+SBNA-USER-DATA+" #x80010005)
  (:const "+SBNA-ENABLED+" #x80010006)
  (:const "+SBNA-SPACING+" #x80010007)
  (:const "+SBNA-HIGHLIGHT+" #x80010008)
  (:const "+SBNA-IMAGE+" #x80010009)
  (:const "+SBNA-SEL-IMAGE+" #x8001000A)
  (:const "+SBNA-HELP+" #x8001000B)
  (:const "+SBNA-TOGGLE+" #x8001000C)
  (:const "+SBNA-SELECTED+" #x8001000D)
  (:const "+SBNA-MX-GROUP+" #x8001000E)
  (:const "+SBNA-DISABLED+" #x8001000F)
  (:const "+SBNA-TEXT+" #x80010010)
  (:const "+SBNA-SPACER+" #x80010011)
  (:const "+SBNA-SEPARATOR+" #x80010012)
  (:const "+SBNA-HINT-INFO+" #x80010013)
  (:const "+SBNA-BUTTON-ID+" #x80010014)
  (:const "+SBH-NONE+" 0)
  (:const "+SBH-BACKFILL+" 1)
  (:const "+SBH-RECESS+" 2)
  (:const "+SBH-IMAGE+" 3)
  (:const "+SPEEDBAR-DUMMY+" #x85013000)
  (:const "+SPEEDBAR-BUTTONS+" #x85013001)
  (:const "+SPEEDBAR-ORIENTATION+" #x85013002)
  (:const "+SPEEDBAR-BACKGROUND+" #x85013003)
  (:const "+SPEEDBAR-WINDOW+" #x85013004)
  (:const "+SPEEDBAR-STRUM-BAR+" #x85013005)
  (:const "+SPEEDBAR-ON-BUTTON+" #x85013006)
  (:const "+SPEEDBAR-OFF-BUTTON+" #x85013007)
  (:const "+SPEEDBAR-SCROLL-LEFT+" #x85013008)
  (:const "+SPEEDBAR-SCROLL-RIGHT+" #x85013009)
  (:const "+SPEEDBAR-TOP+" #x8501300A)
  (:const "+SPEEDBAR-VISIBLE+" #x8501300B)
  (:const "+SPEEDBAR-TOTAL+" #x8501300C)
  (:const "+SPEEDBAR-HELP+" #x8501300D)
  (:const "+SPEEDBAR-BEVEL-STYLE+" #x8501300E)
  (:const "+SPEEDBAR-SELECTED+" #x8501300F)
  (:const "+SPEEDBAR-SELECTED-NODE+" #x85013010)
  (:const "+SPEEDBAR-EVEN-SIZE+" #x85013011)
  (:const "+SPEEDBAR-FONT+" #x85013012)
  (:const "+SPEEDBAR-TOP-NODE+" #x85013013)
  (:const "+SPEEDBAR-BUTTON-TYPE+" #x85013014)
  (:const "+SPEEDBAR-HORIZ-PADDING+" #x85013015)
  (:const "+SPEEDBAR-VERT-PADDING+" #x85013016)
  (:const "+SPEEDBAR-BUTTON-BEVEL-STYLE+" #x85013801)
  (:const "+SBM-SETNODEATTRS+" #x58000A)
  (:const "+SBORIENT-HORIZ+" 0)
  (:const "+SBORIENT-VERT+" 1)
  (:const "+SPEEDBAR-HORIZONTAL+" 0)
  (:const "+SPEEDBAR-VERTICAL+" 1)
  (:const "+SBTYPE-BOTH+" 0)
  (:const "+SBTYPE-TEXT+" 1)
  (:const "+SBTYPE-IMAGE+" 2)

  ;; --- functions (speedbar_lib.sfd + MorphOS SDK) ---
  (:fn "SPEEDBAR-GET-CLASS" -30 () :pointer 40)   ; Class * SPEEDBAR_GetClass() () LVO -30
  (:fn "ALLOC-SPEED-BUTTON-NODE-A" -36 (:d0 :a0) :pointer 40)   ; struct Node * AllocSpeedButtonNodeA(ULONG number, struct TagItem * tags) (D0,A0) LVO -36
  (:fn "FREE-SPEED-BUTTON-NODE" -42 (:a0) :void 40)   ; VOID FreeSpeedButtonNode(struct Node * node) (A0) LVO -42
  (:fn "SET-SPEED-BUTTON-NODE-ATTRS-A" -48 (:a0 :a1) :void 40)   ; VOID SetSpeedButtonNodeAttrsA(struct Node * node, struct TagItem * tags) (A0,A1) LVO -48
  (:fn "GET-SPEED-BUTTON-NODE-ATTRS-A" -54 (:a0 :a1) :void 40)   ; VOID GetSpeedButtonNodeAttrsA(struct Node * node, struct TagItem * tags) (A0,A1) LVO -54
  )

(provide "amiga/raw/gadgets/speedbar")
