;;; amiga/raw/gadgets/string  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   string_lib.sfd ($VER: string_lib.sfd 47.1 (30.11.2021))
;;;   MorphOS SDK string_lib.fd + clib/string_protos.h (via fd2sfd)
;;;   gadgets/string.h
;;;
;;; 1 functions, 23 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.GADGETS.STRING"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export "*STRING-BASE*" "*STRING-VERSION*"))

(in-package "AMIGA.RAW.GADGETS.STRING")

;;; Library base  opened at load time on AmigaOS/MorphOS; NIL on other
;;; hosts (the module still loads there for testing and compilation).
(defvar *string-base*
  (when (member :amigaos *features*)
    (amiga.ffi:open-library-or-die "gadgets/string.gadget" 0)))
(defvar *string-version*
  (and *string-base* (amiga.ffi:library-version *string-base*)))
(defun %version>= (n)
  (and *string-version* (>= *string-version* n)))

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.GADGETS.STRING"
    (:base *string-base* :version *string-version*)

  ;; --- constants from gadgets/string.h ---
  (:const "+STRINGA-MIN-VISIBLE+" #x85055000)
  (:const "+STRINGA-HOOK-TYPE+" #x85055001)
  (:const "+STRINGA-REL-VERIFY-SPECIAL+" #x8505500A)
  (:const "+STRINGA-GET-BLOCK-POS+" #x85055010)
  (:const "+STRINGA-MARK+" #x85055011)
  (:const "+STRINGA-ALLOW-MARKING+" #x85055012)
  (:const "+STRINGA-INTERIM-UPDATES+" #x85055013)
  (:const "+STRINGA-ASL-TAGS+" #x85055013)
  (:const "+STRINGA-MARK-ACTIVE+" #x85055014)
  (:const "+STRINGA-DISABLE-POPUP+" #x85055015)
  (:const "+STRINGA-MIN-VAL+" #x85055016)
  (:const "+STRINGA-MAX-VAL+" #x85055017)
  (:const "+SHK-CUSTOM+" 0)
  (:const "+SHK-PASSWORD+" 1)
  (:const "+SHK-IPADDRESS+" 2)
  (:const "+SHK-FLOAT+" 3)
  (:const "+SHK-HEXIDECIMAL+" 4)
  (:const "+SHK-TELEPHONE+" 5)
  (:const "+SHK-POSTALCODE+" 6)
  (:const "+SHK-AMOUNT+" 7)
  (:const "+SHK-UPPERCASE+" 8)
  (:const "+SHK-HOTKEY+" 9)
  (:const "+SHK-HEXADECIMAL+" 4)

  ;; --- functions (string_lib.sfd + MorphOS SDK) ---
  (:fn "STRING-GET-CLASS" -30 () :pointer 40)   ; Class * STRING_GetClass() () LVO -30
  )

(provide "amiga/raw/gadgets/string")
