;;; amiga/raw/gadgets/tabs  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   gadgets/tabs.h
;;;
;;; 0 functions, 8 constants, 0 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

(require "amiga/ffi")

(defpackage "AMIGA.RAW.GADGETS.TABS"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "+TL-TEXTPEN+" "+TL-BACKGROUNDPEN+" "+TL-FILLTEXTPEN+" "+TL-FILLPEN+" 
   "+MAX-TL-PENS+" "+TABS-DUMMY+" "+TABS-LABELS+" "+TABS-CURRENT+" ))

(in-package "AMIGA.RAW.GADGETS.TABS")

;;; --- constants from gadgets/tabs.h ---
(defconstant +tl-textpen+ 0)
(defconstant +tl-backgroundpen+ 1)
(defconstant +tl-filltextpen+ 2)
(defconstant +tl-fillpen+ 3)
(defconstant +max-tl-pens+ 4)
(defconstant +tabs-dummy+ #x84000000)
(defconstant +tabs-labels+ #x84000001)
(defconstant +tabs-current+ #x84000002)

(provide "amiga/raw/gadgets/tabs")
