;;; amiga/raw/libraries/mathlibrary  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   libraries/mathlibrary.i
;;;
;;; 0 functions, 0 constants, 1 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.LIBRARIES.MATHLIBRARY"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export
   "*MATH-IEEE-BASE-SIZE*" "MATH-IEEE-BASE-MATH-IEEE-BASE-LIB-NODE" 
   "MATH-IEEE-BASE-MATH-IEEE-BASE-RESERVED" 
   "MATH-IEEE-BASE-MATH-IEEE-BASE-TASK-OPEN-LIB" 
   "MATH-IEEE-BASE-MATH-IEEE-BASE-TASK-CLOSE-LIB" ))

(in-package "AMIGA.RAW.LIBRARIES.MATHLIBRARY")

;;; --- structures from libraries/mathlibrary.i ---
(ffi:defcstruct (math-ieee-base :size 60)   ; MathIEEEBase (libraries/mathlibrary.i)
  (math-ieee-base-lib-node (:struct 34) 0)
  (math-ieee-base-reserved (:struct 18) 34)
  (math-ieee-base-task-open-lib :fptr 52)
  (math-ieee-base-task-close-lib :fptr 56)
)

(provide "amiga/raw/libraries/mathlibrary")
