;;; amiga/raw/libraries/mathlibrary  GENERATED by scripts/gen-amiga-bindings.lisp. DO NOT EDIT.
;;;
;;; Sources:
;;;   libraries/mathlibrary.i
;;;
;;; 0 functions, 0 constants, 1 structs.
;;; Regenerate with `make gen-amiga-bindings`  see README "Raw OS bindings".

;; compile-time too: COMPILE-FILE (the host builds the lib/amiga FASLs) must see
;; AMIGA.FFI at read time, not only LOAD.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "amiga/ffi"))

(defpackage "AMIGA.RAW.LIBRARIES.MATHLIBRARY"
  (:use "CL" "FFI" "AMIGA.FFI")
  (:export))

(in-package "AMIGA.RAW.LIBRARIES.MATHLIBRARY")

;;; Binding table  every name below is built the first time anything
;;; refers to it (specs/raw-bindings-footprint.md); until then the module
;;; costs the packed table only.  Row syntax: AMIGA.FFI:DEFINE-BINDING-TABLE.
(amiga.ffi:define-binding-table "AMIGA.RAW.LIBRARIES.MATHLIBRARY" ()

  ;; --- structures from libraries/mathlibrary.i ---
  (:struct "MATH-IEEE-BASE" 60   ; MathIEEEBase (libraries/mathlibrary.i)
    ("MATH-IEEE-BASE-LIB-NODE" (:struct 34) 0)
    ("MATH-IEEE-BASE-RESERVED" (:struct 18) 34)
    ("MATH-IEEE-BASE-TASK-OPEN-LIB" :fptr 52)
    ("MATH-IEEE-BASE-TASK-CLOSE-LIB" :fptr 56)
    )
  )

(provide "amiga/raw/libraries/mathlibrary")
